// B2レベル穴埋め問題プール（コイン協力モード用）
// answer は小文字で保持し、判定時に両者を小文字化して比較する
module.exports = [
  { sentence: "She managed to ___ the difficult situation calmly.", hint: "h_____", answer: "handle", ja: "彼女は難しい状況を冷静に対処した" },
  { sentence: "The company decided to ___ its new product next month.", hint: "l_____", answer: "launch", ja: "会社は来月新製品を発売することにした" },
  { sentence: "You should ___ your appointment before visiting.", hint: "c______", answer: "confirm", ja: "訪問前に予約を確認すべきだ" },
  { sentence: "The movie didn't ___ my expectations.", hint: "m___", answer: "meet", ja: "その映画は期待に届かなかった" },
  { sentence: "We need to ___ a solution to this problem.", hint: "f___", answer: "find", ja: "この問題の解決策を見つける必要がある" },
  { sentence: "He couldn't ___ the temptation to check his phone.", hint: "r_____", answer: "resist", ja: "彼はスマホを見たい誘惑に抗えなかった" },
  { sentence: "The government plans to ___ new taxes on imports.", hint: "i_____", answer: "impose", ja: "政府は輸入品に新しい税を課す予定だ" },
  { sentence: "Please ___ from smoking in this area.", hint: "r______", answer: "refrain", ja: "この場所での喫煙はご遠慮ください" },
  { sentence: "The two countries finally reached an ___.", hint: "a________", answer: "agreement", ja: "両国はついに合意に達した" },
  { sentence: "She has a strong ___ to succeed in her career.", hint: "d_____________", answer: "determination", ja: "彼女にはキャリアで成功する強い決意がある" },
  { sentence: "The evidence was not ___ to prove his guilt.", hint: "s_________", answer: "sufficient", ja: "証拠は彼の有罪を証明するのに十分ではなかった" },
  { sentence: "It's important to ___ a balance between work and life.", hint: "m_______", answer: "maintain", ja: "仕事と生活のバランスを保つことが大切だ" },
  { sentence: "The manager will ___ the new policy to the staff.", hint: "e______", answer: "explain", ja: "マネージャーは新方針をスタッフに説明する" },
  { sentence: "They had to ___ the event due to bad weather.", hint: "p_______", answer: "postpone", ja: "悪天候のためイベントを延期しなければならなかった" },
  { sentence: "His speech made a deep ___ on the audience.", hint: "i_________", answer: "impression", ja: "彼のスピーチは聴衆に深い印象を与えた" },
  { sentence: "We should ___ the risks before making a decision.", hint: "a_____", answer: "assess", ja: "決定する前にリスクを評価すべきだ" },
  { sentence: "The new law will ___ into effect next year.", hint: "c___", answer: "come", ja: "新しい法律は来年施行される" },
  { sentence: "She tried to ___ her nervousness during the interview.", hint: "h___", answer: "hide", ja: "彼女は面接中、緊張を隠そうとした" },
  { sentence: "The team worked hard to ___ the deadline.", hint: "m___", answer: "meet", ja: "チームは締め切りに間に合わせるため懸命に働いた" },
  { sentence: "Can you ___ the difference between these two words?", hint: "e______", answer: "explain", ja: "この2つの単語の違いを説明できますか" },
  { sentence: "The city plans to ___ the old bridge next year.", hint: "r______", answer: "replace", ja: "市は来年、古い橋を架け替える予定だ" },
  { sentence: "He didn't ___ to offend anyone with his comment.", hint: "i_____", answer: "intend", ja: "彼はコメントで誰かを怒らせるつもりはなかった" },
  { sentence: "The research aims to ___ the causes of the disease.", hint: "i__________", answer: "investigate", ja: "その研究は病気の原因を調査することを目的とする" },
  { sentence: "You need to ___ your skills to get a better job.", hint: "i______", answer: "improve", ja: "より良い仕事を得るにはスキルを磨く必要がある" },
  { sentence: "The witness agreed to ___ what she had seen.", hint: "d_______", answer: "describe", ja: "目撃者は見たことを説明することに同意した" },
  { sentence: "The company must ___ to the new regulations.", hint: "a_____", answer: "adjust", ja: "会社は新しい規制に適応しなければならない" },
  { sentence: "His success is the ___ of years of hard work.", hint: "r_____", answer: "result", ja: "彼の成功は長年の努力の結果だ" },
  { sentence: "Don't ___ to ask if you have any questions.", hint: "h_______", answer: "hesitate", ja: "質問があれば遠慮なく聞いてください" },
  { sentence: "The teacher asked us to ___ the main idea of the text.", hint: "s________", answer: "summarize", ja: "先生は本文の要旨をまとめるよう求めた" },
  { sentence: "We must ___ our natural resources for future generations.", hint: "p_______", answer: "preserve", ja: "将来の世代のために天然資源を守らなければならない" }
];
