// Clacel 2.0 単語テスト問題（PDFのWord List例文から生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
// Series 8 のみ12語（副詞・接続詞・前置詞。PDF側の設計で語数が少ない）
module.exports = {
  label: "Clacel 2.0",
  series: [
    {
      name: "Series 1",
      items: [
        { sentence: "Yesterday, the children ___ to be superheroes.", answer: "pretended", base: "pretend", hint: "p________", ja: "ふりをする" },
        { sentence: "Please ___ your shoes before entering the room.", answer: "remove", base: "remove", hint: "r_____", ja: "取り除く" },
        { sentence: "She can't ___ the summer heat.", answer: "stand", base: "stand", hint: "s____", ja: "立つ、耐える" },
        { sentence: "The rising prices ___ many families.", answer: "concern", base: "concern", hint: "c______", ja: "心配させる、関係する" },
        { sentence: "I didn't ___ her with her new haircut.", answer: "recognize", base: "recognize", hint: "r________", ja: "認識する、見分ける" },
        { sentence: "The dog likes to ___ holes in the garden.", answer: "dig", base: "dig", hint: "d__", ja: "掘る" },
        { sentence: "The fire ___ quickly through the dry forest.", answer: "spread", base: "spread", hint: "s_____", ja: "広げる、広がる" },
        { sentence: "Please don't ___ her while she is studying.", answer: "disturb", base: "disturb", hint: "d______", ja: "邪魔する" },
        { sentence: "Yesterday, she ___ the difficult question very calmly.", answer: "handled", base: "handle", hint: "h______", ja: "扱う、対処する" },
        { sentence: "Don't ___ water while brushing your teeth.", answer: "waste", base: "waste", hint: "w____", ja: "無駄にする" },
        { sentence: "I will ___ a meeting for next week.", answer: "arrange", base: "arrange", hint: "a______", ja: "手配する、整える" },
        { sentence: "Many people ___ advice before making a big decision.", answer: "seek", base: "seek", hint: "s___", ja: "探し求める" },
        { sentence: "The company currently ___ fresh vegetables to the school.", answer: "supplies", base: "supply", hint: "s_______", ja: "供給する" },
        { sentence: "Let's ___ the cake among the four of us.", answer: "divide", base: "divide", hint: "d_____", ja: "分ける、割る" },
        { sentence: "We need to ___ early to catch the train.", answer: "leave", base: "leave", hint: "l____", ja: "去る、残す" },
        { sentence: "Please ___ the guide through the museum.", answer: "follow", base: "follow", hint: "f_____", ja: "ついていく、従う" },
        { sentence: "She likes to ___ pictures of animals.", answer: "draw", base: "draw", hint: "d___", ja: "描く" },
        { sentence: "Last night, snow ___ the entire mountain in white.", answer: "covered", base: "cover", hint: "c______", ja: "覆う" },
        { sentence: "Childhood experiences often ___ our personalities.", answer: "shape", base: "shape", hint: "s____", ja: "形作る" },
        { sentence: "Please ___ seated until the bus stops.", answer: "remain", base: "remain", hint: "r_____", ja: "とどまる、～のままである" },
      ],
    },
    {
      name: "Series 2",
      items: [
        { sentence: "Please ___ the plastic from the paper waste.", answer: "separate", base: "separate", hint: "s_______", ja: "分ける、分離する" },
        { sentence: "Yesterday, she ___ to finish the report on time.", answer: "managed", base: "manage", hint: "m______", ja: "なんとかやり遂げる、管理する" },
        { sentence: "Last week, the storm ___ us to cancel the trip.", answer: "forced", base: "force", hint: "f_____", ja: "強制する" },
        { sentence: "If you don't hurry, you'll ___ the bus.", answer: "miss", base: "miss", hint: "m___", ja: "逃す、寂しく思う" },
        { sentence: "This job currently ___ good communication skills.", answer: "requires", base: "require", hint: "r_______", ja: "必要とする" },
        { sentence: "A ticket to the concert currently ___ fifty dollars.", answer: "costs", base: "cost", hint: "c____", ja: "（費用が）かかる" },
        { sentence: "This umbrella currently ___ to my sister.", answer: "belongs", base: "belong", hint: "b______", ja: "所属する、～のものである" },
        { sentence: "Can you ___ the man you saw?", answer: "describe", base: "describe", hint: "d_______", ja: "描写する、説明する" },
        { sentence: "These days, she ___ the piano for an hour every day.", answer: "practices", base: "practice", hint: "p________", ja: "練習する" },
        { sentence: "Loud noises ___ me when I'm studying.", answer: "bother", base: "bother", hint: "b_____", ja: "悩ます、わざわざ～する" },
        { sentence: "Please don't ___ answers from your classmate.", answer: "copy", base: "copy", hint: "c___", ja: "複写する、まねる" },
        { sentence: "Last night, he ___ on paying for dinner.", answer: "insisted", base: "insist", hint: "i_______", ja: "強く主張する" },
        { sentence: "You can ___ the files from any computer.", answer: "access", base: "access", hint: "a_____", ja: "アクセスする、利用する" },
        { sentence: "Be quiet as you ___ the sleeping baby.", answer: "approach", base: "approach", hint: "a_______", ja: "近づく" },
        { sentence: "Please ___ me to call the dentist.", answer: "remind", base: "remind", hint: "r_____", ja: "思い出させる" },
        { sentence: "The two brothers often ___ about small things.", answer: "argue", base: "argue", hint: "a____", ja: "言い争う、主張する" },
        { sentence: "The band will ___ at the school festival.", answer: "perform", base: "perform", hint: "p______", ja: "行う、演じる" },
        { sentence: "They had to ___ the game because of the rain.", answer: "cancel", base: "cancel", hint: "c_____", ja: "中止する、キャンセルする" },
        { sentence: "Washing your hands can ___ illness.", answer: "prevent", base: "prevent", hint: "p______", ja: "防ぐ" },
        { sentence: "Could you help me ___ these boxes?", answer: "carry", base: "carry", hint: "c____", ja: "運ぶ" },
      ],
    },
    {
      name: "Series 3",
      items: [
        { sentence: "She hired a ___ to help with her math.", answer: "tutor", base: "tutor", hint: "t____", ja: "家庭教師、個別指導者" },
        { sentence: "He made a good ___ at the interview.", answer: "impression", base: "impression", hint: "i_________", ja: "印象" },
        { sentence: "The ambassador lives in an official ___.", answer: "residence", base: "residence", hint: "r________", ja: "住居、邸宅" },
        { sentence: "I downloaded the latest ___ of the app.", answer: "version", base: "version", hint: "v______", ja: "版、バージョン" },
        { sentence: "The ___ takes one year to circle the sun.", answer: "earth", base: "earth", hint: "e____", ja: "地球、大地" },
        { sentence: "Pollution has a serious ___ on the environment.", answer: "effect", base: "effect", hint: "e_____", ja: "影響、効果" },
        { sentence: "She passed the exam through hard ___.", answer: "effort", base: "effort", hint: "e_____", ja: "努力" },
        { sentence: "The snacks are in the third ___ of the store.", answer: "aisle", base: "aisle", hint: "a____", ja: "通路" },
        { sentence: "Swimming is my favorite weekend ___.", answer: "activity", base: "activity", hint: "a_______", ja: "活動" },
        { sentence: "The hero is the most popular ___ in the book.", answer: "character", base: "character", hint: "c________", ja: "性格、登場人物" },
        { sentence: "Children seem to have endless ___.", answer: "energy", base: "energy", hint: "e_____", ja: "エネルギー、活力" },
        { sentence: "The ___ of the word is Latin.", answer: "origin", base: "origin", hint: "o_____", ja: "起源、由来" },
        { sentence: "She raised an ___ to the new plan.", answer: "objection", base: "objection", hint: "o________", ja: "反対、異議" },
        { sentence: "This is an effective ___ for learning words.", answer: "method", base: "method", hint: "m_____", ja: "方法" },
        { sentence: "She kept her many ___ to herself during the meeting.", answer: "thoughts", base: "thought", hint: "t_______", ja: "考え、思考" },
        { sentence: "The old house was in a poor ___.", answer: "state", base: "state", hint: "s____", ja: "状態" },
        { sentence: "We enjoyed the beauty of ___ on our hike.", answer: "nature", base: "nature", hint: "n_____", ja: "自然、性質" },
        { sentence: "She sent her ___ for the scholarship.", answer: "application", base: "application", hint: "a__________", ja: "申し込み、応用、アプリ" },
        { sentence: "The painting has great ___ to collectors.", answer: "value", base: "value", hint: "v____", ja: "価値" },
        { sentence: "The teacher explained the ___ calmly.", answer: "situation", base: "situation", hint: "s________", ja: "状況" },
      ],
    },
    {
      name: "Series 4",
      items: [
        { sentence: "Call this number in case of an ___.", answer: "emergency", base: "emergency", hint: "e________", ja: "緊急事態" },
        { sentence: "She deserves ___ for her hard work.", answer: "credit", base: "credit", hint: "c_____", ja: "信用、功績、クレジット" },
        { sentence: "The ___ of the lake was perfectly calm.", answer: "surface", base: "surface", hint: "s______", ja: "表面" },
        { sentence: "We asked the waiter for the ___.", answer: "bill", base: "bill", hint: "b___", ja: "請求書、勘定" },
        { sentence: "This is an important ___ we must discuss.", answer: "matter", base: "matter", hint: "m_____", ja: "事柄、問題" },
        { sentence: "The clown's tricks were a source of ___.", answer: "amusement", base: "amusement", hint: "a________", ja: "楽しみ、娯楽" },
        { sentence: "The neighbors live together in ___.", answer: "harmony", base: "harmony", hint: "h______", ja: "調和" },
        { sentence: "The hotel room has a beautiful ___ of the sea.", answer: "view", base: "view", hint: "v___", ja: "眺め、見解" },
        { sentence: "The teacher praised the students' good ___.", answer: "behavior", base: "behavior", hint: "b_______", ja: "行動、ふるまい" },
        { sentence: "There was a long ___ before she answered.", answer: "pause", base: "pause", hint: "p____", ja: "休止、間" },
        { sentence: "She learned a new ___ for painting.", answer: "technique", base: "technique", hint: "t________", ja: "技術、手法" },
        { sentence: "There is a growing ___ toward healthy eating.", answer: "trend", base: "trend", hint: "t____", ja: "傾向、流行" },
        { sentence: "The temperature dropped by ten ___ overnight.", answer: "degrees", base: "degree", hint: "d______", ja: "度、学位、程度" },
        { sentence: "He was late because of a traffic ___.", answer: "accident", base: "accident", hint: "a_______", ja: "事故、偶然" },
        { sentence: "I do the ___ every Sunday morning.", answer: "laundry", base: "laundry", hint: "l______", ja: "洗濯（物）" },
        { sentence: "She gave an excellent ___ in class.", answer: "presentation", base: "presentation", hint: "p___________", ja: "発表、プレゼン" },
        { sentence: "He has a strong ___ of heights.", answer: "fear", base: "fear", hint: "f___", ja: "恐怖" },
        { sentence: "This is a popular ___ for taking photos.", answer: "spot", base: "spot", hint: "s___", ja: "場所、斑点" },
        { sentence: "Read all the ___ carefully before you start.", answer: "instructions", base: "instruction", hint: "i___________", ja: "指示、説明" },
        { sentence: "He ran for office as an ___.", answer: "independent", base: "independent", hint: "i__________", ja: "独立した人・もの" },
      ],
    },
    {
      name: "Series 5",
      items: [
        { sentence: "We wore ___ clothes at the festival.", answer: "traditional", base: "traditional", hint: "t__________", ja: "伝統的な" },
        { sentence: "The volunteer work gave her ___ experience.", answer: "valuable", base: "valuable", hint: "v_______", ja: "貴重な、価値のある" },
        { sentence: "He wants to become a ___ soccer player.", answer: "professional", base: "professional", hint: "p___________", ja: "プロの、専門的な" },
        { sentence: "Can you tell me the ___ time of the meeting?", answer: "exact", base: "exact", hint: "e____", ja: "正確な" },
        { sentence: "Smith is a very ___ family name in England.", answer: "common", base: "common", hint: "c_____", ja: "一般的な、共通の" },
        { sentence: "Sushi is made with ___ fish.", answer: "raw", base: "raw", hint: "r__", ja: "生の、未加工の" },
        { sentence: "There is a ___ library near the station.", answer: "public", base: "public", hint: "p_____", ja: "公共の" },
        { sentence: "Eating vegetables is part of a ___ diet.", answer: "healthy", base: "healthy", hint: "h______", ja: "健康的な、健康な" },
        { sentence: "It is ___ to rain later this afternoon.", answer: "likely", base: "likely", hint: "l_____", ja: "ありそうな" },
        { sentence: "The two brothers have very ___ voices.", answer: "similar", base: "similar", hint: "s______", ja: "似ている" },
        { sentence: "Everyone should learn ___ first-aid skills.", answer: "basic", base: "basic", hint: "b____", ja: "基本的な" },
        { sentence: "We had ___ chicken for dinner.", answer: "roast", base: "roast", hint: "r____", ja: "焼いた、ローストした" },
        { sentence: "The earth is a large ___ object.", answer: "round", base: "round", hint: "r____", ja: "丸い" },
        { sentence: "Do we have ___ chairs for everyone?", answer: "enough", base: "enough", hint: "e_____", ja: "十分な" },
        { sentence: "We had a ___ walk in the park.", answer: "pleasant", base: "pleasant", hint: "p_______", ja: "快い、感じのよい" },
        { sentence: "Please give a ___ example in your answer.", answer: "specific", base: "specific", hint: "s_______", ja: "具体的な、特定の" },
        { sentence: "These shoes are light and ___.", answer: "comfortable", base: "comfortable", hint: "c__________", ja: "快適な" },
        { sentence: "She ate the ___ pizza by herself.", answer: "whole", base: "whole", hint: "w____", ja: "全体の" },
        { sentence: "The baby is finally ___.", answer: "asleep", base: "asleep", hint: "a_____", ja: "眠って" },
        { sentence: "He showed off his ___ smartphone.", answer: "brand-new", base: "brand-new", hint: "b________", ja: "新品の" },
      ],
    },
    {
      name: "Series 6",
      items: [
        { sentence: "There is an ___ charge for late delivery.", answer: "additional", base: "additional", hint: "a_________", ja: "追加の" },
        { sentence: "We need a ___ surface to set up the tent.", answer: "flat", base: "flat", hint: "f___", ja: "平らな" },
        { sentence: "She is a ___ author in Japan.", answer: "well-known", base: "well-known", hint: "w_________", ja: "有名な" },
        { sentence: "A ___ storm hit the coast last night.", answer: "violent", base: "violent", hint: "v______", ja: "暴力的な、激しい" },
        { sentence: "The train was very ___ this morning.", answer: "crowded", base: "crowded", hint: "c______", ja: "混雑した" },
        { sentence: "Only a ___ students came to the early class.", answer: "few", base: "few", hint: "f__", ja: "ほとんどない、少しの" },
        { sentence: "The old town has many ___ streets.", answer: "narrow", base: "narrow", hint: "n_____", ja: "狭い" },
        { sentence: "Cut the bread into ___ slices.", answer: "thin", base: "thin", hint: "t___", ja: "薄い、細い" },
        { sentence: "My best friend lives ___ to my house.", answer: "close", base: "close", hint: "c____", ja: "近い、親しい" },
        { sentence: "I am ___ that I locked the door.", answer: "certain", base: "certain", hint: "c______", ja: "確信して、確かな" },
        { sentence: "Do you have this shirt in any ___ colors?", answer: "other", base: "other", hint: "o____", ja: "ほかの" },
        { sentence: "Rain is ___ weather for this season.", answer: "typical", base: "typical", hint: "t______", ja: "典型的な" },
        { sentence: "She is ___ of the dark.", answer: "afraid", base: "afraid", hint: "a_____", ja: "恐れて、心配して" },
        { sentence: "We will meet again the ___ week.", answer: "following", base: "following", hint: "f________", ja: "次の" },
        { sentence: "Is there a ___ train to the airport?", answer: "direct", base: "direct", hint: "d_____", ja: "直接の" },
        { sentence: "This old book is ___ a lot of money.", answer: "worth", base: "worth", hint: "w____", ja: "～の価値がある" },
        { sentence: "The bottle is completely ___.", answer: "empty", base: "empty", hint: "e____", ja: "空の" },
        { sentence: "He ___ eats fast food.", answer: "rarely", base: "rarely", hint: "r_____", ja: "めったに～ない" },
        { sentence: "I have been to Kyoto only ___.", answer: "once", base: "once", hint: "o___", ja: "一度、かつて" },
        { sentence: "The shop was ___ a small bakery.", answer: "originally", base: "originally", hint: "o_________", ja: "もともと、最初は" },
      ],
    },
    {
      name: "Series 7",
      items: [
        { sentence: "The train left at ___ nine o'clock.", answer: "exactly", base: "exactly", hint: "e______", ja: "正確に、ちょうど" },
        { sentence: "Try to eat ___ and exercise more.", answer: "less", base: "less", hint: "l___", ja: "より少なく" },
        { sentence: "___, the weather will be sunny tomorrow.", answer: "hopefully", base: "hopefully", hint: "h________", ja: "願わくは、うまくいけば" },
        { sentence: "The customers are ___ young students.", answer: "mostly", base: "mostly", hint: "m_____", ja: "たいてい、主に" },
        { sentence: "I ___ forgot about the meeting.", answer: "completely", base: "completely", hint: "c_________", ja: "完全に" },
        { sentence: "The flowers were arranged very ___.", answer: "nicely", base: "nicely", hint: "n_____", ja: "うまく、よく" },
        { sentence: "The test was ___ difficult this time.", answer: "rather", base: "rather", hint: "r_____", ja: "かなり、むしろ" },
        { sentence: "The movie was ___ good, actually.", answer: "pretty", base: "pretty", hint: "p_____", ja: "かなり、なかなか" },
        { sentence: "She wants to study ___ next year.", answer: "abroad", base: "abroad", hint: "a_____", ja: "海外で、海外へ" },
        { sentence: "He lives ___ in a small apartment.", answer: "alone", base: "alone", hint: "a____", ja: "一人で" },
        { sentence: "Have you finished your homework ___?", answer: "yet", base: "yet", hint: "y__", ja: "まだ、もう" },
        { sentence: "She solved the puzzle ___.", answer: "easily", base: "easily", hint: "e_____", ja: "簡単に" },
        { sentence: "I don't play that game ___.", answer: "anymore", base: "anymore", hint: "a______", ja: "もはや～ない" },
        { sentence: "You can call me ___ you need help.", answer: "anytime", base: "anytime", hint: "a______", ja: "いつでも" },
        { sentence: "It's cold today. It was warm yesterday, ___.", answer: "though", base: "though", hint: "t_____", ja: "でも、もっとも" },
        { sentence: "It was raining ___ all morning.", answer: "heavily", base: "heavily", hint: "h______", ja: "激しく、大量に" },
        { sentence: "I'm ___ finished with my report.", answer: "almost", base: "almost", hint: "a_____", ja: "ほとんど" },
        { sentence: "After many tries, he ___ succeeded.", answer: "eventually", base: "eventually", hint: "e_________", ja: "結局、ついに" },
        { sentence: "I could ___ hear her quiet voice.", answer: "hardly", base: "hardly", hint: "h_____", ja: "ほとんど～ない" },
        { sentence: "The exam was ___ easy for most students.", answer: "quite", base: "quite", hint: "q____", ja: "かなり、まったく" },
      ],
    },
    {
      name: "Series 8",
      items: [
        { sentence: "Please call me ___ if there is a problem.", answer: "immediately", base: "immediately", hint: "i__________", ja: "すぐに" },
        { sentence: "We had dinner and went for a walk ___.", answer: "afterward", base: "afterward", hint: "a________", ja: "あとで" },
        { sentence: "The café was closed, so we went to the park ___.", answer: "instead", base: "instead", hint: "i______", ja: "代わりに" },
        { sentence: "We'll go hiking ___ it rains.", answer: "unless", base: "unless", hint: "u_____", ja: "～でない限り" },
        { sentence: "___ it was raining, we enjoyed the trip.", answer: "although", base: "although", hint: "a_______", ja: "～だけれども" },
        { sentence: "The shop is open every day ___ Sunday.", answer: "except", base: "except", hint: "e_____", ja: "～を除いて" },
        { sentence: "The cat is hiding ___ the sofa.", answer: "behind", base: "behind", hint: "b_____", ja: "～の後ろに" },
        { sentence: "The mountains lie ___ the river.", answer: "beyond", base: "beyond", hint: "b_____", ja: "～の向こうに、～を超えて" },
        { sentence: "I can't read this menu ___ my glasses.", answer: "without", base: "without", hint: "w______", ja: "～なしで" },
        { sentence: "___ her sister, she enjoys sports.", answer: "unlike", base: "unlike", hint: "u_____", ja: "～と違って" },
        { sentence: "Call me ___ you need help.", answer: "whenever", base: "whenever", hint: "w_______", ja: "～するときはいつでも" },
        { sentence: "Please reply ___ three days.", answer: "within", base: "within", hint: "w_____", ja: "～以内に、～の中で" },
      ],
    },
  ],
};
