// IELTS 単語テスト問題（PDFのWord List例文から生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
module.exports = {
  label: "IELTS",
  series: [
    {
      name: "Series 1",
      items: [
        { sentence: "Researchers ___ the data from a large national survey.", answer: "obtained", base: "obtain", hint: "o_______", ja: "得る、入手する" },
        { sentence: "Modern technology ___ communication between countries.", answer: "facilitates", base: "facilitate", hint: "f__________", ja: "促進する、容易にする" },
        { sentence: "Children learn social skills by ___ with others.", answer: "interacting", base: "interact", hint: "i__________", ja: "相互に作用する、交流する" },
        { sentence: "It is difficult to ___ the two closely related species.", answer: "differentiate", base: "differentiate", hint: "d____________", ja: "区別する" },
        { sentence: "Scientists must carefully ___ the results of the study.", answer: "interpret", base: "interpret", hint: "i________", ja: "解釈する" },
        { sentence: "Researchers ___ the temperature to test the reaction.", answer: "manipulated", base: "manipulate", hint: "m__________", ja: "操作する" },
        { sentence: "Wind farms ___ electricity without producing pollution.", answer: "generate", base: "generate", hint: "g_______", ja: "生み出す、発生させる" },
        { sentence: "It is hard to ___ of a society without any rules.", answer: "conceive", base: "conceive", hint: "c_______", ja: "思いつく、想像する" },
        { sentence: "The company ___ natural resources in the region.", answer: "exploits", base: "exploit", hint: "e_______", ja: "活用する、搾取する" },
        { sentence: "Limited funding ___ the scope of the research.", answer: "constrained", base: "constrain", hint: "c__________", ja: "制約する" },
        { sentence: "Many modern words ___ from Latin and Greek.", answer: "derive", base: "derive", hint: "d_____", ja: "（～から）得る、由来する" },
        { sentence: "Certain chemicals can ___ changes in cell growth.", answer: "induce", base: "induce", hint: "i_____", ja: "引き起こす、誘発する" },
        { sentence: "The painting ___ a busy market in the old city.", answer: "depicts", base: "depict", hint: "d______", ja: "描く、表現する" },
        { sentence: "The author ___ that education reduces inequality.", answer: "asserts", base: "assert", hint: "a______", ja: "主張する、断言する" },
        { sentence: "The school aims to ___ technology into every subject.", answer: "integrate", base: "integrate", hint: "i________", ja: "統合する" },
        { sentence: "The government may ___ when prices rise too sharply.", answer: "intervene", base: "intervene", hint: "i________", ja: "介入する" },
        { sentence: "The teacher tried to ___ the difficult concept.", answer: "clarify", base: "clarify", hint: "c______", ja: "明確にする" },
        { sentence: "A few large firms ___ the global market.", answer: "dominate", base: "dominate", hint: "d_______", ja: "支配する、優位を占める" },
        { sentence: "The city has ___ major changes in recent decades.", answer: "undergone", base: "undergo", hint: "u________", ja: "経験する、受ける" },
        { sentence: "Sediment ___ slowly at the bottom of the lake.", answer: "accumulates", base: "accumulate", hint: "a__________", ja: "蓄積する" },
      ],
    },
    {
      name: "Series 2",
      items: [
        { sentence: "The government will ___ more funds to public health.", answer: "allocate", base: "allocate", hint: "a_______", ja: "割り当てる、配分する" },
        { sentence: "Extra training can ___ for a lack of experience.", answer: "compensate", base: "compensate", hint: "c_________", ja: "埋め合わせる、補償する" },
        { sentence: "Scientists ___ living things into several kingdoms.", answer: "classify", base: "classify", hint: "c_______", ja: "分類する" },
        { sentence: "We should ___ water during the dry season.", answer: "conserve", base: "conserve", hint: "c_______", ja: "保存する、節約する" },
        { sentence: "Plants ___ sunlight into energy.", answer: "convert", base: "convert", hint: "c______", ja: "変える、転換する" },
        { sentence: "The new system aims to ___ waste.", answer: "eliminate", base: "eliminate", hint: "e________", ja: "排除する" },
        { sentence: "Reading widely can ___ your writing skills.", answer: "enhance", base: "enhance", hint: "e______", ja: "高める、向上させる" },
        { sentence: "Experts ___ that the population will double by 2050.", answer: "estimate", base: "estimate", hint: "e_______", ja: "推定する、見積もる" },
        { sentence: "Teachers ___ students through exams and projects.", answer: "evaluate", base: "evaluate", hint: "e_______", ja: "評価する" },
        { sentence: "The study ___ the effects of stress on health.", answer: "examines", base: "examine", hint: "e_______", ja: "詳しく調べる" },
        { sentence: "The results ___ a clear link between diet and health.", answer: "demonstrate", base: "demonstrate", hint: "d__________", ja: "実証する、示す" },
        { sentence: "New evidence has ___ about the cause of the illness.", answer: "emerged", base: "emerge", hint: "e______", ja: "現れる、明らかになる" },
        { sentence: "Engineers ___ the design to reduce the cost.", answer: "modified", base: "modify", hint: "m_______", ja: "修正する、変更する" },
        { sentence: "Burning fossil fuels ___ to climate change.", answer: "contributes", base: "contribute", hint: "c__________", ja: "貢献する、一因となる" },
        { sentence: "Children ___ language quickly in their early years.", answer: "acquire", base: "acquire", hint: "a______", ja: "習得する、獲得する" },
        { sentence: "Doctors ___ each patient before deciding on treatment.", answer: "assess", base: "assess", hint: "a_____", ja: "評価する、査定する" },
        { sentence: "Wealth is not evenly ___ across the country.", answer: "distributed", base: "distribute", hint: "d__________", ja: "分配する、分布させる" },
        { sentence: "The survey ___ that most people support the plan.", answer: "indicates", base: "indicate", hint: "i________", ja: "示す、示唆する" },
        { sentence: "These findings ___ the need for stricter rules.", answer: "reinforce", base: "reinforce", hint: "r________", ja: "強化する、補強する" },
        { sentence: "It is hard to ___ economic growth for many years.", answer: "sustain", base: "sustain", hint: "s______", ja: "維持する、持続させる" },
      ],
    },
    {
      name: "Series 3",
      items: [
        { sentence: "The experiment was designed to test the ___.", answer: "hypothesis", base: "hypothesis", hint: "h_________", ja: "仮説" },
        { sentence: "The essay examines several ___ of urban life.", answer: "aspects", base: "aspect", hint: "a______", ja: "側面、観点" },
        { sentence: "Applications are judged against three main ___.", answer: "criteria", base: "criteria", hint: "c_______", ja: "基準" },
        { sentence: "The company has a strict ___ of management.", answer: "hierarchy", base: "hierarchy", hint: "h________", ja: "階層、序列" },
        { sentence: "Global warming is a worldwide ___.", answer: "phenomenon", base: "phenomenon", hint: "p_________", ja: "現象" },
        { sentence: "Scientists have reached a ___ on climate change.", answer: "consensus", base: "consensus", hint: "c________", ja: "合意、総意" },
        { sentence: "She faced a ___ between work and family.", answer: "dilemma", base: "dilemma", hint: "d______", ja: "ジレンマ、板挟み" },
        { sentence: "The study provides a useful ___ for future research.", answer: "framework", base: "framework", hint: "f________", ja: "枠組み" },
        { sentence: "The ___ of the disease has fallen in recent years.", answer: "incidence", base: "incidence", hint: "i________", ja: "発生率" },
        { sentence: "The country invested heavily in its ___.", answer: "infrastructure", base: "infrastructure", hint: "i_____________", ja: "インフラ、社会基盤" },
        { sentence: "The researchers explained their ___ in detail.", answer: "methodology", base: "methodology", hint: "m__________", ja: "方法論" },
        { sentence: "Working from home has become the ___ for many people.", answer: "norm", base: "norm", hint: "n___", ja: "規範、標準" },
        { sentence: "The ___ of the election surprised many people.", answer: "outcome", base: "outcome", hint: "o______", ja: "結果" },
        { sentence: "It is a ___ that the wealthiest nations waste the most food.", answer: "paradox", base: "paradox", hint: "p______", ja: "逆説、矛盾" },
        { sentence: "The book offers a fresh ___ on history.", answer: "perspective", base: "perspective", hint: "p__________", ja: "観点、見方" },
        { sentence: "There is a wide ___ in income between regions.", answer: "disparity", base: "disparity", hint: "d________", ja: "格差、相違" },
        { sentence: "The ___ that the earth was flat lasted for centuries.", answer: "notion", base: "notion", hint: "n_____", ja: "観念、概念" },
        { sentence: "The ecosystem maintains a delicate ___.", answer: "equilibrium", base: "equilibrium", hint: "e__________", ja: "均衡" },
        { sentence: "Each branch operates as a separate legal ___.", answer: "entity", base: "entity", hint: "e_____", ja: "存在、実体" },
        { sentence: "The ___ of the internet changed daily life.", answer: "emergence", base: "emergence", hint: "e________", ja: "出現" },
      ],
    },
    {
      name: "Series 4",
      items: [
        { sentence: "A careful ___ of the data revealed a clear pattern.", answer: "analysis", base: "analysis", hint: "a_______", ja: "分析" },
        { sentence: "Diet is an important ___ in good health.", answer: "factor", base: "factor", hint: "f_____", ja: "要因" },
        { sentence: "Soil erosion is a serious ___ of deforestation.", answer: "consequence", base: "consequence", hint: "c__________", ja: "結果、影響" },
        { sentence: "The study has important ___ for public policy.", answer: "implications", base: "implication", hint: "i___________", ja: "影響、含意" },
        { sentence: "There is a growing ___ toward remote working.", answer: "trend", base: "trend", hint: "t____", ja: "傾向、動向" },
        { sentence: "A large ___ of students own a smartphone.", answer: "proportion", base: "proportion", hint: "p_________", ja: "割合" },
        { sentence: "The map shows the ___ of rainfall across the country.", answer: "distribution", base: "distribution", hint: "d___________", ja: "分布、分配" },
        { sentence: "There is a strong ___ between income and education.", answer: "correlation", base: "correlation", hint: "c__________", ja: "相関関係" },
        { sentence: "The experiment controlled every ___ except temperature.", answer: "variable", base: "variable", hint: "v_______", ja: "変数、変化要因" },
        { sentence: "Trust is a key ___ of any good relationship.", answer: "element", base: "element", hint: "e______", ja: "要素" },
        { sentence: "There is strong ___ that exercise improves mood.", answer: "evidence", base: "evidence", hint: "e_______", ja: "証拠" },
        { sentence: "The ___ of voters supported the new law.", answer: "majority", base: "majority", hint: "m_______", ja: "大多数" },
        { sentence: "The city has changed greatly over the past ___.", answer: "decade", base: "decade", hint: "d_____", ja: "10年間" },
        { sentence: "The main ___ of the heart is to pump blood.", answer: "function", base: "function", hint: "f_______", ja: "機能" },
        { sentence: "Books in the library are arranged by ___.", answer: "category", base: "category", hint: "c_______", ja: "カテゴリー、分類" },
        { sentence: "Safety is the company's top ___.", answer: "priority", base: "priority", hint: "p_______", ja: "優先事項" },
        { sentence: "Water is a precious natural ___.", answer: "resource", base: "resource", hint: "r_______", ja: "資源" },
        { sentence: "The two groups have been in ___ for years.", answer: "conflict", base: "conflict", hint: "c_______", ja: "対立、紛争" },
        { sentence: "The country is going through a ___ to clean energy.", answer: "transition", base: "transition", hint: "t_________", ja: "移行、変遷" },
        { sentence: "The government is responsible for the ___ of its citizens.", answer: "welfare", base: "welfare", hint: "w______", ja: "福祉、幸福" },
      ],
    },
    {
      name: "Series 5",
      items: [
        { sentence: "There was a ___ increase in average temperatures.", answer: "significant", base: "significant", hint: "s__________", ja: "重要な、著しい" },
        { sentence: "English is the ___ language in international business.", answer: "dominant", base: "dominant", hint: "d_______", ja: "支配的な、優勢な" },
        { sentence: "The instructions were ___ about what to do.", answer: "explicit", base: "explicit", hint: "e_______", ja: "明示的な、明確な" },
        { sentence: "The book gives a ___ overview of the subject.", answer: "comprehensive", base: "comprehensive", hint: "c____________", ja: "包括的な、総合的な" },
        { sentence: "The city is home to a ___ range of cultures.", answer: "diverse", base: "diverse", hint: "d______", ja: "多様な" },
        { sentence: "Some conflict is ___ in any large group.", answer: "inevitable", base: "inevitable", hint: "i_________", ja: "避けられない" },
        { sentence: "The project required a ___ amount of money.", answer: "substantial", base: "substantial", hint: "s__________", ja: "かなりの、相当な" },
        { sentence: "A good essay presents a ___ argument.", answer: "coherent", base: "coherent", hint: "c_______", ja: "首尾一貫した" },
        { sentence: "It was ___ that the new method had failed.", answer: "evident", base: "evident", hint: "e______", ja: "明白な" },
        { sentence: "The claim is supported by strong ___ evidence.", answer: "empirical", base: "empirical", hint: "e________", ja: "経験的な、実証的な" },
        { sentence: "Sleep plays a ___ role in learning and memory.", answer: "crucial", base: "crucial", hint: "c______", ja: "極めて重要な" },
        { sentence: "Please include only ___ information in your essay.", answer: "relevant", base: "relevant", hint: "r_______", ja: "関連のある" },
        { sentence: "The funding was barely ___ for the research.", answer: "adequate", base: "adequate", hint: "a_______", ja: "十分な、適切な" },
        { sentence: "The two species have ___ markings.", answer: "distinct", base: "distinct", hint: "d_______", ja: "明確に異なる" },
        { sentence: "The survey question was ___ and confused readers.", answer: "ambiguous", base: "ambiguous", hint: "a________", ja: "曖昧な" },
        { sentence: "Building the bridge in one year is not ___.", answer: "feasible", base: "feasible", hint: "f_______", ja: "実行可能な" },
        { sentence: "Smartphones are now ___ among young people.", answer: "prevalent", base: "prevalent", hint: "p________", ja: "広く行き渡った" },
        { sentence: "The product went through ___ safety testing.", answer: "rigorous", base: "rigorous", hint: "r_______", ja: "厳密な、厳格な" },
        { sentence: "The first test failed, but ___ attempts succeeded.", answer: "subsequent", base: "subsequent", hint: "s_________", ja: "その後の" },
        { sentence: "Clean water is ___ for human health.", answer: "vital", base: "vital", hint: "v____", ja: "極めて重要な、不可欠な" },
      ],
    },
  ],
};
