// Clacel 2.0 単語テスト問題（PDFのWord List例文から生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
// Series 8 のみ12語（副詞・接続詞・前置詞。PDF側の設計で語数が少ない）
module.exports = {
  label: "Clacel",
  series: [
    {
      name: "Day 1",
      items: [
        { sentence: "Yesterday, the children ___ to be superheroes.", answer: "pretended", base: "pretend", hint: "p________", ja: "ふりをする", sentenceJa: "昨日、子供たちはスーパーヒーローのふりをした。" },
        { sentence: "Please ___ your shoes before entering the room.", answer: "remove", base: "remove", hint: "r_____", ja: "取り除く", sentenceJa: "部屋に入る前に靴を脱いでください。" },
        { sentence: "She can't ___ the summer heat.", answer: "stand", base: "stand", hint: "s____", ja: "立つ、耐える", sentenceJa: "彼女は夏の暑さに耐えられない。" },
        { sentence: "These days, the rising prices ___ many families.", answer: "concern", base: "concern", hint: "c______", ja: "心配させる、関係する", sentenceJa: "近頃、物価の上昇は多くの家庭を心配させている。" },
        { sentence: "I didn't ___ her with her new haircut.", answer: "recognize", base: "recognize", hint: "r________", ja: "認識する、見分ける、認める", sentenceJa: "新しい髪型の彼女だと気づかなかった。" },
        { sentence: "The dog likes to ___ holes in the garden.", answer: "dig", base: "dig", hint: "d__", ja: "掘る", sentenceJa: "その犬は庭に穴を掘るのが好きだ。" },
        { sentence: "Last night, the fire ___ quickly through the dry forest.", answer: "spread", base: "spread", hint: "s_____", ja: "広げる、広がる", sentenceJa: "昨夜、火は乾燥した森の中に素早く広がった。" },
        { sentence: "Please don't ___ her while she is studying.", answer: "disturb", base: "disturb", hint: "d______", ja: "邪魔する", sentenceJa: "勉強している間は彼女の邪魔をしないでください。" },
        { sentence: "Yesterday, she ___ the difficult question very calmly.", answer: "handled", base: "handle", hint: "h______", ja: "扱う、対処する、手を触れる", sentenceJa: "昨日、彼女はその難しい質問にとても冷静に対応した。" },
        { sentence: "Don't ___ water while brushing your teeth.", answer: "waste", base: "waste", hint: "w____", ja: "無駄にする", sentenceJa: "歯を磨いている間、水を無駄にしないで。" },
        { sentence: "I will ___ a meeting for next week.", answer: "arrange", base: "arrange", hint: "a______", ja: "手配する、整える", sentenceJa: "来週の会議を手配します。" },
        { sentence: "These days, many people ___ advice before making a big decision.", answer: "seek", base: "seek", hint: "s___", ja: "探し求める", sentenceJa: "近頃、多くの人は大きな決断をする前に助言を求める。" },
        { sentence: "The company currently ___ fresh vegetables to the school.", answer: "supplies", base: "supply", hint: "s_______", ja: "供給する", sentenceJa: "その会社は現在、学校に新鮮な野菜を供給している。" },
        { sentence: "Let's ___ the cake among the four of us.", answer: "divide", base: "divide", hint: "d_____", ja: "分ける、割る", sentenceJa: "ケーキを私たち4人で分けよう。" },
        { sentence: "We need to ___ early to catch the train.", answer: "leave", base: "leave", hint: "l____", ja: "去る、残す、置き忘れる", sentenceJa: "電車に間に合うように早く出発する必要がある。" },
        { sentence: "Please ___ the guide through the museum.", answer: "follow", base: "follow", hint: "f_____", ja: "ついていく、従う", sentenceJa: "博物館ではガイドについて行ってください。" },
        { sentence: "She likes to ___ pictures of animals.", answer: "draw", base: "draw", hint: "d___", ja: "描く、引く", sentenceJa: "彼女は動物の絵を描くのが好きだ。" },
        { sentence: "Last night, snow ___ the entire mountain in white.", answer: "covered", base: "cover", hint: "c______", ja: "覆う、（話題を）扱う", sentenceJa: "昨夜、雪が山全体を白く覆った。" },
        { sentence: "Childhood experiences often ___ our personalities.", answer: "shape", base: "shape", hint: "s____", ja: "形作る", sentenceJa: "幼少期の経験はしばしば私たちの性格を形作る。" },
        { sentence: "Please ___ seated until the bus stops.", answer: "remain", base: "remain", hint: "r_____", ja: "とどまる、～のままである、残る", sentenceJa: "バスが停止するまで座ったままでいてください。" },
      ],
    },
    {
      name: "Day 2",
      items: [
        { sentence: "Please ___ the plastic from the paper waste.", answer: "separate", base: "separate", hint: "s_______", ja: "分ける、分離する", sentenceJa: "プラスチックと紙ゴミを分けてください。" },
        { sentence: "Yesterday, she ___ to finish the report on time.", answer: "managed", base: "manage", hint: "m______", ja: "なんとかやり遂げる、管理する", sentenceJa: "昨日、彼女は何とか時間通りにレポートを終わらせた。" },
        { sentence: "Last week, the storm ___ us to cancel the trip.", answer: "forced", base: "force", hint: "f_____", ja: "強制する", sentenceJa: "先週、嵐のせいで私たちは旅行を中止せざるを得なかった。" },
        { sentence: "If you don't hurry, you'll ___ the bus.", answer: "miss", base: "miss", hint: "m___", ja: "逃す、寂しく思う", sentenceJa: "急がないとバスに乗り遅れますよ。" },
        { sentence: "This job currently ___ good communication skills.", answer: "requires", base: "require", hint: "r_______", ja: "必要とする", sentenceJa: "この仕事は現在、優れたコミュニケーション能力を必要としている。" },
        { sentence: "A ticket to the concert currently ___ fifty dollars.", answer: "costs", base: "cost", hint: "c____", ja: "（費用が）かかる", sentenceJa: "コンサートのチケットは現在50ドルする。" },
        { sentence: "This umbrella currently ___ to my sister.", answer: "belongs", base: "belong", hint: "b______", ja: "所属する、～のものである", sentenceJa: "この傘は今、私の妹のものだ。" },
        { sentence: "Can you ___ the man you saw?", answer: "describe", base: "describe", hint: "d_______", ja: "描写する、説明する", sentenceJa: "あなたが見た男性について説明してもらえますか？" },
        { sentence: "These days, she ___ the piano for an hour every day.", answer: "practices", base: "practice", hint: "p________", ja: "練習する", sentenceJa: "最近、彼女は毎日1時間ピアノを練習している。" },
        { sentence: "Loud noises usually ___ me when I'm studying.", answer: "bother", base: "bother", hint: "b_____", ja: "悩ます、わざわざ～する", sentenceJa: "勉強しているとき、大きな音はたいてい私を悩ませる。" },
        { sentence: "Please don't ___ answers from your classmate.", answer: "copy", base: "copy", hint: "c___", ja: "複写する、まねる", sentenceJa: "クラスメートの答えを写さないでください。" },
        { sentence: "Last night, he ___ on paying for dinner.", answer: "insisted", base: "insist", hint: "i_______", ja: "強く主張する", sentenceJa: "昨夜、彼は夕食代を払うと強く主張した。" },
        { sentence: "Be quiet as you ___ the sleeping baby.", answer: "approach", base: "approach", hint: "a_______", ja: "近づく", sentenceJa: "眠っている赤ちゃんに近づくときは静かにしてください。" },
        { sentence: "Please ___ me to call the dentist.", answer: "remind", base: "remind", hint: "r_____", ja: "思い出させる", sentenceJa: "歯医者に電話するのを私に思い出させてください。" },
        { sentence: "The two brothers often ___ about small things.", answer: "argue", base: "argue", hint: "a____", ja: "言い争う、主張する", sentenceJa: "その二人の兄弟はよく些細なことで言い争う。" },
        { sentence: "The band will ___ at the school festival.", answer: "perform", base: "perform", hint: "p______", ja: "行う、演じる", sentenceJa: "そのバンドは学園祭で演奏する予定だ。" },
        { sentence: "They had to ___ the game because of the rain.", answer: "cancel", base: "cancel", hint: "c_____", ja: "中止する、キャンセルする", sentenceJa: "雨のため、彼らは試合を中止しなければならなかった。" },
        { sentence: "Washing your hands can ___ illness.", answer: "prevent", base: "prevent", hint: "p______", ja: "防ぐ", sentenceJa: "手を洗うことは病気を防ぐことができる。" },
        { sentence: "Could you help me ___ these boxes?", answer: "carry", base: "carry", hint: "c____", ja: "運ぶ", sentenceJa: "これらの箱を運ぶのを手伝ってもらえますか？" },
      ],
    },
    {
      name: "Day 3",
      items: [
        { sentence: "She hired a ___ to help with her math.", answer: "tutor", base: "tutor", hint: "t____", ja: "家庭教師、個別指導者", sentenceJa: "彼女は数学を手伝ってもらうために家庭教師を雇った。" },
        { sentence: "He made a good ___ at the interview.", answer: "impression", base: "impression", hint: "i_________", ja: "印象", sentenceJa: "彼は面接で良い印象を与えた。" },
        { sentence: "The ambassador lives in an official ___.", answer: "residence", base: "residence", hint: "r________", ja: "住居、邸宅", sentenceJa: "大使は公邸に住んでいる。" },
        { sentence: "I downloaded the latest ___ of the app.", answer: "version", base: "version", hint: "v______", ja: "版、バージョン", sentenceJa: "私はそのアプリの最新版をダウンロードした。" },
        { sentence: "The ___ takes one year to circle the sun.", answer: "earth", base: "earth", hint: "e____", ja: "地球、大地", sentenceJa: "地球は太陽の周りを一周するのに一年かかる。" },
        { sentence: "Pollution has a serious ___ on the environment.", answer: "effect", base: "effect", hint: "e_____", ja: "影響、効果", sentenceJa: "汚染は環境に深刻な影響を与える。" },
        { sentence: "She passed the exam through hard ___.", answer: "effort", base: "effort", hint: "e_____", ja: "努力", sentenceJa: "彼女は努力の末、試験に合格した。" },
        { sentence: "The snacks are in the third ___ of the store.", answer: "aisle", base: "aisle", hint: "a____", ja: "通路", sentenceJa: "お菓子はその店の3番目の通路にある。" },
        { sentence: "Swimming is my favorite weekend ___.", answer: "activity", base: "activity", hint: "a_______", ja: "活動", sentenceJa: "水泳は私のお気に入りの週末の活動だ。" },
        { sentence: "The hero is the most popular ___ in the book.", answer: "character", base: "character", hint: "c________", ja: "性格、登場人物", sentenceJa: "その主人公はその本で最も人気のある登場人物だ。" },
        { sentence: "Children seem to have endless ___.", answer: "energy", base: "energy", hint: "e_____", ja: "エネルギー、活力", sentenceJa: "子どもたちは無限のエネルギーを持っているようだ。" },
        { sentence: "The ___ of the word is Latin.", answer: "origin", base: "origin", hint: "o_____", ja: "起源、由来", sentenceJa: "その単語の起源はラテン語だ。" },
        { sentence: "She raised an ___ to the new plan.", answer: "objection", base: "objection", hint: "o________", ja: "反対、異議", sentenceJa: "彼女は新しい計画に異議を唱えた。" },
        { sentence: "This is an effective ___ for learning words.", answer: "method", base: "method", hint: "m_____", ja: "方法", sentenceJa: "これは単語を覚えるのに効果的な方法だ。" },
        { sentence: "She kept her many ___ to herself during the meeting.", answer: "thoughts", base: "thought", hint: "t_______", ja: "考え、思考", sentenceJa: "彼女は会議中、多くの考えを自分の中にとどめておいた。" },
        { sentence: "The old house was in a poor ___.", answer: "state", base: "state", hint: "s____", ja: "状態", sentenceJa: "その古い家はひどい状態だった。" },
        { sentence: "We enjoyed the beauty of ___ on our hike.", answer: "nature", base: "nature", hint: "n_____", ja: "自然、性質", sentenceJa: "私たちはハイキングで自然の美しさを楽しんだ。" },
        { sentence: "She sent her ___ for the scholarship.", answer: "application", base: "application", hint: "a__________", ja: "申し込み、応用、アプリ", sentenceJa: "彼女は奨学金のための申込書を送った。" },
        { sentence: "The painting has great ___ to collectors.", answer: "value", base: "value", hint: "v____", ja: "価値", sentenceJa: "その絵画はコレクターにとって大きな価値がある。" },
        { sentence: "The teacher explained the ___ calmly.", answer: "situation", base: "situation", hint: "s________", ja: "状況", sentenceJa: "先生はその状況を落ち着いて説明した。" },
      ],
    },
    {
      name: "Day 4",
      items: [
        { sentence: "Call this number in case of an ___.", answer: "emergency", base: "emergency", hint: "e________", ja: "緊急事態", sentenceJa: "緊急時はこの番号に電話してください。" },
        { sentence: "She deserves ___ for her hard work.", answer: "credit", base: "credit", hint: "c_____", ja: "信用、功績、クレジット", sentenceJa: "彼女は頑張った分の評価を受けるに値する。" },
        { sentence: "The ___ of the lake was perfectly calm.", answer: "surface", base: "surface", hint: "s______", ja: "表面", sentenceJa: "湖の水面は完全に穏やかだった。" },
        { sentence: "We asked the waiter for the ___.", answer: "bill", base: "bill", hint: "b___", ja: "請求書、勘定", sentenceJa: "私たちはウェイターに会計をお願いした。" },
        { sentence: "This is an important ___ we must discuss.", answer: "matter", base: "matter", hint: "m_____", ja: "事柄、問題", sentenceJa: "これは私たちが話し合わなければならない重要な問題だ。" },
        { sentence: "The clown's tricks were a source of ___.", answer: "amusement", base: "amusement", hint: "a________", ja: "楽しみ、娯楽", sentenceJa: "ピエロの芸は楽しみの種だった。" },
        { sentence: "The neighbors live together in ___.", answer: "harmony", base: "harmony", hint: "h______", ja: "調和", sentenceJa: "隣人たちは調和して暮らしている。" },
        { sentence: "The hotel room has a beautiful ___ of the sea.", answer: "view", base: "view", hint: "v___", ja: "眺め、見解", sentenceJa: "そのホテルの部屋からは海の美しい眺めが見える。" },
        { sentence: "The teacher praised the students' good ___.", answer: "behavior", base: "behavior", hint: "b_______", ja: "行動、ふるまい", sentenceJa: "先生は生徒たちの良い行動を褒めた。" },
        { sentence: "There was a long ___ before she answered.", answer: "pause", base: "pause", hint: "p____", ja: "休止、間", sentenceJa: "彼女が答える前に長い間があった。" },
        { sentence: "She learned a new ___ for painting.", answer: "technique", base: "technique", hint: "t________", ja: "技術、手法", sentenceJa: "彼女は絵を描く新しい技法を学んだ。" },
        { sentence: "There is a growing ___ toward healthy eating.", answer: "trend", base: "trend", hint: "t____", ja: "傾向、流行", sentenceJa: "健康的な食事を求める傾向が高まっている。" },
        { sentence: "The temperature dropped by ten ___ overnight.", answer: "degrees", base: "degree", hint: "d______", ja: "度、学位、程度", sentenceJa: "気温は一晩で10度下がった。" },
        { sentence: "He was late because of a traffic ___.", answer: "accident", base: "accident", hint: "a_______", ja: "事故、偶然", sentenceJa: "彼は交通事故のせいで遅刻した。" },
        { sentence: "I do the ___ every Sunday morning.", answer: "laundry", base: "laundry", hint: "l______", ja: "洗濯（物）", sentenceJa: "私は毎週日曜日の朝に洗濯をする。" },
        { sentence: "She gave an excellent ___ in class.", answer: "presentation", base: "presentation", hint: "p___________", ja: "発表、プレゼン", sentenceJa: "彼女は授業で素晴らしい発表をした。" },
        { sentence: "He has a strong ___ of heights.", answer: "fear", base: "fear", hint: "f___", ja: "恐怖", sentenceJa: "彼は高所に対する強い恐怖心を持っている。" },
        { sentence: "This is a popular ___ for taking photos.", answer: "spot", base: "spot", hint: "s___", ja: "場所、斑点", sentenceJa: "ここは写真を撮るのに人気のある場所だ。" },
        { sentence: "Read all the ___ carefully before you start.", answer: "instructions", base: "instruction", hint: "i___________", ja: "指示、説明", sentenceJa: "始める前にすべての指示をよく読んでください。" },
        { sentence: "He ran for office as an ___.", answer: "independent", base: "independent", hint: "i__________", ja: "独立した人・もの", sentenceJa: "彼は無所属で立候補した。" },
      ],
    },
    {
      name: "Day 5",
      items: [
        { sentence: "We wore ___ clothes at the festival.", answer: "traditional", base: "traditional", hint: "t__________", ja: "伝統的な", sentenceJa: "私たちは祭りで伝統的な服を着た。" },
        { sentence: "The volunteer work gave her ___ experience.", answer: "valuable", base: "valuable", hint: "v_______", ja: "貴重な、価値のある", sentenceJa: "そのボランティア活動は彼女に貴重な経験を与えた。" },
        { sentence: "He wants to become a ___ soccer player.", answer: "professional", base: "professional", hint: "p___________", ja: "プロの、専門的な", sentenceJa: "彼はプロのサッカー選手になりたいと思っている。" },
        { sentence: "Can you tell me the ___ time of the meeting?", answer: "exact", base: "exact", hint: "e____", ja: "正確な", sentenceJa: "会議の正確な時間を教えてもらえますか？" },
        { sentence: "Smith is a very ___ family name in England.", answer: "common", base: "common", hint: "c_____", ja: "一般的な、共通の", sentenceJa: "スミスはイギリスでとても一般的な姓だ。" },
        { sentence: "Sushi is made with ___ fish.", answer: "raw", base: "raw", hint: "r__", ja: "生の、未加工の", sentenceJa: "寿司は生の魚で作られる。" },
        { sentence: "There is a ___ library near the station.", answer: "public", base: "public", hint: "p_____", ja: "公共の", sentenceJa: "駅の近くに公共図書館がある。" },
        { sentence: "Eating vegetables is part of a ___ diet.", answer: "healthy", base: "healthy", hint: "h______", ja: "健康的な、健康な", sentenceJa: "野菜を食べることは健康的な食事の一部だ。" },
        { sentence: "It is ___ to rain later this afternoon.", answer: "likely", base: "likely", hint: "l_____", ja: "ありそうな", sentenceJa: "今日の午後遅くに雨が降りそうだ。" },
        { sentence: "The two brothers have very ___ voices.", answer: "similar", base: "similar", hint: "s______", ja: "似ている", sentenceJa: "その兄弟は声がとてもよく似ている。" },
        { sentence: "Everyone should learn ___ first-aid skills.", answer: "basic", base: "basic", hint: "b____", ja: "基本的な", sentenceJa: "誰もが基本的な応急処置のスキルを学ぶべきだ。" },
        { sentence: "We had ___ chicken for dinner.", answer: "roast", base: "roast", hint: "r____", ja: "焼いた、ローストした", sentenceJa: "夕食にローストチキンを食べた。" },
        { sentence: "The earth is a large ___ object.", answer: "round", base: "round", hint: "r____", ja: "丸い", sentenceJa: "地球は大きな丸い物体だ。" },
        { sentence: "Do we have ___ chairs for everyone?", answer: "enough", base: "enough", hint: "e_____", ja: "十分な", sentenceJa: "全員分の十分な椅子はあるだろうか？" },
        { sentence: "We had a ___ walk in the park.", answer: "pleasant", base: "pleasant", hint: "p_______", ja: "快い、感じのよい", sentenceJa: "私たちは公園で気持ちのよい散歩をした。" },
        { sentence: "Please give a ___ example in your answer.", answer: "specific", base: "specific", hint: "s_______", ja: "具体的な、特定の", sentenceJa: "答えには具体的な例を挙げてください。" },
        { sentence: "These shoes are light and ___.", answer: "comfortable", base: "comfortable", hint: "c__________", ja: "快適な", sentenceJa: "この靴は軽くて快適だ。" },
        { sentence: "She ate the ___ pizza by herself.", answer: "whole", base: "whole", hint: "w____", ja: "全体の", sentenceJa: "彼女はピザを一人で全部食べた。" },
        { sentence: "The baby is finally ___.", answer: "asleep", base: "asleep", hint: "a_____", ja: "眠って", sentenceJa: "赤ちゃんはついに眠った。" },
        { sentence: "He showed off his ___ smartphone.", answer: "brand-new", base: "brand-new", hint: "b________", ja: "新品の", sentenceJa: "彼は新品のスマートフォンを見せびらかした。" },
      ],
    },
    {
      name: "Day 6",
      items: [
        { sentence: "There is an ___ charge for late delivery.", answer: "additional", base: "additional", hint: "a_________", ja: "追加の", sentenceJa: "延着の場合は追加料金がかかります。" },
        { sentence: "We need a ___ surface to set up the tent.", answer: "flat", base: "flat", hint: "f___", ja: "平らな", sentenceJa: "テントを張るには平らな地面が必要だ。" },
        { sentence: "She is a ___ author in Japan.", answer: "well-known", base: "well-known", hint: "w_________", ja: "有名な", sentenceJa: "彼女は日本で有名な作家だ。" },
        { sentence: "A ___ storm hit the coast last night.", answer: "violent", base: "violent", hint: "v______", ja: "暴力的な、激しい", sentenceJa: "昨夜、激しい嵐が海岸を襲った。" },
        { sentence: "The train was very ___ this morning.", answer: "crowded", base: "crowded", hint: "c______", ja: "混雑した", sentenceJa: "今朝の電車はとても混雑していた。" },
        { sentence: "Only a ___ students came to the early class.", answer: "few", base: "few", hint: "f__", ja: "ほとんどない、少しの", sentenceJa: "早朝の授業に来た学生はほとんどいなかった。" },
        { sentence: "The old town has many ___ streets.", answer: "narrow", base: "narrow", hint: "n_____", ja: "狭い", sentenceJa: "旧市街には狭い通りがたくさんある。" },
        { sentence: "Cut the bread into ___ slices.", answer: "thin", base: "thin", hint: "t___", ja: "薄い、細い", sentenceJa: "パンを薄く切ってください。" },
        { sentence: "My best friend lives ___ to my house.", answer: "close", base: "close", hint: "c____", ja: "近い、親しい", sentenceJa: "私の親友は私の家の近くに住んでいる。" },
        { sentence: "I am ___ that I locked the door.", answer: "certain", base: "certain", hint: "c______", ja: "確信して、確かな", sentenceJa: "私はドアに鍵をかけたと確信している。" },
        { sentence: "Do you have this shirt in any ___ colors?", answer: "other", base: "other", hint: "o____", ja: "ほかの", sentenceJa: "このシャツはほかの色もありますか。" },
        { sentence: "Rain is ___ weather for this season.", answer: "typical", base: "typical", hint: "t______", ja: "典型的な", sentenceJa: "雨はこの季節の典型的な天気だ。" },
        { sentence: "She is ___ of the dark.", answer: "afraid", base: "afraid", hint: "a_____", ja: "恐れて、心配して", sentenceJa: "彼女は暗闇を恐れている。" },
        { sentence: "We will meet again the ___ week.", answer: "following", base: "following", hint: "f________", ja: "次の", sentenceJa: "私たちは次の週にまた会う予定だ。" },
        { sentence: "Is there a ___ train to the airport?", answer: "direct", base: "direct", hint: "d_____", ja: "直接の", sentenceJa: "空港まで直通の電車はありますか。" },
        { sentence: "This old book is ___ a lot of money.", answer: "worth", base: "worth", hint: "w____", ja: "～の価値がある", sentenceJa: "この古い本は大金の価値がある。" },
        { sentence: "The bottle is completely ___.", answer: "empty", base: "empty", hint: "e____", ja: "空の", sentenceJa: "そのボトルは完全に空だ。" },
        { sentence: "He ___ eats fast food.", answer: "rarely", base: "rarely", hint: "r_____", ja: "めったに～ない", sentenceJa: "彼はめったにファストフードを食べない。" },
        { sentence: "I have been to Kyoto only ___.", answer: "once", base: "once", hint: "o___", ja: "一度、かつて", sentenceJa: "私は一度しか京都に行ったことがない。" },
        { sentence: "The shop was ___ a small bakery.", answer: "originally", base: "originally", hint: "o_________", ja: "もともと、最初は", sentenceJa: "その店はもともと小さなパン屋だった。" },
      ],
    },
    {
      name: "Day 7",
      items: [
        { sentence: "The train left at ___ nine o'clock.", answer: "exactly", base: "exactly", hint: "e______", ja: "正確に、ちょうど", sentenceJa: "電車はちょうど9時に出発した。" },
        { sentence: "Try to eat ___ and exercise more.", answer: "less", base: "less", hint: "l___", ja: "より少なく", sentenceJa: "食べる量を減らして、もっと運動するようにしてください。" },
        { sentence: "___, the weather will be sunny tomorrow.", answer: "hopefully", base: "hopefully", hint: "h________", ja: "願わくは、うまくいけば", sentenceJa: "願わくは、明日は晴れますように。" },
        { sentence: "The customers are ___ young students.", answer: "mostly", base: "mostly", hint: "m_____", ja: "たいてい、主に", sentenceJa: "お客さんはたいてい若い学生です。" },
        { sentence: "I ___ forgot about the meeting.", answer: "completely", base: "completely", hint: "c_________", ja: "完全に", sentenceJa: "私はその会議のことを完全に忘れていた。" },
        { sentence: "The flowers were arranged very ___.", answer: "nicely", base: "nicely", hint: "n_____", ja: "うまく、よく", sentenceJa: "花はとても上手に生けられていた。" },
        { sentence: "The test was ___ difficult this time.", answer: "rather", base: "rather", hint: "r_____", ja: "かなり、むしろ", sentenceJa: "今回のテストはかなり難しかった。" },
        { sentence: "The movie was ___ good, actually.", answer: "pretty", base: "pretty", hint: "p_____", ja: "かなり、なかなか", sentenceJa: "その映画は実際、かなり良かった。" },
        { sentence: "She wants to study ___ next year.", answer: "abroad", base: "abroad", hint: "a_____", ja: "海外で、海外へ", sentenceJa: "彼女は来年、海外に留学したいと思っている。" },
        { sentence: "He lives ___ in a small apartment.", answer: "alone", base: "alone", hint: "a____", ja: "一人で", sentenceJa: "彼は小さなアパートに一人で住んでいる。" },
        { sentence: "Have you finished your homework ___?", answer: "yet", base: "yet", hint: "y__", ja: "まだ、もう", sentenceJa: "もう宿題は終わった？" },
        { sentence: "She solved the puzzle ___.", answer: "easily", base: "easily", hint: "e_____", ja: "簡単に", sentenceJa: "彼女はそのパズルを簡単に解いた。" },
        { sentence: "I don't play that game ___.", answer: "anymore", base: "anymore", hint: "a______", ja: "もはや～ない", sentenceJa: "私はもうそのゲームをしない。" },
        { sentence: "You can call me ___ you need help.", answer: "anytime", base: "anytime", hint: "a______", ja: "いつでも", sentenceJa: "助けが必要なときはいつでも電話していいよ。" },
        { sentence: "It's cold today. It was warm yesterday, ___.", answer: "though", base: "though", hint: "t_____", ja: "でも、もっとも", sentenceJa: "今日は寒い。でも昨日は暖かかった。" },
        { sentence: "It was raining ___ all morning.", answer: "heavily", base: "heavily", hint: "h______", ja: "激しく、大量に", sentenceJa: "午前中ずっと激しく雨が降っていた。" },
        { sentence: "I'm ___ finished with my report.", answer: "almost", base: "almost", hint: "a_____", ja: "ほとんど", sentenceJa: "レポートはほとんど終わっている。" },
        { sentence: "After many tries, he ___ succeeded.", answer: "eventually", base: "eventually", hint: "e_________", ja: "結局、ついに", sentenceJa: "何度も挑戦した後、彼はついに成功した。" },
        { sentence: "I could ___ hear her quiet voice.", answer: "hardly", base: "hardly", hint: "h_____", ja: "ほとんど～ない", sentenceJa: "彼女の小さな声はほとんど聞こえなかった。" },
        { sentence: "The exam was ___ easy for most students.", answer: "quite", base: "quite", hint: "q____", ja: "かなり、まったく", sentenceJa: "試験はほとんどの生徒にとってかなり簡単だった。" },
      ],
    },
    {
      name: "Day 8",
      items: [
        { sentence: "Please call me ___ if there is a problem.", answer: "immediately", base: "immediately", hint: "i__________", ja: "すぐに", sentenceJa: "問題があれば、すぐに私に電話してください。" },
        { sentence: "We had dinner and went for a walk ___.", answer: "afterward", base: "afterward", hint: "a________", ja: "あとで", sentenceJa: "私たちは夕食をとり、その後散歩に行った。" },
        { sentence: "The café was closed, so we went to the park ___.", answer: "instead", base: "instead", hint: "i______", ja: "代わりに", sentenceJa: "そのカフェは閉まっていたので、代わりに公園へ行った。" },
        { sentence: "We'll go hiking ___ it rains.", answer: "unless", base: "unless", hint: "u_____", ja: "～でない限り", sentenceJa: "雨が降らない限り、ハイキングに行くつもりだ。" },
        { sentence: "___ it was raining, we enjoyed the trip.", answer: "although", base: "although", hint: "a_______", ja: "～だけれども", sentenceJa: "雨が降っていたけれども、私たちは旅行を楽しんだ。" },
        { sentence: "The shop is open every day ___ Sunday.", answer: "except", base: "except", hint: "e_____", ja: "～を除いて", sentenceJa: "その店は日曜日を除いて毎日営業している。" },
        { sentence: "The cat is hiding ___ the sofa.", answer: "behind", base: "behind", hint: "b_____", ja: "～の後ろに", sentenceJa: "猫はソファの後ろに隠れている。" },
        { sentence: "The mountains lie ___ the river.", answer: "beyond", base: "beyond", hint: "b_____", ja: "～の向こうに、～を超えて", sentenceJa: "山々は川の向こうにある。" },
        { sentence: "I can't read this menu ___ my glasses.", answer: "without", base: "without", hint: "w______", ja: "～なしで", sentenceJa: "メガネなしではこのメニューを読めない。" },
        { sentence: "___ her sister, she enjoys sports.", answer: "unlike", base: "unlike", hint: "u_____", ja: "～と違って", sentenceJa: "姉（妹）と違って、彼女はスポーツを楽しむ。" },
        { sentence: "Call me ___ you need help.", answer: "whenever", base: "whenever", hint: "w_______", ja: "～するときはいつでも", sentenceJa: "助けが必要なときはいつでも私に電話してください。" },
        { sentence: "Please reply ___ three days.", answer: "within", base: "within", hint: "w_____", ja: "～以内に、～の中で", sentenceJa: "3   日以内に返信してください。" },
      ],
    },
  ],
};
