// IELTS 単語テスト問題（9月「1ヶ月分」、osh-vocab-test/data/*.pyから自動生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
// Day7/14/21/28は復習日のため欠番
module.exports = {
  label: "IELTS",
  series: [
    {
      name: "Day 1",
      items: [
        { sentence: "Last year, researchers ___ the data from a large national survey.", answer: "obtained", base: "obtain", hint: "o_____", ja: "得る、入手する", sentenceJa: "昨年、研究者たちは大規模な全国調査からデータを入手した。" },
        { sentence: "Modern technology ___ communication between countries.", answer: "facilitates", base: "facilitate", hint: "f_________", ja: "促進する、容易にする", sentenceJa: "現代の技術は国家間のコミュニケーションを促進している。" },
        { sentence: "Children learn social skills by ___ with others.", answer: "interacting", base: "interact", hint: "i_______", ja: "相互に作用する、交流する", sentenceJa: "子供たちは他者と交流することで社会的スキルを学ぶ。" },
        { sentence: "It is difficult to ___ the two closely related species.", answer: "differentiate", base: "differentiate", hint: "d____________", ja: "区別する", sentenceJa: "近縁の2種を区別するのは難しい。" },
        { sentence: "Last month, the research team carefully ___ the results of the study.", answer: "interpreted", base: "interpret", hint: "i________", ja: "解釈する", sentenceJa: "先月、研究チームは研究結果を慎重に解釈した。" },
        { sentence: "Last month, researchers ___ the temperature to test the reaction.", answer: "manipulated", base: "manipulate", hint: "m_________", ja: "操作する", sentenceJa: "先月、研究者たちは反応を調べるために温度を操作した。" },
        { sentence: "Currently, this solar panel ___ enough electricity for one household.", answer: "generates", base: "generate", hint: "g_______", ja: "生み出す、発生させる", sentenceJa: "現在、この太陽光パネルは一世帯分の電気を発電している。" },
        { sentence: "It is hard to ___ of a society without any rules.", answer: "conceive", base: "conceive", hint: "c_______", ja: "思いつく、想像する", sentenceJa: "ルールが全くない社会を思い描くのは難しい。" },
        { sentence: "The company ___ natural resources in the region.", answer: "exploits", base: "exploit", hint: "e______", ja: "活用する、搾取する", sentenceJa: "その会社はその地域の天然資源を活用している。" },
        { sentence: "Last year, limited funding ___ the scope of the research.", answer: "constrained", base: "constrain", hint: "c________", ja: "制約する", sentenceJa: "昨年、限られた資金が研究の範囲を制約した。" },
        { sentence: "Many modern English words are ___ from Latin and Greek.", answer: "derived", base: "derive", hint: "d_____", ja: "（～から）得る、由来する", sentenceJa: "多くの現代英語の単語はラテン語やギリシャ語に由来している。" },
        { sentence: "Certain chemicals can ___ changes in cell growth.", answer: "induce", base: "induce", hint: "i_____", ja: "引き起こす、誘発する", sentenceJa: "特定の化学物質は細胞の成長に変化を引き起こすことがある。" },
        { sentence: "This painting still ___ a busy market in the old city.", answer: "depicts", base: "depict", hint: "d_____", ja: "描く、表現する", sentenceJa: "この絵は今も旧市街の賑やかな市場を描いている。" },
        { sentence: "To this day, the author ___ that education reduces inequality.", answer: "asserts", base: "assert", hint: "a_____", ja: "主張する、断言する", sentenceJa: "今日に至るまで、その著者は教育が不平等を減らすと主張している。" },
        { sentence: "The school aims to ___ technology into every subject.", answer: "integrate", base: "integrate", hint: "i________", ja: "統合する", sentenceJa: "その学校はあらゆる科目に技術を統合することを目指している。" },
        { sentence: "The government may ___ when prices rise too sharply.", answer: "intervene", base: "intervene", hint: "i________", ja: "介入する", sentenceJa: "価格が急激に上昇した場合、政府が介入することがある。" },
        { sentence: "The teacher tried to ___ the difficult concept.", answer: "clarify", base: "clarify", hint: "c______", ja: "明確にする", sentenceJa: "先生はその難しい概念を明確にしようとした。" },
        { sentence: "Currently, a few large firms ___ the global market.", answer: "dominate", base: "dominate", hint: "d_______", ja: "支配する、優位を占める", sentenceJa: "現在、少数の大企業が世界市場を支配している。" },
        { sentence: "The city has ___ major changes in recent decades.", answer: "undergone", base: "undergo", hint: "u______", ja: "経験する、受ける", sentenceJa: "その都市はここ数十年で大きな変化を経験した。" },
        { sentence: "Even now, sediment ___ slowly at the bottom of the lake.", answer: "accumulates", base: "accumulate", hint: "a_________", ja: "蓄積する", sentenceJa: "今でも、堆積物は湖の底にゆっくりと蓄積している。" },
      ],
    },
    {
      name: "Day 2",
      items: [
        { sentence: "The government will ___ more funds to public health.", answer: "allocate", base: "allocate", hint: "a_______", ja: "割り当てる、配分する", sentenceJa: "政府は公衆衛生にさらに多くの資金を割り当てる予定だ。" },
        { sentence: "Extra training can ___ for a lack of experience.", answer: "compensate", base: "compensate", hint: "c_________", ja: "埋め合わせる、補償する", sentenceJa: "追加の訓練は経験不足を埋め合わせることができる。" },
        { sentence: "Generally, scientists ___ living things into several kingdoms.", answer: "classify", base: "classify", hint: "c_______", ja: "分類する", sentenceJa: "一般的に、科学者は生物をいくつかの界に分類する。" },
        { sentence: "We should ___ water during the dry season.", answer: "conserve", base: "conserve", hint: "c_______", ja: "保存する、節約する", sentenceJa: "乾季には水を節約すべきだ。" },
        { sentence: "Generally, plants ___ sunlight into energy.", answer: "convert", base: "convert", hint: "c______", ja: "変える、転換する", sentenceJa: "一般的に、植物は太陽光をエネルギーに変換する。" },
        { sentence: "The new system aims to ___ waste.", answer: "eliminate", base: "eliminate", hint: "e________", ja: "排除する", sentenceJa: "新しいシステムは無駄を排除することを目指している。" },
        { sentence: "Reading widely can ___ your writing skills.", answer: "enhance", base: "enhance", hint: "e______", ja: "高める、向上させる", sentenceJa: "幅広く読書することは文章力を高めることができる。" },
        { sentence: "Experts ___ that the population will double by 2050.", answer: "estimate", base: "estimate", hint: "e_______", ja: "推定する、見積もる", sentenceJa: "専門家は2050年までに人口が倍増すると推定している。" },
        { sentence: "Teachers ___ students through exams and projects.", answer: "evaluate", base: "evaluate", hint: "e_______", ja: "評価する", sentenceJa: "教師は試験や課題を通して生徒を評価する。" },
        { sentence: "This study ___ the effects of stress on health.", answer: "examines", base: "examine", hint: "e______", ja: "詳しく調べる", sentenceJa: "この研究はストレスが健康に与える影響を詳しく調べている。" },
        { sentence: "These results ___ a clear link between diet and health.", answer: "demonstrate", base: "demonstrate", hint: "d__________", ja: "実証する、示す", sentenceJa: "これらの結果は食事と健康の明確な関連性を示している。" },
        { sentence: "New evidence has ___ about the cause of the illness.", answer: "emerged", base: "emerge", hint: "e_____", ja: "現れる、明らかになる", sentenceJa: "その病気の原因について新たな証拠が明らかになった。" },
        { sentence: "Last month, engineers ___ the design to reduce the cost.", answer: "modified", base: "modify", hint: "m_____", ja: "修正する、変更する", sentenceJa: "先月、エンジニアはコストを削減するために設計を変更した。" },
        { sentence: "Burning fossil fuels ___ to climate change.", answer: "contributes", base: "contribute", hint: "c_________", ja: "貢献する、一因となる", sentenceJa: "化石燃料の燃焼は気候変動の一因となっている。" },
        { sentence: "Generally, children ___ language quickly in their early years.", answer: "acquire", base: "acquire", hint: "a______", ja: "習得する、獲得する", sentenceJa: "一般的に、子供は幼少期に言語を素早く習得する。" },
        { sentence: "Doctors always ___ each patient before deciding on treatment.", answer: "assess", base: "assess", hint: "a_____", ja: "評価する、査定する", sentenceJa: "医師はいつも、治療方針を決める前に各患者を評価する。" },
        { sentence: "Wealth is not evenly ___ across the country.", answer: "distributed", base: "distribute", hint: "d_________", ja: "分配する、分布させる", sentenceJa: "富はその国全体に均等に分配されていない。" },
        { sentence: "This survey ___ that most people support the plan.", answer: "indicates", base: "indicate", hint: "i_______", ja: "示す、示唆する", sentenceJa: "この調査は大多数の人がその計画を支持していることを示している。" },
        { sentence: "These findings ___ the need for stricter rules.", answer: "reinforce", base: "reinforce", hint: "r________", ja: "強化する、補強する", sentenceJa: "これらの調査結果はより厳格な規則の必要性を強化している。" },
        { sentence: "It is hard to ___ economic growth for many years.", answer: "sustain", base: "sustain", hint: "s______", ja: "維持する、持続させる", sentenceJa: "長年にわたって経済成長を維持することは難しい。" },
      ],
    },
    {
      name: "Day 3",
      items: [
        { sentence: "The experiment was designed to test the ___.", answer: "hypothesis", base: "hypothesis", hint: "h_________", ja: "仮説", sentenceJa: "その実験は仮説を検証するために設計された。" },
        { sentence: "The essay examines several ___ of urban life.", answer: "aspects", base: "aspect", hint: "a_____", ja: "側面、観点", sentenceJa: "そのエッセイは都市生活のいくつかの側面を考察している。" },
        { sentence: "Applications are judged against three main ___.", answer: "criteria", base: "criteria", hint: "c_______", ja: "基準", sentenceJa: "応募は3つの主要な基準に基づいて審査される。" },
        { sentence: "The company has a strict ___ of management.", answer: "hierarchy", base: "hierarchy", hint: "h________", ja: "階層、序列", sentenceJa: "その会社には厳格な管理階層がある。" },
        { sentence: "Global warming is a worldwide ___.", answer: "phenomenon", base: "phenomenon", hint: "p_________", ja: "現象", sentenceJa: "地球温暖化は世界的な現象である。" },
        { sentence: "Scientists have reached a ___ on climate change.", answer: "consensus", base: "consensus", hint: "c________", ja: "合意、総意", sentenceJa: "科学者たちは気候変動について合意に達した。" },
        { sentence: "She faced a ___ between work and family.", answer: "dilemma", base: "dilemma", hint: "d______", ja: "ジレンマ、板挟み", sentenceJa: "彼女は仕事と家庭の間でジレンマに直面した。" },
        { sentence: "The study provides a useful ___ for future research.", answer: "framework", base: "framework", hint: "f________", ja: "枠組み", sentenceJa: "その研究は今後の研究に役立つ枠組みを提供している。" },
        { sentence: "The ___ of the disease has fallen in recent years.", answer: "incidence", base: "incidence", hint: "i________", ja: "発生率", sentenceJa: "その病気の発生率は近年低下している。" },
        { sentence: "The country invested heavily in its ___.", answer: "infrastructure", base: "infrastructure", hint: "i_____________", ja: "インフラ、社会基盤", sentenceJa: "その国はインフラに多額の投資をした。" },
        { sentence: "The researchers explained their ___ in detail.", answer: "methodology", base: "methodology", hint: "m__________", ja: "方法論", sentenceJa: "研究者たちは自分たちの方法論を詳しく説明した。" },
        { sentence: "Working from home has become the ___ for many people.", answer: "norm", base: "norm", hint: "n___", ja: "規範、標準", sentenceJa: "在宅勤務は多くの人にとって当たり前のことになった。" },
        { sentence: "The ___ of the election surprised many people.", answer: "outcome", base: "outcome", hint: "o______", ja: "結果", sentenceJa: "選挙の結果は多くの人を驚かせた。" },
        { sentence: "It is a ___ that the wealthiest nations waste the most food.", answer: "paradox", base: "paradox", hint: "p______", ja: "逆説、矛盾", sentenceJa: "最も裕福な国々が最も多くの食料を無駄にしているのは逆説的だ。" },
        { sentence: "The book offers a fresh ___ on history.", answer: "perspective", base: "perspective", hint: "p__________", ja: "観点、見方", sentenceJa: "その本は歴史について新しい視点を提供している。" },
        { sentence: "There is a wide ___ in income between regions.", answer: "disparity", base: "disparity", hint: "d________", ja: "格差、相違", sentenceJa: "地域間の所得格差は大きい。" },
        { sentence: "The ___ that the earth was flat lasted for centuries.", answer: "notion", base: "notion", hint: "n_____", ja: "観念、概念", sentenceJa: "地球が平らだという考えは何世紀にもわたって続いた。" },
        { sentence: "The ecosystem maintains a delicate ___.", answer: "equilibrium", base: "equilibrium", hint: "e__________", ja: "均衡", sentenceJa: "その生態系は微妙な均衡を保っている。" },
        { sentence: "Each branch operates as a separate legal ___.", answer: "entity", base: "entity", hint: "e_____", ja: "存在、実体", sentenceJa: "各支店は独立した法人として運営されている。" },
        { sentence: "The ___ of the internet changed daily life.", answer: "emergence", base: "emergence", hint: "e________", ja: "出現", sentenceJa: "インターネットの出現は日常生活を変えた。" },
      ],
    },
    {
      name: "Day 4",
      items: [
        { sentence: "A careful ___ of the data revealed a clear pattern.", answer: "analysis", base: "analysis", hint: "a_______", ja: "分析", sentenceJa: "データの慎重な分析により、明確なパターンが明らかになった。" },
        { sentence: "Diet is an important ___ in good health.", answer: "factor", base: "factor", hint: "f_____", ja: "要因", sentenceJa: "食事は健康にとって重要な要因である。" },
        { sentence: "Soil erosion is a serious ___ of deforestation.", answer: "consequence", base: "consequence", hint: "c__________", ja: "結果、影響", sentenceJa: "土壌浸食は森林伐採の深刻な結果である。" },
        { sentence: "The study has several important ___ for public policy.", answer: "implications", base: "implication", hint: "i__________", ja: "影響、含意", sentenceJa: "その研究は公共政策にとっていくつかの重要な影響を持つ。" },
        { sentence: "There is a growing ___ toward remote working.", answer: "trend", base: "trend", hint: "t____", ja: "傾向、動向", sentenceJa: "リモートワークへの傾向が高まっている。" },
        { sentence: "A large ___ of students own a smartphone.", answer: "proportion", base: "proportion", hint: "p_________", ja: "割合", sentenceJa: "学生の大部分がスマートフォンを持っている。" },
        { sentence: "The map shows the ___ of rainfall across the country.", answer: "distribution", base: "distribution", hint: "d___________", ja: "分布、分配", sentenceJa: "その地図は国内の降雨の分布を示している。" },
        { sentence: "There is a strong ___ between income and education.", answer: "correlation", base: "correlation", hint: "c__________", ja: "相関関係", sentenceJa: "収入と教育の間には強い相関関係がある。" },
        { sentence: "The experiment controlled every ___ except temperature.", answer: "variable", base: "variable", hint: "v_______", ja: "変数、変化要因", sentenceJa: "その実験は温度以外のすべての変数を制御した。" },
        { sentence: "Trust is a key ___ of any good relationship.", answer: "element", base: "element", hint: "e______", ja: "要素", sentenceJa: "信頼はどんな良い関係にとっても重要な要素である。" },
        { sentence: "There is strong ___ that exercise improves mood.", answer: "evidence", base: "evidence", hint: "e_______", ja: "証拠", sentenceJa: "運動が気分を改善するという強い証拠がある。" },
        { sentence: "The ___ of voters supported the new law.", answer: "majority", base: "majority", hint: "m_______", ja: "大多数", sentenceJa: "有権者の大多数が新しい法律を支持した。" },
        { sentence: "The city has changed greatly over the past ___.", answer: "decade", base: "decade", hint: "d_____", ja: "10年間", sentenceJa: "その都市はこの10年間で大きく変化した。" },
        { sentence: "The main ___ of the heart is to pump blood.", answer: "function", base: "function", hint: "f_______", ja: "機能", sentenceJa: "心臓の主な機能は血液を送り出すことである。" },
        { sentence: "Books in the library are arranged by ___.", answer: "category", base: "category", hint: "c_______", ja: "カテゴリー、分類", sentenceJa: "図書館の本はカテゴリー別に並べられている。" },
        { sentence: "Safety is the company's top ___.", answer: "priority", base: "priority", hint: "p_______", ja: "優先事項", sentenceJa: "安全はその会社の最優先事項である。" },
        { sentence: "Water is a precious natural ___.", answer: "resource", base: "resource", hint: "r_______", ja: "資源", sentenceJa: "水は貴重な天然資源である。" },
        { sentence: "The two groups have been in ___ for years.", answer: "conflict", base: "conflict", hint: "c_______", ja: "対立、紛争", sentenceJa: "その2つのグループは長年対立してきた。" },
        { sentence: "The country is going through a ___ to clean energy.", answer: "transition", base: "transition", hint: "t_________", ja: "移行、変遷", sentenceJa: "その国はクリーンエネルギーへの移行を経験している。" },
        { sentence: "The government is responsible for the ___ of its citizens.", answer: "welfare", base: "welfare", hint: "w______", ja: "福祉、幸福", sentenceJa: "政府は国民の福祉に責任がある。" },
      ],
    },
    {
      name: "Day 5",
      items: [
        { sentence: "There was a ___ increase in average temperatures.", answer: "significant", base: "significant", hint: "s__________", ja: "重要な、著しい", sentenceJa: "平均気温に著しい上昇があった。" },
        { sentence: "English is the ___ language in international business.", answer: "dominant", base: "dominant", hint: "d_______", ja: "支配的な、優勢な", sentenceJa: "英語は国際ビジネスにおいて支配的な言語である。" },
        { sentence: "The instructions were ___ about what to do.", answer: "explicit", base: "explicit", hint: "e_______", ja: "明示的な、明確な", sentenceJa: "指示は何をすべきかについて明確だった。" },
        { sentence: "The book gives a ___ overview of the subject.", answer: "comprehensive", base: "comprehensive", hint: "c____________", ja: "包括的な、総合的な", sentenceJa: "その本はそのテーマについて包括的な概要を示している。" },
        { sentence: "The city is home to a ___ range of cultures.", answer: "diverse", base: "diverse", hint: "d______", ja: "多様な", sentenceJa: "その都市には多様な文化がある。" },
        { sentence: "Some conflict is ___ in any large group.", answer: "inevitable", base: "inevitable", hint: "i_________", ja: "避けられない", sentenceJa: "どんな大きな集団にも、ある程度の対立は避けられない。" },
        { sentence: "The project required a ___ amount of money.", answer: "substantial", base: "substantial", hint: "s__________", ja: "かなりの、相当な", sentenceJa: "そのプロジェクトにはかなりの額のお金が必要だった。" },
        { sentence: "A good essay presents a ___ argument.", answer: "coherent", base: "coherent", hint: "c_______", ja: "首尾一貫した", sentenceJa: "良いエッセイは首尾一貫した論旨を示す。" },
        { sentence: "It was ___ that the new method had failed.", answer: "evident", base: "evident", hint: "e______", ja: "明白な", sentenceJa: "新しい方法が失敗したことは明白だった。" },
        { sentence: "The claim is supported by strong ___ evidence.", answer: "empirical", base: "empirical", hint: "e________", ja: "経験的な、実証的な", sentenceJa: "その主張は強力な実証的証拠に裏付けられている。" },
        { sentence: "Sleep plays a ___ role in learning and memory.", answer: "crucial", base: "crucial", hint: "c______", ja: "極めて重要な", sentenceJa: "睡眠は学習と記憶において極めて重要な役割を果たす。" },
        { sentence: "Please include only ___ information in your essay.", answer: "relevant", base: "relevant", hint: "r_______", ja: "関連のある", sentenceJa: "エッセイには関連のある情報だけを含めてください。" },
        { sentence: "The funding was barely ___ for the research.", answer: "adequate", base: "adequate", hint: "a_______", ja: "十分な、適切な", sentenceJa: "その研究資金はかろうじて十分な程度だった。" },
        { sentence: "The two species have ___ markings.", answer: "distinct", base: "distinct", hint: "d_______", ja: "明確に異なる", sentenceJa: "その2種は明確に異なる模様を持っている。" },
        { sentence: "The survey question was ___ and confused readers.", answer: "ambiguous", base: "ambiguous", hint: "a________", ja: "曖昧な", sentenceJa: "その調査質問は曖昧で、回答者を混乱させた。" },
        { sentence: "Building the bridge in one year is not ___.", answer: "feasible", base: "feasible", hint: "f_______", ja: "実行可能な", sentenceJa: "1   年でその橋を建設するのは実行可能ではない。" },
        { sentence: "Smartphones are now ___ among young people.", answer: "prevalent", base: "prevalent", hint: "p________", ja: "広く行き渡った", sentenceJa: "スマートフォンは今、若者の間で広く行き渡っている。" },
        { sentence: "The product went through ___ safety testing.", answer: "rigorous", base: "rigorous", hint: "r_______", ja: "厳密な、厳格な", sentenceJa: "その製品は厳密な安全性試験を受けた。" },
        { sentence: "The first test failed, but ___ attempts succeeded.", answer: "subsequent", base: "subsequent", hint: "s_________", ja: "その後の", sentenceJa: "最初のテストは失敗したが、その後の試みは成功した。" },
        { sentence: "Clean water is ___ for human health.", answer: "vital", base: "vital", hint: "v____", ja: "極めて重要な、不可欠な", sentenceJa: "清潔な水は人間の健康にとって極めて重要だ。" },
      ],
    },
    {
      name: "Day 6",
      items: [
        { sentence: "The two theories are ___ the same.", answer: "essentially", base: "essentially", hint: "e__________", ja: "本質的に", sentenceJa: "その2つの理論は本質的に同じだ。" },
        { sentence: "The author ___ states her main argument in the introduction.", answer: "explicitly", base: "explicitly", hint: "e_________", ja: "明確に", sentenceJa: "著者は序論で自身の主な主張を明確に述べている。" },
        { sentence: "The two approaches are ___ different.", answer: "fundamentally", base: "fundamentally", hint: "f____________", ja: "根本的に", sentenceJa: "その2つのアプローチは根本的に異なる。" },
        { sentence: "Rapid urbanization ___ leads to environmental pressure.", answer: "inevitably", base: "inevitably", hint: "i_________", ja: "必然的に", sentenceJa: "急速な都市化は必然的に環境への負荷につながる。" },
        { sentence: "This is ___ true in developing countries.", answer: "particularly", base: "particularly", hint: "p___________", ja: "特に", sentenceJa: "これは発展途上国において特に当てはまる。" },
        { sentence: "The theory was ___ rejected by most scientists.", answer: "initially", base: "initially", hint: "i________", ja: "最初は", sentenceJa: "その理論は当初、ほとんどの科学者に否定された。" },
        { sentence: "The argument is ___ consistent.", answer: "logically", base: "logically", hint: "l________", ja: "論理的に", sentenceJa: "その議論は論理的に一貫している。" },
        { sentence: "Several factors, ___ climate, affect crop yields.", answer: "notably", base: "notably", hint: "n______", ja: "特に、顕著に", sentenceJa: "気候をはじめとするいくつかの要因が農作物の収穫量に影響する。" },
        { sentence: "The findings were ___ published last year.", answer: "officially", base: "officially", hint: "o_________", ja: "正式に", sentenceJa: "その調査結果は昨年正式に発表された。" },
        { sentence: "The region remains ___ unstable.", answer: "politically", base: "politically", hint: "p__________", ja: "政治的に", sentenceJa: "その地域は政治的に不安定なままだ。" },
        { sentence: "Regular exercise ___ affects mental health.", answer: "positively", base: "positively", hint: "p_________", ja: "肯定的に", sentenceJa: "定期的な運動は精神的健康に良い影響を与える。" },
        { sentence: "The results can be ___ divided into three categories.", answer: "broadly", base: "broadly", hint: "b______", ja: "大まかに、広く", sentenceJa: "結果は大きく3つのカテゴリーに分けられる。" },
        { sentence: "Students are encouraged to read the text ___.", answer: "critically", base: "critically", hint: "c_________", ja: "批判的に、重大に", sentenceJa: "学生はそのテキストを批判的に読むよう奨励されている。" },
        { sentence: "The researcher ___ excluded outliers from the data.", answer: "deliberately", base: "deliberately", hint: "d___________", ja: "意図的に", sentenceJa: "その研究者は意図的に外れ値をデータから除外した。" },
        { sentence: "The policy was ___ beneficial in the short term.", answer: "economically", base: "economically", hint: "e___________", ja: "経済的に", sentenceJa: "その政策は短期的には経済的に有益だった。" },
        { sentence: "___, the region relied on agriculture.", answer: "historically", base: "historically", hint: "h___________", ja: "歴史的に", sentenceJa: "歴史的に、その地域は農業に依存していた。" },
        { sentence: "More ___, the study lacked a control group.", answer: "importantly", base: "importantly", hint: "i__________", ja: "重要なことに", sentenceJa: "さらに重要なことに、その研究には対照群が欠けていた。" },
        { sentence: "Each group worked ___ on the project.", answer: "independently", base: "independently", hint: "i____________", ja: "独立して", sentenceJa: "各グループはそのプロジェクトに独立して取り組んだ。" },
        { sentence: "Students were assessed ___.", answer: "individually", base: "individually", hint: "i___________", ja: "個別に", sentenceJa: "学生は個別に評価された。" },
        { sentence: "This is ___ one possible explanation.", answer: "merely", base: "merely", hint: "m_____", ja: "単に", sentenceJa: "これは単に考えられる説明の一つに過ぎない。" },
      ],
    },
    {
      name: "Day 8",
      items: [
        { sentence: "Last year, economic growth ___ in the second half of the year.", answer: "accelerated", base: "accelerate", hint: "a_________", ja: "加速する", sentenceJa: "昨年、経済成長は下半期に加速した。" },
        { sentence: "This report ___ a clear vision for future research.", answer: "articulates", base: "articulate", hint: "a_________", ja: "はっきり述べる", sentenceJa: "この報告書は今後の研究に向けた明確なビジョンをはっきりと述べている。" },
        { sentence: "Higher income tends to ___ with better health outcomes.", answer: "correlate", base: "correlate", hint: "c________", ja: "相関する", sentenceJa: "高い収入はより良い健康状態と相関する傾向がある。" },
        { sentence: "Schools should ___ critical thinking skills in students.", answer: "cultivate", base: "cultivate", hint: "c________", ja: "育成する、養う", sentenceJa: "学校は生徒の批判的思考力を育成すべきだ。" },
        { sentence: "Plastic waste can ___ the quality of marine ecosystems.", answer: "degrade", base: "degrade", hint: "d______", ja: "劣化させる", sentenceJa: "プラスチック廃棄物は海洋生態系の質を劣化させる可能性がある。" },
        { sentence: "The test is designed to ___ between the two groups.", answer: "discriminate", base: "discriminate", hint: "d___________", ja: "差別する、区別する", sentenceJa: "そのテストは2つのグループを区別するよう設計されている。" },
        { sentence: "Generally, salt ___ quickly in warm water.", answer: "dissolves", base: "dissolve", hint: "d_______", ja: "溶解する", sentenceJa: "一般的に、塩は温かい水にすぐに溶ける。" },
        { sentence: "Their opinions began to ___ as the debate continued.", answer: "diverge", base: "diverge", hint: "d______", ja: "分岐する、異なる", sentenceJa: "議論が続くにつれて彼らの意見は分かれ始めた。" },
        { sentence: "Could you ___ on that point?", answer: "elaborate", base: "elaborate", hint: "e________", ja: "詳しく説明する", sentenceJa: "その点について詳しく説明していただけますか。" },
        { sentence: "These findings ___ the importance of early intervention.", answer: "elevate", base: "elevate", hint: "e______", ja: "高める", sentenceJa: "これらの発見は早期介入の重要性を高めている。" },
        { sentence: "Last month, participants ___ signs of improved memory.", answer: "exhibited", base: "exhibit", hint: "e______", ja: "示す", sentenceJa: "先月、参加者は記憶力の改善の兆候を示した。" },
        { sentence: "Last month, researchers ___ key themes from the interview data.", answer: "extracted", base: "extract", hint: "e______", ja: "抽出する", sentenceJa: "先月、研究者たちはインタビューデータから主要なテーマを抽出した。" },
        { sentence: "Last month, the committee ___ a new set of guidelines.", answer: "formulated", base: "formulate", hint: "f________", ja: "策定する", sentenceJa: "先月、委員会は新しいガイドラインを策定した。" },
        { sentence: "Last year, scientists ___ that the virus spread through water.", answer: "hypothesized", base: "hypothesize", hint: "h__________", ja: "仮説を立てる", sentenceJa: "昨年、科学者たちはそのウイルスが水を介して広がったと仮説を立てた。" },
        { sentence: "This new curriculum ___ elements of both approaches.", answer: "incorporates", base: "incorporate", hint: "i__________", ja: "組み込む", sentenceJa: "この新しいカリキュラムは両方のアプローチの要素を組み込んでいる。" },
        { sentence: "Certain chemicals can ___ plant growth.", answer: "inhibit", base: "inhibit", hint: "i______", ja: "抑制する", sentenceJa: "特定の化学物質は植物の成長を抑制することがある。" },
        { sentence: "Competition among firms has ___ in recent years.", answer: "intensified", base: "intensify", hint: "i________", ja: "強める", sentenceJa: "近年、企業間の競争は激化している。" },
        { sentence: "This study ___ the causes of urban migration.", answer: "investigates", base: "investigate", hint: "i__________", ja: "調査する", sentenceJa: "この研究は都市への移住の原因を調査している。" },
        { sentence: "It is difficult to ___ a single cause for the decline.", answer: "isolate", base: "isolate", hint: "i______", ja: "分離する、孤立させる", sentenceJa: "衰退の単一の原因を特定するのは難しい。" },
        { sentence: "Last month, the organization ___ volunteers to help with relief efforts.", answer: "mobilized", base: "mobilize", hint: "m_______", ja: "動員する", sentenceJa: "先月、その団体は救援活動を手伝うためボランティアを動員した。" },
      ],
    },
    {
      name: "Day 9",
      items: [
        { sentence: "The government began to ___ the new emissions law.", answer: "enforce", base: "enforce", hint: "e______", ja: "施行する、強制する", sentenceJa: "政府は新しい排出規制法の施行を開始した。" },
        { sentence: "Researchers took steps to ___ the accuracy of their data.", answer: "ensure", base: "ensure", hint: "e_____", ja: "確実にする", sentenceJa: "研究者たちはデータの正確性を確実にするための対策を取った。" },
        { sentence: "Language continues to ___ over time.", answer: "evolve", base: "evolve", hint: "e_____", ja: "進化する", sentenceJa: "言語は時間とともに進化し続ける。" },
        { sentence: "The plan was carefully ___ over several months.", answer: "executed", base: "execute", hint: "e______", ja: "実行する", sentenceJa: "その計画は数ヶ月かけて慎重に実行された。" },
        { sentence: "Last month, the study ___ participants to varying levels of noise.", answer: "exposed", base: "expose", hint: "e_____", ja: "さらす", sentenceJa: "先月、その研究は参加者をさまざまなレベルの騒音にさらした。" },
        { sentence: "Generally, prices ___ depending on supply and demand.", answer: "fluctuate", base: "fluctuate", hint: "f________", ja: "変動する", sentenceJa: "一般的に、価格は需要と供給に応じて変動する。" },
        { sentence: "The program aims to ___ cooperation between countries.", answer: "foster", base: "foster", hint: "f_____", ja: "育む", sentenceJa: "そのプログラムは国家間の協力を育むことを目指している。" },
        { sentence: "The policy failed to ___ its original goals.", answer: "fulfill", base: "fulfill", hint: "f______", ja: "満たす、果たす", sentenceJa: "その政策は当初の目標を果たせなかった。" },
        { sentence: "This graph ___ the trend over the past decade.", answer: "illustrates", base: "illustrate", hint: "i_________", ja: "説明する、示す", sentenceJa: "このグラフは過去10年間の傾向を示している。" },
        { sentence: "Last year, the government ___ new restrictions on imports.", answer: "imposed", base: "impose", hint: "i_____", ja: "課す", sentenceJa: "昨年、政府は輸入に新たな制限を課した。" },
        { sentence: "Participants were asked to ___ about their family history.", answer: "inquire", base: "inquire", hint: "i______", ja: "尋ねる", sentenceJa: "参加者は家族の病歴について尋ねるよう求められた。" },
        { sentence: "Her research was ___ by earlier studies on memory.", answer: "inspired", base: "inspire", hint: "i______", ja: "触発する", sentenceJa: "彼女の研究は記憶に関する以前の研究から着想を得た。" },
        { sentence: "Last year, the university ___ a new grading policy.", answer: "instituted", base: "institute", hint: "i________", ja: "導入する、制定する", sentenceJa: "昨年、その大学は新しい成績評価方針を導入した。" },
        { sentence: "Noise can ___ with concentration during exams.", answer: "interfere", base: "interfere", hint: "i________", ja: "干渉する、妨げる", sentenceJa: "騒音は試験中の集中力を妨げることがある。" },
        { sentence: "Last month, the researchers ___ a new method for measuring stress.", answer: "introduced", base: "introduce", hint: "i________", ja: "導入する", sentenceJa: "先月、研究者たちはストレスを測定する新しい方法を導入した。" },
        { sentence: "Last year, the invasive species quickly ___ the local habitat.", answer: "invaded", base: "invade", hint: "i_____", ja: "侵入する", sentenceJa: "昨年、その侵略的な種はすぐに地域の生息地に侵入した。" },
        { sentence: "The author fails to ___ her main claim with evidence.", answer: "justify", base: "justify", hint: "j______", ja: "正当化する", sentenceJa: "著者は自身の主な主張を証拠によって正当化できていない。" },
        { sentence: "It is difficult to ___ against every possible risk.", answer: "legislate", base: "legislate", hint: "l________", ja: "法律を制定する", sentenceJa: "あらゆる可能性のあるリスクに対して法律を制定するのは難しい。" },
        { sentence: "Social media can ___ the effects of misinformation.", answer: "magnify", base: "magnify", hint: "m______", ja: "拡大する", sentenceJa: "ソーシャルメディアは誤情報の影響を拡大させることがある。" },
        { sentence: "This new law ___ stricter safety inspections.", answer: "mandates", base: "mandate", hint: "m______", ja: "義務付ける", sentenceJa: "この新しい法律はより厳格な安全点検を義務付けている。" },
      ],
    },
    {
      name: "Day 10",
      items: [
        { sentence: "The ___ of nutrients occurs mainly in the small intestine.", answer: "absorption", base: "absorption", hint: "a_________", ja: "吸収", sentenceJa: "栄養素の吸収は主に小腸で起こる。" },
        { sentence: "The study measured the ___ of particles in the experiment.", answer: "acceleration", base: "acceleration", hint: "a___________", ja: "加速", sentenceJa: "その研究は実験における粒子の加速度を測定した。" },
        { sentence: "The report points to an ___ of evidence supporting the theory.", answer: "accumulation", base: "accumulation", hint: "a___________", ja: "蓄積", sentenceJa: "その報告書はその理論を支持する証拠の蓄積を指摘している。" },
        { sentence: "___ to climate change is a major research focus.", answer: "adaptation", base: "adaptation", hint: "a_________", ja: "適応", sentenceJa: "気候変動への適応は主要な研究課題だ。" },
        { sentence: "University ___ rates have declined in recent years.", answer: "admission", base: "admission", hint: "a________", ja: "入学、認めること", sentenceJa: "近年、大学の入学率は低下している。" },
        { sentence: "The two universities formed a research ___.", answer: "alliance", base: "alliance", hint: "a_______", ja: "同盟", sentenceJa: "その2つの大学は研究同盟を結成した。" },
        { sentence: "The ___ of funding depends on the size of the project.", answer: "allocation", base: "allocation", hint: "a_________", ja: "割り当て", sentenceJa: "資金の割り当てはプロジェクトの規模による。" },
        { sentence: "Plant growth slows significantly at high ___.", answer: "altitude", base: "altitude", hint: "a_______", ja: "高度", sentenceJa: "高地では植物の成長が大幅に遅くなる。" },
        { sentence: "The professor used an ___ to explain the concept.", answer: "analogy", base: "analogy", hint: "a______", ja: "類推、類似", sentenceJa: "教授はその概念を説明するために類推を用いた。" },
        { sentence: "Humans share a common ___ with other primates.", answer: "ancestor", base: "ancestor", hint: "a_______", ja: "祖先", sentenceJa: "人間は他の霊長類と共通の祖先を持つ。" },
        { sentence: "Overuse of ___ has led to resistant bacteria.", answer: "antibiotics", base: "antibiotic", hint: "a_________", ja: "抗生物質", sentenceJa: "抗生物質の乱用は耐性菌を生み出してきた。" },
        { sentence: "The immune system produces ___ in response to infection.", answer: "antibodies", base: "antibody", hint: "a_______", ja: "抗体", sentenceJa: "免疫システムは感染に反応して抗体を作り出す。" },
        { sentence: "___ relies heavily on careful excavation techniques.", answer: "archaeology", base: "archaeology", hint: "a__________", ja: "考古学", sentenceJa: "考古学は慎重な発掘技術に大きく依存している。" },
        { sentence: "The ___ designed the building with sustainability in mind.", answer: "architect", base: "architect", hint: "a________", ja: "建築家", sentenceJa: "その建築家は持続可能性を考慮してその建物を設計した。" },
        { sentence: "Researchers discovered several ___ at the excavation site.", answer: "artifacts", base: "artifact", hint: "a_______", ja: "人工遺物", sentenceJa: "研究者たちは発掘現場でいくつかの人工遺物を発見した。" },
        { sentence: "The ___ of the device requires several precise steps.", answer: "assembly", base: "assembly", hint: "a_______", ja: "組み立て、集会", sentenceJa: "その装置の組み立てにはいくつかの精密な手順が必要だ。" },
        { sentence: "Each molecule consists of two or more ___.", answer: "atoms", base: "atom", hint: "a___", ja: "原子", sentenceJa: "各分子は2つ以上の原子から構成されている。" },
        { sentence: "The local ___ approved the new construction plan.", answer: "authority", base: "authority", hint: "a________", ja: "権威、当局", sentenceJa: "地方自治体は新しい建設計画を承認した。" },
        { sentence: "The study examines how much ___ workers have over their schedules.", answer: "autonomy", base: "autonomy", hint: "a_______", ja: "自治、自律性", sentenceJa: "その研究は労働者が自分のスケジュールにどれほどの自律性を持つかを調べている。" },
        { sentence: "___ can survive in extreme environments.", answer: "bacteria", base: "bacteria", hint: "b_______", ja: "細菌", sentenceJa: "細菌は極限環境でも生存できる。" },
      ],
    },
    {
      name: "Day 11",
      items: [
        { sentence: "The report includes a ___ of expenses by category.", answer: "breakdown", base: "breakdown", hint: "b________", ja: "内訳、故障", sentenceJa: "その報告書には項目別の費用の内訳が含まれている。" },
        { sentence: "The ___ of the population lives in urban areas.", answer: "bulk", base: "bulk", hint: "b___", ja: "大部分、大量", sentenceJa: "人口の大部分は都市部に住んでいる。" },
        { sentence: "The ___ was based on several assumptions.", answer: "calculation", base: "calculation", hint: "c__________", ja: "計算", sentenceJa: "その計算はいくつかの前提に基づいていた。" },
        { sentence: "Most students live on ___ during their first year.", answer: "campus", base: "campus", hint: "c_____", ja: "キャンパス", sentenceJa: "ほとんどの学生は1年目にキャンパス内に住んでいる。" },
        { sentence: "Only a small number of ___ met the criteria.", answer: "candidates", base: "candidate", hint: "c________", ja: "候補者", sentenceJa: "その基準を満たした候補者はごくわずかだった。" },
        { sentence: "The essay discusses the effects of ___ on income inequality.", answer: "capitalism", base: "capitalism", hint: "c_________", ja: "資本主義", sentenceJa: "そのエッセイは資本主義が所得格差に与える影響について論じている。" },
        { sentence: "Some individuals can be ___ of the disease without symptoms.", answer: "carriers", base: "carrier", hint: "c______", ja: "保菌者、運搬者", sentenceJa: "一部の人は症状がなくてもその病気の保菌者になり得る。" },
        { sentence: "The painting was sold at ___ for a record price.", answer: "auction", base: "auction", hint: "a______", ja: "競売", sentenceJa: "その絵画は競売で記録的な価格で売却された。" },
        { sentence: "An independent ___ confirmed the accuracy of the data.", answer: "audit", base: "audit", hint: "a____", ja: "監査", sentenceJa: "独立監査によってデータの正確性が確認された。" },
        { sentence: "Additional data can be found in the ___.", answer: "appendix", base: "appendix", hint: "a_______", ja: "付録", sentenceJa: "追加のデータは付録に記載されている。" },
        { sentence: "The speech was met with enthusiastic ___.", answer: "applause", base: "applause", hint: "a_______", ja: "拍手", sentenceJa: "そのスピーチは熱烈な拍手で迎えられた。" },
        { sentence: "The museum displays a wide ___ of ancient artifacts.", answer: "array", base: "array", hint: "a____", ja: "配列、多様さ", sentenceJa: "その博物館は多種多様な古代の遺物を展示している。" },
        { sentence: "Oil prices are typically measured per ___.", answer: "barrel", base: "barrel", hint: "b_____", ja: "樽、バレル", sentenceJa: "原油価格は通常バレル単位で測定される。" },
        { sentence: "The river ___ supports a wide variety of wildlife.", answer: "basin", base: "basin", hint: "b____", ja: "盆地、流域", sentenceJa: "その流域は多様な野生生物を支えている。" },
        { sentence: "The bridge is supported by steel ___.", answer: "beams", base: "beam", hint: "b___", ja: "梁、光線", sentenceJa: "その橋は鋼鉄の梁で支えられている。" },
        { sentence: "The city has invested in more ___ lanes.", answer: "bicycle", base: "bicycle", hint: "b______", ja: "自転車", sentenceJa: "その市はより多くの自転車専用レーンに投資してきた。" },
        { sentence: "She majored in ___ at university.", answer: "biology", base: "biology", hint: "b______", ja: "生物学", sentenceJa: "彼女は大学で生物学を専攻した。" },
        { sentence: "Households in the lowest income ___ were most affected.", answer: "bracket", base: "bracket", hint: "b______", ja: "括弧、階層", sentenceJa: "最も低い所得層の世帯が最も影響を受けた。" },
        { sentence: "Economists warned of a housing market ___.", answer: "bubble", base: "bubble", hint: "b_____", ja: "泡、バブル", sentenceJa: "経済学者たちは住宅市場のバブルについて警告した。" },
        { sentence: "Researchers collected rainwater samples in a ___.", answer: "bucket", base: "bucket", hint: "b_____", ja: "バケツ", sentenceJa: "研究者たちはバケツで雨水のサンプルを採取した。" },
      ],
    },
    {
      name: "Day 12",
      items: [
        { sentence: "The region is experiencing an ___ shortage of clean water.", answer: "acute", base: "acute", hint: "a____", ja: "深刻な、鋭い", sentenceJa: "その地域はきれいな水の深刻な不足に直面している。" },
        { sentence: "The drug can cause several ___ side effects.", answer: "adverse", base: "adverse", hint: "a______", ja: "不利な、悪影響を及ぼす", sentenceJa: "その薬にはいくつかの悪影響を及ぼす副作用がある可能性がある。" },
        { sentence: "The cutoff score seemed rather ___.", answer: "arbitrary", base: "arbitrary", hint: "a________", ja: "恣意的な", sentenceJa: "その合格基準はかなり恣意的に思えた。" },
        { sentence: "___ stress can weaken the immune system.", answer: "chronic", base: "chronic", hint: "c______", ja: "慢性的な", sentenceJa: "慢性的なストレスは免疫システムを弱める可能性がある。" },
        { sentence: "The test measures several aspects of ___ development.", answer: "cognitive", base: "cognitive", hint: "c________", ja: "認知の", sentenceJa: "そのテストは認知発達のいくつかの側面を測定する。" },
        { sentence: "The report reflects the ___ opinion of the researchers.", answer: "collective", base: "collective", hint: "c_________", ja: "集団の", sentenceJa: "その報告書は研究者たちの集団的な意見を反映している。" },
        { sentence: "The two studies produced ___ results.", answer: "comparable", base: "comparable", hint: "c_________", ja: "匹敵する、比較可能な", sentenceJa: "その2つの研究は匹敵する結果を出した。" },
        { sentence: "The committee found the candidate highly ___.", answer: "competent", base: "competent", hint: "c________", ja: "有能な", sentenceJa: "委員会はその候補者を非常に有能だと判断した。" },
        { sentence: "The paper offers a ___ framework for the analysis.", answer: "conceptual", base: "conceptual", hint: "c_________", ja: "概念的な", sentenceJa: "その論文はその分析のための概念的な枠組みを提示している。" },
        { sentence: "The data was divided into ___ categories.", answer: "discrete", base: "discrete", hint: "d_______", ja: "個別の、離散した", sentenceJa: "そのデータは個別のカテゴリーに分けられた。" },
        { sentence: "The market is highly ___ and changes quickly.", answer: "dynamic", base: "dynamic", hint: "d______", ja: "動的な", sentenceJa: "その市場は非常に動的で急速に変化する。" },
        { sentence: "The dam had a significant ___ impact on the river.", answer: "ecological", base: "ecological", hint: "e_________", ja: "生態学的な", sentenceJa: "そのダムはその川に重大な生態学的影響を与えた。" },
        { sentence: "Natural resources are ___ and must be managed carefully.", answer: "finite", base: "finite", hint: "f_____", ja: "有限の", sentenceJa: "天然資源は有限であり、慎重に管理されなければならない。" },
        { sentence: "The organization has a strict ___ structure.", answer: "hierarchical", base: "hierarchical", hint: "h___________", ja: "階層的な", sentenceJa: "その組織は厳格な階層構造を持っている。" },
        { sentence: "The plant is ___ to the region.", answer: "indigenous", base: "indigenous", hint: "i_________", ja: "先住の、固有の", sentenceJa: "その植物はその地域に固有のものだ。" },
        { sentence: "The ___ results were promising.", answer: "preliminary", base: "preliminary", hint: "p__________", ja: "予備的な", sentenceJa: "予備的な結果は有望だった。" },
        { sentence: "The researchers used a ___ approach based on interviews.", answer: "qualitative", base: "qualitative", hint: "q__________", ja: "質的な", sentenceJa: "研究者たちはインタビューに基づく質的アプローチを用いた。" },
        { sentence: "___ data was collected through a large-scale survey.", answer: "quantitative", base: "quantitative", hint: "q___________", ja: "量的な", sentenceJa: "量的データは大規模な調査によって収集された。" },
        { sentence: "Some critics argue that the evaluation criteria are too ___.", answer: "subjective", base: "subjective", hint: "s_________", ja: "主観的な", sentenceJa: "一部の批評家はその評価基準があまりに主観的だと主張している。" },
        { sentence: "The team carried out a ___ review of the literature.", answer: "systematic", base: "systematic", hint: "s_________", ja: "体系的な", sentenceJa: "そのチームは文献の体系的なレビューを行った。" },
      ],
    },
    {
      name: "Day 13",
      items: [
        { sentence: "The results improved ___ after the intervention.", answer: "significantly", base: "significantly", hint: "s____________", ja: "著しく、有意に", sentenceJa: "介入後、結果は著しく改善した。" },
        { sentence: "The cost of the equipment is ___ low.", answer: "relatively", base: "relatively", hint: "r_________", ja: "比較的", sentenceJa: "その機材のコストは比較的低い。" },
        { sentence: "The theory is ___ concerned with human behavior.", answer: "primarily", base: "primarily", hint: "p________", ja: "主に", sentenceJa: "その理論は主に人間の行動に関するものだ。" },
        { sentence: "The experiment ___ confirmed the original hypothesis.", answer: "ultimately", base: "ultimately", hint: "u_________", ja: "最終的に", sentenceJa: "その実験は最終的に当初の仮説を裏付けた。" },
        { sentence: "This is ___ the most influential study in the field.", answer: "arguably", base: "arguably", hint: "a_______", ja: "おそらく、議論の余地はあるが", sentenceJa: "これはおそらくこの分野で最も影響力のある研究だ。" },
        { sentence: "The data were ___ analyzed using statistical software.", answer: "subsequently", base: "subsequently", hint: "s___________", ja: "その後", sentenceJa: "そのデータはその後、統計ソフトを使って分析された。" },
        { sentence: "The chemical could ___ harm aquatic life.", answer: "potentially", base: "potentially", hint: "p__________", ja: "潜在的に", sentenceJa: "その化学物質は水生生物に害を及ぼす可能性がある。" },
        { sentence: "___, the model should apply to any population.", answer: "theoretically", base: "theoretically", hint: "t____________", ja: "理論的には", sentenceJa: "理論的には、そのモデルはどの集団にも適用できるはずだ。" },
        { sentence: "The sample size varied ___ between studies.", answer: "considerably", base: "considerably", hint: "c___________", ja: "かなり", sentenceJa: "サンプルサイズは研究によってかなり異なった。" },
        { sentence: "The topic has been ___ studied in previous research.", answer: "extensively", base: "extensively", hint: "e__________", ja: "広範囲に", sentenceJa: "そのテーマは以前の研究で広範囲に研究されてきた。" },
        { sentence: "The participants were ___ university students.", answer: "predominantly", base: "predominantly", hint: "p____________", ja: "主に、大部分", sentenceJa: "参加者は主に大学生だった。" },
        { sentence: "Researchers are ___ relying on digital data.", answer: "increasingly", base: "increasingly", hint: "i___________", ja: "ますます", sentenceJa: "研究者たちはますますデジタルデータに頼るようになっている。" },
        { sentence: "The new method performed only ___ better.", answer: "marginally", base: "marginally", hint: "m_________", ja: "わずかに", sentenceJa: "その新しい方法はわずかに良い結果を出しただけだった。" },
        { sentence: "___, the change in policy caused the decline.", answer: "presumably", base: "presumably", hint: "p_________", ja: "おそらく", sentenceJa: "おそらく、その政策変更が減少を引き起こした。" },
        { sentence: "The outcome was ___ determined by early conditions.", answer: "largely", base: "largely", hint: "l______", ja: "主として", sentenceJa: "その結果は主に初期条件によって決まった。" },
        { sentence: "___, the two variables are closely related.", answer: "apparently", base: "apparently", hint: "a_________", ja: "見たところ", sentenceJa: "見たところ、その2つの変数は密接に関連している。" },
        { sentence: "The hypothesis was revised ___.", answer: "accordingly", base: "accordingly", hint: "a__________", ja: "それに応じて", sentenceJa: "その仮説はそれに応じて修正された。" },
        { sentence: "The disease is ___ rare in developed countries.", answer: "comparatively", base: "comparatively", hint: "c____________", ja: "比較的", sentenceJa: "その病気は先進国では比較的まれだ。" },
        { sentence: "The study focused ___ on adult participants.", answer: "exclusively", base: "exclusively", hint: "e__________", ja: "もっぱら", sentenceJa: "その研究は成人の参加者のみに焦点を当てた。" },
        { sentence: "The two groups scored 72% and 85%, ___.", answer: "respectively", base: "respectively", hint: "r___________", ja: "それぞれ", sentenceJa: "その2つのグループはそれぞれ72%と85%のスコアを取った。" },
      ],
    },
    {
      name: "Day 15",
      items: [
        { sentence: "Last year, the advertisement ___ many consumers.", answer: "deceived", base: "deceive", hint: "d______", ja: "欺く、だます", sentenceJa: "昨年、その広告は多くの消費者を欺いた。" },
        { sentence: "In this diagram, the arrow always ___ direction of flow.", answer: "denotes", base: "denote", hint: "d_____", ja: "示す、意味する", sentenceJa: "この図では、矢印はいつも流れの方向を示す。" },
        { sentence: "Last month, doctors ___ the patient with a rare condition.", answer: "diagnosed", base: "diagnose", hint: "d_______", ja: "診断する", sentenceJa: "先月、医師たちはその患者を珍しい病状だと診断した。" },
        { sentence: "The professor will ___ the terms of the assignment.", answer: "dictate", base: "dictate", hint: "d______", ja: "書き取らせる、命令する", sentenceJa: "教授が課題の条件を指示する予定だ。" },
        { sentence: "Please ___ the solution before use.", answer: "dilute", base: "dilute", hint: "d_____", ja: "薄める、希釈する", sentenceJa: "使用前に溶液を薄めてください。" },
        { sentence: "Yesterday, the researcher ___ a sensor in the device.", answer: "embedded", base: "embed", hint: "e____", ja: "埋め込む", sentenceJa: "昨日、研究者はその装置にセンサーを埋め込んだ。" },
        { sentence: "This engine ___ far less carbon than older models.", answer: "emits", base: "emit", hint: "e___", ja: "放出する", sentenceJa: "このエンジンは旧型よりもはるかに少ない炭素を放出している。" },
        { sentence: "The system will ___ the data before transmission.", answer: "encode", base: "encode", hint: "e_____", ja: "符号化する", sentenceJa: "そのシステムは送信前にデータを符号化する予定だ。" },
        { sentence: "Last month, the price shock ___ a wave of layoffs.", answer: "precipitated", base: "precipitate", hint: "p__________", ja: "引き起こす、沈殿させる", sentenceJa: "先月、その価格の急変が一連のレイオフを引き起こした。" },
        { sentence: "It can be difficult to ___ from such a small sample.", answer: "generalize", base: "generalize", hint: "g_________", ja: "一般化する", sentenceJa: "そのような小さなサンプルから一般化するのは難しい場合がある。" },
        { sentence: "Last year, the virus ___ thousands of people worldwide.", answer: "infected", base: "infect", hint: "i_____", ja: "感染させる", sentenceJa: "昨年、そのウイルスは世界中で何千人もの人々に感染した。" },
        { sentence: "The university will ___ a new research program next year.", answer: "initiate", base: "initiate", hint: "i_______", ja: "開始する", sentenceJa: "その大学は来年、新しい研究プログラムを開始する予定だ。" },
        { sentence: "Yesterday, the nurse ___ the vaccine into the patient's arm.", answer: "injected", base: "inject", hint: "i_____", ja: "注入する、注射する", sentenceJa: "昨日、看護師は患者の腕にワクチンを注射した。" },
        { sentence: "Please ___ the disk before starting the program.", answer: "insert", base: "insert", hint: "i_____", ja: "挿入する", sentenceJa: "プログラムを開始する前にディスクを挿入してください。" },
        { sentence: "Yesterday, a power failure ___ the experiment.", answer: "interrupted", base: "interrupt", hint: "i________", ja: "中断させる", sentenceJa: "昨日、停電がその実験を中断させた。" },
        { sentence: "Please ___ the image before printing it.", answer: "invert", base: "invert", hint: "i_____", ja: "逆にする、反転させる", sentenceJa: "印刷する前に画像を反転させてください。" },
        { sentence: "Last week, the metal surface ___ rapidly in the humid air.", answer: "oxidized", base: "oxidize", hint: "o______", ja: "酸化する", sentenceJa: "先週、その金属表面は湿った空気の中で急速に酸化した。" },
        { sentence: "Last month, a neutral party ___ the dispute.", answer: "mediated", base: "mediate", hint: "m______", ja: "仲介する、調停する", sentenceJa: "先月、中立の立場の者がその紛争を仲介した。" },
        { sentence: "Last year, many young graduates ___ to bigger cities for work.", answer: "migrated", base: "migrate", hint: "m______", ja: "移住する、移動する", sentenceJa: "昨年、多くの若い卒業生が仕事のために大都市へ移住した。" },
        { sentence: "Please ___ the order of the survey questions.", answer: "randomize", base: "randomize", hint: "r________", ja: "無作為化する", sentenceJa: "アンケートの質問の順番を無作為化してください。" },
      ],
    },
    {
      name: "Day 16",
      items: [
        { sentence: "Last year, the new protocol ___ workplace accidents significantly.", answer: "minimized", base: "minimize", hint: "m_______", ja: "最小限にする", sentenceJa: "昨年、その新しいプロトコルは職場の事故を大幅に減らした。" },
        { sentence: "The orientation program helps new students ___ themselves on campus.", answer: "orient", base: "orient", hint: "o_____", ja: "順応させる、方向づける", sentenceJa: "そのオリエンテーションプログラムは新入生がキャンパスに順応する助けとなる。" },
        { sentence: "Last year, the documentary ___ the effects of climate change.", answer: "portrayed", base: "portray", hint: "p______", ja: "描写する", sentenceJa: "昨年、そのドキュメンタリーは気候変動の影響を描写した。" },
        { sentence: "A period of drought often ___ a famine.", answer: "precedes", base: "precede", hint: "p______", ja: "先行する、前に起こる", sentenceJa: "干ばつの期間はしばしば飢饉に先行する。" },
        { sentence: "We should not ___ guilt without evidence.", answer: "presume", base: "presume", hint: "p______", ja: "推定する、想定する", sentenceJa: "証拠なしに有罪だと推定すべきではない。" },
        { sentence: "Yesterday, the teacher ___ each new word slowly for the class.", answer: "pronounced", base: "pronounce", hint: "p________", ja: "発音する", sentenceJa: "昨日、先生はクラスのために新出単語を一つずつゆっくり発音した。" },
        { sentence: "Last year, historians ___ the timeline of events.", answer: "reconstructed", base: "reconstruct", hint: "r__________", ja: "再構築する", sentenceJa: "昨年、歴史家たちは出来事の年表を再構築した。" },
        { sentence: "Last month, another team ___ the original experiment.", answer: "replicated", base: "replicate", hint: "r________", ja: "再現する、複製する", sentenceJa: "先月、別のチームが元の実験を再現した。" },
        { sentence: "This species still closely ___ its extinct ancestor.", answer: "resembles", base: "resemble", hint: "r_______", ja: "似ている", sentenceJa: "この種は今でもその絶滅した祖先によく似ている。" },
        { sentence: "The Earth always ___ on its axis.", answer: "rotates", base: "rotate", hint: "r_____", ja: "回転する", sentenceJa: "地球はいつもその軸を中心に回転している。" },
        { sentence: "Last night, the wind ___ leaves across the yard.", answer: "scattered", base: "scatter", hint: "s______", ja: "散らす、散らばる", sentenceJa: "昨夜、風が庭中に葉を散らした。" },
        { sentence: "The software can ___ real-world traffic conditions.", answer: "simulate", base: "simulate", hint: "s_______", ja: "シミュレートする", sentenceJa: "そのソフトウェアは現実世界の交通状況をシミュレートできる。" },
        { sentence: "Students ___ mostly through social media.", answer: "socialize", base: "socialize", hint: "s________", ja: "社交する、交流する", sentenceJa: "学生は主にソーシャルメディアを通じて交流する。" },
        { sentence: "Last month, the central bank acted to ___ the currency.", answer: "stabilize", base: "stabilize", hint: "s________", ja: "安定させる", sentenceJa: "先月、中央銀行は通貨を安定させるために行動した。" },
        { sentence: "The committee decided to ___ the testing procedure.", answer: "standardize", base: "standardize", hint: "s__________", ja: "標準化する", sentenceJa: "委員会はその試験手順を標準化することを決定した。" },
        { sentence: "Yesterday, the assistant ___ the entire interview.", answer: "transcribed", base: "transcribe", hint: "t_________", ja: "書き起こす", sentenceJa: "昨日、アシスタントはそのインタビュー全体を書き起こした。" },
        { sentence: "Mosquitoes can ___ several serious diseases.", answer: "transmit", base: "transmit", hint: "t_______", ja: "伝達する、送信する", sentenceJa: "蚊はいくつかの深刻な病気を媒介することがある。" },
        { sentence: "Last year, the scandal ___ public trust in the institution.", answer: "undermined", base: "undermine", hint: "u________", ja: "弱体化させる、損なう", sentenceJa: "昨年、そのスキャンダルはその機関への公衆の信頼を損なった。" },
        { sentence: "The new policy aims to ___ standards across all regions.", answer: "unify", base: "unify", hint: "u____", ja: "統一する", sentenceJa: "その新しい方針は全地域にわたって基準を統一することを目的としている。" },
        { sentence: "Last semester, the class ___ a range of digital tools.", answer: "utilized", base: "utilize", hint: "u______", ja: "活用する", sentenceJa: "先学期、そのクラスは様々なデジタルツールを活用した。" },
      ],
    },
    {
      name: "Day 17",
      items: [
        { sentence: "The publisher rejected her first ___.", answer: "manuscript", base: "manuscript", hint: "m_________", ja: "原稿", sentenceJa: "その出版社は彼女の最初の原稿を却下した。" },
        { sentence: "The poet used a striking ___ to describe grief.", answer: "metaphor", base: "metaphor", hint: "m_______", ja: "隠喩、比喩", sentenceJa: "その詩人は悲しみを表現するために印象的な隠喩を用いた。" },
        { sentence: "The annual ___ of birds spans thousands of miles.", answer: "migration", base: "migration", hint: "m________", ja: "移住、渡り", sentenceJa: "鳥の毎年の渡りは何千マイルにも及ぶ。" },
        { sentence: "Social ___ has declined in many developed countries.", answer: "mobility", base: "mobility", hint: "m_______", ja: "流動性、機動性", sentenceJa: "多くの先進国で社会的流動性が低下している。" },
        { sentence: "The campaign gained ___ after the first debate.", answer: "momentum", base: "momentum", hint: "m_______", ja: "勢い、運動量", sentenceJa: "その運動は最初の討論の後に勢いを増した。" },
        { sentence: "The company once held a ___ on the local market.", answer: "monopoly", base: "monopoly", hint: "m_______", ja: "独占", sentenceJa: "その会社はかつて地元市場を独占していた。" },
        { sentence: "The novel raises questions about ___ and justice.", answer: "morality", base: "morality", hint: "m_______", ja: "道徳", sentenceJa: "その小説は道徳と正義についての問いを投げかけている。" },
        { sentence: "Infant ___ has dropped significantly over the past century.", answer: "mortality", base: "mortality", hint: "m________", ja: "死亡率", sentenceJa: "この一世紀で乳児死亡率は大幅に低下した。" },
        { sentence: "It is a common ___ that we only use ten percent of our brains.", answer: "myth", base: "myth", hint: "m___", ja: "俗説、神話", sentenceJa: "私たちは脳の10パーセントしか使っていないというのはよくある俗説だ。" },
        { sentence: "Rising ___ influenced the election results.", answer: "nationalism", base: "nationalism", hint: "n__________", ja: "国家主義", sentenceJa: "高まる国家主義が選挙結果に影響を与えた。" },
        { sentence: "Clean water is a basic ___ for survival.", answer: "necessity", base: "necessity", hint: "n________", ja: "必要性", sentenceJa: "きれいな水は生存のための基本的な必需品だ。" },
        { sentence: "The startup found a profitable ___ in the market.", answer: "niche", base: "niche", hint: "n____", ja: "ニッチ", sentenceJa: "そのスタートアップは市場で利益の出るニッチを見つけた。" },
        { sentence: "The lawyer raised an ___ during the trial.", answer: "objection", base: "objection", hint: "o________", ja: "異議、反対", sentenceJa: "その弁護士は裁判中に異議を申し立てた。" },
        { sentence: "An independent ___ monitored the election.", answer: "observer", base: "observer", hint: "o_______", ja: "監視員、観察者", sentenceJa: "独立した監視員がその選挙を監視した。" },
        { sentence: "Teaching is a demanding but rewarding ___.", answer: "occupation", base: "occupation", hint: "o_________", ja: "職業", sentenceJa: "教職は大変だがやりがいのある職業だ。" },
        { sentence: "Earthquakes are a common ___ in this region.", answer: "occurrence", base: "occurrence", hint: "o_________", ja: "出来事、発生", sentenceJa: "地震はこの地域ではよくある出来事だ。" },
        { sentence: "Early symptoms can signal the ___ of the disease.", answer: "onset", base: "onset", hint: "o____", ja: "発症、始まり", sentenceJa: "初期症状はその病気の発症を示すことがある。" },
        { sentence: "The discovery represented a ___ shift in physics.", answer: "paradigm", base: "paradigm", hint: "p_______", ja: "パラダイム", sentenceJa: "その発見は物理学におけるパラダイムシフトを表した。" },
        { sentence: "Researchers adjusted a key ___ in the model.", answer: "parameter", base: "parameter", hint: "p________", ja: "パラメータ", sentenceJa: "研究者たちはそのモデルの重要なパラメータを調整した。" },
        { sentence: "The country's ___ led to decades of conflict.", answer: "partition", base: "partition", hint: "p________", ja: "分割", sentenceJa: "その国の分割は数十年にわたる紛争につながった。" },
      ],
    },
    {
      name: "Day 18",
      items: [
        { sentence: "The ancient ___ questioned the nature of reality.", answer: "philosopher", base: "philosopher", hint: "p__________", ja: "哲学者", sentenceJa: "その古代の哲学者は現実の本質について問うた。" },
        { sentence: "She built an impressive design ___ during college.", answer: "portfolio", base: "portfolio", hint: "p________", ja: "ポートフォリオ、作品集", sentenceJa: "彼女は大学時代に印象的なデザインポートフォリオを作り上げた。" },
        { sentence: "A licensed ___ must approve the treatment.", answer: "practitioner", base: "practitioner", hint: "p___________", ja: "開業医、実践者", sentenceJa: "免許を持つ開業医がその治療を承認しなければならない。" },
        { sentence: "The study explores unconscious ___ in hiring decisions.", answer: "prejudice", base: "prejudice", hint: "p________", ja: "偏見", sentenceJa: "その研究は採用決定における無意識の偏見を探っている。" },
        { sentence: "Remote work can improve employee ___.", answer: "productivity", base: "productivity", hint: "p___________", ja: "生産性", sentenceJa: "リモートワークは従業員の生産性を向上させることがある。" },
        { sentence: "The disease follows a predictable ___.", answer: "progression", base: "progression", hint: "p__________", ja: "進行、進展", sentenceJa: "その病気は予測可能な進行過程をたどる。" },
        { sentence: "The board rejected the merger ___.", answer: "proposition", base: "proposition", hint: "p__________", ja: "提案", sentenceJa: "取締役会はその合併案を却下した。" },
        { sentence: "Researchers must follow a strict ethical ___.", answer: "protocol", base: "protocol", hint: "p_______", ja: "プロトコル", sentenceJa: "研究者は厳格な倫理プロトコルに従わなければならない。" },
        { sentence: "The ___ specializes in childhood development.", answer: "psychologist", base: "psychologist", hint: "p___________", ja: "心理学者", sentenceJa: "その心理学者は幼児期の発達を専門としている。" },
        { sentence: "Participants completed a short ___ before the study.", answer: "questionnaire", base: "questionnaire", hint: "q____________", ja: "アンケート", sentenceJa: "参加者は研究の前に短いアンケートに回答した。" },
        { sentence: "Economists often assume perfect ___ in consumers.", answer: "rationality", base: "rationality", hint: "r__________", ja: "合理性", sentenceJa: "経済学者はしばしば消費者に完全な合理性を仮定する。" },
        { sentence: "The new ___ introduced strict censorship laws.", answer: "regime", base: "regime", hint: "r_____", ja: "政権、体制", sentenceJa: "その新しい政権は厳しい検閲法を導入した。" },
        { sentence: "The test's ___ was questioned by critics.", answer: "reliability", base: "reliability", hint: "r__________", ja: "信頼性", sentenceJa: "その試験の信頼性は批評家から疑問視された。" },
        { sentence: "The orchestra expanded its ___ this season.", answer: "repertoire", base: "repertoire", hint: "r_________", ja: "レパートリー", sentenceJa: "そのオーケストラは今シーズン、レパートリーを広げた。" },
        { sentence: "The company is searching for a suitable ___.", answer: "replacement", base: "replacement", hint: "r__________", ja: "後任者、交換", sentenceJa: "その会社は適切な後任者を探している。" },
        { sentence: "The city's water comes from a nearby ___.", answer: "reservoir", base: "reservoir", hint: "r________", ja: "貯水池", sentenceJa: "その市の水は近くの貯水池から来ている。" },
        { sentence: "Political ___ often oversimplifies complex issues.", answer: "rhetoric", base: "rhetoric", hint: "r_______", ja: "レトリック", sentenceJa: "政治的レトリックはしばしば複雑な問題を単純化しすぎる。" },
        { sentence: "Analysts modeled several possible ___.", answer: "scenarios", base: "scenario", hint: "s_______", ja: "シナリオ", sentenceJa: "アナリストたちはいくつかの起こりうるシナリオをモデル化した。" },
        { sentence: "The test has high ___ for early detection.", answer: "sensitivity", base: "sensitivity", hint: "s__________", ja: "感度、敏感さ", sentenceJa: "その検査は早期発見に対して高い感度を持つ。" },
        { sentence: "There is a striking ___ between the two theories.", answer: "similarity", base: "similarity", hint: "s_________", ja: "類似点、類似性", sentenceJa: "その二つの理論の間には著しい類似点がある。" },
      ],
    },
    {
      name: "Day 19",
      items: [
        { sentence: "The renovation improved the building's ___ appeal.", answer: "aesthetic", base: "aesthetic", hint: "a________", ja: "美的な", sentenceJa: "その改装はその建物の美的魅力を高めた。" },
        { sentence: "The drink contains no ___ flavors.", answer: "artificial", base: "artificial", hint: "a_________", ja: "人工の", sentenceJa: "その飲み物には人工香料が含まれていない。" },
        { sentence: "The university offers several ___ scholarships.", answer: "athletic", base: "athletic", hint: "a_______", ja: "運動の、運動選手の", sentenceJa: "その大学はいくつかの運動部特待生制度を提供している。" },
        { sentence: "The clinic specializes in ___ therapy.", answer: "behavioral", base: "behavioral", hint: "b_________", ja: "行動の", sentenceJa: "そのクリニックは行動療法を専門としている。" },
        { sentence: "Growing up ___ has cognitive benefits.", answer: "bilingual", base: "bilingual", hint: "b________", ja: "バイリンガルの", sentenceJa: "バイリンガルとして育つことには認知的な利点がある。" },
        { sentence: "The museum displays artifacts from the ___ era.", answer: "colonial", base: "colonial", hint: "c_______", ja: "植民地の", sentenceJa: "その博物館は植民地時代の遺物を展示している。" },
        { sentence: "The paper takes a ___ approach to the two systems.", answer: "comparative", base: "comparative", hint: "c__________", ja: "比較の", sentenceJa: "その論文はその二つのシステムを比較する手法をとっている。" },
        { sentence: "Consumers are becoming more ___ of environmental issues.", answer: "conscious", base: "conscious", hint: "c________", ja: "意識している", sentenceJa: "消費者は環境問題をより意識するようになってきている。" },
        { sentence: "The factory processes ___ oil into fuel.", answer: "crude", base: "crude", hint: "c____", ja: "未加工の、粗雑な", sentenceJa: "その工場は原油を燃料に加工する。" },
        { sentence: "The committee raised ___ concerns about the experiment.", answer: "ethical", base: "ethical", hint: "e______", ja: "倫理的な", sentenceJa: "その委員会はその実験に関する倫理的な懸念を提起した。" },
        { sentence: "The company reported a ___ profit of ten million dollars.", answer: "gross", base: "gross", hint: "g____", ja: "総計の", sentenceJa: "その会社は1000万ドルの総利益を報告した。" },
        { sentence: "The two samples were nearly ___ in composition.", answer: "identical", base: "identical", hint: "i________", ja: "同一の", sentenceJa: "その二つの試料は組成がほぼ同一だった。" },
        { sentence: "The vaccine helps the body become ___ to the virus.", answer: "immune", base: "immune", hint: "i_____", ja: "免疫がある", sentenceJa: "そのワクチンは体がそのウイルスに対して免疫を持つ助けとなる。" },
        { sentence: "The material proved ___ to the original design.", answer: "inferior", base: "inferior", hint: "i_______", ja: "劣った", sentenceJa: "その素材は元の設計より劣ることが分かった。" },
        { sentence: "In theory, the universe could be ___.", answer: "infinite", base: "infinite", hint: "i_______", ja: "無限の", sentenceJa: "理論上、宇宙は無限である可能性がある。" },
        { sentence: "The new policy had only a ___ effect on sales.", answer: "marginal", base: "marginal", hint: "m_______", ja: "わずかな、限界的な", sentenceJa: "その新しい方針は売上にわずかな影響しか与えなかった。" },
        { sentence: "She has a strong ___ background.", answer: "mathematical", base: "mathematical", hint: "m___________", ja: "数学の", sentenceJa: "彼女は数学の強い素養を持っている。" },
        { sentence: "The delay was caused by a ___ failure.", answer: "mechanical", base: "mechanical", hint: "m_________", ja: "機械的な", sentenceJa: "その遅延は機械的な故障が原因だった。" },
        { sentence: "The central bank adjusted its ___ policy.", answer: "monetary", base: "monetary", hint: "m_______", ja: "金融の、金銭的な", sentenceJa: "中央銀行はその金融政策を調整した。" },
        { sentence: "The reference is too ___ for most readers.", answer: "obscure", base: "obscure", hint: "o______", ja: "難解な、不明瞭な", sentenceJa: "その言及はほとんどの読者にとって難解すぎる。" },
      ],
    },
    {
      name: "Day 20",
      items: [
        { sentence: "The economy took a step ___ last quarter.", answer: "backward", base: "backward", hint: "b_______", ja: "後方へ、逆行して", sentenceJa: "その経済は前四半期、後退した。" },
        { sentence: "This herb is ___ used in traditional medicine.", answer: "commonly", base: "commonly", hint: "c_______", ja: "一般的に", sentenceJa: "このハーブは伝統医療で一般的に使われている。" },
        { sentence: "Public opinion has changed ___ over the decade.", answer: "enormously", base: "enormously", hint: "e_________", ja: "非常に、桁外れに", sentenceJa: "この10年で世論は非常に大きく変化した。" },
        { sentence: "The two countries ___ signed the agreement yesterday.", answer: "formally", base: "formally", hint: "f_______", ja: "正式に", sentenceJa: "昨日、その二国は正式にその協定に署名した。" },
        { sentence: "Information now flows more ___ across borders.", answer: "freely", base: "freely", hint: "f_____", ja: "自由に", sentenceJa: "今では情報が国境を越えてより自由に流れている。" },
        { sentence: "The results were ___ consistent across all trials.", answer: "incredibly", base: "incredibly", hint: "i_________", ja: "信じられないほど", sentenceJa: "その結果は全ての試験を通して信じられないほど一貫していた。" },
        { sentence: "Two factors, ___ cost and time, influenced the decision.", answer: "namely", base: "namely", hint: "n_____", ja: "すなわち", sentenceJa: "二つの要因、すなわちコストと時間が、その決定に影響を与えた。" },
        { sentence: "The two theories fit together ___.", answer: "nicely", base: "nicely", hint: "n_____", ja: "うまく、見事に", sentenceJa: "その二つの理論はうまく調和している。" },
        { sentence: "From this point ___, the data becomes less reliable.", answer: "onwards", base: "onwards", hint: "o______", ja: "それ以降", sentenceJa: "この時点以降、そのデータの信頼性は下がる。" },
        { sentence: "The task is not ___ demanding.", answer: "physically", base: "physically", hint: "p_________", ja: "肉体的に", sentenceJa: "その作業は肉体的にきついものではない。" },
        { sentence: "The decision was based ___ on financial factors.", answer: "purely", base: "purely", hint: "p_____", ja: "純粋に", sentenceJa: "その決定は純粋に財務的な要因に基づいていた。" },
        { sentence: "The information is ___ available online.", answer: "readily", base: "readily", hint: "r______", ja: "容易に", sentenceJa: "その情報はオンラインで容易に入手できる。" },
        { sentence: "The results will be published ___.", answer: "shortly", base: "shortly", hint: "s______", ja: "間もなく", sentenceJa: "その結果は間もなく公表される予定だ。" },
        { sentence: "The two experiments were conducted ___.", answer: "simultaneously", base: "simultaneously", hint: "s_____________", ja: "同時に", sentenceJa: "その二つの実験は同時に行われた。" },
        { sentence: "The difference between the groups was ___ significant.", answer: "statistically", base: "statistically", hint: "s____________", ja: "統計的に", sentenceJa: "そのグループ間の差は統計的に有意だった。" },
        { sentence: "Access to the lab is ___ controlled.", answer: "strictly", base: "strictly", hint: "s_______", ja: "厳しく", sentenceJa: "その研究室への立ち入りは厳しく管理されている。" },
        { sentence: "The medicine is ___ effective within an hour.", answer: "supposedly", base: "supposedly", hint: "s_________", ja: "とされている、うわさでは", sentenceJa: "その薬は1時間以内に効くとされている。" },
        { sentence: "The plan went ___ wrong from the start.", answer: "terribly", base: "terribly", hint: "t_______", ja: "ひどく", sentenceJa: "その計画は最初からひどくうまくいかなかった。" },
        { sentence: "The company cut costs, ___ increasing profit.", answer: "thereby", base: "thereby", hint: "t______", ja: "それによって", sentenceJa: "その会社はコストを削減し、それによって利益を増やした。" },
        { sentence: "The report is expected ___ next month.", answer: "sometime", base: "sometime", hint: "s_______", ja: "そのうち、いつか", sentenceJa: "その報告書は来月のいつか、公表される見込みだ。" },
      ],
    },
    {
      name: "Day 22",
      items: [
        { sentence: "Last week, the new data ___ the earlier findings.", answer: "contradicted", base: "contradict", hint: "c_________", ja: "矛盾する、反論する", sentenceJa: "先週、新しいデータは以前の調査結果と矛盾した。" },
        { sentence: "The two research fields increasingly ___.", answer: "converge", base: "converge", hint: "c_______", ja: "収束する、一致する", sentenceJa: "その二つの研究分野はますます収束しつつある。" },
        { sentence: "Please ___ the schedule with the other team.", answer: "coordinate", base: "coordinate", hint: "c_________", ja: "調整する", sentenceJa: "他のチームとスケジュールを調整してください。" },
        { sentence: "Last month, the panel ___ each submission carefully.", answer: "critiqued", base: "critique", hint: "c_______", ja: "批評する", sentenceJa: "先月、審査団は各応募作を注意深く批評した。" },
        { sentence: "The study's conclusions must ___ themselves to the sample tested.", answer: "confine", base: "confine", hint: "c______", ja: "制限する、閉じ込める", sentenceJa: "その研究の結論は検証されたサンプルの範囲内に限定されなければならない。" },
        { sentence: "Last year, the results ___ even the leading experts.", answer: "confounded", base: "confound", hint: "c_______", ja: "混同させる、当惑させる", sentenceJa: "昨年、その結果は第一線の専門家たちさえも当惑させた。" },
        { sentence: "The court will ___ its earlier ruling next week.", answer: "affirm", base: "affirm", hint: "a_____", ja: "断言する、肯定する", sentenceJa: "裁判所は来週、以前の判決を支持する予定だ。" },
        { sentence: "Yesterday, the second experiment ___ the original hypothesis.", answer: "validated", base: "validate", hint: "v_______", ja: "検証する、実証する", sentenceJa: "昨日、二回目の実験は当初の仮説を実証した。" },
        { sentence: "Last quarter, the firm ___ its returns through careful planning.", answer: "maximized", base: "maximize", hint: "m_______", ja: "最大化する", sentenceJa: "前四半期、その企業は入念な計画によって利益を最大化した。" },
        { sentence: "Please ___ the key formulas before the exam.", answer: "memorize", base: "memorize", hint: "m_______", ja: "暗記する", sentenceJa: "試験の前に主要な公式を暗記してください。" },
        { sentence: "Last year, the two departments ___ into one.", answer: "merged", base: "merge", hint: "m____", ja: "合併する、融合する", sentenceJa: "昨年、その二つの部門は一つに統合された。" },
        { sentence: "The journal will ___ the study next spring.", answer: "publish", base: "publish", hint: "p______", ja: "出版する、発表する", sentenceJa: "その学術誌は来春、その研究を発表する予定だ。" },
        { sentence: "Yesterday, the team ___ the original data set.", answer: "retrieved", base: "retrieve", hint: "r_______", ja: "取り戻す、検索する", sentenceJa: "昨日、チームは元のデータセットを取り戻した。" },
        { sentence: "Please ___ the introduction more concisely.", answer: "rewrite", base: "rewrite", hint: "r______", ja: "書き直す", sentenceJa: "序論をもっと簡潔に書き直してください。" },
        { sentence: "Last month, the editor ___ the complex terminology.", answer: "simplified", base: "simplify", hint: "s_______", ja: "単純化する", sentenceJa: "先月、編集者はその複雑な専門用語を単純化した。" },
        { sentence: "Last month, researchers ___ public opinion through a nationwide survey.", answer: "gauged", base: "gauge", hint: "g____", ja: "測定する、判断する", sentenceJa: "先月、研究者たちは全国調査を通じて世論を測定した。" },
        { sentence: "Students often struggle to ___ this abstract concept.", answer: "grasp", base: "grasp", hint: "g____", ja: "理解する、把握する", sentenceJa: "学生はしばしばこの抽象的な概念を理解するのに苦労する。" },
        { sentence: "Last year, the jury ___ a unanimous verdict.", answer: "rendered", base: "render", hint: "r_____", ja: "〜にする、下す", sentenceJa: "昨年、陪審団は全会一致の評決を下した。" },
        { sentence: "Last month, other scientists ___ the result independently.", answer: "reproduced", base: "reproduce", hint: "r________", ja: "再現する、複製する", sentenceJa: "先月、他の科学者たちはその結果を独立して再現した。" },
        { sentence: "Last week, the software ___ data from multiple sources.", answer: "aggregated", base: "aggregate", hint: "a________", ja: "集計する、集める", sentenceJa: "先週、そのソフトウェアは複数の情報源からデータを集計した。" },
      ],
    },
    {
      name: "Day 23",
      items: [
        { sentence: "Last month, the team ___ a comprehensive report.", answer: "compiled", base: "compile", hint: "c______", ja: "編集する、まとめる", sentenceJa: "先月、チームは包括的な報告書をまとめた。" },
        { sentence: "This device can ___ temperature with great precision.", answer: "measure", base: "measure", hint: "m______", ja: "測定する", sentenceJa: "この装置は非常に高い精度で温度を測定できる。" },
        { sentence: "Please ___ that the deadline has changed.", answer: "note", base: "note", hint: "n___", ja: "気づく、記録する", sentenceJa: "締め切りが変更されたことにご留意ください。" },
        { sentence: "Last week, researchers ___ unusual behavior in the sample group.", answer: "observed", base: "observe", hint: "o______", ja: "観察する、気づく", sentenceJa: "先週、研究者たちはそのサンプル群に異常な行動を観察した。" },
        { sentence: "The author will ___ that the policy has failed.", answer: "argue", base: "argue", hint: "a____", ja: "主張する", sentenceJa: "著者はその方針が失敗したと主張する予定だ。" },
        { sentence: "Last year, the report ___ a major breakthrough.", answer: "claimed", base: "claim", hint: "c____", ja: "主張する", sentenceJa: "昨年、その報告書は大きな進展を主張した。" },
        { sentence: "Let's ___ the variables remain constant.", answer: "assume", base: "assume", hint: "a_____", ja: "想定する", sentenceJa: "変数は一定のままだと想定しましょう。" },
        { sentence: "Yesterday, her comment ___ a deeper concern.", answer: "implied", base: "imply", hint: "i____", ja: "暗示する、意味する", sentenceJa: "昨日、彼女のコメントはより深い懸念を暗示していた。" },
        { sentence: "Evidence increasingly ___ a link between the two.", answer: "suggests", base: "suggest", hint: "s______", ja: "示唆する、提案する", sentenceJa: "証拠はますますその二つの関連性を示唆している。" },
        { sentence: "The committee will ___ a revised timeline next week.", answer: "propose", base: "propose", hint: "p______", ja: "提案する", sentenceJa: "委員会は来週、修正されたスケジュールを提案する予定だ。" },
        { sentence: "Last year, the school ___ a new curriculum.", answer: "adopted", base: "adopt", hint: "a____", ja: "採用する", sentenceJa: "昨年、その学校は新しいカリキュラムを採用した。" },
        { sentence: "The new rule will ___ access to the archive.", answer: "restrict", base: "restrict", hint: "r_______", ja: "制限する", sentenceJa: "その新しい規則はアーカイブへのアクセスを制限する予定だ。" },
        { sentence: "Last month, the team ___ the damaged manuscript.", answer: "restored", base: "restore", hint: "r______", ja: "回復させる、修復する", sentenceJa: "先月、チームはその損傷した原稿を修復した。" },
        { sentence: "Yesterday, the survey ___ a surprising trend.", answer: "revealed", base: "reveal", hint: "r_____", ja: "明らかにする", sentenceJa: "昨日、その調査は驚くべき傾向を明らかにした。" },
        { sentence: "Historians ___ the custom back to the medieval period.", answer: "trace", base: "trace", hint: "t____", ja: "たどる", sentenceJa: "歴史家はその習慣を中世まで遡ってたどる。" },
        { sentence: "Last year, experts ___ the decline to climate change.", answer: "attributed", base: "attribute", hint: "a________", ja: "帰する、〜のせいにする", sentenceJa: "昨年、専門家たちはその減少を気候変動のせいだとした。" },
        { sentence: "Please ___ your argument before the next draft.", answer: "refine", base: "refine", hint: "r_____", ja: "洗練させる、精製する", sentenceJa: "次の草稿までに議論を洗練させてください。" },
        { sentence: "Last decade, the population ___ rapidly in this region.", answer: "multiplied", base: "multiply", hint: "m_______", ja: "増やす、掛け算する", sentenceJa: "過去10年で、その地域の人口は急速に増加した。" },
        { sentence: "Yesterday, the editor ___ the two recordings together.", answer: "spliced", base: "splice", hint: "s_____", ja: "つなぎ合わせる", sentenceJa: "昨日、編集者はその二つの録音をつなぎ合わせた。" },
        { sentence: "Last year, the government ___ several news reports.", answer: "censored", base: "censor", hint: "c_____", ja: "検閲する", sentenceJa: "昨年、政府はいくつかのニュース報道を検閲した。" },
      ],
    },
    {
      name: "Day 24",
      items: [
        { sentence: "The device measures temperature with high ___.", answer: "accuracy", base: "accuracy", hint: "a_______", ja: "精度、正確さ", sentenceJa: "その装置は高い精度で温度を測定する。" },
        { sentence: "The new ___ processes data much faster than before.", answer: "algorithm", base: "algorithm", hint: "a________", ja: "アルゴリズム", sentenceJa: "その新しいアルゴリズムは以前よりもはるかに速くデータを処理する。" },
        { sentence: "She studied ___ before switching to sociology.", answer: "anthropology", base: "anthropology", hint: "a___________", ja: "人類学", sentenceJa: "彼女は社会学に転向する前に人類学を学んだ。" },
        { sentence: "The artifact dates back to ___.", answer: "antiquity", base: "antiquity", hint: "a________", ja: "古代", sentenceJa: "その遺物は古代にまで遡る。" },
        { sentence: "The ___ of clean water varies across regions.", answer: "availability", base: "availability", hint: "a___________", ja: "入手可能性", sentenceJa: "きれいな水の入手可能性は地域によって異なる。" },
        { sentence: "Deforestation threatens the region's ___.", answer: "biodiversity", base: "biodiversity", hint: "b___________", ja: "生物多様性", sentenceJa: "森林伐採はその地域の生物多様性を脅かしている。" },
        { sentence: "The ___ discovered a new species of insect.", answer: "biologist", base: "biologist", hint: "b________", ja: "生物学者", sentenceJa: "その生物学者は新種の昆虫を発見した。" },
        { sentence: "The offer includes a ___ of software tools.", answer: "bundle", base: "bundle", hint: "b_____", ja: "束、一式", sentenceJa: "その提供内容にはソフトウェアツールの一式が含まれている。" },
        { sentence: "The book critiques the modern ___ system.", answer: "capitalist", base: "capitalist", hint: "c_________", ja: "資本主義者", sentenceJa: "その本は現代の資本主義システムを批判している。" },
        { sentence: "Critics praised the novel's rich ___.", answer: "characterization", base: "characterization", hint: "c_______________", ja: "人物描写、特徴づけ", sentenceJa: "批評家たちはその小説の豊かな人物描写を称賛した。" },
        { sentence: "The magazine's ___ has grown steadily.", answer: "circulation", base: "circulation", hint: "c__________", ja: "発行部数、循環", sentenceJa: "その雑誌の発行部数は着実に伸びている。" },
        { sentence: "Ancient ___ left behind remarkable architecture.", answer: "civilization", base: "civilization", hint: "c___________", ja: "文明", sentenceJa: "古代文明は驚くべき建築物を残した。" },
        { sentence: "The ___ of species relies on shared traits.", answer: "classification", base: "classification", hint: "c_____________", ja: "分類", sentenceJa: "種の分類は共通の特徴に依拠している。" },
        { sentence: "Scientists successfully created a ___ of the plant.", answer: "clone", base: "clone", hint: "c____", ja: "クローン", sentenceJa: "科学者たちはその植物のクローンを作り出すことに成功した。" },
        { sentence: "The factory's ___ affected hundreds of workers.", answer: "closure", base: "closure", hint: "c______", ja: "閉鎖", sentenceJa: "その工場の閉鎖は何百人もの労働者に影響を与えた。" },
        { sentence: "The ___ gained independence in the twentieth century.", answer: "colony", base: "colony", hint: "c_____", ja: "植民地", sentenceJa: "その植民地は20世紀に独立を果たした。" },
        { sentence: "The professor offered valuable ___ on the text.", answer: "commentary", base: "commentary", hint: "c_________", ja: "論評、解説", sentenceJa: "教授はその文章について貴重な論評を提供した。" },
        { sentence: "Oil remains a vital global ___.", answer: "commodity", base: "commodity", hint: "c________", ja: "商品、必需品", sentenceJa: "石油は依然として世界的に重要な商品である。" },
        { sentence: "The ___ government controlled all industries.", answer: "communist", base: "communist", hint: "c________", ja: "共産主義者", sentenceJa: "その共産主義政府は全ての産業を管理していた。" },
        { sentence: "The test measures a candidate's linguistic ___.", answer: "competence", base: "competence", hint: "c_________", ja: "能力、力量", sentenceJa: "その試験は候補者の言語運用能力を測定する。" },
      ],
    },
    {
      name: "Day 25",
      items: [
        { sentence: "The scarf is a perfect ___ to the outfit.", answer: "complement", base: "complement", hint: "c_________", ja: "添え物、補完するもの", sentenceJa: "そのスカーフはその服装に完璧に合う添え物だ。" },
        { sentence: "The surgery proceeded without any ___.", answer: "complication", base: "complication", hint: "c___________", ja: "合併症、複雑化", sentenceJa: "その手術は合併症もなく進行した。" },
        { sentence: "The material is a ___ of plastic and metal.", answer: "composite", base: "composite", hint: "c________", ja: "複合材、合成物", sentenceJa: "その素材はプラスチックと金属の複合材だ。" },
        { sentence: "The exam tests reading ___ skills.", answer: "comprehension", base: "comprehension", hint: "c____________", ja: "理解、読解力", sentenceJa: "その試験は読解力を測定する。" },
        { sentence: "The default ___ works for most users.", answer: "configuration", base: "configuration", hint: "c____________", ja: "設定、構成", sentenceJa: "デフォルトの設定はほとんどのユーザーに適している。" },
        { sentence: "The word carries a negative ___ in this context.", answer: "connotation", base: "connotation", hint: "c__________", ja: "含意、言外の意味", sentenceJa: "その単語はこの文脈では否定的な含意を持つ。" },
        { sentence: "The novel explores the nature of human ___.", answer: "consciousness", base: "consciousness", hint: "c____________", ja: "意識", sentenceJa: "その小説は人間の意識の本質を探求している。" },
        { sentence: "Researchers must obtain informed ___ from participants.", answer: "consent", base: "consent", hint: "c______", ja: "同意", sentenceJa: "研究者は参加者からインフォームドコンセントを得なければならない。" },
        { sentence: "The organization focuses on wildlife ___.", answer: "conservation", base: "conservation", hint: "c___________", ja: "保護、保全", sentenceJa: "その団体は野生生物の保護に重点を置いている。" },
        { sentence: "The country's ___ guarantees basic freedoms.", answer: "constitution", base: "constitution", hint: "c___________", ja: "憲法", sentenceJa: "その国の憲法は基本的自由を保障している。" },
        { sentence: "Patients can book a free initial ___.", answer: "consultation", base: "consultation", hint: "c___________", ja: "相談、協議", sentenceJa: "患者は無料の初回相談を予約できる。" },
        { sentence: "The director aimed for visual ___ between scenes.", answer: "continuity", base: "continuity", hint: "c_________", ja: "連続性", sentenceJa: "その監督はシーン間の視覚的な連続性を目指した。" },
        { sentence: "The report contains a clear ___.", answer: "contradiction", base: "contradiction", hint: "c____________", ja: "矛盾", sentenceJa: "その報告書には明らかな矛盾がある。" },
        { sentence: "___ to expectations, sales actually rose.", answer: "contrary", base: "contrary", hint: "c_______", ja: "反対、逆", sentenceJa: "予想に反して、売上は実際には上昇した。" },
        { sentence: "The decision sparked significant ___.", answer: "controversy", base: "controversy", hint: "c__________", ja: "論争", sentenceJa: "その決定は大きな論争を引き起こした。" },
        { sentence: "The ___ of the two rivers creates a natural landmark.", answer: "convergence", base: "convergence", hint: "c__________", ja: "収束、合流", sentenceJa: "その二つの川の合流点は自然の目印を作り出している。" },
        { sentence: "The project required close ___ between teams.", answer: "coordination", base: "coordination", hint: "c___________", ja: "連携、調整", sentenceJa: "そのプロジェクトはチーム間の緊密な連携を必要とした。" },
        { sentence: "The study analyzed a large ___ of newspaper articles.", answer: "corpus", base: "corpus", hint: "c_____", ja: "コーパス", sentenceJa: "その研究は新聞記事の大規模なコーパスを分析した。" },
        { sentence: "The historian studied the writer's personal ___.", answer: "correspondence", base: "correspondence", hint: "c_____________", ja: "書簡、通信", sentenceJa: "その歴史家はその作家の個人的な書簡を研究した。" },
        { sentence: "The scandal damaged the politician's ___.", answer: "credibility", base: "credibility", hint: "c__________", ja: "信頼性", sentenceJa: "そのスキャンダルはその政治家の信頼性を傷つけた。" },
      ],
    },
    {
      name: "Day 26",
      items: [
        { sentence: "She has always shown strong ___ talent.", answer: "artistic", base: "artistic", hint: "a_______", ja: "芸術的な", sentenceJa: "彼女は常に強い芸術的才能を示してきた。" },
        { sentence: "The forest was too ___ to walk through easily.", answer: "dense", base: "dense", hint: "d____", ja: "密生した、密集した", sentenceJa: "その森は簡単には歩き抜けられないほど密生していた。" },
        { sentence: "The two groups showed a clear ___ response to treatment.", answer: "differential", base: "differential", hint: "d___________", ja: "差異のある、差別的な", sentenceJa: "その二つのグループは治療に対して明確に異なる反応を示した。" },
        { sentence: "The material is highly ___ and returns to its shape.", answer: "elastic", base: "elastic", hint: "e______", ja: "弾力性のある", sentenceJa: "その素材は非常に弾力性があり、元の形に戻る。" },
        { sentence: "Only an ___ group of athletes qualified for the finals.", answer: "elite", base: "elite", hint: "e____", ja: "選ばれた", sentenceJa: "エリート集団の選手たちだけが決勝に進んだ。" },
        { sentence: "The trait offers a clear ___ advantage.", answer: "evolutionary", base: "evolutionary", hint: "e___________", ja: "進化上の", sentenceJa: "その特徴は明確な進化上の利点をもたらす。" },
        { sentence: "Her writing style is ___ and easy to follow.", answer: "fluid", base: "fluid", hint: "f____", ja: "流暢な、流動的な", sentenceJa: "彼女の文体は流暢で読みやすい。" },
        { sentence: "There was an ___ agreement between the two parties.", answer: "implicit", base: "implicit", hint: "i_______", ja: "暗黙の", sentenceJa: "その二者の間には暗黙の合意があった。" },
        { sentence: "The team achieved ___ results in a short time.", answer: "incredible", base: "incredible", hint: "i_________", ja: "信じられないほどの", sentenceJa: "そのチームは短期間で信じられないほどの結果を達成した。" },
        { sentence: "The policy had an ___ effect on employment.", answer: "indirect", base: "indirect", hint: "i_______", ja: "間接的な", sentenceJa: "その方針は雇用に間接的な影響を与えた。" },
        { sentence: "The meeting was ___ and relaxed.", answer: "informal", base: "informal", hint: "i_______", ja: "非公式の、くだけた", sentenceJa: "その会議は非公式で和やかだった。" },
        { sentence: "Curiosity seems to be an ___ human trait.", answer: "innate", base: "innate", hint: "i_____", ja: "生まれつきの", sentenceJa: "好奇心は人間の生まれつきの特性のようだ。" },
        { sentence: "Trust is ___ to any successful partnership.", answer: "integral", base: "integral", hint: "i_______", ja: "不可欠な", sentenceJa: "信頼はどんな成功したパートナーシップにも不可欠だ。" },
        { sentence: "The course is designed for ___ learners.", answer: "intermediate", base: "intermediate", hint: "i___________", ja: "中級の、中間の", sentenceJa: "そのコースは中級学習者向けに設計されている。" },
        { sentence: "The mediator remained ___ throughout the negotiation.", answer: "neutral", base: "neutral", hint: "n______", ja: "中立の", sentenceJa: "その調停者は交渉を通じて中立を保った。" },
        { sentence: "The report presents ___ evidence for the trend.", answer: "numerical", base: "numerical", hint: "n________", ja: "数値の", sentenceJa: "その報告書はその傾向を裏付ける数値的な証拠を提示している。" },
        { sentence: "Researchers identified the ___ temperature for growth.", answer: "optimal", base: "optimal", hint: "o______", ja: "最適な", sentenceJa: "研究者たちは成長にとって最適な温度を特定した。" },
        { sentence: "Students must pass both a written and an ___ exam.", answer: "oral", base: "oral", hint: "o___", ja: "口頭の", sentenceJa: "学生は筆記試験と口頭試験の両方に合格しなければならない。" },
        { sentence: "The lecture raised several ___ questions.", answer: "philosophical", base: "philosophical", hint: "p____________", ja: "哲学的な", sentenceJa: "その講義はいくつかの哲学的な問いを提起した。" },
        { sentence: "The manager took a ___ approach to the problem.", answer: "pragmatic", base: "pragmatic", hint: "p________", ja: "実用的な", sentenceJa: "そのマネージャーはその問題に実用的な手法で取り組んだ。" },
      ],
    },
    {
      name: "Day 27",
      items: [
        { sentence: "The plan was risky; ___, the board approved it.", answer: "nonetheless", base: "nonetheless", hint: "n__________", ja: "それでも", sentenceJa: "その計画は危険だったが、それでも取締役会はそれを承認した。" },
        { sentence: "The company introduced a new system ___ employees can work remotely.", answer: "whereby", base: "whereby", hint: "w______", ja: "それによって", sentenceJa: "その会社は従業員が在宅勤務できる新しい制度を導入した。" },
        { sentence: "They discussed the results and went for lunch ___.", answer: "afterward", base: "afterward", hint: "a________", ja: "その後で", sentenceJa: "彼らは結果について話し合い、その後で昼食に行った。" },
        { sentence: "The research findings were recognized ___.", answer: "internationally", base: "internationally", hint: "i______________", ja: "国際的に", sentenceJa: "その研究結果は国際的に認められた。" },
        { sentence: "The two species are ___ very similar.", answer: "genetically", base: "genetically", hint: "g__________", ja: "遺伝的に", sentenceJa: "その二つの種は遺伝的に非常に似ている。" },
        { sentence: "The professor praised the essay, and the reviewers did ___.", answer: "likewise", base: "likewise", hint: "l_______", ja: "同様に", sentenceJa: "教授はその論文を称賛し、査読者たちも同様にそうした。" },
        { sentence: "The plan is expensive; ___, it lacks clear benefits.", answer: "moreover", base: "moreover", hint: "m_______", ja: "その上、さらに", sentenceJa: "その計画は費用がかかる上に、明確な利点も欠けている。" },
        { sentence: "The data is outdated; ___, the sample size was too small.", answer: "furthermore", base: "furthermore", hint: "f__________", ja: "さらに、その上", sentenceJa: "そのデータは古い上に、サンプルサイズも小さすぎた。" },
        { sentence: "The results were disappointing; ___, the team continued the research.", answer: "nevertheless", base: "nevertheless", hint: "n___________", ja: "それにもかかわらず", sentenceJa: "その結果はがっかりするものだったが、それでもチームは研究を続けた。" },
        { sentence: "The bridge was closed for repairs, ___ the traffic delay.", answer: "hence", base: "hence", hint: "h____", ja: "それゆえに", sentenceJa: "その橋は修理のために閉鎖されており、それゆえに交通渋滞が起きた。" },
        { sentence: "The experiment failed, and ___ the theory was rejected.", answer: "thus", base: "thus", hint: "t___", ja: "こうして、それゆえ", sentenceJa: "その実験は失敗し、こうしてその理論は否定された。" },
        { sentence: "The manager reviewed the budget; ___, the team prepared the presentation.", answer: "meanwhile", base: "meanwhile", hint: "m________", ja: "その間、一方で", sentenceJa: "マネージャーは予算を見直し、その間チームはプレゼンの準備をした。" },
        { sentence: "The rule takes effect today; ___, all visitors must register.", answer: "henceforth", base: "henceforth", hint: "h_________", ja: "これ以降", sentenceJa: "その規則は本日より発効し、これ以降全ての訪問者は登録しなければならない。" },
        { sentence: "___, the project was considered a success.", answer: "overall", base: "overall", hint: "o______", ja: "全体として", sentenceJa: "全体として、そのプロジェクトは成功とみなされた。" },
        { sentence: "The survey included ___ one thousand participants.", answer: "roughly", base: "roughly", hint: "r______", ja: "およそ", sentenceJa: "その調査にはおよそ1000人の参加者が含まれていた。" },
        { sentence: "The two designs are ___ identical.", answer: "virtually", base: "virtually", hint: "v________", ja: "実質的に、ほぼ", sentenceJa: "その二つのデザインは実質的に同一だ。" },
        { sentence: "The two events were, ___, unrelated.", answer: "seemingly", base: "seemingly", hint: "s________", ja: "見たところ、一見", sentenceJa: "その二つの出来事は、見たところ、無関係だった。" },
        { sentence: "The results ___ point to the same conclusion.", answer: "invariably", base: "invariably", hint: "i_________", ja: "決まって、常に", sentenceJa: "その結果は決まって同じ結論を示す。" },
        { sentence: "The candidates were interviewed ___ throughout the day.", answer: "successively", base: "successively", hint: "s___________", ja: "次々に、連続して", sentenceJa: "その候補者たちはその日を通じて次々に面接を受けた。" },
        { sentence: "The symptoms became ___ worse over time.", answer: "progressively", base: "progressively", hint: "p____________", ja: "徐々に", sentenceJa: "その症状は時間とともに徐々に悪化した。" },
      ],
    },
    {
      name: "Day 29",
      items: [
        { sentence: "This theory still ___ that all matter is made of tiny particles.", answer: "postulates", base: "postulate", hint: "p________", ja: "仮定する、提唱する", sentenceJa: "この理論は今でも、全ての物質が微小な粒子でできていると仮定している。" },
        { sentence: "This contract ___ a thirty-day notice period.", answer: "stipulates", base: "stipulate", hint: "s________", ja: "規定する、明記する", sentenceJa: "この契約書は30日前の通知期間を規定している。" },
        { sentence: "Last year, new evidence ___ the original claim.", answer: "substantiated", base: "substantiate", hint: "s___________", ja: "実証する、裏付ける", sentenceJa: "昨年、新しい証拠が当初の主張を裏付けた。" },
        { sentence: "Additional testimony should ___ the police report.", answer: "corroborate", base: "corroborate", hint: "c__________", ja: "裏付ける、確証する", sentenceJa: "追加の証言は警察の報告書を裏付けるはずだ。" },
        { sentence: "Last year, researchers ___ future trends from the existing data.", answer: "extrapolated", base: "extrapolate", hint: "e__________", ja: "推定する、外挿する", sentenceJa: "昨年、研究者たちは既存のデータから将来の傾向を推定した。" },
        { sentence: "The report will ___ findings from multiple studies.", answer: "synthesize", base: "synthesize", hint: "s_________", ja: "統合する、合成する", sentenceJa: "その報告書は複数の研究結果を統合する予定だ。" },
        { sentence: "Please ___ the agreement in writing.", answer: "formalize", base: "formalize", hint: "f________", ja: "正式なものにする", sentenceJa: "その合意を書面で正式なものにしてください。" },
        { sentence: "Last century, the rules were ___ into a single legal document.", answer: "codified", base: "codify", hint: "c_____", ja: "成文化する、体系化する", sentenceJa: "前世紀、その規則は一つの法律文書にまとめられた。" },
        { sentence: "This map ___ the boundary between the two regions.", answer: "delineates", base: "delineate", hint: "d________", ja: "明確に示す、輪郭を描く", sentenceJa: "この地図はその二つの地域の境界を明確に示している。" },
        { sentence: "Please ___ the main causes of the decline.", answer: "enumerate", base: "enumerate", hint: "e________", ja: "列挙する", sentenceJa: "その減少の主な原因を列挙してください。" },
        { sentence: "This case still ___ a common problem in the field.", answer: "exemplifies", base: "exemplify", hint: "e________", ja: "例証する、典型となる", sentenceJa: "この事例は今でも、その分野におけるよくある問題の典型となっている。" },
        { sentence: "Please ___ the document with your comments.", answer: "annotate", base: "annotate", hint: "a_______", ja: "注釈をつける", sentenceJa: "その文書にあなたのコメントで注釈をつけてください。" },
        { sentence: "Great art can ___ cultural boundaries.", answer: "transcend", base: "transcend", hint: "t________", ja: "超越する", sentenceJa: "優れた芸術は文化の境界を超越することがある。" },
        { sentence: "Strong evidence still ___ the researchers' conclusion.", answer: "underpins", base: "underpin", hint: "u_______", ja: "支える、基礎となる", sentenceJa: "強力な証拠が今でも研究者たちの結論を支えている。" },
        { sentence: "The organization will ___ the report to all members.", answer: "disseminate", base: "disseminate", hint: "d__________", ja: "広める、普及させる", sentenceJa: "その団体はその報告書を全会員に広める予定だ。" },
        { sentence: "Last year, the policy ___ existing inequalities.", answer: "perpetuated", base: "perpetuate", hint: "p_________", ja: "永続させる", sentenceJa: "昨年、その方針は既存の不平等を永続させた。" },
        { sentence: "Social media platforms ___ rapidly last decade.", answer: "proliferated", base: "proliferate", hint: "p__________", ja: "急増する、増殖する", sentenceJa: "この前の10年、ソーシャルメディアのプラットフォームは急速に急増した。" },
        { sentence: "Last month, the two companies ___ their differences.", answer: "reconciled", base: "reconcile", hint: "r________", ja: "和解させる、調和させる", sentenceJa: "先月、その二つの会社は意見の相違を解消した。" },
        { sentence: "Last year, the new data ___ the earlier hypothesis.", answer: "refuted", base: "refute", hint: "r_____", ja: "論駁する、反証する", sentenceJa: "昨年、新しいデータは以前の仮説を反証した。" },
        { sentence: "The professor will ___ the main points at the end.", answer: "reiterate", base: "reiterate", hint: "r________", ja: "繰り返し述べる", sentenceJa: "教授は最後に要点を繰り返し述べる予定だ。" },
      ],
    },
    {
      name: "Day 30",
      items: [
        { sentence: "Historically, many of these problems ___ from poor communication.", answer: "stemmed", base: "stem", hint: "s___", ja: "生じる、由来する", sentenceJa: "歴史的に、これらの問題の多くはコミュニケーション不足に起因していた。" },
        { sentence: "New ideas can ___ an organization slowly, even without formal training.", answer: "permeate", base: "permeate", hint: "p_______", ja: "浸透する", sentenceJa: "新しいアイデアは、正式な研修がなくても組織にゆっくりと浸透することがある。" },
        { sentence: "Last month, a minor dispute ___ a major conflict.", answer: "instigated", base: "instigate", hint: "i________", ja: "扇動する、引き起こす", sentenceJa: "先月、些細な対立が大きな衝突を引き起こした。" },
        { sentence: "Last year, the new law ___ practices that were once informal.", answer: "legitimized", base: "legitimize", hint: "l_________", ja: "正当化する", sentenceJa: "昨年、その新しい法律はかつて非公式だった慣行を正当化した。" },
        { sentence: "Last month, engineers ___ the code for faster performance.", answer: "optimized", base: "optimize", hint: "o_______", ja: "最適化する", sentenceJa: "先月、エンジニアたちはより速いパフォーマンスのためにコードを最適化した。" },
        { sentence: "The various arguments in the essay do not ___ well.", answer: "cohere", base: "cohere", hint: "c_____", ja: "まとまる、一貫する", sentenceJa: "そのエッセイの様々な議論はうまくまとまっていない。" },
        { sentence: "Last year, new regulations ___ the approval process.", answer: "complicated", base: "complicate", hint: "c_________", ja: "複雑にする", sentenceJa: "昨年、新しい規制が承認プロセスを複雑にした。" },
        { sentence: "The company plans to ___ spending next quarter.", answer: "curtail", base: "curtail", hint: "c______", ja: "削減する、切り詰める", sentenceJa: "その会社は来四半期、支出を削減する計画だ。" },
        { sentence: "A simple principle still ___ this complex theory.", answer: "underlies", base: "underlie", hint: "u_______", ja: "根底にある", sentenceJa: "単純な原理が今でもこの複雑な理論の根底にある。" },
        { sentence: "This sentence still ___ the author's main argument well.", answer: "encapsulates", base: "encapsulate", hint: "e__________", ja: "要約する、凝縮する", sentenceJa: "この一文は今でも著者の主な主張をうまく要約している。" },
        { sentence: "New measures were introduced to ___ the risk.", answer: "mitigate", base: "mitigate", hint: "m_______", ja: "軽減する", sentenceJa: "リスクを軽減するために新しい対策が導入された。" },
        { sentence: "Last month, the new policy ___ some of the financial pressure.", answer: "alleviated", base: "alleviate", hint: "a________", ja: "緩和する", sentenceJa: "先月、その新しい方針は財政的な圧力の一部を緩和した。" },
        { sentence: "Poor sleep can ___ stress levels.", answer: "exacerbate", base: "exacerbate", hint: "e_________", ja: "悪化させる", sentenceJa: "睡眠不足はストレスレベルを悪化させることがある。" },
        { sentence: "Last year, the government introduced measures to ___ inflation.", answer: "counteract", base: "counteract", hint: "c_________", ja: "中和する、対抗する", sentenceJa: "昨年、政府はインフレに対抗する対策を導入した。" },
        { sentence: "Please ___ the error before submitting the final report.", answer: "rectify", base: "rectify", hint: "r______", ja: "是正する、修正する", sentenceJa: "最終報告書を提出する前にその誤りを是正してください。" },
        { sentence: "Last year, the two firms ___ their operations.", answer: "consolidated", base: "consolidate", hint: "c__________", ja: "統合する、強化する", sentenceJa: "昨年、その二つの企業は業務を統合した。" },
        { sentence: "Last year, the new software ___ the entire workflow.", answer: "streamlined", base: "streamline", hint: "s_________", ja: "効率化する", sentenceJa: "昨年、その新しいソフトウェアは業務フロー全体を効率化した。" },
        { sentence: "Last year, the exhibit ___ modern and ancient art.", answer: "juxtaposed", base: "juxtapose", hint: "j________", ja: "並置する", sentenceJa: "昨年、その展示会は現代美術と古代美術を並置した。" },
        { sentence: "Yesterday, technicians ___ the equipment before the test.", answer: "calibrated", base: "calibrate", hint: "c________", ja: "調整する、較正する", sentenceJa: "昨日、技術者たちは試験の前に機器を較正した。" },
        { sentence: "Please ___ the quotation in your own words.", answer: "paraphrase", base: "paraphrase", hint: "p_________", ja: "言い換える", sentenceJa: "その引用をあなた自身の言葉で言い換えてください。" },
      ],
    },
  ],
};
