// TOEIC 単語テスト問題（PDFのWord List例文から生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
module.exports = {
  label: "TOEIC",
  series: [
    {
      name: "Series 1",
      items: [
        { sentence: "The company will ___ its annual report next week.", answer: "publish", base: "publish", hint: "p______", ja: "出版する、公表する" },
        { sentence: "Please ___ a copy of your receipt with the form.", answer: "enclose", base: "enclose", hint: "e______", ja: "同封する" },
        { sentence: "We will ___ you as soon as your order ships.", answer: "notify", base: "notify", hint: "n_____", ja: "通知する" },
        { sentence: "You can ___ a visitor's pass at the front desk.", answer: "obtain", base: "obtain", hint: "o_____", ja: "入手する、得る" },
        { sentence: "The manager decided to ___ the meeting until Friday.", answer: "postpone", base: "postpone", hint: "p_______", ja: "延期する" },
        { sentence: "The express train will ___ from platform 3.", answer: "depart", base: "depart", hint: "d_____", ja: "出発する" },
        { sentence: "Don't forget to ___ your membership before it expires.", answer: "renew", base: "renew", hint: "r____", ja: "更新する" },
        { sentence: "Your parking permit will ___ at the end of the month.", answer: "expire", base: "expire", hint: "e_____", ja: "期限が切れる" },
        { sentence: "A technician will ___ the equipment tomorrow.", answer: "inspect", base: "inspect", hint: "i______", ja: "検査する" },
        { sentence: "Several customers called to ___ about the new service.", answer: "inquire", base: "inquire", hint: "i______", ja: "問い合わせる" },
        { sentence: "Company rules ___ the use of phones during meetings.", answer: "prohibit", base: "prohibit", hint: "p_______", ja: "禁止する" },
        { sentence: "She will ___ the new team of interns.", answer: "supervise", base: "supervise", hint: "s________", ja: "監督する" },
        { sentence: "Many readers ___ to our weekly newsletter.", answer: "subscribe", base: "subscribe", hint: "s________", ja: "定期購読する、加入する" },
        { sentence: "Only the director can ___ these payments.", answer: "authorize", base: "authorize", hint: "a________", ja: "許可する、承認する" },
        { sentence: "The hall can ___ up to 300 guests.", answer: "accommodate", base: "accommodate", hint: "a__________", ja: "収容する、対応する" },
        { sentence: "These days, he ___ to the office by train every day.", answer: "commutes", base: "commute", hint: "c_______", ja: "通勤する" },
        { sentence: "The firm plans to ___ its head office next year.", answer: "relocate", base: "relocate", hint: "r_______", ja: "移転する" },
        { sentence: "Please ___ your email address before logging in.", answer: "verify", base: "verify", hint: "v_____", ja: "確認する、検証する" },
        { sentence: "Could you ___ your reservation by Friday?", answer: "confirm", base: "confirm", hint: "c______", ja: "確認する、確定する" },
        { sentence: "Hundreds of students ___ in the program each year.", answer: "enroll", base: "enroll", hint: "e_____", ja: "登録する、入会する" },
      ],
    },
    {
      name: "Series 2",
      items: [
        { sentence: "Workers ___ the furniture before it is shipped.", answer: "assemble", base: "assemble", hint: "a_______", ja: "組み立てる、集める" },
        { sentence: "She will ___ the schedules of all the departments.", answer: "coordinate", base: "coordinate", hint: "c_________", ja: "調整する、まとめる" },
        { sentence: "The company will ___ a new area for parking.", answer: "designate", base: "designate", hint: "d________", ja: "指定する、任命する" },
        { sentence: "Volunteers will ___ brochures at the entrance.", answer: "distribute", base: "distribute", hint: "d_________", ja: "配布する、流通させる" },
        { sentence: "The company will ___ you for travel costs.", answer: "reimburse", base: "reimburse", hint: "r________", ja: "払い戻す、精算する" },
        { sentence: "It may take a few days to ___ your refund.", answer: "process", base: "process", hint: "p______", ja: "処理する" },
        { sentence: "The new software will ___ online ordering.", answer: "facilitate", base: "facilitate", hint: "f_________", ja: "促進する、容易にする" },
        { sentence: "All factories must ___ with safety regulations.", answer: "comply", base: "comply", hint: "c_____", ja: "（規則に）従う" },
        { sentence: "Managers ___ the performance of each employee yearly.", answer: "assess", base: "assess", hint: "a_____", ja: "評価する、査定する" },
        { sentence: "The firm will ___ a survey of its customers.", answer: "conduct", base: "conduct", hint: "c______", ja: "（業務などを）行う" },
        { sentence: "A technician came to ___ the new printer.", answer: "install", base: "install", hint: "i______", ja: "設置する、導入する" },
        { sentence: "Please ___ your report by the end of the day.", answer: "submit", base: "submit", hint: "s_____", ja: "提出する" },
        { sentence: "You can ___ tickets at the front counter.", answer: "purchase", base: "purchase", hint: "p_______", ja: "購入する" },
        { sentence: "The manager will ___ the terms of the contract.", answer: "negotiate", base: "negotiate", hint: "n________", ja: "交渉する" },
        { sentence: "The company is trying to ___ skilled engineers.", answer: "recruit", base: "recruit", hint: "r______", ja: "採用する、募集する" },
        { sentence: "Last week, the builder ___ the cost of the repairs.", answer: "estimated", base: "estimate", hint: "e________", ja: "見積もる" },
        { sentence: "Only trained staff may ___ this machine.", answer: "operate", base: "operate", hint: "o______", ja: "操作する、運営する" },
        { sentence: "The store will ___ its sale on social media.", answer: "promote", base: "promote", hint: "p______", ja: "昇進させる、宣伝する" },
        { sentence: "The board must ___ the new budget.", answer: "approve", base: "approve", hint: "a______", ja: "承認する" },
        { sentence: "All managers must ___ the monthly meeting.", answer: "attend", base: "attend", hint: "a_____", ja: "出席する" },
      ],
    },
    {
      name: "Series 3",
      items: [
        { sentence: "She is taking a two-week ___ in July.", answer: "vacation", base: "vacation", hint: "v_______", ja: "休暇" },
        { sentence: "Our biggest ___ signed a new contract today.", answer: "client", base: "client", hint: "c_____", ja: "顧客、依頼人" },
        { sentence: "I made a ___ for four at the restaurant.", answer: "reservation", base: "reservation", hint: "r__________", ja: "予約" },
        { sentence: "Ask your ___ before changing the schedule.", answer: "supervisor", base: "supervisor", hint: "s_________", ja: "上司、監督者" },
        { sentence: "Customers can request a full ___ within 30 days.", answer: "refund", base: "refund", hint: "r_____", ja: "返金" },
        { sentence: "We must finish the project before the ___.", answer: "deadline", base: "deadline", hint: "d_______", ja: "締め切り" },
        { sentence: "The supplier sent an ___ for last month's order.", answer: "invoice", base: "invoice", hint: "i______", ja: "請求書" },
        { sentence: "Pick up a ___ for details about the tour.", answer: "brochure", base: "brochure", hint: "b_______", ja: "パンフレット" },
        { sentence: "Each ___ must attend an interview.", answer: "applicant", base: "applicant", hint: "a________", ja: "応募者" },
        { sentence: "Keep your ___ in case you return the item.", answer: "receipt", base: "receipt", hint: "r______", ja: "レシート、領収書" },
        { sentence: "The ___ of supplies arrived this morning.", answer: "shipment", base: "shipment", hint: "s_______", ja: "発送、出荷" },
        { sentence: "This laptop comes with a two-year ___.", answer: "warranty", base: "warranty", hint: "w_______", ja: "保証（書）" },
        { sentence: "The staff check the ___ every month.", answer: "inventory", base: "inventory", hint: "i________", ja: "在庫（品）" },
        { sentence: "She attended a marketing ___ last week.", answer: "seminar", base: "seminar", hint: "s______", ja: "セミナー、研修会" },
        { sentence: "The hotel is a popular ___ for conferences.", answer: "venue", base: "venue", hint: "v____", ja: "会場" },
        { sentence: "The ___ of the two firms was announced today.", answer: "merger", base: "merger", hint: "m_____", ja: "合併" },
        { sentence: "The travel agent emailed us the ___.", answer: "itinerary", base: "itinerary", hint: "i________", ja: "旅程（表）" },
        { sentence: "He earned extra pay for working ___.", answer: "overtime", base: "overtime", hint: "o_______", ja: "残業" },
        { sentence: "We welcome your ___ on our new service.", answer: "feedback", base: "feedback", hint: "f_______", ja: "意見、フィードバック" },
        { sentence: "All travel ___ will be paid by the company.", answer: "expenses", base: "expense", hint: "e_______", ja: "費用、経費" },
      ],
    },
    {
      name: "Series 4",
      items: [
        { sentence: "The first item on the ___ is the budget review.", answer: "agenda", base: "agenda", hint: "a_____", ja: "議題" },
        { sentence: "The team went over its ___ last quarter.", answer: "budget", base: "budget", hint: "b_____", ja: "予算" },
        { sentence: "She had lunch with two ___ from her team.", answer: "colleagues", base: "colleague", hint: "c_________", ja: "同僚" },
        { sentence: "Both companies signed the ___ yesterday.", answer: "contract", base: "contract", hint: "c_______", ja: "契約（書）" },
        { sentence: "He works in the accounting ___.", answer: "department", base: "department", hint: "d_________", ja: "部署、部門" },
        { sentence: "The gym bought new ___ this year.", answer: "equipment", base: "equipment", hint: "e________", ja: "機器、設備" },
        { sentence: "The new sports ___ has a pool and a gym.", answer: "facility", base: "facility", hint: "f_______", ja: "施設、設備" },
        { sentence: "The company's ___ is in Chicago.", answer: "headquarters", base: "headquarters", hint: "h___________", ja: "本社、本部" },
        { sentence: "The store sells every kitchen ___ you need.", answer: "appliance", base: "appliance", hint: "a________", ja: "家電製品" },
        { sentence: "We received a ___ about the late delivery.", answer: "complaint", base: "complaint", hint: "c________", ja: "苦情" },
        { sentence: "Every ___ gets ten days of paid leave.", answer: "employee", base: "employee", hint: "e_______", ja: "従業員" },
        { sentence: "This job is a great ___ to learn new skills.", answer: "opportunity", base: "opportunity", hint: "o__________", ja: "機会" },
        { sentence: "The new train ___ starts next month.", answer: "schedule", base: "schedule", hint: "s_______", ja: "予定、スケジュール" },
        { sentence: "Our bank opened a new ___ downtown.", answer: "branch", base: "branch", hint: "b_____", ja: "支店" },
        { sentence: "Free ___ is available for orders over $50.", answer: "delivery", base: "delivery", hint: "d_______", ja: "配達" },
        { sentence: "The job offers a good ___ and benefits.", answer: "salary", base: "salary", hint: "s_____", ja: "給料" },
        { sentence: "We found a cheaper ___ for the materials.", answer: "supplier", base: "supplier", hint: "s_______", ja: "供給業者、仕入先" },
        { sentence: "___ for the workshop closes on Friday.", answer: "registration", base: "registration", hint: "r___________", ja: "登録" },
        { sentence: "You need a ___ to park in this area.", answer: "permit", base: "permit", hint: "p_____", ja: "許可証" },
        { sentence: "The company sent a ___ for the repair work.", answer: "quotation", base: "quotation", hint: "q________", ja: "見積もり" },
      ],
    },
    {
      name: "Series 5",
      items: [
        { sentence: "Her explanation was clear and ___.", answer: "logical", base: "logical", hint: "l______", ja: "論理的な" },
        { sentence: "The station is in a very ___ location.", answer: "convenient", base: "convenient", hint: "c_________", ja: "便利な" },
        { sentence: "Your ticket is ___ for one month.", answer: "valid", base: "valid", hint: "v____", ja: "有効な" },
        { sentence: "Full-time staff are ___ for the bonus.", answer: "eligible", base: "eligible", hint: "e_______", ja: "資格のある" },
        { sentence: "She received an award for her ___ work.", answer: "outstanding", base: "outstanding", hint: "o__________", ja: "傑出した、未払いの" },
        { sentence: "Safety training is ___ for all new staff.", answer: "mandatory", base: "mandatory", hint: "m________", ja: "義務的な、必須の" },
        { sentence: "These boots are strong and ___.", answer: "durable", base: "durable", hint: "d______", ja: "耐久性のある、丈夫な" },
        { sentence: "The store offers stylish but ___ clothes.", answer: "affordable", base: "affordable", hint: "a_________", ja: "手頃な価格の" },
        { sentence: "All medical records are kept ___.", answer: "confidential", base: "confidential", hint: "c___________", ja: "機密の" },
        { sentence: "Please reply soon; this is an ___ matter.", answer: "urgent", base: "urgent", hint: "u_____", ja: "緊急の" },
        { sentence: "They hired some ___ staff for the holidays.", answer: "temporary", base: "temporary", hint: "t________", ja: "一時的な" },
        { sentence: "The new system is faster and more ___.", answer: "efficient", base: "efficient", hint: "e________", ja: "効率的な" },
        { sentence: "We need a ___ supplier for our parts.", answer: "reliable", base: "reliable", hint: "r_______", ja: "信頼できる" },
        { sentence: "The hotel offers a ___ breakfast.", answer: "complimentary", base: "complimentary", hint: "c____________", ja: "無料の" },
        { sentence: "Attendance at the evening session is ___.", answer: "optional", base: "optional", hint: "o_______", ja: "任意の、選択できる" },
        { sentence: "The new office is bright and ___.", answer: "spacious", base: "spacious", hint: "s_______", ja: "広々とした" },
        { sentence: "The agent showed the house to several ___ buyers.", answer: "prospective", base: "prospective", hint: "p__________", ja: "見込みのある、将来の" },
        { sentence: "The building is ___ to wheelchair users.", answer: "accessible", base: "accessible", hint: "a_________", ja: "利用しやすい、行きやすい" },
        { sentence: "The shop offers ___ prices on electronics.", answer: "competitive", base: "competitive", hint: "c__________", ja: "競争力のある" },
        { sentence: "Our company offers ___ working hours.", answer: "flexible", base: "flexible", hint: "f_______", ja: "柔軟な" },
      ],
    },
  ],
};
