// Clacel 2.0 単語テスト問題（9月「1ヶ月分」、osh-vocab-test/data/*.pyから自動生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
// Day7/14/21/28は復習日のため欠番。Day9は12語、Day18は19語、Day29は19語（元データの語数通り）
module.exports = {
  label: "Clacel",
  series: [
    {
      name: "Day 1",
      items: [
        { sentence: "Yesterday, the children ___ to be superheroes.", answer: "pretended", base: "pretend", hint: "p______", ja: "ふりをする", sentenceJa: "昨日、子供たちはスーパーヒーローのふりをした。" },
        { sentence: "Yesterday, she ___ her shoes before entering the room.", answer: "removed", base: "remove", hint: "r_____", ja: "取り除く", sentenceJa: "昨日、彼女は部屋に入る前に靴を脱いだ。" },
        { sentence: "She can't ___ the summer heat.", answer: "stand", base: "stand", hint: "s____", ja: "立つ、耐える", sentenceJa: "彼女は夏の暑さに耐えられない。" },
        { sentence: "The rising prices ___ many families.", answer: "concern", base: "concern", hint: "c______", ja: "心配させる、関係する", sentenceJa: "物価の上昇は多くの家庭を心配させている。" },
        { sentence: "Yesterday, he ___ an old classmate of his on the street.", answer: "recognized", base: "recognize", hint: "r________", ja: "認識する、見分ける、認める", sentenceJa: "昨日、彼は道で昔の同級生に気づいた。" },
        { sentence: "The dog likes to ___ holes in the garden.", answer: "dig", base: "dig", hint: "d__", ja: "掘る", sentenceJa: "その犬は庭に穴を掘るのが好きだ。" },
        { sentence: "News ___ quickly on social media.", answer: "spreads", base: "spread", hint: "s_____", ja: "広げる、広がる", sentenceJa: "ニュースはSNSで素早く広がる。" },
        { sentence: "Please don't ___ her while she is studying.", answer: "disturb", base: "disturb", hint: "d______", ja: "邪魔する", sentenceJa: "勉強している間は彼女の邪魔をしないでください。" },
        { sentence: "Yesterday, she ___ the difficult question very calmly.", answer: "handled", base: "handle", hint: "h_____", ja: "扱う、対処する、手を触れる", sentenceJa: "昨日、彼女はその難しい質問にとても冷静に対応した。" },
        { sentence: "Yesterday, he ___ an entire afternoon looking for his keys.", answer: "wasted", base: "waste", hint: "w____", ja: "無駄にする", sentenceJa: "昨日、彼は鍵を探すのに午後をまるまる無駄にした。" },
        { sentence: "I will ___ a meeting for next week.", answer: "arrange", base: "arrange", hint: "a______", ja: "手配する、整える", sentenceJa: "来週の会議を手配します。" },
        { sentence: "Many people ___ advice before making a big decision.", answer: "seek", base: "seek", hint: "s___", ja: "探し求める", sentenceJa: "多くの人は大きな決断をする前に助言を求める。" },
        { sentence: "The company ___ fresh vegetables to the school.", answer: "supplies", base: "supply", hint: "s_____", ja: "供給する", sentenceJa: "その会社は学校に新鮮な野菜を供給している。" },
        { sentence: "Yesterday, the teacher ___ the class into four groups.", answer: "divided", base: "divide", hint: "d_____", ja: "分ける、割る", sentenceJa: "昨日、先生はクラスを4つのグループに分けた。" },
        { sentence: "She ___ her umbrella on the train yesterday.", answer: "left", base: "leave", hint: "l____", ja: "去る、残す、置き忘れる", sentenceJa: "彼女は昨日、電車に傘を置き忘れた。" },
        { sentence: "He always ___ the same route to work.", answer: "follows", base: "follow", hint: "f_____", ja: "ついていく、従う", sentenceJa: "彼はいつも同じ道順で通勤している。" },
        { sentence: "She likes to ___ pictures of animals.", answer: "draw", base: "draw", hint: "d___", ja: "描く、引く", sentenceJa: "彼女は動物の絵を描くのが好きだ。" },
        { sentence: "This textbook ___ all the basic grammar rules.", answer: "covers", base: "cover", hint: "c____", ja: "覆う、（話題を）扱う", sentenceJa: "この教科書は基本的な文法規則をすべて扱っている。" },
        { sentence: "Childhood experiences often ___ our personalities.", answer: "shape", base: "shape", hint: "s____", ja: "形作る", sentenceJa: "幼少期の経験はしばしば私たちの性格を形作る。" },
        { sentence: "Last week, the store ___ open despite the storm.", answer: "remained", base: "remain", hint: "r_____", ja: "とどまる、～のままである、残る", sentenceJa: "先週、その店は嵐にもかかわらず営業を続けた。" },
      ],
    },
    {
      name: "Day 2",
      items: [
        { sentence: "Please ___ the plastic from the paper waste.", answer: "separate", base: "separate", hint: "s_______", ja: "分ける、分離する", sentenceJa: "プラスチックと紙ゴミを分けてください。" },
        { sentence: "Yesterday, she ___ to finish the report on time.", answer: "managed", base: "manage", hint: "m_____", ja: "なんとかやり遂げる、管理する", sentenceJa: "昨日、彼女は何とか時間通りにレポートを終わらせた。" },
        { sentence: "Last week, the storm ___ us to cancel the trip.", answer: "forced", base: "force", hint: "f____", ja: "強制する", sentenceJa: "先週、嵐のせいで私たちは旅行を中止せざるを得なかった。" },
        { sentence: "If you don't hurry, you'll ___ the bus.", answer: "miss", base: "miss", hint: "m___", ja: "逃す、寂しく思う", sentenceJa: "急がないとバスに乗り遅れますよ。" },
        { sentence: "This job ___ good communication skills.", answer: "requires", base: "require", hint: "r______", ja: "必要とする", sentenceJa: "この仕事は優れたコミュニケーション能力を必要としている。" },
        { sentence: "A ticket to the concert ___ fifty dollars.", answer: "costs", base: "cost", hint: "c___", ja: "（費用が）かかる、（労力・犠牲などを）要する", sentenceJa: "コンサートのチケットは50ドルする。" },
        { sentence: "This umbrella ___ to my sister.", answer: "belongs", base: "belong", hint: "b_____", ja: "所属する、〜のものである", sentenceJa: "この傘は私の妹のものだ。" },
        { sentence: "Can you ___ the man you saw?", answer: "describe", base: "describe", hint: "d_______", ja: "描写する、説明する", sentenceJa: "あなたが見た男性について説明してもらえますか？" },
        { sentence: "She ___ the piano for an hour every day.", answer: "practices", base: "practice", hint: "p_______", ja: "練習する", sentenceJa: "彼女は毎日1時間ピアノを練習している。" },
        { sentence: "Loud noises ___ me when I'm studying.", answer: "bother", base: "bother", hint: "b_____", ja: "悩ます、わざわざ〜する", sentenceJa: "勉強しているとき、大きな音は私を悩ませる。" },
        { sentence: "Please don't ___ answers from your classmate.", answer: "copy", base: "copy", hint: "c___", ja: "複写する、まねる", sentenceJa: "クラスメートの答えを写さないでください。" },
        { sentence: "Last night, he ___ on paying for dinner.", answer: "insisted", base: "insist", hint: "i_____", ja: "強く主張する", sentenceJa: "昨夜、彼は夕食代を払うと強く主張した。" },
        { sentence: "Be quiet as you ___ the sleeping baby.", answer: "approach", base: "approach", hint: "a_______", ja: "近づく", sentenceJa: "眠っている赤ちゃんに近づくときは静かにしてください。" },
        { sentence: "Please ___ me to call the dentist.", answer: "remind", base: "remind", hint: "r_____", ja: "思い出させる", sentenceJa: "歯医者に電話するのを私に思い出させてください。" },
        { sentence: "The two brothers often ___ about small things.", answer: "argue", base: "argue", hint: "a____", ja: "言い争う、主張する", sentenceJa: "その二人の兄弟はよく些細なことで言い争う。" },
        { sentence: "The band will ___ at the school festival.", answer: "perform", base: "perform", hint: "p______", ja: "行う、実行する、演じる", sentenceJa: "そのバンドは学園祭で演奏する予定だ。" },
        { sentence: "They had to ___ the game because of the rain.", answer: "cancel", base: "cancel", hint: "c_____", ja: "中止する", sentenceJa: "雨のため、彼らは試合を中止しなければならなかった。" },
        { sentence: "Washing your hands can ___ illness.", answer: "prevent", base: "prevent", hint: "p______", ja: "防ぐ", sentenceJa: "手を洗うことは病気を防ぐことができる。" },
        { sentence: "Could you help me ___ these boxes?", answer: "carry", base: "carry", hint: "c____", ja: "運ぶ", sentenceJa: "これらの箱を運ぶのを手伝ってもらえますか？" },
      ],
    },
    {
      name: "Day 3",
      items: [
        { sentence: "She hired a ___ to help with her math.", answer: "tutor", base: "tutor", hint: "t____", ja: "家庭教師、個別指導者", sentenceJa: "彼女は数学を手伝ってもらうために家庭教師を雇った。" },
        { sentence: "He made a good ___ at the interview.", answer: "impression", base: "impression", hint: "i_________", ja: "印象", sentenceJa: "彼は面接で良い印象を与えた。" },
        { sentence: "The ambassador lives in an official ___.", answer: "residence", base: "residence", hint: "r________", ja: "住居、邸宅", sentenceJa: "大使は公邸に住んでいる。" },
        { sentence: "I downloaded the latest ___ of the app.", answer: "version", base: "version", hint: "v______", ja: "版", sentenceJa: "私はそのアプリの最新版をダウンロードした。" },
        { sentence: "The ___ takes one year to circle the sun.", answer: "earth", base: "earth", hint: "e____", ja: "地球、大地", sentenceJa: "地球は太陽の周りを一周するのに一年かかる。" },
        { sentence: "Pollution has a serious ___ on the environment.", answer: "effect", base: "effect", hint: "e_____", ja: "影響、効果", sentenceJa: "汚染は環境に深刻な影響を与える。" },
        { sentence: "She passed the exam through hard ___.", answer: "effort", base: "effort", hint: "e_____", ja: "努力", sentenceJa: "彼女は努力の末、試験に合格した。" },
        { sentence: "The snacks are in the third ___ of the store.", answer: "aisle", base: "aisle", hint: "a____", ja: "通路", sentenceJa: "お菓子はその店の3番目の通路にある。" },
        { sentence: "Swimming is my favorite weekend ___.", answer: "activity", base: "activity", hint: "a_______", ja: "活動", sentenceJa: "水泳は私のお気に入りの週末の活動だ。" },
        { sentence: "The hero is the most popular ___ in the book.", answer: "character", base: "character", hint: "c________", ja: "性格、登場人物", sentenceJa: "その主人公はその本で最も人気のある登場人物だ。" },
        { sentence: "Children seem to have endless ___.", answer: "energy", base: "energy", hint: "e_____", ja: "エネルギー、活力", sentenceJa: "子どもたちは無限のエネルギーを持っているようだ。" },
        { sentence: "The ___ of the word is Latin.", answer: "origin", base: "origin", hint: "o_____", ja: "起源、由来", sentenceJa: "その単語の起源はラテン語だ。" },
        { sentence: "She raised an ___ to the new plan.", answer: "objection", base: "objection", hint: "o________", ja: "反対、異議", sentenceJa: "彼女は新しい計画に異議を唱えた。" },
        { sentence: "This is an effective ___ for learning words.", answer: "method", base: "method", hint: "m_____", ja: "方法", sentenceJa: "これは単語を覚えるのに効果的な方法だ。" },
        { sentence: "She kept her many ___ to herself during the meeting.", answer: "thoughts", base: "thought", hint: "t______", ja: "考え、思考", sentenceJa: "彼女は会議中、多くの考えを自分の中にとどめておいた。" },
        { sentence: "The old house was in a poor ___.", answer: "state", base: "state", hint: "s____", ja: "状態、（米国などの）州", sentenceJa: "その古い家はひどい状態だった。" },
        { sentence: "We enjoyed the beauty of ___ on our hike.", answer: "nature", base: "nature", hint: "n_____", ja: "自然、性質", sentenceJa: "私たちはハイキングで自然の美しさを楽しんだ。" },
        { sentence: "She sent her ___ for the scholarship.", answer: "application", base: "application", hint: "a__________", ja: "申し込み、応用、アプリ", sentenceJa: "彼女は奨学金のための申込書を送った。" },
        { sentence: "The painting has great ___ to collectors.", answer: "value", base: "value", hint: "v____", ja: "価値", sentenceJa: "その絵画はコレクターにとって大きな価値がある。" },
        { sentence: "The teacher explained the ___ calmly.", answer: "situation", base: "situation", hint: "s________", ja: "状況", sentenceJa: "先生はその状況を落ち着いて説明した。" },
      ],
    },
    {
      name: "Day 4",
      items: [
        { sentence: "Call this number in case of an ___.", answer: "emergency", base: "emergency", hint: "e________", ja: "緊急事態", sentenceJa: "緊急時はこの番号に電話してください。" },
        { sentence: "She deserves ___ for her hard work.", answer: "credit", base: "credit", hint: "c_____", ja: "信用、功績、クレジット", sentenceJa: "彼女は頑張った分の評価を受けるに値する。" },
        { sentence: "The ___ of the lake was perfectly calm.", answer: "surface", base: "surface", hint: "s______", ja: "表面", sentenceJa: "湖の水面は完全に穏やかだった。" },
        { sentence: "We asked the waiter for the ___.", answer: "bill", base: "bill", hint: "b___", ja: "請求書、勘定", sentenceJa: "私たちはウェイターに会計をお願いした。" },
        { sentence: "This is an important ___ we must discuss.", answer: "matter", base: "matter", hint: "m_____", ja: "事柄、問題", sentenceJa: "これは私たちが話し合わなければならない重要な問題だ。" },
        { sentence: "The clown's tricks were a source of ___.", answer: "amusement", base: "amusement", hint: "a________", ja: "楽しみ、娯楽", sentenceJa: "ピエロの芸は楽しみの種だった。" },
        { sentence: "The neighbors live together in ___.", answer: "harmony", base: "harmony", hint: "h______", ja: "調和", sentenceJa: "隣人たちは調和して暮らしている。" },
        { sentence: "The hotel room has a beautiful ___ of the sea.", answer: "view", base: "view", hint: "v___", ja: "眺め、見解", sentenceJa: "そのホテルの部屋からは海の美しい眺めが見える。" },
        { sentence: "The teacher praised the students' good ___.", answer: "behavior", base: "behavior", hint: "b_______", ja: "行動、ふるまい", sentenceJa: "先生は生徒たちの良い行動を褒めた。" },
        { sentence: "There was a long ___ before she answered.", answer: "pause", base: "pause", hint: "p____", ja: "休止、間", sentenceJa: "彼女が答える前に長い間があった。" },
        { sentence: "She learned a new ___ for painting.", answer: "technique", base: "technique", hint: "t________", ja: "技術、手法", sentenceJa: "彼女は絵を描く新しい技法を学んだ。" },
        { sentence: "There is a growing ___ toward healthy eating.", answer: "trend", base: "trend", hint: "t____", ja: "傾向、流行", sentenceJa: "健康的な食事を求める傾向が高まっている。" },
        { sentence: "The temperature dropped by ten ___ overnight.", answer: "degrees", base: "degree", hint: "d_____", ja: "度、学位、程度", sentenceJa: "気温は一晩で10度下がった。" },
        { sentence: "He was late because of a traffic ___.", answer: "accident", base: "accident", hint: "a_______", ja: "事故、偶然", sentenceJa: "彼は交通事故のせいで遅刻した。" },
        { sentence: "I do the ___ every Sunday morning.", answer: "laundry", base: "laundry", hint: "l______", ja: "洗濯（物）", sentenceJa: "私は毎週日曜日の朝に洗濯をする。" },
        { sentence: "She gave an excellent ___ in class.", answer: "presentation", base: "presentation", hint: "p___________", ja: "発表", sentenceJa: "彼女は授業で素晴らしい発表をした。" },
        { sentence: "He has a strong ___ of heights.", answer: "fear", base: "fear", hint: "f___", ja: "恐怖", sentenceJa: "彼は高所に対する強い恐怖心を持っている。" },
        { sentence: "This is a popular ___ for taking photos.", answer: "spot", base: "spot", hint: "s___", ja: "場所、斑点", sentenceJa: "ここは写真を撮るのに人気のある場所だ。" },
        { sentence: "Read all the ___ carefully before you start.", answer: "instructions", base: "instruction", hint: "i__________", ja: "指示、説明", sentenceJa: "始める前にすべての指示をよく読んでください。" },
        { sentence: "He ran for office as an ___.", answer: "independent", base: "independent", hint: "i__________", ja: "独立した人・もの", sentenceJa: "彼は無所属で立候補した。" },
      ],
    },
    {
      name: "Day 5",
      items: [
        { sentence: "We wore ___ clothes at the festival.", answer: "traditional", base: "traditional", hint: "t__________", ja: "伝統的な", sentenceJa: "私たちは祭りで伝統的な服を着た。" },
        { sentence: "The volunteer work gave her ___ experience.", answer: "valuable", base: "valuable", hint: "v_______", ja: "貴重な、価値のある", sentenceJa: "そのボランティア活動は彼女に貴重な経験を与えた。" },
        { sentence: "He wants to become a ___ soccer player.", answer: "professional", base: "professional", hint: "p___________", ja: "専門的な", sentenceJa: "彼はプロのサッカー選手になりたいと思っている。" },
        { sentence: "Can you tell me the ___ time of the meeting?", answer: "exact", base: "exact", hint: "e____", ja: "正確な", sentenceJa: "会議の正確な時間を教えてもらえますか？" },
        { sentence: "Smith is a very ___ family name in England.", answer: "common", base: "common", hint: "c_____", ja: "一般的な、共通の", sentenceJa: "スミスはイギリスでとても一般的な姓だ。" },
        { sentence: "Sushi is made with ___ fish.", answer: "raw", base: "raw", hint: "r__", ja: "生の、未加工の", sentenceJa: "寿司は生の魚で作られる。" },
        { sentence: "There is a ___ library near the station.", answer: "public", base: "public", hint: "p_____", ja: "公共の", sentenceJa: "駅の近くに公共図書館がある。" },
        { sentence: "Eating vegetables is part of a ___ diet.", answer: "healthy", base: "healthy", hint: "h______", ja: "健康的な、健康な", sentenceJa: "野菜を食べることは健康的な食事の一部だ。" },
        { sentence: "It is ___ to rain later this afternoon.", answer: "likely", base: "likely", hint: "l_____", ja: "ありそうな", sentenceJa: "今日の午後遅くに雨が降りそうだ。" },
        { sentence: "The two brothers have very ___ voices.", answer: "similar", base: "similar", hint: "s______", ja: "似ている", sentenceJa: "その兄弟は声がとてもよく似ている。" },
        { sentence: "Everyone should learn ___ first-aid skills.", answer: "basic", base: "basic", hint: "b____", ja: "基本的な", sentenceJa: "誰もが基本的な応急処置のスキルを学ぶべきだ。" },
        { sentence: "We had ___ chicken for dinner.", answer: "roast", base: "roast", hint: "r____", ja: "焼いた", sentenceJa: "夕食にローストチキンを食べた。" },
        { sentence: "The earth is a large ___ object.", answer: "round", base: "round", hint: "r____", ja: "丸い", sentenceJa: "地球は大きな丸い物体だ。" },
        { sentence: "Do we have ___ chairs for everyone?", answer: "enough", base: "enough", hint: "e_____", ja: "十分な", sentenceJa: "全員分の十分な椅子はあるだろうか？" },
        { sentence: "We had a ___ walk in the park.", answer: "pleasant", base: "pleasant", hint: "p_______", ja: "快い、感じのよい", sentenceJa: "私たちは公園で気持ちのよい散歩をした。" },
        { sentence: "Please give a ___ example in your answer.", answer: "specific", base: "specific", hint: "s_______", ja: "具体的な、特定の", sentenceJa: "答えには具体的な例を挙げてください。" },
        { sentence: "These shoes are light and ___.", answer: "comfortable", base: "comfortable", hint: "c__________", ja: "快適な", sentenceJa: "この靴は軽くて快適だ。" },
        { sentence: "She ate the ___ pizza by herself.", answer: "whole", base: "whole", hint: "w____", ja: "全体の", sentenceJa: "彼女はピザを一人で全部食べた。" },
        { sentence: "The baby is finally ___.", answer: "asleep", base: "asleep", hint: "a_____", ja: "眠って", sentenceJa: "赤ちゃんはついに眠った。" },
        { sentence: "He showed off his ___ smartphone.", answer: "brand-new", base: "brand-new", hint: "b________", ja: "新品の", sentenceJa: "彼は新品のスマートフォンを見せびらかした。" },
      ],
    },
    {
      name: "Day 6",
      items: [
        { sentence: "There is an ___ charge for late delivery.", answer: "additional", base: "additional", hint: "a_________", ja: "追加の", sentenceJa: "延着の場合は追加料金がかかります。" },
        { sentence: "We need a ___ surface to set up the tent.", answer: "flat", base: "flat", hint: "f___", ja: "平らな", sentenceJa: "テントを張るには平らな地面が必要だ。" },
        { sentence: "She is a ___ author in Japan.", answer: "well-known", base: "well-known", hint: "w_________", ja: "有名な", sentenceJa: "彼女は日本で有名な作家だ。" },
        { sentence: "A ___ storm hit the coast last night.", answer: "violent", base: "violent", hint: "v______", ja: "暴力的な、激しい", sentenceJa: "昨夜、激しい嵐が海岸を襲った。" },
        { sentence: "The train was very ___ this morning.", answer: "crowded", base: "crowded", hint: "c______", ja: "混雑した", sentenceJa: "今朝の電車はとても混雑していた。" },
        { sentence: "Only a ___ students came to the early class.", answer: "few", base: "few", hint: "f__", ja: "ほとんどない、少しの", sentenceJa: "早朝の授業に来た学生はほとんどいなかった。" },
        { sentence: "The old town has many ___ streets.", answer: "narrow", base: "narrow", hint: "n_____", ja: "狭い", sentenceJa: "旧市街には狭い通りがたくさんある。" },
        { sentence: "Cut the bread into ___ slices.", answer: "thin", base: "thin", hint: "t___", ja: "薄い、細い", sentenceJa: "パンを薄く切ってください。" },
        { sentence: "My best friend lives ___ to my house.", answer: "close", base: "close", hint: "c____", ja: "近い、親しい", sentenceJa: "私の親友は私の家の近くに住んでいる。" },
        { sentence: "I am ___ that I locked the door.", answer: "certain", base: "certain", hint: "c______", ja: "確信して、確かな", sentenceJa: "私はドアに鍵をかけたと確信している。" },
        { sentence: "Do you have this shirt in any ___ colors?", answer: "other", base: "other", hint: "o____", ja: "ほかの", sentenceJa: "このシャツはほかの色もありますか。" },
        { sentence: "Rain is ___ weather for this season.", answer: "typical", base: "typical", hint: "t______", ja: "典型的な", sentenceJa: "雨はこの季節の典型的な天気だ。" },
        { sentence: "She is ___ of the dark.", answer: "afraid", base: "afraid", hint: "a_____", ja: "恐れて、心配して", sentenceJa: "彼女は暗闇を恐れている。" },
        { sentence: "We will meet again the ___ week.", answer: "following", base: "following", hint: "f________", ja: "次の", sentenceJa: "私たちは次の週にまた会う予定だ。" },
        { sentence: "Is there a ___ train to the airport?", answer: "direct", base: "direct", hint: "d_____", ja: "直接の", sentenceJa: "空港まで直通の電車はありますか。" },
        { sentence: "This old book is ___ a lot of money.", answer: "worth", base: "worth", hint: "w____", ja: "～の価値がある", sentenceJa: "この古い本は大金の価値がある。" },
        { sentence: "The bottle is completely ___.", answer: "empty", base: "empty", hint: "e____", ja: "空の", sentenceJa: "そのボトルは完全に空だ。" },
        { sentence: "He ___ eats fast food.", answer: "rarely", base: "rarely", hint: "r_____", ja: "めったに～ない", sentenceJa: "彼はめったにファストフードを食べない。" },
        { sentence: "I have been to Kyoto only ___.", answer: "once", base: "once", hint: "o___", ja: "一度、かつて", sentenceJa: "私は一度しか京都に行ったことがない。" },
        { sentence: "The shop was ___ a small bakery.", answer: "originally", base: "originally", hint: "o_________", ja: "もともと、最初は", sentenceJa: "その店はもともと小さなパン屋だった。" },
      ],
    },
    {
      name: "Day 8",
      items: [
        { sentence: "The train left at ___ nine o'clock.", answer: "exactly", base: "exactly", hint: "e______", ja: "正確に、ちょうど", sentenceJa: "電車はちょうど9時に出発した。" },
        { sentence: "Try to eat ___ and exercise more.", answer: "less", base: "less", hint: "l___", ja: "より少なく", sentenceJa: "食べる量を減らして、もっと運動するようにしてください。" },
        { sentence: "___, the weather will be sunny tomorrow.", answer: "hopefully", base: "hopefully", hint: "h________", ja: "願わくは、うまくいけば", sentenceJa: "願わくは、明日は晴れますように。" },
        { sentence: "The customers are ___ young students.", answer: "mostly", base: "mostly", hint: "m_____", ja: "たいてい、主に", sentenceJa: "お客さんはたいてい若い学生です。" },
        { sentence: "I ___ forgot about the meeting.", answer: "completely", base: "completely", hint: "c_________", ja: "完全に", sentenceJa: "私はその会議のことを完全に忘れていた。" },
        { sentence: "The flowers were arranged very ___.", answer: "nicely", base: "nicely", hint: "n_____", ja: "うまく、よく", sentenceJa: "花はとても上手に生けられていた。" },
        { sentence: "The test was ___ difficult this time.", answer: "rather", base: "rather", hint: "r_____", ja: "かなり、むしろ", sentenceJa: "今回のテストはかなり難しかった。" },
        { sentence: "The movie was ___ good, actually.", answer: "pretty", base: "pretty", hint: "p_____", ja: "かなり、なかなか", sentenceJa: "その映画は実際、かなり良かった。" },
        { sentence: "She wants to study ___ next year.", answer: "abroad", base: "abroad", hint: "a_____", ja: "海外で、海外へ", sentenceJa: "彼女は来年、海外に留学したいと思っている。" },
        { sentence: "He lives ___ in a small apartment.", answer: "alone", base: "alone", hint: "a____", ja: "一人で", sentenceJa: "彼は小さなアパートに一人で住んでいる。" },
        { sentence: "Have you finished your homework ___?", answer: "yet", base: "yet", hint: "y__", ja: "まだ、もう", sentenceJa: "もう宿題は終わった？" },
        { sentence: "She solved the puzzle ___.", answer: "easily", base: "easily", hint: "e_____", ja: "簡単に", sentenceJa: "彼女はそのパズルを簡単に解いた。" },
        { sentence: "I don't play that game ___.", answer: "anymore", base: "anymore", hint: "a______", ja: "もはや〜ない", sentenceJa: "私はもうそのゲームをしない。" },
        { sentence: "You can call me ___ you need help.", answer: "anytime", base: "anytime", hint: "a______", ja: "いつでも", sentenceJa: "助けが必要なときはいつでも電話していいよ。" },
        { sentence: "It's cold today. It was warm yesterday, ___.", answer: "though", base: "though", hint: "t_____", ja: "でも、もっとも", sentenceJa: "今日は寒い。でも昨日は暖かかった。" },
        { sentence: "It was raining ___ all morning.", answer: "heavily", base: "heavily", hint: "h______", ja: "激しく、大量に", sentenceJa: "午前中ずっと激しく雨が降っていた。" },
        { sentence: "I'm ___ finished with my report.", answer: "almost", base: "almost", hint: "a_____", ja: "ほとんど", sentenceJa: "レポートはほとんど終わっている。" },
        { sentence: "After many tries, he ___ succeeded.", answer: "eventually", base: "eventually", hint: "e_________", ja: "結局、ついに", sentenceJa: "何度も挑戦した後、彼はついに成功した。" },
        { sentence: "I could ___ hear her quiet voice.", answer: "hardly", base: "hardly", hint: "h_____", ja: "ほとんど〜ない", sentenceJa: "彼女の小さな声はほとんど聞こえなかった。" },
        { sentence: "The exam was ___ easy for most students.", answer: "quite", base: "quite", hint: "q____", ja: "かなり、まったく", sentenceJa: "試験はほとんどの生徒にとってかなり簡単だった。" },
      ],
    },
    {
      name: "Day 9",
      items: [
        { sentence: "Please call me ___ if there is a problem.", answer: "immediately", base: "immediately", hint: "i__________", ja: "すぐに", sentenceJa: "問題があれば、すぐに私に電話してください。" },
        { sentence: "We had dinner and went for a walk ___.", answer: "afterward", base: "afterward", hint: "a________", ja: "あとで", sentenceJa: "私たちは夕食をとり、その後散歩に行った。" },
        { sentence: "The café was closed, so we went to the park ___.", answer: "instead", base: "instead", hint: "i______", ja: "代わりに", sentenceJa: "そのカフェは閉まっていたので、代わりに公園へ行った。" },
        { sentence: "We'll go hiking ___ it rains.", answer: "unless", base: "unless", hint: "u_____", ja: "～でない限り", sentenceJa: "雨が降らない限り、ハイキングに行くつもりだ。" },
        { sentence: "___ it was raining, we enjoyed the trip.", answer: "although", base: "although", hint: "a_______", ja: "～だけれども", sentenceJa: "雨が降っていたけれども、私たちは旅行を楽しんだ。" },
        { sentence: "The shop is open every day ___ Sunday.", answer: "except", base: "except", hint: "e_____", ja: "～を除いて", sentenceJa: "その店は日曜日を除いて毎日営業している。" },
        { sentence: "The cat is hiding ___ the sofa.", answer: "behind", base: "behind", hint: "b_____", ja: "～の後ろに", sentenceJa: "猫はソファの後ろに隠れている。" },
        { sentence: "The mountains lie ___ the river.", answer: "beyond", base: "beyond", hint: "b_____", ja: "～の向こうに、～を超えて", sentenceJa: "山々は川の向こうにある。" },
        { sentence: "I can't read this menu ___ my glasses.", answer: "without", base: "without", hint: "w______", ja: "～なしで", sentenceJa: "メガネなしではこのメニューを読めない。" },
        { sentence: "___ her sister, she enjoys sports.", answer: "unlike", base: "unlike", hint: "u_____", ja: "～と違って", sentenceJa: "姉（妹）と違って、彼女はスポーツを楽しむ。" },
        { sentence: "Call me ___ you need help.", answer: "whenever", base: "whenever", hint: "w_______", ja: "～するときはいつでも", sentenceJa: "助けが必要なときはいつでも私に電話してください。" },
        { sentence: "Please reply ___ three days.", answer: "within", base: "within", hint: "w_____", ja: "～以内に、～の中で", sentenceJa: "3   日以内に返信してください。" },
      ],
    },
    {
      name: "Day 10",
      items: [
        { sentence: "In general, sound ___ faster in water than in air.", answer: "travels", base: "travel", hint: "t_____", ja: "移動する（旅行に限らず）", sentenceJa: "一般的に、音は空気中よりも水中の方が速く伝わる。" },
        { sentence: "Please ___ the door before you leave.", answer: "lock", base: "lock", hint: "l___", ja: "鍵をかける", sentenceJa: "出かける前にドアに鍵をかけてください。" },
        { sentence: "Don't ___ these two words; they look similar.", answer: "confuse", base: "confuse", hint: "c______", ja: "混乱させる、混同する", sentenceJa: "この2つの単語を混同しないで。似ているから。" },
        { sentence: "She could barely ___ her excitement.", answer: "contain", base: "contain", hint: "c______", ja: "含む、抑える", sentenceJa: "彼女は興奮を抑えきれなかった。" },
        { sentence: "The beach ___ for miles along the coast.", answer: "stretches", base: "stretch", hint: "s______", ja: "伸ばす、広がる", sentenceJa: "そのビーチは海岸沿いに何マイルも広がっている。" },
        { sentence: "She was ___ a scholarship for her research.", answer: "awarded", base: "award", hint: "a____", ja: "授与する", sentenceJa: "彼女は研究に対して奨学金を授与された。" },
        { sentence: "Every night, two dogs ___ the house.", answer: "guard", base: "guard", hint: "g____", ja: "守る、警備する", sentenceJa: "毎晩、2匹の犬がその家を守っている。" },
        { sentence: "The workers were ___ inside the elevator.", answer: "trapped", base: "trap", hint: "t___", ja: "閉じ込める、わなにかける", sentenceJa: "作業員たちはエレベーターの中に閉じ込められた。" },
        { sentence: "Last spring, they ___ trees along the road.", answer: "planted", base: "plant", hint: "p____", ja: "植える、仕込む", sentenceJa: "去年の春、彼らは道路沿いに木を植えた。" },
        { sentence: "Last month, she ___ the entire event by herself.", answer: "organized", base: "organize", hint: "o_______", ja: "整理する、計画する", sentenceJa: "先月、彼女はそのイベント全体を一人で企画した。" },
        { sentence: "Yesterday, he ___ an excuse for being late.", answer: "invented", base: "invent", hint: "i_____", ja: "発明する、でっち上げる", sentenceJa: "昨日、彼は遅刻の言い訳をでっち上げた。" },
        { sentence: "I ___ what she's doing right now.", answer: "wonder", base: "wonder", hint: "w_____", ja: "〜だろうかと思う", sentenceJa: "彼女は今頃何をしているのだろうか。" },
        { sentence: "Yesterday, the kids ___ snacks at lunch.", answer: "traded", base: "trade", hint: "t____", ja: "取引する、交換する", sentenceJa: "昨日、子供たちは昼食時におやつを交換した。" },
        { sentence: "He ___ more confident as the weeks passed.", answer: "grew", base: "grow", hint: "g___", ja: "育つ、〜になっていく", sentenceJa: "彼は数週間が経つにつれて自信を持つようになった。" },
        { sentence: "Last week, none of the customers ___ on the special offer.", answer: "bit", base: "bite", hint: "b___", ja: "噛む、（話に）食いつく", sentenceJa: "先週、特別オファーに食いついた客は一人もいなかった。" },
        { sentence: "Would you ___ opening the window?", answer: "mind", base: "mind", hint: "m___", ja: "気にする、嫌がる", sentenceJa: "窓を開けていただけますか。" },
        { sentence: "Yesterday, she ___ to call me back later that day.", answer: "promised", base: "promise", hint: "p______", ja: "約束する", sentenceJa: "昨日、彼女はその日のうちにかけ直すと約束した。" },
        { sentence: "We need to ___ the leaking faucet.", answer: "fix", base: "fix", hint: "f__", ja: "修理する、固定する", sentenceJa: "水漏れしている蛇口を直す必要がある。" },
        { sentence: "Nobody knows what will ___ next.", answer: "happen", base: "happen", hint: "h_____", ja: "起こる", sentenceJa: "次に何が起こるか誰にもわからない。" },
        { sentence: "Every week, this data ___ directly into the main report.", answer: "feeds", base: "feed", hint: "f___", ja: "食べさせる、供給する", sentenceJa: "毎週、このデータは直接メインレポートに反映される。" },
      ],
    },
    {
      name: "Day 11",
      items: [
        { sentence: "They spent all day ___ for a new apartment.", answer: "hunting", base: "hunt", hint: "h___", ja: "狩る、捜し求める", sentenceJa: "彼らは新しいアパートを探すのに一日中費やした。" },
        { sentence: "Currently, this road ___ the two cities.", answer: "connects", base: "connect", hint: "c______", ja: "つなぐ、接続する", sentenceJa: "現在、この道路は2つの都市をつないでいる。" },
        { sentence: "Several companies ___ for the same customers.", answer: "compete", base: "compete", hint: "c______", ja: "競争する", sentenceJa: "いくつかの会社が同じ顧客を巡って競争している。" },
        { sentence: "Last month, he ___ his chance to get the promotion.", answer: "blew", base: "blow", hint: "b___", ja: "吹く、（機会を）逃す", sentenceJa: "先月、彼は昇進のチャンスを逃した。" },
        { sentence: "Yesterday, we finally ___ an agreement after hours of talking.", answer: "reached", base: "reach", hint: "r____", ja: "到着する、達する", sentenceJa: "昨日、何時間も話し合った末、私たちはついに合意に達した。" },
        { sentence: "My grandfather ___ from teaching last year.", answer: "retired", base: "retire", hint: "r_____", ja: "引退する", sentenceJa: "私の祖父は去年、教師を引退した。" },
        { sentence: "Last month, the new policy ___ a lot of confusion.", answer: "created", base: "create", hint: "c_____", ja: "創造する、作り出す", sentenceJa: "先月、その新しい方針は多くの混乱を生んだ。" },
        { sentence: "This small room ___ as my home office.", answer: "serves", base: "serve", hint: "s____", ja: "提供する、役立つ", sentenceJa: "この小さな部屋は私のホームオフィスとして役立っている。" },
        { sentence: "She ___ to a healthier diet last month.", answer: "switched", base: "switch", hint: "s_____", ja: "切り替える", sentenceJa: "彼女は先月、より健康的な食事に切り替えた。" },
        { sentence: "Yesterday, everyone in the class ___ for a new project idea.", answer: "voted", base: "vote", hint: "v___", ja: "投票する", sentenceJa: "昨日、クラスの全員が新しいプロジェクト案に投票した。" },
        { sentence: "Try not to ___ the baby.", answer: "wake", base: "wake", hint: "w___", ja: "目を覚ます、起こす", sentenceJa: "赤ちゃんを起こさないようにしてください。" },
        { sentence: "Please ___ with your presentation.", answer: "continue", base: "continue", hint: "c_______", ja: "続ける、継続する", sentenceJa: "プレゼンテーションを続けてください。" },
        { sentence: "Yesterday, heavy traffic ___ our arrival by an hour.", answer: "delayed", base: "delay", hint: "d____", ja: "遅らせる", sentenceJa: "昨日、激しい交通渋滞のせいで到着が1時間遅れた。" },
        { sentence: "You can ___ your car behind the building.", answer: "park", base: "park", hint: "p___", ja: "駐車する", sentenceJa: "建物の裏に車を駐車できます。" },
        { sentence: "Last month, she ___ the marathon in under four hours.", answer: "completed", base: "complete", hint: "c_______", ja: "完成させる", sentenceJa: "先月、彼女は4時間以内にマラソンを完走した。" },
        { sentence: "Our plans ___ on the weather this weekend.", answer: "depend", base: "depend", hint: "d_____", ja: "左右される、頼る", sentenceJa: "私たちの計画は今週末の天気次第だ。" },
        { sentence: "Yesterday, he finally ___ that he made a mistake.", answer: "accepted", base: "accept", hint: "a_____", ja: "受け入れる", sentenceJa: "昨日、彼はついに自分が間違いを犯したことを認めた。" },
        { sentence: "Last week, the experiment ___ to produce the expected results.", answer: "failed", base: "fail", hint: "f___", ja: "失敗する", sentenceJa: "先週、その実験は期待した結果を出せなかった。" },
        { sentence: "Yesterday, she ___ the warning and kept driving.", answer: "ignored", base: "ignore", hint: "i_____", ja: "無視する", sentenceJa: "昨日、彼女は警告を無視して運転を続けた。" },
        { sentence: "Last week, the teacher ___ extra time to grade the exams.", answer: "requested", base: "request", hint: "r______", ja: "依頼する、要請する", sentenceJa: "先週、先生は試験の採点に追加の時間を要求した。" },
      ],
    },
    {
      name: "Day 12",
      items: [
        { sentence: "Yesterday, police ___ the area for clues.", answer: "searched", base: "search", hint: "s_____", ja: "捜す", sentenceJa: "昨日、警察はその地域を手がかりを求めて捜索した。" },
        { sentence: "Yesterday, his harsh comment really ___ her feelings.", answer: "hurt", base: "hurt", hint: "h___", ja: "傷つける", sentenceJa: "昨日、彼のきつい発言は本当に彼女の気持ちを傷つけた。" },
        { sentence: "This morning, he ___ coffee all over his desk.", answer: "spilled", base: "spill", hint: "s____", ja: "こぼす", sentenceJa: "今朝、彼はコーヒーを机中にこぼしてしまった。" },
        { sentence: "Try to ___ living without electricity.", answer: "imagine", base: "imagine", hint: "i______", ja: "想像する", sentenceJa: "電気なしで暮らすことを想像してみてください。" },
        { sentence: "Last week, she ___ to my email within an hour.", answer: "replied", base: "reply", hint: "r____", ja: "返事をする", sentenceJa: "先週、彼女は1時間以内に私のメールに返信した。" },
        { sentence: "Last year, her teacher ___ her to apply for the scholarship.", answer: "encouraged", base: "encourage", hint: "e________", ja: "励ます、促す", sentenceJa: "去年、先生は彼女に奨学金に応募するよう勧めた。" },
        { sentence: "Last week, the company ___ the package a day early.", answer: "delivered", base: "deliver", hint: "d______", ja: "配達する、（演説を）行う", sentenceJa: "先週、その会社は荷物を1日早く配達した。" },
        { sentence: "Few buildings ___ last year's earthquake.", answer: "survived", base: "survive", hint: "s______", ja: "生き延びる", sentenceJa: "去年の地震を生き延びた建物はほとんどなかった。" },
        { sentence: "They ___ a small apartment near the station.", answer: "rent", base: "rent", hint: "r___", ja: "賃借りする、賃貸しする", sentenceJa: "彼らは駅の近くの小さなアパートを借りている。" },
        { sentence: "Yesterday, we ___ to leave early to avoid traffic.", answer: "decided", base: "decide", hint: "d_____", ja: "決める", sentenceJa: "昨日、私たちは渋滞を避けるために早めに出発することにした。" },
        { sentence: "This sign always ___ visitors about the slippery floor.", answer: "warns", base: "warn", hint: "w___", ja: "警告する", sentenceJa: "この看板はいつも、床が滑りやすいことを来場者に警告している。" },
        { sentence: "I'd like to ___ a table for two.", answer: "reserve", base: "reserve", hint: "r______", ja: "予約する", sentenceJa: "2名用の席を予約したいのですが。" },
        { sentence: "Yesterday, the weather ___ cold very suddenly.", answer: "turned", base: "turn", hint: "t___", ja: "曲がる、〜になる", sentenceJa: "昨日、天気は急に寒くなった。" },
        { sentence: "Prices have ___ sharply this year.", answer: "risen", base: "rise", hint: "r___", ja: "上がる、昇る", sentenceJa: "今年、物価は急激に上昇した。" },
        { sentence: "All employees are expected to ___ the meeting.", answer: "attend", base: "attend", hint: "a_____", ja: "出席する", sentenceJa: "全従業員が会議に出席することになっている。" },
        { sentence: "Last night, the prisoner ___ through a hole in the fence.", answer: "escaped", base: "escape", hint: "e_____", ja: "逃げる", sentenceJa: "昨夜、その囚人はフェンスの穴から逃げた。" },
        { sentence: "Last month, they ___ a big party for her birthday.", answer: "threw", base: "throw", hint: "t____", ja: "投げる、（催しを）開く", sentenceJa: "先月、彼らは彼女の誕生日に盛大なパーティーを開いた。" },
        { sentence: "Last night, she ___ the baby down gently in the crib.", answer: "laid", base: "lay", hint: "l__", ja: "置く、横たえる", sentenceJa: "昨夜、彼女は赤ちゃんをそっとベビーベッドに寝かせた。" },
        { sentence: "Yesterday, the map ___ us through the old city.", answer: "guided", base: "guide", hint: "g____", ja: "導く、案内する", sentenceJa: "昨日、その地図は旧市街を案内してくれた。" },
        { sentence: "This morning, I ___ a small crack in the wall.", answer: "noticed", base: "notice", hint: "n_____", ja: "気づく", sentenceJa: "今朝、私は壁に小さなひびがあることに気づいた。" },
      ],
    },
    {
      name: "Day 13",
      items: [
        { sentence: "Yesterday, she ___ to the report several times during the meeting.", answer: "referred", base: "refer", hint: "r____", ja: "言及する、紹介する", sentenceJa: "昨日、彼女は会議中に何度もその報告書に言及した。" },
        { sentence: "I really ___ your help with this.", answer: "appreciate", base: "appreciate", hint: "a_________", ja: "感謝する、真価を認める", sentenceJa: "これを手伝ってくれて本当に感謝しています。" },
        { sentence: "Yesterday, the senator ___ the new policy in his speech.", answer: "attacked", base: "attack", hint: "a_____", ja: "攻撃する", sentenceJa: "昨日、その上院議員は演説の中で新しい政策を批判した。" },
        { sentence: "Let's ___ some other options before deciding.", answer: "explore", base: "explore", hint: "e______", ja: "探検する、探る", sentenceJa: "決める前に他の選択肢も検討してみましょう。" },
        { sentence: "Her English has ___ a lot this year.", answer: "improved", base: "improve", hint: "i______", ja: "改善する", sentenceJa: "彼女の英語は今年、大きく上達した。" },
        { sentence: "This price always ___ breakfast and Wi-Fi.", answer: "includes", base: "include", hint: "i______", ja: "含む", sentenceJa: "この料金にはいつも朝食とWi-Fiが含まれている。" },
        { sentence: "Last week, the doctor ___ him to rest for a week.", answer: "advised", base: "advise", hint: "a_____", ja: "助言する", sentenceJa: "先週、医者は彼に1週間休むよう助言した。" },
        { sentence: "Yesterday, she ___ the table after dinner.", answer: "wiped", base: "wipe", hint: "w___", ja: "拭く", sentenceJa: "昨日、彼女は夕食後にテーブルを拭いた。" },
        { sentence: "He ___ waking up early.", answer: "dislikes", base: "dislike", hint: "d______", ja: "嫌う", sentenceJa: "彼は早起きが嫌いだ。" },
        { sentence: "Currently, it ___ that we made a mistake.", answer: "appears", base: "appear", hint: "a_____", ja: "現れる、〜のように見える", sentenceJa: "現時点では、私たちは間違いを犯したようだ。" },
        { sentence: "Yesterday, my laptop ___ right before I saved the file.", answer: "crashed", base: "crash", hint: "c____", ja: "衝突する、（コンピュータが）落ちる", sentenceJa: "昨日、ファイルを保存する直前にノートパソコンがフリーズした。" },
        { sentence: "Last night, we ___ pizza for the party.", answer: "ordered", base: "order", hint: "o____", ja: "注文する、命令する", sentenceJa: "昨夜、私たちはパーティーのためにピザを注文した。" },
        { sentence: "Yesterday, we ___ nearly an hour for the bus.", answer: "waited", base: "wait", hint: "w___", ja: "待つ", sentenceJa: "昨日、私たちはバスを1時間近く待った。" },
        { sentence: "Don't ___ a book by its cover.", answer: "judge", base: "judge", hint: "j____", ja: "判断する、審査する", sentenceJa: "見た目で判断してはいけない。" },
        { sentence: "Last week, she ___ the entire speech.", answer: "memorized", base: "memorize", hint: "m_______", ja: "暗記する", sentenceJa: "先週、彼女はそのスピーチを丸暗記した。" },
        { sentence: "She decided to ___ the plan at the last minute.", answer: "drop", base: "drop", hint: "d___", ja: "落とす、やめる", sentenceJa: "彼女は土壇場で計画をやめることにした。" },
        { sentence: "Last month, scientists ___ a new species of frog.", answer: "discovered", base: "discover", hint: "d_______", ja: "発見する", sentenceJa: "先月、科学者たちは新種のカエルを発見した。" },
        { sentence: "I ___ I could travel more often.", answer: "wish", base: "wish", hint: "w___", ja: "望む", sentenceJa: "もっと頻繁に旅行できたらいいのに。" },
        { sentence: "Yesterday, the train ___ exactly on time.", answer: "arrived", base: "arrive", hint: "a_____", ja: "到着する", sentenceJa: "昨日、電車はちょうど時間通りに到着した。" },
        { sentence: "Someone ___ on the door late last night.", answer: "knocked", base: "knock", hint: "k____", ja: "ノックする、ぶつける", sentenceJa: "昨夜遅く、誰かがドアをノックした。" },
      ],
    },
    {
      name: "Day 15",
      items: [
        { sentence: "These shoes don't ___ me anymore.", answer: "fit", base: "fit", hint: "f__", ja: "合う", sentenceJa: "この靴はもう私に合わない。" },
        { sentence: "Last week, our team ___ the final game by one point.", answer: "lost", base: "lose", hint: "l___", ja: "なくす、負ける", sentenceJa: "先週、私たちのチームは決勝戦を1点差で落とした。" },
        { sentence: "We ___ the meeting to end by five o'clock.", answer: "expect", base: "expect", hint: "e_____", ja: "予期する、期待する", sentenceJa: "私たちは会議が5時までに終わると予想している。" },
        { sentence: "Yesterday, her kind words ___ everyone in the room.", answer: "touched", base: "touch", hint: "t____", ja: "触れる、感動させる", sentenceJa: "昨日、彼女の優しい言葉はその場にいた全員の心を打った。" },
        { sentence: "Last night, the waiter ___ the seafood pasta.", answer: "recommended", base: "recommend", hint: "r________", ja: "勧める", sentenceJa: "昨夜、ウェイターはシーフードパスタを勧めた。" },
        { sentence: "They got ___ last summer.", answer: "married", base: "marry", hint: "m____", ja: "結婚する", sentenceJa: "彼らは去年の夏に結婚した。" },
        { sentence: "You can ___ him to keep his promise.", answer: "trust", base: "trust", hint: "t____", ja: "信頼する", sentenceJa: "彼は約束を守ると信頼できる。" },
        { sentence: "Yesterday, she ___ quickly and left for work.", answer: "dressed", base: "dress", hint: "d____", ja: "服を着せる、着る", sentenceJa: "昨日、彼女は急いで着替えて仕事に出かけた。" },
        { sentence: "We need to ___ quickly before it's too late.", answer: "act", base: "act", hint: "a__", ja: "行動する、演じる", sentenceJa: "手遅れになる前に素早く行動する必要がある。" },
        { sentence: "Last summer, they ___ the mountain in six hours.", answer: "climbed", base: "climb", hint: "c____", ja: "登る", sentenceJa: "去年の夏、彼らは6時間でその山に登った。" },
        { sentence: "Yesterday, we ___ about our weekend plans.", answer: "chatted", base: "chat", hint: "c___", ja: "おしゃべりする", sentenceJa: "昨日、私たちは週末の予定についておしゃべりした。" },
        { sentence: "I still ___ she is telling the truth.", answer: "believe", base: "believe", hint: "b______", ja: "信じる", sentenceJa: "私は今でも彼女が本当のことを言っていると思う。" },
        { sentence: "Yesterday, he ___ that he might move abroad.", answer: "mentioned", base: "mention", hint: "m______", ja: "言及する", sentenceJa: "昨日、彼は海外に引っ越すかもしれないと言っていた。" },
        { sentence: "The ice cream ___ before we got home.", answer: "melted", base: "melt", hint: "m___", ja: "溶ける", sentenceJa: "家に着く前にアイスクリームは溶けてしまった。" },
        { sentence: "The phone ___ three times before she answered.", answer: "rang", base: "ring", hint: "r___", ja: "鳴る、電話する", sentenceJa: "彼女が出るまでに電話は3回鳴った。" },
        { sentence: "This lawyer ___ in international business.", answer: "specializes", base: "specialize", hint: "s_________", ja: "専門にする", sentenceJa: "この弁護士は国際ビジネスを専門にしている。" },
        { sentence: "Yesterday, he ___ the bill before leaving the restaurant.", answer: "paid", base: "pay", hint: "p__", ja: "支払う", sentenceJa: "昨日、彼はレストランを出る前に会計を済ませた。" },
        { sentence: "Please ___ the page to see the latest results.", answer: "refresh", base: "refresh", hint: "r______", ja: "元気を回復させる、更新する", sentenceJa: "最新の結果を見るにはページを更新してください。" },
        { sentence: "Yesterday, she ___ a letter from her old friend.", answer: "received", base: "receive", hint: "r______", ja: "受け取る", sentenceJa: "昨日、彼女は旧友から手紙を受け取った。" },
        { sentence: "Last week, the tight deadline ___ her to work faster.", answer: "pressed", base: "press", hint: "p____", ja: "押す、迫る", sentenceJa: "先週、厳しい締め切りが彼女に急いで作業するよう迫った。" },
      ],
    },
    {
      name: "Day 16",
      items: [
        { sentence: "The company is ___ serious financial problems.", answer: "facing", base: "face", hint: "f___", ja: "直面する、向く", sentenceJa: "その会社は深刻な財政問題に直面している。" },
        { sentence: "I'm ___ to see the new movie.", answer: "dying", base: "die", hint: "d__", ja: "死ぬ、切望する", sentenceJa: "その新作映画をどうしても見たい。" },
        { sentence: "Yesterday, he ___ for being late.", answer: "apologized", base: "apologize", hint: "a________", ja: "謝る", sentenceJa: "昨日、彼は遅刻したことを謝った。" },
        { sentence: "Last week, the ending of the movie ___ a lot of fans.", answer: "disappointed", base: "disappoint", hint: "d_________", ja: "がっかりさせる", sentenceJa: "先週、その映画の結末は多くのファンをがっかりさせた。" },
        { sentence: "Yesterday, the reporter ___ several witnesses.", answer: "interviewed", base: "interview", hint: "i________", ja: "面接する、取材する", sentenceJa: "昨日、その記者は複数の目撃者に取材した。" },
        { sentence: "This museum always ___ artifacts from ancient Egypt.", answer: "displays", base: "display", hint: "d______", ja: "展示する", sentenceJa: "この博物館はいつも古代エジプトの遺物を展示している。" },
        { sentence: "Last night, firefighters ___ the family from the burning house.", answer: "rescued", base: "rescue", hint: "r_____", ja: "救助する", sentenceJa: "昨夜、消防士たちは燃えている家からその家族を救出した。" },
        { sentence: "Yesterday, she ___ the gift in colorful paper.", answer: "wrapped", base: "wrap", hint: "w___", ja: "包む", sentenceJa: "昨日、彼女はプレゼントをカラフルな紙で包んだ。" },
        { sentence: "He spends hours ___ the internet every night.", answer: "surfing", base: "surf", hint: "s___", ja: "サーフィンする、（ネットを）見て回る", sentenceJa: "彼は毎晩何時間もネットサーフィンをして過ごす。" },
        { sentence: "They ___ to a bigger house last month.", answer: "moved", base: "move", hint: "m___", ja: "動く、引っ越す", sentenceJa: "彼らは先月、もっと大きな家に引っ越した。" },
        { sentence: "Yesterday, she ___ at us from across the street.", answer: "waved", base: "wave", hint: "w___", ja: "手を振る", sentenceJa: "昨日、彼女は通りの向こうから私たちに手を振った。" },
        { sentence: "He often ___ breakfast when he's busy.", answer: "skips", base: "skip", hint: "s___", ja: "抜かす、跳ねる", sentenceJa: "彼は忙しいとよく朝食を抜く。" },
        { sentence: "She ___ very confident about the interview.", answer: "seems", base: "seem", hint: "s___", ja: "〜のように見える", sentenceJa: "彼女はその面接についてとても自信があるように見える。" },
        { sentence: "Yesterday, the police ___ two suspects near the station.", answer: "arrested", base: "arrest", hint: "a_____", ja: "逮捕する", sentenceJa: "昨日、警察は駅の近くで容疑者2人を逮捕した。" },
        { sentence: "Yesterday, the news ___ everyone in the office.", answer: "surprised", base: "surprise", hint: "s_______", ja: "驚かせる", sentenceJa: "昨日、そのニュースはオフィスの全員を驚かせた。" },
        { sentence: "Yesterday, he ___ the heavy box onto the shelf.", answer: "lifted", base: "lift", hint: "l___", ja: "持ち上げる", sentenceJa: "昨日、彼は重い箱を持ち上げて棚に乗せた。" },
        { sentence: "Last month, the company ___ its prices for the holiday sale.", answer: "reduced", base: "reduce", hint: "r_____", ja: "減らす", sentenceJa: "先月、その会社はホリデーセールのために価格を下げた。" },
        { sentence: "She ___ her neighbor's kids every weekend.", answer: "babysits", base: "babysit", hint: "b______", ja: "子守りをする", sentenceJa: "彼女は毎週末、近所の子供たちの子守りをする。" },
        { sentence: "Yesterday, he ___ the cart down the aisle.", answer: "pushed", base: "push", hint: "p___", ja: "押す", sentenceJa: "昨日、彼はカートを通路の先へ押していった。" },
        { sentence: "She ___ at the animal shelter every weekend.", answer: "volunteers", base: "volunteer", hint: "v________", ja: "志願する、無償で行う", sentenceJa: "彼女は毎週末、動物保護施設でボランティアをしている。" },
      ],
    },
    {
      name: "Day 17",
      items: [
        { sentence: "Yesterday, she ___ some tea for her guests.", answer: "poured", base: "pour", hint: "p___", ja: "注ぐ", sentenceJa: "昨日、彼女はお客さんにお茶を注いだ。" },
        { sentence: "Please ___ your password to continue.", answer: "enter", base: "enter", hint: "e____", ja: "入る、入力する", sentenceJa: "続けるにはパスワードを入力してください。" },
        { sentence: "The factory ___ thousands of cars each year.", answer: "produces", base: "produce", hint: "p______", ja: "生産する", sentenceJa: "その工場は毎年何千台もの車を生産している。" },
        { sentence: "Last month, public opinion ___ quickly after the debate.", answer: "swung", base: "swing", hint: "s____", ja: "揺れる、変動する", sentenceJa: "先月、討論の後、世論は急速に変化した。" },
        { sentence: "She struggled to ___ her temper.", answer: "control", base: "control", hint: "c______", ja: "制御する", sentenceJa: "彼女は感情を抑えるのに苦労した。" },
        { sentence: "Last weekend, they ___ all their neighbors to the barbecue.", answer: "invited", base: "invite", hint: "i_____", ja: "招待する", sentenceJa: "先週末、彼らは近所の人を全員バーベキューに招待した。" },
        { sentence: "Currently, the river ___ through three different countries.", answer: "flows", base: "flow", hint: "f___", ja: "流れる", sentenceJa: "現在、その川は3つの異なる国を流れている。" },
        { sentence: "Yesterday, we ___ the budget for over an hour.", answer: "discussed", base: "discuss", hint: "d______", ja: "話し合う", sentenceJa: "昨日、私たちは1時間以上予算について話し合った。" },
        { sentence: "Yesterday, the manager ___ the report before the meeting.", answer: "reviewed", base: "review", hint: "r_____", ja: "見直す、批評する", sentenceJa: "昨日、マネージャーは会議の前にその報告書を見直した。" },
        { sentence: "Last week, she ___ not asking for more time.", answer: "regretted", base: "regret", hint: "r_____", ja: "後悔する", sentenceJa: "先週、彼女はもっと時間をもらうよう頼まなかったことを後悔した。" },
        { sentence: "He ___ the table before the guests arrived.", answer: "set", base: "set", hint: "s__", ja: "置く、設定する", sentenceJa: "彼はお客さんが来る前にテーブルを整えた。" },
        { sentence: "The comment ___ her more than she expected.", answer: "upset", base: "upset", hint: "u____", ja: "動揺させる", sentenceJa: "そのコメントは彼女が思っていた以上に彼女を動揺させた。" },
        { sentence: "The school doesn't ___ phones in class.", answer: "allow", base: "allow", hint: "a____", ja: "許可する", sentenceJa: "その学校では授業中の携帯電話を許可していない。" },
        { sentence: "Please ___ us if you have any questions.", answer: "contact", base: "contact", hint: "c______", ja: "連絡する", sentenceJa: "ご質問があればご連絡ください。" },
        { sentence: "Last year, many farmers ___ from the long drought.", answer: "suffered", base: "suffer", hint: "s_____", ja: "苦しむ", sentenceJa: "去年、多くの農家がその長い干ばつで苦しんだ。" },
        { sentence: "Last year, the whole family ___ for the holidays.", answer: "gathered", base: "gather", hint: "g_____", ja: "集まる、集める", sentenceJa: "去年、家族全員が休暇のために集まった。" },
        { sentence: "Yesterday, she ___ the book to the library on time.", answer: "returned", base: "return", hint: "r_____", ja: "戻る、返す", sentenceJa: "昨日、彼女は期限内に本を図書館に返却した。" },
        { sentence: "The festival ___ thousands of visitors every year.", answer: "attracts", base: "attract", hint: "a______", ja: "引きつける", sentenceJa: "その祭りは毎年何千人もの来場者を引きつける。" },
        { sentence: "The doctor advised him to ___ his sugar intake.", answer: "limit", base: "limit", hint: "l____", ja: "制限する", sentenceJa: "医者は彼に糖分の摂取を制限するよう助言した。" },
        { sentence: "We need to ___ the broken window.", answer: "replace", base: "replace", hint: "r______", ja: "交換する、取り替える", sentenceJa: "私たちは壊れた窓を交換する必要がある。" },
      ],
    },
    {
      name: "Day 18",
      items: [
        { sentence: "Yesterday, the weather ___ suddenly in the afternoon.", answer: "changed", base: "change", hint: "c_____", ja: "変える、変わる", sentenceJa: "昨日、午後になって天気が急に変わった。" },
        { sentence: "For the first time in her career, she ___ success.", answer: "tasted", base: "taste", hint: "t____", ja: "味わう、経験する", sentenceJa: "彼女はキャリアで初めて成功を味わった。" },
        { sentence: "I still ___ he'll be late again.", answer: "suppose", base: "suppose", hint: "s______", ja: "想定する、〜だと思う", sentenceJa: "彼はまた遅刻するだろうと私は今でも思っている。" },
        { sentence: "The soup was so hot it ___ my tongue.", answer: "burned", base: "burn", hint: "b___", ja: "燃える、ひりひりする", sentenceJa: "そのスープはとても熱くて舌を火傷した。" },
        { sentence: "Sales ___ a record high this quarter.", answer: "hit", base: "hit", hint: "h__", ja: "打つ、達する", sentenceJa: "今四半期、売上は過去最高を記録した。" },
        { sentence: "The school will ___ its annual festival next week.", answer: "hold", base: "hold", hint: "h___", ja: "持つ、開催する", sentenceJa: "その学校は来週、恒例の学園祭を開催する。" },
        { sentence: "We're ___ moving to a new city.", answer: "considering", base: "consider", hint: "c_______", ja: "検討する", sentenceJa: "私たちは新しい街に引っ越すことを検討している。" },
        { sentence: "Please ___ your email for the confirmation.", answer: "check", base: "check", hint: "c____", ja: "確認する", sentenceJa: "確認メールをチェックしてください。" },
        { sentence: "Last year, sales ___ sharply during the winter months.", answer: "decreased", base: "decrease", hint: "d_______", ja: "減少する", sentenceJa: "去年、冬の間、売上は急激に減少した。" },
        { sentence: "Last month, she ___ in finishing the project early.", answer: "succeeded", base: "succeed", hint: "s______", ja: "成功する", sentenceJa: "先月、彼女はそのプロジェクトを早めに終わらせることに成功した。" },
        { sentence: "His heart ___ when he heard the news.", answer: "sank", base: "sink", hint: "s___", ja: "沈む、（気持ちが）沈む", sentenceJa: "そのニュースを聞いて彼は気持ちが沈んだ。" },
        { sentence: "Could you ___ two copies of this document?", answer: "print", base: "print", hint: "p____", ja: "印刷する", sentenceJa: "この書類を2部印刷してもらえますか。" },
        { sentence: "Yesterday, she ___ her gratitude to the whole team.", answer: "expressed", base: "express", hint: "e______", ja: "表現する", sentenceJa: "昨日、彼女はチーム全員に感謝の気持ちを伝えた。" },
        { sentence: "Last month, the store ___ its prices for the summer sale.", answer: "lowered", base: "lower", hint: "l____", ja: "下げる", sentenceJa: "先月、その店は夏のセールのために価格を下げた。" },
        { sentence: "It took them a week to ___ the puzzle.", answer: "solve", base: "solve", hint: "s____", ja: "解決する", sentenceJa: "そのパズルを解くのに彼らは1週間かかった。" },
        { sentence: "___ a little salt to the soup.", answer: "add", base: "add", hint: "a__", ja: "加える", sentenceJa: "スープに少し塩を加えてください。" },
        { sentence: "Yesterday, she ___ cookies for the school event.", answer: "baked", base: "bake", hint: "b___", ja: "焼く", sentenceJa: "昨日、彼女は学校行事のためにクッキーを焼いた。" },
        { sentence: "I can't ___ where I put my keys.", answer: "remember", base: "remember", hint: "r_______", ja: "覚えている", sentenceJa: "鍵をどこに置いたか思い出せない。" },
        { sentence: "Yesterday, she ___ the picture on the wall.", answer: "hung", base: "hang", hint: "h___", ja: "掛ける、ぶら下がる", sentenceJa: "昨日、彼女は壁に絵をかけた。" },
      ],
    },
    {
      name: "Day 19",
      items: [
        { sentence: "It's hard to ___ the twins apart.", answer: "tell", base: "tell", hint: "t___", ja: "見分ける、判断する", sentenceJa: "その双子を見分けるのは難しい。" },
        { sentence: "She ___ a small bakery downtown.", answer: "owns", base: "own", hint: "o__", ja: "所有する", sentenceJa: "彼女は繁華街に小さなパン屋を所有している。" },
        { sentence: "The proposal doesn't ___ our budget requirements.", answer: "meet", base: "meet", hint: "m___", ja: "満たす、応じる", sentenceJa: "その提案は私たちの予算要件を満たしていない。" },
        { sentence: "Poor sleep can ___ to health problems.", answer: "lead", base: "lead", hint: "l___", ja: "つながる、至る", sentenceJa: "睡眠不足は健康問題につながることがある。" },
        { sentence: "Take a moment to ___ on what happened.", answer: "reflect", base: "reflect", hint: "r______", ja: "よく考える、熟考する", sentenceJa: "何が起きたのか、少し時間を取って考えてみてください。" },
        { sentence: "I'd like to ___ a concern about the schedule.", answer: "raise", base: "raise", hint: "r____", ja: "（話題を）持ち出す", sentenceJa: "スケジュールについて懸念を伝えたいのですが。" },
        { sentence: "I still ___ my success to my mentor's advice.", answer: "owe", base: "owe", hint: "o__", ja: "恩がある、〜のおかげである", sentenceJa: "私は今でも、自分の成功はメンターの助言のおかげだと思っている。" },
        { sentence: "She ___ a small restaurant in town.", answer: "runs", base: "run", hint: "r__", ja: "経営する、運営する", sentenceJa: "彼女は町で小さなレストランを経営している。" },
        { sentence: "Every vote always ___ in this election.", answer: "counts", base: "count", hint: "c____", ja: "重要である、価値がある", sentenceJa: "この選挙では一票一票がいつも重要だ。" },
        { sentence: "Please ___ these files by date.", answer: "sort", base: "sort", hint: "s___", ja: "分類する、整理する", sentenceJa: "これらのファイルを日付順に分類してください。" },
        { sentence: "Yesterday, the meeting ___ for two hours.", answer: "lasted", base: "last", hint: "l___", ja: "続く、持続する", sentenceJa: "昨日、その会議は2時間続いた。" },
        { sentence: "You still ___ a break after all that work.", answer: "deserve", base: "deserve", hint: "d______", ja: "〜に値する", sentenceJa: "あれだけ働いたのだから、あなたは今でも休憩に値する。" },
        { sentence: "Last week, he ___ to finishing the project on time.", answer: "committed", base: "commit", hint: "c_____", ja: "誓う、専念する", sentenceJa: "先週、彼は期限内にプロジェクトを終わらせると誓った。" },
        { sentence: "The company will ___ a new app next month.", answer: "launch", base: "launch", hint: "l_____", ja: "開始する、立ち上げる", sentenceJa: "その会社は来月、新しいアプリを開始する。" },
        { sentence: "Don't ___ your trash on the street.", answer: "dump", base: "dump", hint: "d___", ja: "捨てる", sentenceJa: "道にゴミを捨てないでください。" },
        { sentence: "I ___ she's already finished her homework.", answer: "bet", base: "bet", hint: "b__", ja: "きっと〜だと思う", sentenceJa: "彼女はもう宿題を終えているに違いない。" },
        { sentence: "Yesterday, we finally ___ the missing keys.", answer: "located", base: "locate", hint: "l_____", ja: "位置を特定する、見つけ出す", sentenceJa: "昨日、私たちはついになくした鍵を見つけた。" },
        { sentence: "Last month, he ___ to finish the marathon.", answer: "struggled", base: "struggle", hint: "s_______", ja: "苦労する、奮闘する", sentenceJa: "先月、彼はマラソンを完走するのに苦労した。" },
        { sentence: "Let's ___ the bill evenly.", answer: "split", base: "split", hint: "s____", ja: "分ける、割る", sentenceJa: "会計を均等に割りましょう。" },
        { sentence: "It takes time to ___ all this new information.", answer: "absorb", base: "absorb", hint: "a_____", ja: "吸収する、理解する", sentenceJa: "この新しい情報をすべて理解するには時間がかかる。" },
      ],
    },
    {
      name: "Day 20",
      items: [
        { sentence: "Yesterday, she ___ to help me carry the boxes.", answer: "offered", base: "offer", hint: "o____", ja: "申し出る、提供する", sentenceJa: "昨日、彼女は箱を運ぶのを手伝うと申し出た。" },
        { sentence: "This hotel always ___ extra for breakfast.", answer: "charges", base: "charge", hint: "c_____", ja: "請求する", sentenceJa: "このホテルはいつも朝食に追加料金を請求する。" },
        { sentence: "Last week, scientists ___ the water samples.", answer: "analyzed", base: "analyze", hint: "a______", ja: "分析する", sentenceJa: "先週、科学者たちは水のサンプルを分析した。" },
        { sentence: "She ___ new employees every month.", answer: "trains", base: "train", hint: "t____", ja: "訓練する、鍛える", sentenceJa: "彼女は毎月新入社員を訓練している。" },
        { sentence: "Please ___ the file to your email.", answer: "attach", base: "attach", hint: "a_____", ja: "取り付ける、添付する", sentenceJa: "ファイルをメールに添付してください。" },
        { sentence: "Please ___ out this application form.", answer: "fill", base: "fill", hint: "f___", ja: "満たす、記入する", sentenceJa: "この申込用紙にご記入ください。" },
        { sentence: "Can you ___ how old I am?", answer: "guess", base: "guess", hint: "g____", ja: "推測する", sentenceJa: "私が何歳か当てられますか。" },
        { sentence: "Does Friday afternoon ___ you for the meeting?", answer: "suit", base: "suit", hint: "s___", ja: "都合が良い、似合う", sentenceJa: "会議は金曜日の午後でご都合よろしいですか。" },
        { sentence: "Yesterday, the doctor ___ the patient's injury.", answer: "treated", base: "treat", hint: "t____", ja: "扱う、治療する", sentenceJa: "昨日、医者はその患者の怪我を治療した。" },
        { sentence: "Yesterday, we ___ time at the airport by reading magazines.", answer: "killed", base: "kill", hint: "k___", ja: "時間をつぶす", sentenceJa: "昨日、私たちは雑誌を読んで空港で時間をつぶした。" },
        { sentence: "This job ___ a lot of travel.", answer: "involves", base: "involve", hint: "i______", ja: "伴う、含む", sentenceJa: "この仕事は出張が多く伴う。" },
        { sentence: "Last night, the fire ___ the entire building.", answer: "destroyed", base: "destroy", hint: "d______", ja: "破壊する", sentenceJa: "昨夜、その火事は建物全体を破壊した。" },
        { sentence: "I need to ___ my suitcase tonight.", answer: "pack", base: "pack", hint: "p___", ja: "荷造りする", sentenceJa: "今夜、スーツケースに荷造りをしなければならない。" },
        { sentence: "It's hard to ___ to a diet during the holidays.", answer: "stick", base: "stick", hint: "s____", ja: "やり通す、固執する", sentenceJa: "休暇中にダイエットを続けるのは難しい。" },
        { sentence: "Yesterday, I ___ the article for the main points.", answer: "scanned", base: "scan", hint: "s___", ja: "ざっと目を通す", sentenceJa: "昨日、私はその記事の要点をざっと確認した。" },
        { sentence: "Technology has ___ rapidly in the last decade.", answer: "advanced", base: "advance", hint: "a______", ja: "前進する、進歩する", sentenceJa: "この10年でテクノロジーは急速に進歩した。" },
        { sentence: "She ___ when she saw the spider.", answer: "froze", base: "freeze", hint: "f_____", ja: "凍りつく、動けなくなる", sentenceJa: "彼女はクモを見て凍りついた。" },
        { sentence: "Yesterday, he ___ on the sofa all afternoon.", answer: "lay", base: "lie", hint: "l__", ja: "横たわる", sentenceJa: "昨日、彼は午後じゅうソファに横になっていた。" },
        { sentence: "We had to ___ the trip because of the storm.", answer: "postpone", base: "postpone", hint: "p_______", ja: "延期する", sentenceJa: "嵐のため、私たちは旅行を延期しなければならなかった。" },
        { sentence: "Please ___ the volume on the TV.", answer: "adjust", base: "adjust", hint: "a_____", ja: "調整する", sentenceJa: "テレビの音量を調整してください。" },
      ],
    },
    {
      name: "Day 22",
      items: [
        { sentence: "What you're saying doesn't make ___ to me.", answer: "sense", base: "sense", hint: "s____", ja: "分別、意味", sentenceJa: "あなたの言っていることは私には理解できない。" },
        { sentence: "Getting enough sleep should be a ___.", answer: "priority", base: "priority", hint: "p_______", ja: "優先事項", sentenceJa: "十分な睡眠を取ることを優先すべきだ。" },
        { sentence: "Please turn down the ___ on the TV.", answer: "volume", base: "volume", hint: "v_____", ja: "量、音量", sentenceJa: "テレビの音量を下げてください。" },
        { sentence: "The teacher gave us extra ___ to study.", answer: "material", base: "material", hint: "m_______", ja: "資料、素材", sentenceJa: "先生は私たちに勉強用の追加資料をくれた。" },
        { sentence: "She works in the marketing ___.", answer: "department", base: "department", hint: "d_________", ja: "部門、部署", sentenceJa: "彼女はマーケティング部門で働いている。" },
        { sentence: "In that ___, we should reschedule the meeting.", answer: "case", base: "case", hint: "c___", ja: "場合、事例", sentenceJa: "その場合は、会議の予定を変更した方がいい。" },
        { sentence: "I'll finish the ___ of the report tomorrow.", answer: "rest", base: "rest", hint: "r___", ja: "残り", sentenceJa: "報告書の残りは明日仕上げます。" },
        { sentence: "I have a dentist ___ this afternoon.", answer: "appointment", base: "appointment", hint: "a__________", ja: "予約、約束", sentenceJa: "今日の午後、歯医者の予約がある。" },
        { sentence: "A balanced ___ includes plenty of vegetables.", answer: "diet", base: "diet", hint: "d___", ja: "食事、食生活", sentenceJa: "バランスの取れた食事には野菜がたくさん含まれる。" },
        { sentence: "They have a close ___ with their neighbors.", answer: "relationship", base: "relationship", hint: "r___________", ja: "関係", sentenceJa: "彼らは近所の人たちと親しい関係を築いている。" },
        { sentence: "There was a strange ___ on the table.", answer: "object", base: "object", hint: "o_____", ja: "物体", sentenceJa: "テーブルの上に奇妙な物体があった。" },
        { sentence: "This ice cream has a strong chocolate ___.", answer: "flavor", base: "flavor", hint: "f_____", ja: "風味、味", sentenceJa: "このアイスクリームは濃いチョコレート味がする。" },
        { sentence: "Could you do me a ___ and open the door?", answer: "favor", base: "favor", hint: "f____", ja: "頼み事、親切な行為", sentenceJa: "お願いがあるのですが、ドアを開けてもらえますか。" },
        { sentence: "Email is a quick ___ of communication.", answer: "means", base: "means", hint: "m____", ja: "手段", sentenceJa: "メールは迅速なコミュニケーション手段だ。" },
        { sentence: "Biting your nails is a hard ___ to break.", answer: "habit", base: "habit", hint: "h____", ja: "習慣、癖", sentenceJa: "爪を噛む癖はやめるのが難しい。" },
        { sentence: "We were stuck in a traffic ___ for an hour.", answer: "jam", base: "jam", hint: "j__", ja: "詰まること、渋滞", sentenceJa: "私たちは1時間、交通渋滞にはまっていた。" },
        { sentence: "Here's a ___ for saving time in the kitchen.", answer: "tip", base: "tip", hint: "t__", ja: "助言、コツ", sentenceJa: "台所仕事の時間を節約するコツを教えます。" },
        { sentence: "There isn't much ___ for more furniture.", answer: "room", base: "room", hint: "r___", ja: "余地、空間", sentenceJa: "これ以上家具を置くスペースはあまりない。" },
        { sentence: "She has a positive ___ toward challenges.", answer: "attitude", base: "attitude", hint: "a_______", ja: "態度、考え方", sentenceJa: "彼女は困難に対して前向きな姿勢を持っている。" },
        { sentence: "The hotel offers a special vacation ___.", answer: "package", base: "package", hint: "p______", ja: "一式、セット", sentenceJa: "そのホテルは特別な休暇パッケージを提供している。" },
      ],
    },
    {
      name: "Day 23",
      items: [
        { sentence: "Is this seat ___?", answer: "available", base: "available", hint: "a________", ja: "利用できる、手が空いている", sentenceJa: "この席は空いていますか。" },
        { sentence: "You can park on ___ side of the street.", answer: "either", base: "either", hint: "e_____", ja: "どちらか一方の", sentenceJa: "通りのどちら側にも駐車できます。" },
        { sentence: "She gave a ___ overview of the plan.", answer: "general", base: "general", hint: "g______", ja: "全般的な、一般的な", sentenceJa: "彼女はその計画の全体的な概要を説明した。" },
        { sentence: "He is a ___ employee of this company.", answer: "former", base: "former", hint: "f_____", ja: "以前の、前者の", sentenceJa: "彼はこの会社の元従業員だ。" },
        { sentence: "Is Tuesday a ___ day for you?", answer: "convenient", base: "convenient", hint: "c_________", ja: "便利な、都合が良い", sentenceJa: "火曜日はご都合よろしいですか。" },
        { sentence: "He felt ___ of his brother's new car.", answer: "jealous", base: "jealous", hint: "j______", ja: "嫉妬した、うらやましく思う", sentenceJa: "彼は兄の新しい車をうらやましく思った。" },
        { sentence: "She is ___ for training new staff.", answer: "responsible", base: "responsible", hint: "r__________", ja: "責任がある", sentenceJa: "彼女は新人スタッフの研修を担当している。" },
        { sentence: "This car has proven to be very ___.", answer: "reliable", base: "reliable", hint: "r_______", ja: "信頼できる", sentenceJa: "この車はとても信頼できることが分かっている。" },
        { sentence: "She stayed ___ despite the setback.", answer: "positive", base: "positive", hint: "p_______", ja: "前向きな、確信して", sentenceJa: "彼女は挫折にもかかわらず前向きでいた。" },
        { sentence: "The students were fully ___ in the discussion.", answer: "engaged", base: "engaged", hint: "e______", ja: "従事して、婚約して", sentenceJa: "生徒たちは議論に完全に没頭していた。" },
        { sentence: "His desk is always ___.", answer: "messy", base: "messy", hint: "m____", ja: "散らかった", sentenceJa: "彼の机はいつも散らかっている。" },
        { sentence: "I feel ___ for forgetting her birthday.", answer: "guilty", base: "guilty", hint: "g_____", ja: "罪悪感を感じる、有罪の", sentenceJa: "彼女の誕生日を忘れてしまい罪悪感を感じる。" },
        { sentence: "The children were ___ about the old house.", answer: "curious", base: "curious", hint: "c______", ja: "好奇心が強い", sentenceJa: "子供たちはその古い家に好奇心を抱いていた。" },
        { sentence: "The exam was more ___ than expected.", answer: "challenging", base: "challenging", hint: "c__________", ja: "やりがいがある、困難な", sentenceJa: "試験は予想していたより難しかった。" },
        { sentence: "Regular exercise is ___ for your health.", answer: "beneficial", base: "beneficial", hint: "b_________", ja: "有益な", sentenceJa: "定期的な運動は健康に有益だ。" },
        { sentence: "Have you seen the ___ episode?", answer: "latest", base: "latest", hint: "l_____", ja: "最新の", sentenceJa: "最新のエピソードを見ましたか。" },
        { sentence: "All employees were ___ at the meeting.", answer: "present", base: "present", hint: "p______", ja: "現在の、出席して", sentenceJa: "全従業員がその会議に出席していた。" },
        { sentence: "Each ___ student received feedback.", answer: "individual", base: "individual", hint: "i_________", ja: "個々の", sentenceJa: "個々の生徒がフィードバックを受け取った。" },
        { sentence: "She took a ___ job over the summer.", answer: "temporary", base: "temporary", hint: "t________", ja: "一時的な", sentenceJa: "彼女は夏の間、一時的な仕事に就いた。" },
        { sentence: "The restroom is ___.", answer: "occupied", base: "occupied", hint: "o_______", ja: "使用中の、忙しい", sentenceJa: "そのお手洗いは使用中です。" },
      ],
    },
    {
      name: "Day 24",
      items: [
        { sentence: "It will ___ rain tomorrow.", answer: "probably", base: "probably", hint: "p_______", ja: "おそらく", sentenceJa: "明日はおそらく雨が降るだろう。" },
        { sentence: "I ___ enjoyed the movie.", answer: "actually", base: "actually", hint: "a_______", ja: "実は、実際に", sentenceJa: "私は実はその映画を楽しんだ。" },
        { sentence: "I love fruit, ___ strawberries.", answer: "especially", base: "especially", hint: "e_________", ja: "特に", sentenceJa: "私は果物が好きで、特にいちごが好きだ。" },
        { sentence: "___, the store closes at nine.", answer: "technically", base: "technically", hint: "t__________", ja: "厳密に言えば", sentenceJa: "厳密に言うと、その店は9時に閉まる。" },
        { sentence: "I ___ just woke up five minutes ago.", answer: "literally", base: "literally", hint: "l________", ja: "文字通り", sentenceJa: "私は文字通り5分前に起きたばかりだ。" },
        { sentence: "Prices have risen ___ this year.", answer: "dramatically", base: "dramatically", hint: "d___________", ja: "劇的に", sentenceJa: "今年、物価は劇的に上昇した。" },
        { sentence: "I will ___ come to the party.", answer: "definitely", base: "definitely", hint: "d_________", ja: "間違いなく", sentenceJa: "私は間違いなくパーティーに行きます。" },
        { sentence: "I ___ forgot about the meeting.", answer: "totally", base: "totally", hint: "t______", ja: "完全に", sentenceJa: "私はその会議のことを完全に忘れていた。" },
        { sentence: "___, we need more time to finish.", answer: "basically", base: "basically", hint: "b________", ja: "基本的に", sentenceJa: "基本的に、終わらせるにはもっと時間が必要だ。" },
        { sentence: "___, we need to leave earlier next time.", answer: "obviously", base: "obviously", hint: "o________", ja: "明らかに", sentenceJa: "明らかに、次回はもっと早く出発する必要がある。" },
        { sentence: "She ___ lives in her hometown.", answer: "still", base: "still", hint: "s____", ja: "まだ、依然として", sentenceJa: "彼女は今も故郷に住んでいる。" },
        { sentence: "They kept the celebration pretty ___.", answer: "low-key", base: "low-key", hint: "l______", ja: "控えめに", sentenceJa: "彼らはお祝いをかなり控えめにした。" },
        { sentence: "The two houses stand far ___.", answer: "apart", base: "apart", hint: "a____", ja: "離れて、バラバラに", sentenceJa: "その2軒の家は遠く離れて建っている。" },
        { sentence: "He is ___ checking his phone.", answer: "constantly", base: "constantly", hint: "c_________", ja: "絶えず", sentenceJa: "彼は絶えず携帯電話をチェックしている。" },
        { sentence: "You should take this warning ___.", answer: "seriously", base: "seriously", hint: "s________", ja: "真剣に、真面目に", sentenceJa: "この警告は真剣に受け止めるべきだ。" },
        { sentence: "It's ___ a matter of practice.", answer: "simply", base: "simply", hint: "s_____", ja: "単に、簡単に", sentenceJa: "それは単に練習の問題だ。" },
        { sentence: "___, I prefer tea over coffee.", answer: "personally", base: "personally", hint: "p_________", ja: "個人的には", sentenceJa: "個人的には、コーヒーより紅茶の方が好きだ。" },
        { sentence: "___, everyone wanted to celebrate.", answer: "naturally", base: "naturally", hint: "n________", ja: "当然、自然に", sentenceJa: "当然ながら、みんながお祝いをしたがった。" },
        { sentence: "She has ___ finished her homework.", answer: "already", base: "already", hint: "a______", ja: "すでに", sentenceJa: "彼女はすでに宿題を終えている。" },
        { sentence: "He ___ travels for work.", answer: "frequently", base: "frequently", hint: "f_________", ja: "頻繁に", sentenceJa: "彼は頻繁に仕事で出張する。" },
      ],
    },
    {
      name: "Day 25",
      items: [
        { sentence: "The washing machine ___ again this morning.", answer: "broke down", base: "break down", hint: "b_________", ja: "壊れる、故障する", sentenceJa: "洗濯機が今朝また故障した。" },
        { sentence: "She finally ___ a solution to the problem.", answer: "came up with", base: "come up with", hint: "c___________", ja: "思いつく、考え出す", sentenceJa: "彼女はついにその問題の解決策を思いついた。" },
        { sentence: "He knocked over the vase ___.", answer: "on purpose", base: "on purpose", hint: "o_________", ja: "わざと、故意に", sentenceJa: "彼はわざと花瓶を倒した。" },
        { sentence: "The printer in the office is ___ again.", answer: "out of order", base: "out of order", hint: "o___________", ja: "故障中", sentenceJa: "オフィスのプリンターがまた故障している。" },
        { sentence: "I'm really ___ this constant noise.", answer: "sick of", base: "sick of", hint: "s______", ja: "うんざりしている", sentenceJa: "この絶え間ない騒音には本当にうんざりしている。" },
        { sentence: "I'd rather explain the situation ___.", answer: "in person", base: "in person", hint: "i________", ja: "直接会って、本人が", sentenceJa: "その状況は直接会って説明したい。" },
        { sentence: "Who I invite to my party is ___.", answer: "none of your business", base: "none of one's business", hint: "n_____________________", ja: "他人には関係ないこと", sentenceJa: "私が誰をパーティーに招待しようと、あなたには関係ない。" },
        { sentence: "I agree with your opinion ___.", answer: "to some extent", base: "to some extent", hint: "t_____________", ja: "ある程度は", sentenceJa: "あなたの意見にはある程度賛成だ。" },
        { sentence: "Yesterday, with tax, the total bill ___ $42.", answer: "came to", base: "come to", hint: "c______", ja: "合計で〜になる", sentenceJa: "昨日、税込みで、合計金額は42ドルになった。" },
        { sentence: "___ price, this laptop is the best option.", answer: "in terms of", base: "in terms of", hint: "i__________", ja: "〜の点では、〜に関して", sentenceJa: "価格の点では、このノートパソコンが一番の選択肢だ。" },
        { sentence: "It took me a while to ___ the puzzle.", answer: "figure out", base: "figure out", hint: "f_________", ja: "理解する、解決する", sentenceJa: "そのパズルを解くのにしばらく時間がかかった。" },
        { sentence: "He ___ works at that company.", answer: "no longer", base: "no longer", hint: "n________", ja: "もはや〜ない", sentenceJa: "彼はもうその会社では働いていない。" },
        { sentence: "___, the trip has been amazing.", answer: "so far", base: "so far", hint: "s_____", ja: "今のところ", sentenceJa: "今のところ、旅行はとても素晴らしい。" },
        { sentence: "It took months to ___ the cold weather.", answer: "get used to", base: "get used to", hint: "g__________", ja: "〜に慣れる", sentenceJa: "その寒さに慣れるのに数ヶ月かかった。" },
        { sentence: "You can borrow my car ___ you return it by six.", answer: "as long as", base: "as long as", hint: "a_________", ja: "〜する限り、〜さえすれば", sentenceJa: "6時までに返してくれるなら、車を貸してもいいよ。" },
        { sentence: "We missed the train and ___ waiting two hours.", answer: "ended up", base: "end up", hint: "e_____", ja: "結局〜することになる", sentenceJa: "電車を逃して、結局2時間待つことになった。" },
        { sentence: "I deleted the file completely ___.", answer: "by accident", base: "by accident", hint: "b__________", ja: "偶然に、うっかり", sentenceJa: "私はうっかりそのファイルを完全に削除してしまった。" },
        { sentence: "We're really ___ the summer festival.", answer: "looking forward to", base: "look forward to", hint: "l______________", ja: "楽しみにする", sentenceJa: "私たちは夏祭りを本当に楽しみにしている。" },
        { sentence: "Last weekend, I ___ an old letter while cleaning the attic.", answer: "came across", base: "come across", hint: "c__________", ja: "偶然出会う", sentenceJa: "先週末、屋根裏を掃除していたら古い手紙を偶然見つけた。" },
        { sentence: "The game was cancelled ___ heavy rain.", answer: "due to", base: "due to", hint: "d_____", ja: "〜のために、〜が原因で", sentenceJa: "その試合は大雨のため中止になった。" },
      ],
    },
    {
      name: "Day 26",
      items: [
        { sentence: "I don't ___ cooking tonight.", answer: "feel like", base: "feel like", hint: "f________", ja: "〜したい気分だ", sentenceJa: "今夜は料理をする気分じゃない。" },
        { sentence: "This tie doesn't ___ your shirt.", answer: "go with", base: "go with", hint: "g______", ja: "合う、選ぶ", sentenceJa: "このネクタイはあなたのシャツに合わない。" },
        { sentence: "I sent the email to the wrong person ___.", answer: "by mistake", base: "by mistake", hint: "b_________", ja: "間違って", sentenceJa: "私は間違って別の人にメールを送ってしまった。" },
        { sentence: "We ___ milk this morning.", answer: "ran out of", base: "run out of", hint: "r_________", ja: "〜を使い果たす", sentenceJa: "今朝、牛乳を切らしてしまった。" },
        { sentence: "We often ___ that clean water is always available.", answer: "take for granted", base: "take for granted", hint: "t_______________", ja: "当然のことと思う", sentenceJa: "私たちはきれいな水がいつでも手に入ることを当然だと思いがちだ。" },
        { sentence: "He ___ talk too fast when he's nervous.", answer: "tends to", base: "tend to", hint: "t______", ja: "〜しがちである", sentenceJa: "彼は緊張すると早口になりがちだ。" },
        { sentence: "Let's ___ each other over coffee.", answer: "catch up with", base: "catch up with", hint: "c____________", ja: "追いつく、近況を語り合う", sentenceJa: "コーヒーでも飲みながら近況を話そう。" },
        { sentence: "I don't know ___ if she's coming.", answer: "for sure", base: "for sure", hint: "f_______", ja: "確かに、間違いなく", sentenceJa: "彼女が来るかどうか確かなことは分からない。" },
        { sentence: "She ___ everyone in the office.", answer: "gets along with", base: "get along with", hint: "g_____________", ja: "仲良くやっていく", sentenceJa: "彼女はオフィスの誰とでもうまくやっている。" },
        { sentence: "The plan sounds simple, but ___ it's quite complex.", answer: "in reality", base: "in reality", hint: "i_________", ja: "実際には", sentenceJa: "その計画は単純に聞こえるが、実際にはかなり複雑だ。" },
        { sentence: "___ the rain, they finished the game.", answer: "in spite of", base: "in spite of", hint: "i__________", ja: "〜にもかかわらず", sentenceJa: "雨にもかかわらず、彼らは試合を終えた。" },
        { sentence: "They tried ___ to fix the old engine.", answer: "in vain", base: "in vain", hint: "i______", ja: "無駄に", sentenceJa: "彼らはその古いエンジンを直そうとしたが無駄だった。" },
        { sentence: "She ___ a difficult time last year.", answer: "went through", base: "go through", hint: "g_________", ja: "経験する、目を通す", sentenceJa: "彼女は去年、辛い時期を経験した。" },
        { sentence: "Are you ___ this software?", answer: "familiar with", base: "familiar with", hint: "f____________", ja: "〜に詳しい、慣れている", sentenceJa: "このソフトウェアに詳しいですか。" },
        { sentence: "He's always ___ help his classmates.", answer: "willing to", base: "willing to", hint: "w_________", ja: "〜する意思がある", sentenceJa: "彼はいつでもクラスメートを進んで手伝う。" },
        { sentence: "You can leave early, ___ you finish your work.", answer: "provided that", base: "provided that", hint: "p____________", ja: "〜という条件で", sentenceJa: "仕事を終わらせるという条件で、早く帰ってもいいですよ。" },
        { sentence: "He likes to ___ his new car.", answer: "show off", base: "show off", hint: "s_______", ja: "見せびらかす", sentenceJa: "彼は新しい車を見せびらかすのが好きだ。" },
        { sentence: "___, the truth always comes out.", answer: "sooner or later", base: "sooner or later", hint: "s______________", ja: "遅かれ早かれ", sentenceJa: "遅かれ早かれ、真実は必ず明らかになる。" },
        { sentence: "It's hard to ___ all these changes.", answer: "keep up with", base: "keep up with", hint: "k___________", ja: "遅れずについていく", sentenceJa: "これらすべての変化についていくのは難しい。" },
        { sentence: "I'm ___ the gym now.", answer: "off to", base: "off to", hint: "o_____", ja: "〜に向かって、出かけて", sentenceJa: "私は今からジムに向かいます。" },
      ],
    },
    {
      name: "Day 27",
      items: [
        { sentence: "Please ___ your assignment by Friday.", answer: "turn in", base: "turn in", hint: "t______", ja: "提出する", sentenceJa: "金曜日までに課題を提出してください。" },
        { sentence: "She ___ a lot of effort on this project.", answer: "put in", base: "put in", hint: "p_____", ja: "（時間や労力を）注ぐ", sentenceJa: "彼女はこのプロジェクトにたくさんの労力を注いだ。" },
        { sentence: "There was too much information to ___ at once.", answer: "take in", base: "take in", hint: "t______", ja: "理解する、吸収する", sentenceJa: "一度に理解するには情報が多すぎた。" },
        { sentence: "He kept ___ while I was talking.", answer: "cutting in", base: "cut in", hint: "c_____", ja: "割り込む", sentenceJa: "私が話している間、彼はずっと割り込んできた。" },
        { sentence: "Someone tried to ___ through the back door.", answer: "break in", base: "break in", hint: "b_______", ja: "侵入する", sentenceJa: "誰かが裏口から侵入しようとした。" },
        { sentence: "She ___ her coat before leaving.", answer: "put on", base: "put on", hint: "p_____", ja: "身につける", sentenceJa: "彼女は出かける前にコートを着た。" },
        { sentence: "Yesterday, we ___ the bus just in time.", answer: "got on", base: "get on", hint: "g_____", ja: "乗る、うまくやっていく", sentenceJa: "昨日、私たちはちょうど間に合ってバスに乗った。" },
        { sentence: "You can always ___ your family.", answer: "rely on", base: "rely on", hint: "r______", ja: "頼る", sentenceJa: "家族にはいつでも頼れる。" },
        { sentence: "I'm ___ my presentation for tomorrow.", answer: "working on", base: "work on", hint: "w______", ja: "取り組む", sentenceJa: "私は明日のプレゼンテーションに取り組んでいる。" },
        { sentence: "It's time to ___ from that mistake.", answer: "move on", base: "move on", hint: "m______", ja: "気持ちを切り替える、次に進む", sentenceJa: "その失敗から気持ちを切り替える時だ。" },
        { sentence: "Let's ___ the numbers more closely.", answer: "look at", base: "look at", hint: "l______", ja: "見る、検討する", sentenceJa: "その数字をもっと詳しく見てみましょう。" },
        { sentence: "Last night, we finally ___ a decision after hours of discussion.", answer: "arrived at", base: "arrive at", hint: "a________", ja: "到着する、（結論に）達する", sentenceJa: "昨夜、何時間も議論した末、私たちはついに結論に達した。" },
        { sentence: "You should ___ your doctor's advice.", answer: "listen to", base: "listen to", hint: "l________", ja: "耳を傾ける", sentenceJa: "医者の助言に耳を傾けるべきだ。" },
        { sentence: "I need to ___ my manager about this.", answer: "talk to", base: "talk to", hint: "t______", ja: "話しかける", sentenceJa: "この件について上司と話す必要がある。" },
        { sentence: "She ___ several local charities.", answer: "gives to", base: "give to", hint: "g______", ja: "（慈善などに）寄付する、与える", sentenceJa: "彼女はいくつかの地元の慈善団体に寄付をしている。" },
        { sentence: "It took weeks to ___ the flu.", answer: "recover from", base: "recover from", hint: "r___________", ja: "回復する", sentenceJa: "インフルエンザから回復するのに数週間かかった。" },
        { sentence: "Last spring, they ___ the small mountain town.", answer: "fell in love with", base: "fall in love with", hint: "f________________", ja: "恋に落ちる、大好きになる", sentenceJa: "去年の春、彼らはその小さな山の町に魅了された。" },
        { sentence: "We need to ___ this issue right away.", answer: "deal with", base: "deal with", hint: "d________", ja: "対処する", sentenceJa: "私たちはこの問題にすぐに対処する必要がある。" },
        { sentence: "I'm ___ my keys.", answer: "looking for", base: "look for", hint: "l_______", ja: "探す", sentenceJa: "私は鍵を探している。" },
        { sentence: "Yesterday, we ___ the bus in the rain.", answer: "waited for", base: "wait for", hint: "w_______", ja: "待つ", sentenceJa: "昨日、私たちは雨の中バスを待った。" },
      ],
    },
    {
      name: "Day 29",
      items: [
        { sentence: "Don't be afraid to ___ help.", answer: "ask for", base: "ask for", hint: "a______", ja: "求める、頼む", sentenceJa: "遠慮せずに助けを求めてください。" },
        { sentence: "I'll ___ dinner tonight.", answer: "pay for", base: "pay for", hint: "p______", ja: "代金を払う", sentenceJa: "今夜の夕食は私が払います。" },
        { sentence: "Feel free to ___ anytime.", answer: "drop by", base: "drop by", hint: "d______", ja: "ちょっと立ち寄る", sentenceJa: "いつでも気軽に立ち寄ってください。" },
        { sentence: "I'll ___ you no matter what happens.", answer: "stand by", base: "stand by", hint: "s_______", ja: "支持する、待機する", sentenceJa: "何があっても私はあなたを支えます。" },
        { sentence: "Yesterday, we ___ the old church on our walk.", answer: "passed by", base: "pass by", hint: "p______", ja: "通り過ぎる", sentenceJa: "昨日、散歩の途中、私たちはその古い教会を通り過ぎた。" },
        { sentence: "Yesterday, he ___ his phone to check the time.", answer: "took out", base: "take out", hint: "t_______", ja: "取り出す、連れ出す", sentenceJa: "昨日、彼は時間を確認するために携帯を取り出した。" },
        { sentence: "Last month, the truth finally ___ after the investigation.", answer: "came out", base: "come out", hint: "c_______", ja: "明らかになる、発売される", sentenceJa: "先月、調査の後、ついに真実が明らかになった。" },
        { sentence: "The party ___ better than we expected.", answer: "turned out", base: "turn out", hint: "t_______", ja: "結局〜になる、判明する", sentenceJa: "パーティーは予想していたよりも良い結果になった。" },
        { sentence: "You should ___ this new restaurant.", answer: "check out", base: "check out", hint: "c________", ja: "確認する、チェックアウトする", sentenceJa: "この新しいレストランを確認してみるといいよ。" },
        { sentence: "We're ___ for dinner this weekend.", answer: "going out", base: "go out", hint: "g_____", ja: "出かける", sentenceJa: "私たちは今週末、夕食に出かける予定だ。" },
        { sentence: "I need to ___ what time the store closes.", answer: "find out", base: "find out", hint: "f_______", ja: "知る、突き止める", sentenceJa: "その店が何時に閉まるか調べる必要がある。" },
        { sentence: "I ___ early this morning.", answer: "woke up", base: "wake up", hint: "w______", ja: "目が覚める", sentenceJa: "私は今朝早く目が覚めた。" },
        { sentence: "Can you ___ some milk on your way home?", answer: "pick up", base: "pick up", hint: "p______", ja: "拾う、迎えに行く、覚える", sentenceJa: "帰りに牛乳を買ってきてくれますか。" },
        { sentence: "Years ago, she ___ in a small town.", answer: "grew up", base: "grow up", hint: "g______", ja: "成長する、育つ", sentenceJa: "何年も前、彼女は小さな町で育った。" },
        { sentence: "He didn't ___ for the meeting.", answer: "show up", base: "show up", hint: "s______", ja: "現れる", sentenceJa: "彼は会議に現れなかった。" },
        { sentence: "Can you ___ the leftovers?", answer: "heat up", base: "heat up", hint: "h______", ja: "温める", sentenceJa: "残り物を温めてもらえますか。" },
        { sentence: "Last year, they ___ after two years together.", answer: "broke up", base: "break up", hint: "b_______", ja: "別れる、分裂する", sentenceJa: "去年、彼らは2年間付き合った後、別れた。" },
        { sentence: "I need to ___ on my reading.", answer: "catch up", base: "catch up", hint: "c_______", ja: "追いつく、近況を話す", sentenceJa: "読書の遅れを取り戻す必要がある。" },
        { sentence: "Don't ___ on your dreams.", answer: "give up", base: "give up", hint: "g______", ja: "あきらめる", sentenceJa: "夢をあきらめないで。" },
      ],
    },
    {
      name: "Day 30",
      items: [
        { sentence: "Last night, he ___ not to notice the mistake.", answer: "pretended", base: "pretend", hint: "p______", ja: "ふりをする", sentenceJa: "昨夜、彼はその間違いに気づかないふりをした。" },
        { sentence: "Please ___ the staples before recycling the paper.", answer: "remove", base: "remove", hint: "r_____", ja: "取り除く", sentenceJa: "紙をリサイクルする前にホチキスの針を取り除いてください。" },
        { sentence: "He couldn't ___ the constant noise from the construction site.", answer: "stand", base: "stand", hint: "s____", ja: "立つ、耐える", sentenceJa: "彼は工事現場からの絶え間ない騒音に耐えられなかった。" },
        { sentence: "Currently, this issue ___ everyone in the department.", answer: "concerns", base: "concern", hint: "c______", ja: "心配させる、関係する", sentenceJa: "現在、この問題は部署の全員に関係している。" },
        { sentence: "Last year, the committee finally ___ her contribution to the project.", answer: "recognized", base: "recognize", hint: "r________", ja: "認識する、見分ける、認める", sentenceJa: "昨年、委員会は最終的に彼女のプロジェクトへの貢献を認めた。" },
        { sentence: "Yesterday, workers ___ a trench for the new pipeline.", answer: "dug", base: "dig", hint: "d__", ja: "掘る", sentenceJa: "昨日、作業員たちは新しいパイプラインのために溝を掘った。" },
        { sentence: "Yesterday, rumors about the merger ___ quickly through the office.", answer: "spread", base: "spread", hint: "s_____", ja: "広げる、広がる", sentenceJa: "昨日、合併についての噂がオフィス中に素早く広まった。" },
        { sentence: "Please don't ___ the meeting in progress.", answer: "disturb", base: "disturb", hint: "d______", ja: "邪魔する", sentenceJa: "進行中の会議の邪魔をしないでください。" },
        { sentence: "Last week, the new manager ___ the crisis calmly.", answer: "handled", base: "handle", hint: "h_____", ja: "扱う、対処する、手を触れる", sentenceJa: "先週、新しいマネージャーはその危機に冷静に対処した。" },
        { sentence: "Yesterday, they ___ an entire day arguing over minor details.", answer: "wasted", base: "waste", hint: "w____", ja: "無駄にする", sentenceJa: "昨日、彼らは些細な事について言い争って丸一日を無駄にした。" },
        { sentence: "Could you ___ transportation for the visiting clients?", answer: "arrange", base: "arrange", hint: "a______", ja: "手配する、整える", sentenceJa: "訪問客のための交通手段を手配していただけますか？" },
        { sentence: "Investors increasingly ___ sustainable companies to fund.", answer: "seek", base: "seek", hint: "s___", ja: "探し求める", sentenceJa: "投資家はますます持続可能な企業への投資を求めている。" },
        { sentence: "This factory ___ parts to three major manufacturers.", answer: "supplies", base: "supply", hint: "s_____", ja: "供給する", sentenceJa: "この工場は3つの大手メーカーに部品を供給している。" },
        { sentence: "The inheritance was ___ equally among the siblings.", answer: "divided", base: "divide", hint: "d_____", ja: "分ける、割る", sentenceJa: "その遺産は兄弟姉妹の間で均等に分けられた。" },
        { sentence: "Yesterday, he ___ a note on the fridge before heading to work.", answer: "left", base: "leave", hint: "l____", ja: "去る、残す、置き忘れる", sentenceJa: "昨日、彼は仕事に行く前に冷蔵庫にメモを残した。" },
        { sentence: "The new employees always ___ the safety checklist.", answer: "follow", base: "follow", hint: "f_____", ja: "ついていく、従う", sentenceJa: "新入社員はいつも安全チェックリストに従う。" },
        { sentence: "The curtains were ___ to block the afternoon sun.", answer: "drawn", base: "draw", hint: "d___", ja: "描く、引く", sentenceJa: "午後の日差しを遮るためにカーテンが引かれた。" },
        { sentence: "The seminar will ___ advanced negotiation techniques.", answer: "cover", base: "cover", hint: "c____", ja: "覆う、（話題を）扱う", sentenceJa: "そのセミナーは高度な交渉術を扱う予定だ。" },
        { sentence: "Last year, early feedback from users ___ the final design.", answer: "shaped", base: "shape", hint: "s____", ja: "形作る", sentenceJa: "昨年、ユーザーからの初期のフィードバックが最終デザインを形作った。" },
        { sentence: "Ticket prices will ___ unchanged next season.", answer: "remain", base: "remain", hint: "r_____", ja: "とどまる、～のままである、残る", sentenceJa: "チケット価格は来シーズンも変わらない予定だ。" },
      ],
    },
  ],
};
