// TOEIC 単語テスト問題（9月「1ヶ月分」、osh-vocab-test/data/*.pyから自動生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
// Day7/14/21/28は復習日のため欠番
module.exports = {
  label: "TOEIC",
  series: [
    {
      name: "Day 1",
      items: [
        { sentence: "Last week, the magazine ___ an article about local businesses.", answer: "published", base: "publish", hint: "p______", ja: "出版する、公表する", sentenceJa: "先週、その雑誌は地元企業についての記事を掲載した。" },
        { sentence: "Yesterday, she ___ a photo with her letter.", answer: "enclosed", base: "enclose", hint: "e______", ja: "同封する", sentenceJa: "昨日、彼女は手紙に写真を同封した。" },
        { sentence: "We will ___ you as soon as your order ships.", answer: "notify", base: "notify", hint: "n_____", ja: "通知する", sentenceJa: "ご注文の発送準備が整い次第、ご連絡いたします。" },
        { sentence: "Last month, he ___ permission to enter the building.", answer: "obtained", base: "obtain", hint: "o_____", ja: "入手する、得る", sentenceJa: "先月、彼はその建物に入る許可を得た。" },
        { sentence: "The manager decided to ___ the meeting until Friday.", answer: "postpone", base: "postpone", hint: "p_______", ja: "延期する", sentenceJa: "マネージャーは会議を金曜日まで延期することにした。" },
        { sentence: "Every night, the last bus ___ at 11 p.m.", answer: "departs", base: "depart", hint: "d_____", ja: "出発する", sentenceJa: "毎晩、最終バスは午後11時に出発する。" },
        { sentence: "She ___ her passport last month.", answer: "renewed", base: "renew", hint: "r____", ja: "更新する", sentenceJa: "彼女は先月パスポートを更新した。" },
        { sentence: "Currently, this coupon ___ at the end of the week.", answer: "expires", base: "expire", hint: "e_____", ja: "期限が切れる", sentenceJa: "現在、このクーポンは今週末に期限が切れる。" },
        { sentence: "A technician will ___ the equipment tomorrow.", answer: "inspect", base: "inspect", hint: "i______", ja: "検査する", sentenceJa: "明日、技術者が設備を点検する予定です。" },
        { sentence: "Yesterday, a customer ___ about the refund policy.", answer: "inquired", base: "inquire", hint: "i______", ja: "問い合わせる", sentenceJa: "昨日、ある顧客が返金ポリシーについて問い合わせた。" },
        { sentence: "Currently, company rules ___ the use of phones during meetings.", answer: "prohibit", base: "prohibit", hint: "p_______", ja: "禁止する", sentenceJa: "現在、会社の規則で会議中の携帯電話の使用は禁止されている。" },
        { sentence: "The manager ___ all new employees during training.", answer: "supervises", base: "supervise", hint: "s________", ja: "監督する", sentenceJa: "マネージャーは研修中の新入社員全員を監督している。" },
        { sentence: "Many readers ___ to our weekly newsletter.", answer: "subscribe", base: "subscribe", hint: "s________", ja: "定期購読する、加入する", sentenceJa: "多くの読者が私たちの週刊ニュースレターを定期購読している。" },
        { sentence: "Last week, the manager ___ the extra budget for the project.", answer: "authorized", base: "authorize", hint: "a________", ja: "許可する、承認する", sentenceJa: "先週、マネージャーはそのプロジェクトの追加予算を承認した。" },
        { sentence: "Currently, the new hotel ___ up to 500 guests.", answer: "accommodates", base: "accommodate", hint: "a__________", ja: "収容する、対応する", sentenceJa: "現在、その新しいホテルは最大500人の宿泊客を収容できる。" },
        { sentence: "He ___ to the office by train every day.", answer: "commutes", base: "commute", hint: "c______", ja: "通勤する", sentenceJa: "彼は毎日電車でオフィスに通勤している。" },
        { sentence: "The firm plans to ___ its head office next year.", answer: "relocate", base: "relocate", hint: "r_______", ja: "移転する", sentenceJa: "その会社は来年、本社を移転する計画だ。" },
        { sentence: "Yesterday, the technician ___ that the system was working correctly.", answer: "verified", base: "verify", hint: "v_____", ja: "確認する、検証する", sentenceJa: "昨日、技術者はシステムが正常に動作していることを確認した。" },
        { sentence: "Could you ___ your reservation by Friday?", answer: "confirm", base: "confirm", hint: "c______", ja: "確認する、確定する", sentenceJa: "金曜日までにご予約を確認していただけますか？" },
        { sentence: "Hundreds of students ___ in the program each year.", answer: "enroll", base: "enroll", hint: "e_____", ja: "登録する、入会する", sentenceJa: "毎年何百人もの学生がこのプログラムに登録している。" },
      ],
    },
    {
      name: "Day 2",
      items: [
        { sentence: "Workers ___ the furniture before it is shipped.", answer: "assemble", base: "assemble", hint: "a_______", ja: "組み立てる、集める", sentenceJa: "作業員は発送する前に家具を組み立てる。" },
        { sentence: "She will ___ the schedules of all the departments.", answer: "coordinate", base: "coordinate", hint: "c_________", ja: "調整する、まとめる", sentenceJa: "彼女は全部署のスケジュールを調整する予定だ。" },
        { sentence: "The company will ___ a new area for parking.", answer: "designate", base: "designate", hint: "d________", ja: "指定する、任命する", sentenceJa: "その会社は駐車場のための新しいエリアを指定する予定だ。" },
        { sentence: "Volunteers will ___ brochures at the entrance.", answer: "distribute", base: "distribute", hint: "d_________", ja: "配布する、流通させる", sentenceJa: "ボランティアが入口でパンフレットを配布する予定だ。" },
        { sentence: "The company will ___ you for travel costs.", answer: "reimburse", base: "reimburse", hint: "r________", ja: "払い戻す、精算する", sentenceJa: "その会社はあなたに旅費を払い戻す予定だ。" },
        { sentence: "It may take a few days to ___ your refund.", answer: "process", base: "process", hint: "p______", ja: "処理する", sentenceJa: "返金の処理には数日かかる場合があります。" },
        { sentence: "The new software will ___ online ordering.", answer: "facilitate", base: "facilitate", hint: "f_________", ja: "促進する、容易にする", sentenceJa: "新しいソフトウェアがオンライン注文を容易にする。" },
        { sentence: "All factories must ___ with safety regulations.", answer: "comply", base: "comply", hint: "c_____", ja: "（規則に）従う", sentenceJa: "すべての工場は安全規則に従わなければならない。" },
        { sentence: "Managers ___ the performance of each employee yearly.", answer: "assess", base: "assess", hint: "a_____", ja: "評価する、査定する", sentenceJa: "マネージャーは毎年各従業員の業績を評価する。" },
        { sentence: "The firm will ___ a survey of its customers.", answer: "conduct", base: "conduct", hint: "c______", ja: "（業務などを）行う", sentenceJa: "その会社は顧客への調査を実施する予定だ。" },
        { sentence: "A technician came to ___ the new printer.", answer: "install", base: "install", hint: "i______", ja: "設置する、導入する", sentenceJa: "技術者が新しいプリンターを設置しに来た。" },
        { sentence: "Please ___ your report by the end of the day.", answer: "submit", base: "submit", hint: "s_____", ja: "提出する", sentenceJa: "今日中にレポートを提出してください。" },
        { sentence: "You can ___ tickets at the front counter.", answer: "purchase", base: "purchase", hint: "p_______", ja: "購入する", sentenceJa: "フロントカウンターでチケットを購入できます。" },
        { sentence: "The manager will ___ the terms of the contract.", answer: "negotiate", base: "negotiate", hint: "n________", ja: "交渉する", sentenceJa: "マネージャーが契約条件について交渉する予定だ。" },
        { sentence: "The company is trying to ___ skilled engineers.", answer: "recruit", base: "recruit", hint: "r______", ja: "採用する、募集する", sentenceJa: "その会社は熟練したエンジニアを採用しようとしている。" },
        { sentence: "Last week, the builder ___ the cost of the repairs.", answer: "estimated", base: "estimate", hint: "e_______", ja: "見積もる", sentenceJa: "先週、建築業者は修理費用を見積もった。" },
        { sentence: "Only trained staff may ___ this machine.", answer: "operate", base: "operate", hint: "o______", ja: "操作する、運営する", sentenceJa: "訓練を受けたスタッフだけがこの機械を操作できる。" },
        { sentence: "The store will ___ its sale on social media.", answer: "promote", base: "promote", hint: "p______", ja: "昇進させる、宣伝する", sentenceJa: "その店はSNSでセールを宣伝する予定だ。" },
        { sentence: "The board must ___ the new budget.", answer: "approve", base: "approve", hint: "a______", ja: "承認する", sentenceJa: "取締役会は新しい予算を承認しなければならない。" },
        { sentence: "All managers must ___ the monthly meeting.", answer: "attend", base: "attend", hint: "a_____", ja: "出席する", sentenceJa: "すべてのマネージャーは月例会議に出席しなければならない。" },
      ],
    },
    {
      name: "Day 3",
      items: [
        { sentence: "She is taking a two-week ___ in July.", answer: "vacation", base: "vacation", hint: "v_______", ja: "休暇", sentenceJa: "彼女は7月に2週間の休暇を取る予定だ。" },
        { sentence: "Our biggest ___ signed a new contract today.", answer: "client", base: "client", hint: "c_____", ja: "顧客、依頼人", sentenceJa: "今日、私たちの最大の顧客が新しい契約に署名した。" },
        { sentence: "I made a ___ for four at the restaurant.", answer: "reservation", base: "reservation", hint: "r__________", ja: "予約", sentenceJa: "私はそのレストランで4人分の予約をした。" },
        { sentence: "Ask your ___ before changing the schedule.", answer: "supervisor", base: "supervisor", hint: "s_________", ja: "上司、監督者", sentenceJa: "予定を変更する前に上司に確認してください。" },
        { sentence: "Customers can request a full ___ within 30 days.", answer: "refund", base: "refund", hint: "r_____", ja: "返金", sentenceJa: "顧客は30日以内であれば全額返金を請求できる。" },
        { sentence: "We must finish the project before the ___.", answer: "deadline", base: "deadline", hint: "d_______", ja: "締め切り", sentenceJa: "私たちは締め切り前にプロジェクトを終わらせなければならない。" },
        { sentence: "The supplier sent an ___ for last month's order.", answer: "invoice", base: "invoice", hint: "i______", ja: "請求書", sentenceJa: "仕入先は先月分の注文の請求書を送ってきた。" },
        { sentence: "Pick up a ___ for details about the tour.", answer: "brochure", base: "brochure", hint: "b_______", ja: "パンフレット", sentenceJa: "ツアーの詳細はパンフレットを手に取ってご覧ください。" },
        { sentence: "Each ___ must attend an interview.", answer: "applicant", base: "applicant", hint: "a________", ja: "応募者", sentenceJa: "各応募者は面接を受けなければならない。" },
        { sentence: "Keep your ___ in case you return the item.", answer: "receipt", base: "receipt", hint: "r______", ja: "領収書", sentenceJa: "商品を返品する場合に備えてレシートを保管しておいてください。" },
        { sentence: "The ___ of supplies arrived this morning.", answer: "shipment", base: "shipment", hint: "s_______", ja: "発送、出荷", sentenceJa: "今朝、物資の発送が届いた。" },
        { sentence: "This laptop comes with a two-year ___.", answer: "warranty", base: "warranty", hint: "w_______", ja: "保証（書）", sentenceJa: "このノートパソコンには2年間の保証が付いている。" },
        { sentence: "The staff check the ___ every month.", answer: "inventory", base: "inventory", hint: "i________", ja: "在庫（品）", sentenceJa: "スタッフは毎月在庫を確認する。" },
        { sentence: "She attended a marketing ___ last week.", answer: "seminar", base: "seminar", hint: "s______", ja: "研修会", sentenceJa: "彼女は先週マーケティングのセミナーに参加した。" },
        { sentence: "The hotel is a popular ___ for conferences.", answer: "venue", base: "venue", hint: "v____", ja: "会場", sentenceJa: "そのホテルは会議の会場として人気がある。" },
        { sentence: "The ___ of the two firms was announced today.", answer: "merger", base: "merger", hint: "m_____", ja: "合併", sentenceJa: "今日、2社の合併が発表された。" },
        { sentence: "The travel agent emailed us the ___.", answer: "itinerary", base: "itinerary", hint: "i________", ja: "旅程（表）", sentenceJa: "旅行代理店が私たちに旅程表をメールで送ってきた。" },
        { sentence: "He earned extra pay for working ___.", answer: "overtime", base: "overtime", hint: "o_______", ja: "残業", sentenceJa: "彼は残業をして追加の給料を得た。" },
        { sentence: "We welcome your ___ on our new service.", answer: "feedback", base: "feedback", hint: "f_______", ja: "意見", sentenceJa: "私たちの新しいサービスについてのご意見をお待ちしています。" },
        { sentence: "All travel ___ will be paid by the company.", answer: "expenses", base: "expense", hint: "e______", ja: "費用、経費", sentenceJa: "すべての旅費は会社が負担します。" },
      ],
    },
    {
      name: "Day 4",
      items: [
        { sentence: "The first item on the ___ is the budget review.", answer: "agenda", base: "agenda", hint: "a_____", ja: "議題", sentenceJa: "議題の最初の項目は予算の見直しだ。" },
        { sentence: "The team went over its ___ last quarter.", answer: "budget", base: "budget", hint: "b_____", ja: "予算", sentenceJa: "チームは前四半期に予算を超過した。" },
        { sentence: "She had lunch with two ___ from her team.", answer: "colleagues", base: "colleague", hint: "c________", ja: "同僚", sentenceJa: "彼女はチームの同僚2人と昼食を食べた。" },
        { sentence: "Both companies signed the ___ yesterday.", answer: "contract", base: "contract", hint: "c_______", ja: "契約（書）", sentenceJa: "両社は昨日その契約書に署名した。" },
        { sentence: "He works in the accounting ___.", answer: "department", base: "department", hint: "d_________", ja: "部署、部門", sentenceJa: "彼は経理部門で働いている。" },
        { sentence: "The gym bought new ___ this year.", answer: "equipment", base: "equipment", hint: "e________", ja: "機器、設備", sentenceJa: "そのジムは今年、新しい機器を購入した。" },
        { sentence: "The new sports ___ has a pool and a gym.", answer: "facility", base: "facility", hint: "f_______", ja: "施設、設備", sentenceJa: "新しいスポーツ施設にはプールとジムがある。" },
        { sentence: "The company's ___ is in Chicago.", answer: "headquarters", base: "headquarters", hint: "h___________", ja: "本社、本部", sentenceJa: "その会社の本社はシカゴにある。" },
        { sentence: "The store sells every kitchen ___ you need.", answer: "appliance", base: "appliance", hint: "a________", ja: "家電製品", sentenceJa: "その店には必要な台所用家電製品が何でも揃っている。" },
        { sentence: "We received a ___ about the late delivery.", answer: "complaint", base: "complaint", hint: "c________", ja: "苦情", sentenceJa: "配達の遅れについて苦情を受けた。" },
        { sentence: "Every ___ gets ten days of paid leave.", answer: "employee", base: "employee", hint: "e_______", ja: "従業員", sentenceJa: "すべての従業員は10日間の有給休暇を取得できる。" },
        { sentence: "This job is a great ___ to learn new skills.", answer: "opportunity", base: "opportunity", hint: "o__________", ja: "機会", sentenceJa: "この仕事は新しいスキルを学ぶ絶好の機会だ。" },
        { sentence: "The new train ___ starts next month.", answer: "schedule", base: "schedule", hint: "s_______", ja: "予定", sentenceJa: "新しい電車の時刻表は来月から始まる。" },
        { sentence: "Our bank opened a new ___ downtown.", answer: "branch", base: "branch", hint: "b_____", ja: "支店", sentenceJa: "私たちの銀行は繁華街に新しい支店を開いた。" },
        { sentence: "Free ___ is available for orders over $50.", answer: "delivery", base: "delivery", hint: "d_______", ja: "配達", sentenceJa: "50   ドルを超える注文には無料配達が利用できる。" },
        { sentence: "The job offers a good ___ and benefits.", answer: "salary", base: "salary", hint: "s_____", ja: "給料", sentenceJa: "その仕事は良い給料と福利厚生を提供している。" },
        { sentence: "We found a cheaper ___ for the materials.", answer: "supplier", base: "supplier", hint: "s_______", ja: "供給業者、仕入先", sentenceJa: "私たちは材料のより安い仕入先を見つけた。" },
        { sentence: "___ for the workshop closes on Friday.", answer: "registration", base: "registration", hint: "r___________", ja: "登録", sentenceJa: "研修会の登録は金曜日で締め切られる。" },
        { sentence: "You need a ___ to park in this area.", answer: "permit", base: "permit", hint: "p_____", ja: "許可証", sentenceJa: "このエリアに駐車するには許可証が必要だ。" },
        { sentence: "The company sent a ___ for the repair work.", answer: "quotation", base: "quotation", hint: "q________", ja: "見積もり", sentenceJa: "その会社は修理作業の見積もりを送ってきた。" },
      ],
    },
    {
      name: "Day 5",
      items: [
        { sentence: "Her explanation was clear and ___.", answer: "logical", base: "logical", hint: "l______", ja: "論理的な", sentenceJa: "彼女の説明は明確で論理的だった。" },
        { sentence: "The station is in a very ___ location.", answer: "convenient", base: "convenient", hint: "c_________", ja: "便利な", sentenceJa: "その駅はとても便利な場所にある。" },
        { sentence: "Your ticket is ___ for one month.", answer: "valid", base: "valid", hint: "v____", ja: "有効な", sentenceJa: "あなたのチケットは1ヶ月間有効です。" },
        { sentence: "Full-time staff are ___ for the bonus.", answer: "eligible", base: "eligible", hint: "e_______", ja: "資格のある", sentenceJa: "正社員はボーナスの対象資格がある。" },
        { sentence: "She received an award for her ___ work.", answer: "outstanding", base: "outstanding", hint: "o__________", ja: "傑出した、未払いの", sentenceJa: "彼女は傑出した仕事で賞を受賞した。" },
        { sentence: "Safety training is ___ for all new staff.", answer: "mandatory", base: "mandatory", hint: "m________", ja: "義務的な、必須の", sentenceJa: "安全研修は全ての新入社員に義務付けられている。" },
        { sentence: "These boots are strong and ___.", answer: "durable", base: "durable", hint: "d______", ja: "耐久性のある、丈夫な", sentenceJa: "このブーツは丈夫で耐久性がある。" },
        { sentence: "The store offers stylish but ___ clothes.", answer: "affordable", base: "affordable", hint: "a_________", ja: "手頃な価格の", sentenceJa: "その店はおしゃれで手頃な価格の服を提供している。" },
        { sentence: "All medical records are kept ___.", answer: "confidential", base: "confidential", hint: "c___________", ja: "機密の", sentenceJa: "すべての医療記録は機密として保管されている。" },
        { sentence: "Please reply soon; this is an ___ matter.", answer: "urgent", base: "urgent", hint: "u_____", ja: "緊急の", sentenceJa: "至急ご返信ください。緊急の件です。" },
        { sentence: "They hired some ___ staff for the holidays.", answer: "temporary", base: "temporary", hint: "t________", ja: "一時的な", sentenceJa: "彼らは休暇シーズンのために一時的なスタッフを雇った。" },
        { sentence: "The new system is faster and more ___.", answer: "efficient", base: "efficient", hint: "e________", ja: "効率的な", sentenceJa: "新しいシステムはより速く、効率的だ。" },
        { sentence: "We need a ___ supplier for our parts.", answer: "reliable", base: "reliable", hint: "r_______", ja: "信頼できる", sentenceJa: "私たちは部品の信頼できる供給業者が必要だ。" },
        { sentence: "The hotel offers a ___ breakfast.", answer: "complimentary", base: "complimentary", hint: "c____________", ja: "無料の", sentenceJa: "そのホテルは無料の朝食を提供している。" },
        { sentence: "Attendance at the evening session is ___.", answer: "optional", base: "optional", hint: "o_______", ja: "任意の、選択できる", sentenceJa: "夜のセッションへの出席は任意です。" },
        { sentence: "The new office is bright and ___.", answer: "spacious", base: "spacious", hint: "s_______", ja: "広々とした", sentenceJa: "新しいオフィスは明るくて広々としている。" },
        { sentence: "The agent showed the house to several ___ buyers.", answer: "prospective", base: "prospective", hint: "p__________", ja: "見込みのある、将来の", sentenceJa: "不動産業者は何人かの見込み客にその家を見せた。" },
        { sentence: "The building is ___ to wheelchair users.", answer: "accessible", base: "accessible", hint: "a_________", ja: "利用しやすい、行きやすい", sentenceJa: "その建物は車椅子利用者にとって利用しやすい。" },
        { sentence: "The shop offers ___ prices on electronics.", answer: "competitive", base: "competitive", hint: "c__________", ja: "競争力のある", sentenceJa: "その店は電化製品で競争力のある価格を提供している。" },
        { sentence: "Our company offers ___ working hours.", answer: "flexible", base: "flexible", hint: "f_______", ja: "柔軟な", sentenceJa: "私たちの会社は柔軟な勤務時間を提供している。" },
      ],
    },
    {
      name: "Day 6",
      items: [
        { sentence: "We ___ apologize for the delay in shipping.", answer: "sincerely", base: "sincerely", hint: "s________", ja: "心から、敬具", sentenceJa: "私たちは配送の遅れについて心よりお詫び申し上げます。" },
        { sentence: "Please make sure the form is filled out ___.", answer: "correctly", base: "correctly", hint: "c________", ja: "正しく", sentenceJa: "フォームが正しく記入されているか確認してください。" },
        { sentence: "The technician responded ___ to our request.", answer: "promptly", base: "promptly", hint: "p_______", ja: "迅速に、時間通りに", sentenceJa: "その技術者は私たちの依頼に迅速に対応した。" },
        { sentence: "The manager will be with you ___.", answer: "shortly", base: "shortly", hint: "s______", ja: "まもなく", sentenceJa: "マネージャーがまもなく参ります。" },
        { sentence: "The report ___ reflects last quarter's sales.", answer: "accurately", base: "accurately", hint: "a_________", ja: "正確に", sentenceJa: "その報告書は前四半期の売上を正確に反映している。" },
        { sentence: "This software is ___ used in accounting departments.", answer: "commonly", base: "commonly", hint: "c_______", ja: "一般的に", sentenceJa: "このソフトウェアは経理部門で一般的に使われている。" },
        { sentence: "Please review the contract ___ before signing.", answer: "thoroughly", base: "thoroughly", hint: "t_________", ja: "徹底的に", sentenceJa: "署名する前に契約書を徹底的に確認してください。" },
        { sentence: "The conference is held ___ in Chicago.", answer: "annually", base: "annually", hint: "a_______", ja: "毎年", sentenceJa: "その会議はシカゴで毎年開催される。" },
        { sentence: "Sales dropped, so we adjusted the budget ___.", answer: "accordingly", base: "accordingly", hint: "a__________", ja: "それに応じて", sentenceJa: "売上が落ちたので、それに応じて予算を調整した。" },
        { sentence: "You can pay online, or ___, visit our office.", answer: "alternatively", base: "alternatively", hint: "a____________", ja: "あるいは、その代わりに", sentenceJa: "オンラインで支払うか、あるいは事務所に来ていただくこともできます。" },
        { sentence: "The team has ___ met its monthly targets.", answer: "consistently", base: "consistently", hint: "c___________", ja: "一貫して", sentenceJa: "そのチームは月ごとの目標を一貫して達成している。" },
        { sentence: "Please invoice the two orders ___.", answer: "separately", base: "separately", hint: "s_________", ja: "別々に", sentenceJa: "2つの注文は別々に請求してください。" },
        { sentence: "All our vegetables are sourced ___.", answer: "locally", base: "locally", hint: "l______", ja: "地元で", sentenceJa: "私たちの野菜はすべて地元で仕入れています。" },
        { sentence: "The merger was ___ announced this morning.", answer: "formally", base: "formally", hint: "f_______", ja: "正式に", sentenceJa: "その合併は今朝正式に発表された。" },
        { sentence: "Make sure the workload is divided ___ among the team.", answer: "evenly", base: "evenly", hint: "e_____", ja: "均等に", sentenceJa: "作業量がチームに均等に分配されるようにしてください。" },
        { sentence: "Fuel prices rose ___ last month.", answer: "sharply", base: "sharply", hint: "s______", ja: "急激に", sentenceJa: "先月、燃料価格が急激に上昇した。" },
        { sentence: "All complaints should be handled ___.", answer: "professionally", base: "professionally", hint: "p_____________", ja: "プロらしく、専門的に", sentenceJa: "苦情はすべてプロらしく対応されるべきだ。" },
        { sentence: "The transition to the new system went ___.", answer: "smoothly", base: "smoothly", hint: "s_______", ja: "円滑に", sentenceJa: "新システムへの移行は円滑に進んだ。" },
        { sentence: "Membership numbers have grown ___ this year.", answer: "steadily", base: "steadily", hint: "s_______", ja: "着実に", sentenceJa: "今年、会員数は着実に増加している。" },
        { sentence: "___, the presentation could have been shorter.", answer: "honestly", base: "honestly", hint: "h_______", ja: "正直に言って", sentenceJa: "正直に言うと、そのプレゼンはもっと短くてもよかった。" },
      ],
    },
    {
      name: "Day 8",
      items: [
        { sentence: "We need to ___ the contract by Friday.", answer: "finalize", base: "finalize", hint: "f_______", ja: "最終決定する", sentenceJa: "金曜日までに契約を最終決定する必要がある。" },
        { sentence: "Last month, the manager ___ staff to update their passwords.", answer: "instructed", base: "instruct", hint: "i_______", ja: "指示する、指導する", sentenceJa: "先月、マネージャーはスタッフにパスワードを更新するよう指示した。" },
        { sentence: "All departments are expected to ___ on the new policy.", answer: "cooperate", base: "cooperate", hint: "c________", ja: "協力する", sentenceJa: "すべての部署がこの新方針について協力することが求められている。" },
        { sentence: "The airline agreed to ___ passengers for the delay.", answer: "compensate", base: "compensate", hint: "c_________", ja: "補償する", sentenceJa: "その航空会社は遅延について乗客に補償することに同意した。" },
        { sentence: "The new software ___ the ordering process.", answer: "simplifies", base: "simplify", hint: "s_______", ja: "簡素化する", sentenceJa: "その新しいソフトウェアは注文プロセスを簡素化している。" },
        { sentence: "She was ___ for Employee of the Year.", answer: "nominated", base: "nominate", hint: "n_______", ja: "指名する、推薦する", sentenceJa: "彼女は今年の従業員賞に推薦された。" },
        { sentence: "The two companies plan to ___ next year.", answer: "merge", base: "merge", hint: "m____", ja: "合併する", sentenceJa: "その2社は来年合併する予定だ。" },
        { sentence: "The contract can be ___ with 30 days' notice.", answer: "terminated", base: "terminate", hint: "t________", ja: "終了する、解除する", sentenceJa: "その契約は30日前の通知で解除できる。" },
        { sentence: "The team worked overtime to ___ the issue.", answer: "resolve", base: "resolve", hint: "r______", ja: "解決する", sentenceJa: "そのチームは問題を解決するために残業した。" },
        { sentence: "We ___ customer feedback closely.", answer: "monitor", base: "monitor", hint: "m______", ja: "監視する", sentenceJa: "私たちは顧客の声を注意深く監視している。" },
        { sentence: "The new system ___ the approval process.", answer: "streamlines", base: "streamline", hint: "s_________", ja: "効率化する", sentenceJa: "その新しいシステムは承認プロセスを効率化している。" },
        { sentence: "The budget was ___ to three main projects.", answer: "allocated", base: "allocate", hint: "a_______", ja: "割り当てる", sentenceJa: "予算は3つの主要プロジェクトに割り当てられた。" },
        { sentence: "You can ___ the report to fit your needs.", answer: "customize", base: "customize", hint: "c________", ja: "カスタマイズする", sentenceJa: "レポートはニーズに合わせてカスタマイズできる。" },
        { sentence: "Yesterday, the technician ___ the problem quickly.", answer: "diagnosed", base: "diagnose", hint: "d_______", ja: "診断する", sentenceJa: "昨日、その技術者は問題を素早く診断した。" },
        { sentence: "The company will ___ this product line.", answer: "discontinue", base: "discontinue", hint: "d__________", ja: "中止する、廃止する", sentenceJa: "その会社はこの製品ラインを廃止する予定だ。" },
        { sentence: "Could you ___ what you mean by that?", answer: "clarify", base: "clarify", hint: "c______", ja: "明確にする", sentenceJa: "それがどういう意味か明確にしていただけますか。" },
        { sentence: "Last week, she ___ the data into a single report.", answer: "compiled", base: "compile", hint: "c______", ja: "まとめる、編集する", sentenceJa: "先週、彼女はデータを1つの報告書にまとめた。" },
        { sentence: "The HR department ___ employee benefits.", answer: "administers", base: "administer", hint: "a_________", ja: "管理する、運営する", sentenceJa: "人事部は従業員の福利厚生を管理している。" },
        { sentence: "A good manager knows how to ___ tasks.", answer: "delegate", base: "delegate", hint: "d_______", ja: "委任する", sentenceJa: "優れたマネージャーは仕事を委任する方法を知っている。" },
        { sentence: "We took steps to ___ the risk of delays.", answer: "minimize", base: "minimize", hint: "m_______", ja: "最小限にする", sentenceJa: "私たちは遅延のリスクを最小限にするための対策を取った。" },
      ],
    },
    {
      name: "Day 9",
      items: [
        { sentence: "The meeting was ___ to next Tuesday.", answer: "rescheduled", base: "reschedule", hint: "r_________", ja: "予定を変更する", sentenceJa: "会議は来週の火曜日に予定変更された。" },
        { sentence: "We plan to ___ our computer systems this fall.", answer: "upgrade", base: "upgrade", hint: "u______", ja: "アップグレードする", sentenceJa: "私たちはこの秋、コンピュータシステムをアップグレードする予定だ。" },
        { sentence: "You can ___ the manual from our website.", answer: "download", base: "download", hint: "d_______", ja: "ダウンロードする", sentenceJa: "マニュアルは弊社ウェブサイトからダウンロードできます。" },
        { sentence: "Last month, she ___ her job to start her own business.", answer: "quit", base: "quit", hint: "q___", ja: "辞める", sentenceJa: "先月、彼女は自分のビジネスを始めるために仕事を辞めた。" },
        { sentence: "This restaurant ___ to large corporate events.", answer: "caters", base: "cater", hint: "c____", ja: "料理を提供する、対応する", sentenceJa: "このレストランは大規模な企業イベントに対応している。" },
        { sentence: "Please ___ the total cost including tax.", answer: "calculate", base: "calculate", hint: "c________", ja: "計算する", sentenceJa: "税込みの合計金額を計算してください。" },
        { sentence: "Don't ___ any required fields on the form.", answer: "omit", base: "omit", hint: "o___", ja: "省略する", sentenceJa: "フォームの必須項目を省略しないでください。" },
        { sentence: "Yesterday, he accidentally ___ an important file.", answer: "deleted", base: "delete", hint: "d_____", ja: "削除する", sentenceJa: "昨日、彼はうっかり重要なファイルを削除してしまった。" },
        { sentence: "Yesterday, the CEO ___ the team on its success.", answer: "congratulated", base: "congratulate", hint: "c___________", ja: "祝う", sentenceJa: "昨日、CEOはチームの成功を祝った。" },
        { sentence: "The apartment comes fully ___.", answer: "furnished", base: "furnish", hint: "f______", ja: "家具を備え付ける、供給する", sentenceJa: "そのアパートは家具付きで提供される。" },
        { sentence: "The manual has been ___ into five languages.", answer: "translated", base: "translate", hint: "t________", ja: "翻訳する", sentenceJa: "そのマニュアルは5か国語に翻訳されている。" },
        { sentence: "Last year, the company ___ several safety regulations.", answer: "violated", base: "violate", hint: "v______", ja: "違反する", sentenceJa: "去年、その会社はいくつかの安全規則に違反した。" },
        { sentence: "The company plans to ___ into new markets.", answer: "expand", base: "expand", hint: "e_____", ja: "拡大する", sentenceJa: "その会社は新市場への拡大を計画している。" },
        { sentence: "The hotel will be ___ next spring.", answer: "renovated", base: "renovate", hint: "r_______", ja: "改装する", sentenceJa: "そのホテルは来春改装される予定だ。" },
        { sentence: "She was ___ to the Tokyo office.", answer: "transferred", base: "transfer", hint: "t_______", ja: "転勤する、移す", sentenceJa: "彼女は東京オフィスに転勤になった。" },
        { sentence: "The bank agreed to ___ the late fee.", answer: "waive", base: "waive", hint: "w____", ja: "免除する", sentenceJa: "銀行は延滞料金を免除することに同意した。" },
        { sentence: "Please ___ the proposal based on our feedback.", answer: "revise", base: "revise", hint: "r_____", ja: "改訂する", sentenceJa: "私たちのフィードバックをもとに提案書を改訂してください。" },
        { sentence: "Yesterday, he ___ a reply to the client's email.", answer: "drafted", base: "draft", hint: "d____", ja: "下書きする", sentenceJa: "昨日、彼はクライアントのメールへの返信を下書きした。" },
        { sentence: "An outside firm will ___ our accounts this year.", answer: "audit", base: "audit", hint: "a____", ja: "監査する", sentenceJa: "外部の会社が今年、私たちの会計を監査する。" },
        { sentence: "The company decided to ___ its IT support.", answer: "outsource", base: "outsource", hint: "o________", ja: "外部委託する", sentenceJa: "その会社はITサポートを外部委託することにした。" },
      ],
    },
    {
      name: "Day 10",
      items: [
        { sentence: "Please read the ___ before the meeting.", answer: "memo", base: "memo", hint: "m___", ja: "覚え書き、メモ", sentenceJa: "会議の前にそのメモを読んでください。" },
        { sentence: "All new hires attend a two-day ___.", answer: "workshop", base: "workshop", hint: "w_______", ja: "研修会", sentenceJa: "新入社員は全員、2日間の研修会に参加する。" },
        { sentence: "Our ___ prepares the monthly financial reports.", answer: "accountant", base: "accountant", hint: "a_________", ja: "会計士", sentenceJa: "私たちの会計士は毎月の財務報告書を作成している。" },
        { sentence: "A ___ will repair the printer this afternoon.", answer: "technician", base: "technician", hint: "t_________", ja: "技術者", sentenceJa: "技術者が今日の午後、プリンターを修理する予定だ。" },
        { sentence: "The ___ on our office expires next month.", answer: "lease", base: "lease", hint: "l____", ja: "賃貸契約", sentenceJa: "私たちのオフィスの賃貸契約は来月切れる。" },
        { sentence: "The company offers an annual ___ to the service.", answer: "subscription", base: "subscription", hint: "s___________", ja: "定期購読、サブスクリプション", sentenceJa: "その会社はそのサービスの年間サブスクリプションを提供している。" },
        { sentence: "Ask the ___ for a visitor badge.", answer: "receptionist", base: "receptionist", hint: "r___________", ja: "受付係", sentenceJa: "来訪者用バッジは受付係に尋ねてください。" },
        { sentence: "Please bring your ___ for the business trip.", answer: "passport", base: "passport", hint: "p_______", ja: "パスポート", sentenceJa: "出張のためにパスポートを持ってきてください。" },
        { sentence: "The files are stored in the ___ by the window.", answer: "cabinet", base: "cabinet", hint: "c______", ja: "戸棚", sentenceJa: "ファイルは窓際のキャビネットに保管されている。" },
        { sentence: "Each employee is issued a company ___.", answer: "laptop", base: "laptop", hint: "l_____", ja: "ノートパソコン", sentenceJa: "各従業員に会社のノートパソコンが支給される。" },
        { sentence: "She completed the ___ ahead of schedule.", answer: "assignment", base: "assignment", hint: "a_________", ja: "任務、課題", sentenceJa: "彼女はその課題を予定より早く完了させた。" },
        { sentence: "The goods are stored in a ___ outside the city.", answer: "warehouse", base: "warehouse", hint: "w________", ja: "倉庫", sentenceJa: "その商品は市外の倉庫に保管されている。" },
        { sentence: "___ will be provided during the conference.", answer: "beverages", base: "beverage", hint: "b_______", ja: "飲み物", sentenceJa: "会議中は飲み物が提供されます。" },
        { sentence: "The ___ found a problem with the engine.", answer: "mechanic", base: "mechanic", hint: "m_______", ja: "整備士", sentenceJa: "整備士はエンジンの不具合を発見した。" },
        { sentence: "He left his ___ on the train.", answer: "briefcase", base: "briefcase", hint: "b________", ja: "ブリーフケース", sentenceJa: "彼は電車にブリーフケースを置き忘れた。" },
        { sentence: "The ___ will finish the renovation next week.", answer: "contractor", base: "contractor", hint: "c_________", ja: "請負業者", sentenceJa: "その請負業者は来週、改装を終える予定だ。" },
        { sentence: "You will need a ___ to access the system.", answer: "password", base: "password", hint: "p_______", ja: "パスワード", sentenceJa: "システムにアクセスするにはパスワードが必要です。" },
        { sentence: "The event will be held at the new ___.", answer: "stadium", base: "stadium", hint: "s______", ja: "スタジアム", sentenceJa: "そのイベントは新しいスタジアムで開催される。" },
        { sentence: "Flights depart from ___ 2.", answer: "terminal", base: "terminal", hint: "t_______", ja: "端末、ターミナル", sentenceJa: "フライトはターミナル2から出発する。" },
        { sentence: "Employees received a ___ for their hard work.", answer: "bonus", base: "bonus", hint: "b____", ja: "ボーナス", sentenceJa: "従業員は頑張りに対してボーナスを受け取った。" },
      ],
    },
    {
      name: "Day 11",
      items: [
        { sentence: "The ___ fixed the bug within a day.", answer: "developer", base: "developer", hint: "d________", ja: "開発者", sentenceJa: "その開発者は1日でそのバグを修正した。" },
        { sentence: "A ___ will deliver the package this morning.", answer: "courier", base: "courier", hint: "c______", ja: "配達員", sentenceJa: "配達員が今朝、荷物を届ける予定だ。" },
        { sentence: "The truck is waiting at the loading ___.", answer: "dock", base: "dock", hint: "d___", ja: "波止場、荷積み場", sentenceJa: "そのトラックは荷積み場で待っている。" },
        { sentence: "The ___ outlines the new office policy.", answer: "memorandum", base: "memorandum", hint: "m_________", ja: "覚書、通達", sentenceJa: "その覚書には新しいオフィス方針がまとめられている。" },
        { sentence: "The company booked a ___ for the visiting client.", answer: "suite", base: "suite", hint: "s____", ja: "スイートルーム", sentenceJa: "その会社は来訪する取引先のためにスイートルームを予約した。" },
        { sentence: "Guests can relax in the ___ before their flight.", answer: "lounge", base: "lounge", hint: "l_____", ja: "ラウンジ", sentenceJa: "お客様はフライトの前にラウンジでくつろぐことができます。" },
        { sentence: "Regular ___ receive a discount on Fridays.", answer: "patrons", base: "patron", hint: "p_____", ja: "常連客、後援者", sentenceJa: "常連のお客様は金曜日に割引を受けられる。" },
        { sentence: "You can pick up your ___ at the pharmacy.", answer: "prescription", base: "prescription", hint: "p___________", ja: "処方箋", sentenceJa: "処方箋は薬局で受け取れます。" },
        { sentence: "The ___ explained the product features.", answer: "salesperson", base: "salesperson", hint: "s__________", ja: "販売員", sentenceJa: "その販売員は製品の特徴を説明した。" },
        { sentence: "All ___ should be sent to the main office.", answer: "correspondence", base: "correspondence", hint: "c_____________", ja: "通信、やり取り", sentenceJa: "すべての通信は本社に送るべきだ。" },
        { sentence: "The store is celebrating its tenth ___.", answer: "anniversary", base: "anniversary", hint: "a__________", ja: "記念日", sentenceJa: "その店は10周年を祝っている。" },
        { sentence: "The hotel reported high ___ during the holidays.", answer: "occupancy", base: "occupancy", hint: "o________", ja: "占有、入居率", sentenceJa: "そのホテルは休暇シーズン中、高い稼働率を報告した。" },
        { sentence: "The ___ of the contract is due next month.", answer: "renewal", base: "renewal", hint: "r______", ja: "更新", sentenceJa: "契約の更新は来月が期限だ。" },
        { sentence: "Passengers must remain in their ___ during landing.", answer: "cabin", base: "cabin", hint: "c____", ja: "客室", sentenceJa: "着陸中、乗客は客室内に留まらなければならない。" },
        { sentence: "The ___ checked everyone's ticket.", answer: "conductor", base: "conductor", hint: "c________", ja: "車掌、指揮者", sentenceJa: "車掌は全員のチケットを確認した。" },
        { sentence: "The ___ reviewed the building for safety violations.", answer: "inspector", base: "inspector", hint: "i________", ja: "検査官", sentenceJa: "検査官はその建物の安全違反を確認した。" },
        { sentence: "The ___ helped organize the marketing files.", answer: "intern", base: "intern", hint: "i_____", ja: "インターン", sentenceJa: "そのインターンはマーケティング資料の整理を手伝った。" },
        { sentence: "You will receive a ___ email after booking.", answer: "confirmation", base: "confirmation", hint: "c___________", ja: "確認", sentenceJa: "予約後に確認メールが届きます。" },
        { sentence: "Customers received a ___ for a free meal.", answer: "voucher", base: "voucher", hint: "v______", ja: "引換券", sentenceJa: "お客様は無料の食事の引換券を受け取った。" },
        { sentence: "Employees are paid by direct deposit instead of ___.", answer: "paycheck", base: "paycheck", hint: "p_______", ja: "給与小切手、給料", sentenceJa: "従業員は給料ではなく口座振込で支払われる。" },
      ],
    },
    {
      name: "Day 12",
      items: [
        { sentence: "An ___ fault caused the power outage.", answer: "electrical", base: "electrical", hint: "e_________", ja: "電気の", sentenceJa: "電気系統の不具合が停電を引き起こした。" },
        { sentence: "Buying in bulk is more ___.", answer: "economical", base: "economical", hint: "e_________", ja: "経済的な、節約になる", sentenceJa: "まとめ買いする方が経済的だ。" },
        { sentence: "The application was rejected because it was ___.", answer: "incomplete", base: "incomplete", hint: "i_________", ja: "不完全な", sentenceJa: "その申請書は不完全だったため却下された。" },
        { sentence: "Members receive ___ access to the lounge.", answer: "exclusive", base: "exclusive", hint: "e________", ja: "独占的な、限定の", sentenceJa: "会員はラウンジへの独占的なアクセス権を得られる。" },
        { sentence: "The new schedule has made the team more ___.", answer: "productive", base: "productive", hint: "p_________", ja: "生産的な", sentenceJa: "新しいスケジュールによりチームの生産性が上がった。" },
        { sentence: "Workers must wear ___ equipment on site.", answer: "protective", base: "protective", hint: "p_________", ja: "保護用の", sentenceJa: "作業員は現場で保護具を着用しなければならない。" },
        { sentence: "The office allows ___ dress on Fridays.", answer: "casual", base: "casual", hint: "c_____", ja: "普段着の、気軽な", sentenceJa: "そのオフィスは金曜日にカジュアルな服装を認めている。" },
        { sentence: "The staff were very ___ about the product.", answer: "knowledgeable", base: "knowledgeable", hint: "k____________", ja: "知識豊富な", sentenceJa: "スタッフはその製品について非常に詳しかった。" },
        { sentence: "The invoice is now two weeks ___.", answer: "overdue", base: "overdue", hint: "o______", ja: "期限を過ぎた", sentenceJa: "その請求書は現在2週間の支払い遅延となっている。" },
        { sentence: "We need a ___ answer by tomorrow.", answer: "definite", base: "definite", hint: "d_______", ja: "明確な、確定した", sentenceJa: "明日までに明確な回答が必要だ。" },
        { sentence: "The new branch became ___ within a year.", answer: "profitable", base: "profitable", hint: "p_________", ja: "利益になる", sentenceJa: "その新支店は1年以内に黒字化した。" },
        { sentence: "The inspector did a ___ check of the building.", answer: "thorough", base: "thorough", hint: "t_______", ja: "徹底的な", sentenceJa: "検査官はその建物を徹底的に点検した。" },
        { sentence: "The store will replace any ___ merchandise.", answer: "defective", base: "defective", hint: "d________", ja: "欠陥のある", sentenceJa: "その店は欠陥のある商品をすべて交換する。" },
        { sentence: "Employees are expected to be ___ to customers.", answer: "polite", base: "polite", hint: "p_____", ja: "礼儀正しい", sentenceJa: "従業員は顧客に対して礼儀正しくあることが求められている。" },
        { sentence: "The training proved ___ for new staff.", answer: "beneficial", base: "beneficial", hint: "b_________", ja: "有益な", sentenceJa: "その研修は新人スタッフにとって有益だとわかった。" },
        { sentence: "The new factory will be fully ___ by June.", answer: "operational", base: "operational", hint: "o__________", ja: "稼働中の、運用の", sentenceJa: "新工場は6月までに完全に稼働する予定だ。" },
        { sentence: "Employees are expected to be ___ for meetings.", answer: "punctual", base: "punctual", hint: "p_______", ja: "時間厳守の", sentenceJa: "従業員は会議に時間通り来ることが求められている。" },
        { sentence: "She works for a ___ law firm.", answer: "prestigious", base: "prestigious", hint: "p__________", ja: "名声のある", sentenceJa: "彼女は名声のある法律事務所で働いている。" },
        { sentence: "The new device is ___ enough for many tasks.", answer: "versatile", base: "versatile", hint: "v________", ja: "多才な、多用途の", sentenceJa: "その新しい機器は多くの作業に対応できるほど多用途だ。" },
        { sentence: "The desks in the office are height-___.", answer: "adjustable", base: "adjustable", hint: "a_________", ja: "調節可能な", sentenceJa: "オフィスの机は高さ調節が可能だ。" },
      ],
    },
    {
      name: "Day 13",
      items: [
        { sentence: "Please contact the supplier ___ for pricing details.", answer: "directly", base: "directly", hint: "d_______", ja: "直接", sentenceJa: "価格の詳細については直接サプライヤーに連絡してください。" },
        { sentence: "Managers should monitor spending ___ each month.", answer: "closely", base: "closely", hint: "c______", ja: "綿密に、密接に", sentenceJa: "マネージャーは毎月の支出を綿密に監視すべきだ。" },
        { sentence: "The workshop was ___ recommended by past attendees.", answer: "highly", base: "highly", hint: "h_____", ja: "非常に", sentenceJa: "その研修会は過去の参加者から非常に高く推薦されていた。" },
        { sentence: "Customers are ___ choosing to shop online.", answer: "increasingly", base: "increasingly", hint: "i___________", ja: "ますます", sentenceJa: "顧客はますますオンラインでの買い物を選ぶようになっている。" },
        { sentence: "Production costs have risen ___ this year.", answer: "considerably", base: "considerably", hint: "c___________", ja: "かなり", sentenceJa: "今年、製造コストがかなり上昇した。" },
        { sentence: "The new process ___ reduced delivery times.", answer: "substantially", base: "substantially", hint: "s____________", ja: "大幅に", sentenceJa: "新しいプロセスは配送時間を大幅に短縮した。" },
        { sentence: "The project was completed ___ ahead of deadline.", answer: "successfully", base: "successfully", hint: "s___________", ja: "首尾よく", sentenceJa: "そのプロジェクトは締め切り前に無事完了した。" },
        { sentence: "Make sure the equipment is stored ___ after use.", answer: "properly", base: "properly", hint: "p_______", ja: "適切に", sentenceJa: "使用後は機材が適切に保管されているか確認してください。" },
        { sentence: "The manager ___ summarized the quarterly results.", answer: "briefly", base: "briefly", hint: "b______", ja: "簡潔に", sentenceJa: "マネージャーは四半期の結果を簡潔にまとめた。" },
        { sentence: "We are ___ hiring for two open positions.", answer: "currently", base: "currently", hint: "c________", ja: "現在", sentenceJa: "私たちは現在2つの空きポジションを募集している。" },
        { sentence: "The building was ___ used as a warehouse.", answer: "previously", base: "previously", hint: "p_________", ja: "以前に", sentenceJa: "その建物は以前、倉庫として使われていた。" },
        { sentence: "___, staff will receive training on the new system.", answer: "additionally", base: "additionally", hint: "a___________", ja: "さらに", sentenceJa: "さらに、スタッフは新システムの研修を受けます。" },
        { sentence: "Sales were ___ strong in the fourth quarter.", answer: "particularly", base: "particularly", hint: "p___________", ja: "特に", sentenceJa: "第4四半期の売上は特に好調だった。" },
        { sentence: "The product is aimed ___ at small businesses.", answer: "primarily", base: "primarily", hint: "p________", ja: "主に", sentenceJa: "その製品は主に中小企業向けに作られている。" },
        { sentence: "The client ___ decided to renew the contract.", answer: "ultimately", base: "ultimately", hint: "u_________", ja: "最終的に", sentenceJa: "そのクライアントは最終的に契約更新を決めた。" },
        { sentence: "The machines are ___ inspected for safety.", answer: "regularly", base: "regularly", hint: "r________", ja: "定期的に", sentenceJa: "その機械は安全のため定期的に点検されている。" },
        { sentence: "The plan was ___ rejected by the board.", answer: "initially", base: "initially", hint: "i________", ja: "最初は", sentenceJa: "その計画は当初、取締役会に却下された。" },
        { sentence: "The office will be closed ___ for renovations.", answer: "temporarily", base: "temporarily", hint: "t__________", ja: "一時的に", sentenceJa: "そのオフィスは改装のため一時的に閉鎖される。" },
        { sentence: "The new software helps staff manage tasks ___.", answer: "effectively", base: "effectively", hint: "e__________", ja: "効果的に", sentenceJa: "その新しいソフトウェアはスタッフが業務を効果的に管理するのに役立つ。" },
        { sentence: "The team worked ___ to meet the deadline.", answer: "efficiently", base: "efficiently", hint: "e__________", ja: "効率的に", sentenceJa: "そのチームは締め切りに間に合うよう効率的に働いた。" },
      ],
    },
    {
      name: "Day 15",
      items: [
        { sentence: "Yesterday, a power outage ___ operations at the warehouse.", answer: "disrupted", base: "disrupt", hint: "d______", ja: "妨害する、混乱させる", sentenceJa: "昨日、停電が倉庫の業務を混乱させた。" },
        { sentence: "Please ___ our thanks to the entire team.", answer: "convey", base: "convey", hint: "c_____", ja: "伝える、運ぶ", sentenceJa: "チーム全員に私たちの感謝を伝えてください。" },
        { sentence: "Yesterday, the delayed flight ___ all the passengers.", answer: "frustrated", base: "frustrate", hint: "f________", ja: "いらだたせる、挫折させる", sentenceJa: "昨日、フライトの遅延が乗客全員をいらだたせた。" },
        { sentence: "They ___ the office for the holiday party last week.", answer: "decorated", base: "decorate", hint: "d_______", ja: "飾る、装飾する", sentenceJa: "先週、彼らは休暇パーティーのためにオフィスを飾り付けた。" },
        { sentence: "The fire alarm ___ the meeting yesterday afternoon.", answer: "interrupted", base: "interrupt", hint: "i________", ja: "中断させる、（話を）遮る", sentenceJa: "昨日の午後、火災警報が会議を中断させた。" },
        { sentence: "The factory plans to ___ most of its production line next year.", answer: "automate", base: "automate", hint: "a_______", ja: "自動化する", sentenceJa: "その工場は来年、生産ラインの大部分を自動化する計画だ。" },
        { sentence: "The manager ___ the new safety policy during yesterday's meeting.", answer: "reinforced", base: "reinforce", hint: "r________", ja: "強化する、徹底させる", sentenceJa: "昨日の会議で、マネージャーは新しい安全方針を改めて徹底させた。" },
        { sentence: "Loud music can ___ employees from their work.", answer: "distract", base: "distract", hint: "d_______", ja: "気を散らす", sentenceJa: "大きな音楽は従業員の仕事の集中を妨げることがある。" },
        { sentence: "Yesterday, the clerk ___ the documents by department.", answer: "classified", base: "classify", hint: "c_______", ja: "分類する", sentenceJa: "昨日、事務員は書類を部署ごとに分類した。" },
        { sentence: "The company ___ every employee with a new laptop last month.", answer: "equipped", base: "equip", hint: "e____", ja: "（設備・道具を）備え付ける", sentenceJa: "先月、その会社は全従業員に新しいノートパソコンを支給した。" },
        { sentence: "A staff member ___ the visitors to the conference room this morning.", answer: "escorted", base: "escort", hint: "e_____", ja: "同行する、案内する、警護する", sentenceJa: "今朝、スタッフが訪問者を会議室まで案内した。" },
        { sentence: "Yesterday, we ___ the furniture before the guests arrived.", answer: "rearranged", base: "rearrange", hint: "r________", ja: "並べ替える、再手配する", sentenceJa: "昨日、私たちはお客様が到着する前に家具を並べ替えた。" },
        { sentence: "The store will ___ next Monday after renovations.", answer: "reopen", base: "reopen", hint: "r_____", ja: "再開する", sentenceJa: "その店は改装後、来週月曜日に再オープンする。" },
        { sentence: "Last month, the advertisement ___ many customers about the product's price.", answer: "misled", base: "mislead", hint: "m______", ja: "誤解させる、惑わす", sentenceJa: "先月、その広告は多くの顧客に製品の価格について誤解を与えた。" },
        { sentence: "Yesterday, she ___ her badge somewhere in the office.", answer: "misplaced", base: "misplace", hint: "m_______", ja: "置き忘れる、紛失する", sentenceJa: "昨日、彼女はオフィスのどこかで社員証を置き忘れた。" },
        { sentence: "The company plans to ___ the lobby next spring.", answer: "remodel", base: "remodel", hint: "r______", ja: "改装する、改築する", sentenceJa: "その会社は来春、ロビーを改装する計画だ。" },
        { sentence: "The accountant will ___ the tax from your salary.", answer: "deduct", base: "deduct", hint: "d_____", ja: "差し引く、控除する", sentenceJa: "経理担当者があなたの給与から税金を差し引きます。" },
        { sentence: "Please ___ the report before you send it.", answer: "proofread", base: "proofread", hint: "p________", ja: "校正する", sentenceJa: "送信する前に報告書を校正してください。" },
        { sentence: "Dust had ___ on the shelves over the years.", answer: "accumulated", base: "accumulate", hint: "a_________", ja: "積み重なる、蓄積する", sentenceJa: "何年もの間に棚にほこりが積もっていた。" },
        { sentence: "All employees must ___ to the company's dress code.", answer: "adhere", base: "adhere", hint: "a_____", ja: "（規則などを）遵守する、固執する", sentenceJa: "全従業員は会社の服装規定を遵守しなければならない。" },
      ],
    },
    {
      name: "Day 16",
      items: [
        { sentence: "Yesterday, the assistant ___ the document and sent a copy to each department.", answer: "duplicated", base: "duplicate", hint: "d________", ja: "複製する", sentenceJa: "昨日、アシスタントはその書類を複製し、各部署にコピーを送った。" },
        { sentence: "Please ___ your seatbelt before the plane takes off.", answer: "fasten", base: "fasten", hint: "f_____", ja: "固定する、締める", sentenceJa: "飛行機が離陸する前にシートベルトを締めてください。" },
        { sentence: "Many employees ___ to work from home on Fridays.", answer: "opt", base: "opt", hint: "o__", ja: "選ぶ、選択する", sentenceJa: "多くの従業員は金曜日に在宅勤務を選んでいる。" },
        { sentence: "Yesterday, she ___ her presentation before the big meeting.", answer: "polished", base: "polish", hint: "p_____", ja: "磨く、仕上げる", sentenceJa: "昨日、彼女は大事な会議の前にプレゼンを仕上げた。" },
        { sentence: "Yesterday, the team ___ their presentation twice before the client meeting.", answer: "rehearsed", base: "rehearse", hint: "r_______", ja: "リハーサルをする、練習する", sentenceJa: "昨日、チームはクライアントとの会議の前に2回プレゼンのリハーサルをした。" },
        { sentence: "Last quarter, the company ___ its profits by cutting costs.", answer: "maximized", base: "maximize", hint: "m_______", ja: "最大化する", sentenceJa: "前四半期、その会社はコストを削減して利益を最大化した。" },
        { sentence: "The inspector will ___ the building as safe next week.", answer: "certify", base: "certify", hint: "c______", ja: "証明する、認定する", sentenceJa: "検査官は来週、その建物を安全だと認定する予定だ。" },
        { sentence: "New employees ___ themselves with the safety rules during orientation last week.", answer: "familiarized", base: "familiarize", hint: "f__________", ja: "慣れさせる、精通させる", sentenceJa: "先週、新入社員はオリエンテーション中に安全規則に慣れ親しんだ。" },
        { sentence: "Yesterday, the manager ___ a small error in the report.", answer: "overlooked", base: "overlook", hint: "o_______", ja: "見落とす、大目に見る", sentenceJa: "昨日、マネージャーは報告書の小さな誤りを見落とした。" },
        { sentence: "The department decided to ___ on office supplies this year.", answer: "economize", base: "economize", hint: "e________", ja: "節約する", sentenceJa: "その部署は今年、事務用品を節約することに決めた。" },
        { sentence: "The new software ___ much of the staff's workload last month.", answer: "relieved", base: "relieve", hint: "r______", ja: "軽減する、和らげる", sentenceJa: "先月、その新しいソフトウェアはスタッフの業務負担を大きく軽減した。" },
        { sentence: "Yesterday, they ___ the meeting to save everyone time.", answer: "shortened", base: "shorten", hint: "s______", ja: "短くする、短縮する", sentenceJa: "昨日、彼らは皆の時間を節約するために会議を短縮した。" },
        { sentence: "Please ___ the discount from the total price.", answer: "subtract", base: "subtract", hint: "s_______", ja: "引く、差し引く", sentenceJa: "合計金額から割引分を差し引いてください。" },
        { sentence: "Can you ___ that sentence more simply?", answer: "paraphrase", base: "paraphrase", hint: "p_________", ja: "言い換える", sentenceJa: "その文をもっと簡単に言い換えてもらえますか？" },
        { sentence: "Please ___ the receipt before submitting the form.", answer: "detach", base: "detach", hint: "d_____", ja: "取り外す、切り離す", sentenceJa: "フォームを提出する前にレシートを切り離してください。" },
        { sentence: "Yesterday, the constant noise ___ the office workers all day.", answer: "irritated", base: "irritate", hint: "i_______", ja: "いらだたせる", sentenceJa: "昨日は一日中、絶え間ない騒音がオフィスワーカーをいらだたせた。" },
        { sentence: "The comedian's jokes ___ the entire audience last night.", answer: "amused", base: "amuse", hint: "a____", ja: "楽しませる、面白がらせる", sentenceJa: "昨夜、そのコメディアンのジョークは観客全員を楽しませた。" },
        { sentence: "The mechanic ___ the broken-down car to the garage this morning.", answer: "towed", base: "tow", hint: "t__", ja: "牽引する、レッカー移動する", sentenceJa: "今朝、整備士は故障した車を修理工場まで牽引した。" },
        { sentence: "She ___ around the park every morning before work.", answer: "jogs", base: "jog", hint: "j__", ja: "ジョギングする", sentenceJa: "彼女は毎朝、仕事の前に公園の周りをジョギングする。" },
        { sentence: "Many customers ___ the new pricing policy.", answer: "dislike", base: "dislike", hint: "d______", ja: "嫌う、好まない", sentenceJa: "多くの顧客はその新しい価格方針を好んでいない。" },
      ],
    },
    {
      name: "Day 17",
      items: [
        { sentence: "The project reached ___ two weeks ahead of schedule.", answer: "completion", base: "completion", hint: "c_________", ja: "完了、完成", sentenceJa: "そのプロジェクトは予定より2週間早く完了した。" },
        { sentence: "The inspector found a small ___ in the machine.", answer: "defect", base: "defect", hint: "d_____", ja: "欠陥、不良", sentenceJa: "検査官はその機械に小さな欠陥を見つけた。" },
        { sentence: "The ___ shows a steady increase in sales.", answer: "graph", base: "graph", hint: "g____", ja: "グラフ", sentenceJa: "そのグラフは売上の着実な増加を示している。" },
        { sentence: "The rent doesn't include ___ costs like electricity and water.", answer: "utility", base: "utility", hint: "u______", ja: "公共料金、実用性", sentenceJa: "家賃には電気や水道などの光熱費は含まれていない。" },
        { sentence: "She signed the contract on ___ of her manager.", answer: "behalf", base: "behalf", hint: "b_____", ja: "代理、代表", sentenceJa: "彼女はマネージャーの代理として契約書に署名した。" },
        { sentence: "The ___ agreed to lower the price after negotiation.", answer: "seller", base: "seller", hint: "s_____", ja: "売り手、販売者", sentenceJa: "その売り手は交渉の末、価格を下げることに同意した。" },
        { sentence: "The package was damaged in ___.", answer: "transit", base: "transit", hint: "t______", ja: "輸送、通過、交通機関", sentenceJa: "その荷物は輸送中に破損した。" },
        { sentence: "The ___ gave me the wrong change.", answer: "cashier", base: "cashier", hint: "c______", ja: "レジ係、会計係", sentenceJa: "そのレジ係は私に間違ったお釣りを渡した。" },
        { sentence: "They put up a ___ advertising the new product.", answer: "poster", base: "poster", hint: "p_____", ja: "ポスター", sentenceJa: "彼らは新製品を宣伝するポスターを貼った。" },
        { sentence: "The ___ offers a discount for bulk orders.", answer: "retailer", base: "retailer", hint: "r_______", ja: "小売業者", sentenceJa: "その小売業者はまとめ買いに割引を提供している。" },
        { sentence: "The hotel had only one ___ left for the weekend.", answer: "vacancy", base: "vacancy", hint: "v______", ja: "空き、欠員", sentenceJa: "そのホテルには週末の空室が一つしか残っていなかった。" },
        { sentence: "You can find her extension in the company ___.", answer: "directory", base: "directory", hint: "d________", ja: "名簿", sentenceJa: "彼女の内線番号は社内名簿で確認できる。" },
        { sentence: "Proper ___ of chemical waste is required by law.", answer: "disposal", base: "disposal", hint: "d_______", ja: "処分、廃棄", sentenceJa: "化学廃棄物の適切な処分は法律で義務付けられている。" },
        { sentence: "The ___ cleans every room on the third floor.", answer: "housekeeper", base: "housekeeper", hint: "h__________", ja: "客室係、家政婦", sentenceJa: "その客室係は3階の全ての部屋を掃除する。" },
        { sentence: "She completed a summer ___ at a law firm.", answer: "internship", base: "internship", hint: "i_________", ja: "インターンシップ、実習", sentenceJa: "彼女は法律事務所で夏のインターンシップを修了した。" },
        { sentence: "The event ___ canceled the concert due to rain.", answer: "organizer", base: "organizer", hint: "o________", ja: "主催者、整理用品", sentenceJa: "イベントの主催者は雨のためコンサートを中止した。" },
        { sentence: "His ___ about the market turned out to be correct.", answer: "prediction", base: "prediction", hint: "p_________", ja: "予測、予言", sentenceJa: "市場についての彼の予測は正しいことが判明した。" },
        { sentence: "The magazine has over ten thousand ___.", answer: "subscribers", base: "subscriber", hint: "s_________", ja: "購読者、加入者", sentenceJa: "その雑誌には1万人以上の購読者がいる。" },
        { sentence: "All new hires must attend the ___ on Monday.", answer: "orientation", base: "orientation", hint: "o__________", ja: "オリエンテーション、方向づけ", sentenceJa: "新入社員は全員、月曜日のオリエンテーションに出席しなければならない。" },
        { sentence: "She bought the shoes at a discount at the ___ store.", answer: "outlet", base: "outlet", hint: "o_____", ja: "アウトレット店、コンセント、はけ口", sentenceJa: "彼女はアウトレット店でその靴を割引価格で買った。" },
      ],
    },
    {
      name: "Day 18",
      items: [
        { sentence: "The product didn't meet the client's ___.", answer: "specifications", base: "specification", hint: "s____________", ja: "仕様、規格", sentenceJa: "その製品は顧客の仕様を満たしていなかった。" },
        { sentence: "You can claim a tax ___ for business travel.", answer: "deduction", base: "deduction", hint: "d________", ja: "控除、差し引き", sentenceJa: "出張費については税控除を申請できる。" },
        { sentence: "They handed out ___ for the store's grand opening.", answer: "flyers", base: "flyer", hint: "f____", ja: "チラシ、ビラ", sentenceJa: "彼らは店のグランドオープンのチラシを配った。" },
        { sentence: "He opened a ___ of the coffee shop downtown.", answer: "franchise", base: "franchise", hint: "f________", ja: "フランチャイズ、加盟店", sentenceJa: "彼は繁華街にそのコーヒーショップのフランチャイズ店を開いた。" },
        { sentence: "The new cars are on display in the ___.", answer: "showroom", base: "showroom", hint: "s_______", ja: "展示場", sentenceJa: "新車はショールームに展示されている。" },
        { sentence: "The system ___ reset everyone's password.", answer: "administrator", base: "administrator", hint: "a____________", ja: "管理者、運営者", sentenceJa: "システム管理者は全員のパスワードをリセットした。" },
        { sentence: "A real estate ___ helped them find their new office.", answer: "broker", base: "broker", hint: "b_____", ja: "仲介業者", sentenceJa: "不動産仲介業者は彼らが新しいオフィスを見つける手助けをした。" },
        { sentence: "The airline charged a fee for the ___.", answer: "cancellation", base: "cancellation", hint: "c___________", ja: "取り消し", sentenceJa: "その航空会社はキャンセル料を請求した。" },
        { sentence: "Water ___ increases sharply during the summer.", answer: "usage", base: "usage", hint: "u____", ja: "使用、使用量", sentenceJa: "水の使用量は夏に急増する。" },
        { sentence: "The manager gave a brief ___ of the new project.", answer: "overview", base: "overview", hint: "o_______", ja: "概要", sentenceJa: "マネージャーは新しいプロジェクトの概要を簡単に説明した。" },
        { sentence: "The factory is facing a ___ of raw materials.", answer: "shortage", base: "shortage", hint: "s_______", ja: "不足", sentenceJa: "その工場は原材料の不足に直面している。" },
        { sentence: "Winning the award was a major ___ for the team.", answer: "accomplishment", base: "accomplishment", hint: "a_____________", ja: "業績、達成", sentenceJa: "その賞を受賞したことはチームにとって大きな業績だった。" },
        { sentence: "The package had no return address for the ___.", answer: "sender", base: "sender", hint: "s_____", ja: "送り主、発信者", sentenceJa: "その荷物には送り主の返送先住所が書かれていなかった。" },
        { sentence: "The company gave a bonus to show its ___.", answer: "appreciation", base: "appreciation", hint: "a___________", ja: "感謝、真価を認めること", sentenceJa: "その会社は感謝の気持ちを示すためにボーナスを支給した。" },
        { sentence: "Students may qualify for a tax ___.", answer: "exemption", base: "exemption", hint: "e________", ja: "免除", sentenceJa: "学生は税の免除を受けられる場合がある。" },
        { sentence: "She received a full ___ to study abroad.", answer: "scholarship", base: "scholarship", hint: "s__________", ja: "奨学金", sentenceJa: "彼女は留学のための全額奨学金を受け取った。" },
        { sentence: "The IT team upgraded the office ___ last week.", answer: "hardware", base: "hardware", hint: "h_______", ja: "ハードウェア、金物", sentenceJa: "先週、IT部門はオフィスのハードウェアをアップグレードした。" },
        { sentence: "A software ___ delayed the entire shipment.", answer: "malfunction", base: "malfunction", hint: "m__________", ja: "誤作動、故障", sentenceJa: "ソフトウェアの誤作動が出荷全体を遅らせた。" },
        { sentence: "The event ___ confirmed all the details with the venue.", answer: "coordinator", base: "coordinator", hint: "c__________", ja: "調整役", sentenceJa: "イベントコーディネーターは会場と全ての詳細を確認した。" },
        { sentence: "The company switched to a cheaper ___ for office supplies.", answer: "vendor", base: "vendor", hint: "v_____", ja: "業者、販売者", sentenceJa: "その会社は事務用品の業者をより安いところに変更した。" },
      ],
    },
    {
      name: "Day 19",
      items: [
        { sentence: "His argument seemed ___ to the rest of the team.", answer: "illogical", base: "illogical", hint: "i________", ja: "非論理的な、筋が通らない", sentenceJa: "彼の主張はチームの他のメンバーには筋が通らないように思えた。" },
        { sentence: "The report shows the ___ effect of the price increases.", answer: "cumulative", base: "cumulative", hint: "c_________", ja: "累積的な", sentenceJa: "その報告書は価格上昇の累積的な影響を示している。" },
        { sentence: "The client offered a ___ discount for early payment.", answer: "generous", base: "generous", hint: "g_______", ja: "気前の良い、寛大な", sentenceJa: "その顧客は早期支払いに対して気前の良い割引を提示した。" },
        { sentence: "The restaurant added several ___ options to the menu.", answer: "vegetarian", base: "vegetarian", hint: "v_________", ja: "菜食主義の", sentenceJa: "そのレストランはメニューにベジタリアン向けの選択肢をいくつか追加した。" },
        { sentence: "The manager asked for a more ___ deadline.", answer: "realistic", base: "realistic", hint: "r________", ja: "現実的な", sentenceJa: "マネージャーはより現実的な締め切りを求めた。" },
        { sentence: "The outdoor event was canceled because it was too ___.", answer: "windy", base: "windy", hint: "w____", ja: "風の強い", sentenceJa: "屋外イベントは風が強すぎたため中止になった。" },
        { sentence: "The company rewards its most ___ customers with special offers.", answer: "loyal", base: "loyal", hint: "l____", ja: "忠実な、常連の", sentenceJa: "その会社は最も忠実な顧客に特別オファーで報いている。" },
        { sentence: "The conference room now has a ___ internet connection.", answer: "wireless", base: "wireless", hint: "w_______", ja: "無線の", sentenceJa: "その会議室には今、無線インターネット接続がある。" },
        { sentence: "The delay was caused by a ___ problem with the printer.", answer: "mechanical", base: "mechanical", hint: "m_________", ja: "機械的な、機械の", sentenceJa: "その遅延はプリンターの機械的な不具合が原因だった。" },
        { sentence: "The store is giving out ___ samples this weekend.", answer: "promotional", base: "promotional", hint: "p__________", ja: "販売促進の、宣伝用の", sentenceJa: "その店は今週末、宣伝用のサンプルを配布している。" },
        { sentence: "The new office building is located in a ___ area.", answer: "residential", base: "residential", hint: "r__________", ja: "住宅の、居住用の", sentenceJa: "その新しいオフィスビルは住宅地に位置している。" },
        { sentence: "Please do not leave your luggage ___ in the lobby.", answer: "unattended", base: "unattended", hint: "u_________", ja: "無人の、放置された", sentenceJa: "ロビーで荷物を放置しないでください。" },
        { sentence: "The office doors have an ___ locking system.", answer: "automatic", base: "automatic", hint: "a________", ja: "自動の", sentenceJa: "そのオフィスのドアには自動施錠システムがある。" },
        { sentence: "The company replaced its ___ computer system last year.", answer: "outdated", base: "outdated", hint: "o_______", ja: "時代遅れの、旧式の", sentenceJa: "その会社は昨年、時代遅れのコンピューターシステムを交換した。" },
        { sentence: "Fixing the machine turned out to be more ___ than expected.", answer: "costly", base: "costly", hint: "c_____", ja: "費用のかかる、高価な", sentenceJa: "その機械の修理は予想以上に費用がかかることが分かった。" },
        { sentence: "The new software felt ___ to most of the staff at first.", answer: "unfamiliar", base: "unfamiliar", hint: "u_________", ja: "不慣れな、なじみのない", sentenceJa: "その新しいソフトウェアは最初、ほとんどのスタッフにとってなじみのないものだった。" },
        { sentence: "The parking lot is ___ to the main building.", answer: "adjacent", base: "adjacent", hint: "a_______", ja: "隣接した", sentenceJa: "その駐車場は本館に隣接している。" },
        { sentence: "Please provide an ___ contact number.", answer: "alternate", base: "alternate", hint: "a________", ja: "代わりの、交互の", sentenceJa: "代わりの連絡先番号を教えてください。" },
        { sentence: "The hotel offers ___ rooms for business travelers.", answer: "inexpensive", base: "inexpensive", hint: "i__________", ja: "安価な", sentenceJa: "そのホテルは出張者向けに安価な部屋を提供している。" },
        { sentence: "Customers praised the ___ quality of the new product.", answer: "superior", base: "superior", hint: "s_______", ja: "優れた、上質な", sentenceJa: "顧客は新製品の優れた品質を称賛した。" },
      ],
    },
    {
      name: "Day 20",
      items: [
        { sentence: "The membership fee is billed ___.", answer: "yearly", base: "yearly", hint: "y_____", ja: "毎年、年に一度", sentenceJa: "会員費は年に一度請求される。" },
        { sentence: "Part-time workers are paid ___.", answer: "hourly", base: "hourly", hint: "h_____", ja: "1時間ごとに、時給で", sentenceJa: "パートタイム従業員は時給で支払われる。" },
        { sentence: "The board meets ___ to review the budget.", answer: "quarterly", base: "quarterly", hint: "q________", ja: "四半期ごとに", sentenceJa: "取締役会は予算を見直すために四半期ごとに開催される。" },
        { sentence: "We had a short meeting and went to lunch ___.", answer: "afterward", base: "afterward", hint: "a________", ja: "その後で", sentenceJa: "私たちは短い会議をして、その後で昼食に行った。" },
        { sentence: "Visitors must ___ follow the safety guidelines.", answer: "strictly", base: "strictly", hint: "s_______", ja: "厳密に、厳しく", sentenceJa: "訪問者は安全ガイドラインを厳密に守らなければならない。" },
        { sentence: "You can contact customer support ___.", answer: "anytime", base: "anytime", hint: "a______", ja: "いつでも", sentenceJa: "カスタマーサポートにはいつでも連絡できます。" },
        { sentence: "Please store the documents ___ in the locked cabinet.", answer: "safely", base: "safely", hint: "s_____", ja: "安全に", sentenceJa: "書類は鍵のかかるキャビネットに安全に保管してください。" },
        { sentence: "Please let us know ___ if you'll be late.", answer: "beforehand", base: "beforehand", hint: "b_________", ja: "前もって、事前に", sentenceJa: "遅れる場合は前もってお知らせください。" },
        { sentence: "The equipment should be inspected ___.", answer: "periodically", base: "periodically", hint: "p___________", ja: "定期的に", sentenceJa: "その機器は定期的に点検されるべきだ。" },
        { sentence: "All passengers must be ___ before the gate closes.", answer: "aboard", base: "aboard", hint: "a_____", ja: "搭乗して、乗って", sentenceJa: "全ての乗客はゲートが閉まる前に搭乗していなければならない。" },
        { sentence: "___, the report should be finished by Friday.", answer: "ideally", base: "ideally", hint: "i______", ja: "理想的には", sentenceJa: "理想的には、その報告書は金曜日までに完成しているべきだ。" },
        { sentence: "This packaging was ___ designed to reduce waste.", answer: "specially", base: "specially", hint: "s________", ja: "特別に", sentenceJa: "この梱包は廃棄物を減らすために特別に設計された。" },
        { sentence: "The hotel is ___ located near the airport.", answer: "conveniently", base: "conveniently", hint: "c___________", ja: "便利に、都合よく", sentenceJa: "そのホテルは空港の近くの便利な場所にある。" },
        { sentence: "The customer ___ called to check on the delivery.", answer: "repeatedly", base: "repeatedly", hint: "r_________", ja: "繰り返して", sentenceJa: "その顧客は配達の状況を確認するために繰り返し電話した。" },
        { sentence: "The staff worked ___ during the exam period.", answer: "silently", base: "silently", hint: "s_______", ja: "静かに、黙って", sentenceJa: "試験期間中、スタッフは静かに作業した。" },
        { sentence: "The manager ___ needs your response by noon.", answer: "urgently", base: "urgently", hint: "u_______", ja: "緊急に", sentenceJa: "マネージャーは正午までにあなたの返答を緊急に必要としている。" },
        { sentence: "Each item is wrapped ___ for shipping.", answer: "individually", base: "individually", hint: "i___________", ja: "個別に", sentenceJa: "各商品は発送のために個別に包装されている。" },
        { sentence: "The manager praised her work, and her colleagues did ___.", answer: "likewise", base: "likewise", hint: "l_______", ja: "同様に", sentenceJa: "マネージャーは彼女の仕事を称賛し、同僚たちも同様にそうした。" },
        { sentence: "The brand is recognized ___ for its quality.", answer: "internationally", base: "internationally", hint: "i______________", ja: "国際的に", sentenceJa: "そのブランドは品質の高さで国際的に認められている。" },
        { sentence: "The team spent the budget ___ this year.", answer: "wisely", base: "wisely", hint: "w_____", ja: "賢明に", sentenceJa: "そのチームは今年、予算を賢明に使った。" },
      ],
    },
    {
      name: "Day 22",
      items: [
        { sentence: "The company plans to ___ the smaller firm next year.", answer: "absorb", base: "absorb", hint: "a_____", ja: "吸収する、理解する", sentenceJa: "その会社は来年、その小さな会社を吸収合併する計画だ。" },
        { sentence: "Please ___ the total cost before Friday.", answer: "approximate", base: "approximate", hint: "a__________", ja: "概算する、近似する", sentenceJa: "金曜日までに総費用を概算してください。" },
        { sentence: "Yesterday, the staff ___ the manager's decision.", answer: "awaited", base: "await", hint: "a____", ja: "待つ", sentenceJa: "昨日、スタッフはマネージャーの決定を待った。" },
        { sentence: "Yesterday, customers ___ the catalog online before buying.", answer: "browsed", base: "browse", hint: "b_____", ja: "閲覧する、見て回る", sentenceJa: "昨日、顧客は購入前にオンラインでカタログを閲覧した。" },
        { sentence: "All products must ___ to safety standards.", answer: "conform", base: "conform", hint: "c______", ja: "従う、一致する", sentenceJa: "全ての製品は安全基準に従わなければならない。" },
        { sentence: "Yesterday, the technician ___ the old printer.", answer: "disconnected", base: "disconnect", hint: "d_________", ja: "切断する、接続を切る", sentenceJa: "昨日、技術者は古いプリンターの接続を切った。" },
        { sentence: "Please ___ of this material carefully.", answer: "dispose", base: "dispose", hint: "d______", ja: "処分する", sentenceJa: "この資材は慎重に処分してください。" },
        { sentence: "Last year, the company ___ its sales department.", answer: "downsized", base: "downsize", hint: "d_______", ja: "縮小する、規模を小さくする", sentenceJa: "去年、その会社は営業部門を縮小した。" },
        { sentence: "Yesterday, the manager ___ the sales figures in his report.", answer: "inflated", base: "inflate", hint: "i______", ja: "膨らませる、水増しする", sentenceJa: "昨日、マネージャーは報告書で売上高を水増しした。" },
        { sentence: "Please ___ your card into the machine.", answer: "insert", base: "insert", hint: "i_____", ja: "挿入する", sentenceJa: "機械にカードを挿入してください。" },
        { sentence: "Last week, she ___ the safety procedures.", answer: "memorized", base: "memorize", hint: "m_______", ja: "暗記する", sentenceJa: "先週、彼女は安全手順を暗記した。" },
        { sentence: "She ___ the entire marketing team.", answer: "oversees", base: "oversee", hint: "o______", ja: "監督する", sentenceJa: "彼女はマーケティングチーム全体を監督している。" },
        { sentence: "Yesterday, the shop accidentally ___ a customer.", answer: "overcharged", base: "overcharge", hint: "o_________", ja: "不当に高く請求する", sentenceJa: "昨日、その店は誤って顧客に過剰請求してしまった。" },
        { sentence: "The company will ___ the merger next week.", answer: "publicize", base: "publicize", hint: "p________", ja: "宣伝する、公表する", sentenceJa: "その会社は来週、合併を公表する予定だ。" },
        { sentence: "Last month, they ___ the entire lobby.", answer: "redecorated", base: "redecorate", hint: "r_________", ja: "改装する、模様替えする", sentenceJa: "先月、彼らはロビー全体を改装した。" },
        { sentence: "Please ___ the page to see the update.", answer: "refresh", base: "refresh", hint: "r______", ja: "更新する、リフレッシュする", sentenceJa: "更新内容を確認するにはページを更新してください。" },
        { sentence: "Yesterday, the printer ___ the document perfectly.", answer: "reproduced", base: "reproduce", hint: "r________", ja: "複製する、再現する", sentenceJa: "昨日、そのプリンターは書類を完璧に複製した。" },
        { sentence: "Guests must ___ the room by eleven o'clock.", answer: "vacate", base: "vacate", hint: "v_____", ja: "退去する、明け渡す", sentenceJa: "宿泊客は11時までに部屋を明け渡さなければならない。" },
        { sentence: "Last quarter, the team ___ its sales goal.", answer: "attained", base: "attain", hint: "a_____", ja: "達成する", sentenceJa: "前四半期、チームは売上目標を達成した。" },
        { sentence: "Last year, senior staff ___ several new employees.", answer: "mentored", base: "mentor", hint: "m_____", ja: "指導する、助言する", sentenceJa: "去年、上級スタッフは何人かの新入社員を指導した。" },
      ],
    },
    {
      name: "Day 23",
      items: [
        { sentence: "All employees must ___ to the new policy.", answer: "consent", base: "consent", hint: "c______", ja: "同意する", sentenceJa: "全従業員は新しい方針に同意しなければならない。" },
        { sentence: "Please ___ your account within 24 hours.", answer: "activate", base: "activate", hint: "a_______", ja: "作動させる、有効にする", sentenceJa: "24時間以内にアカウントを有効化してください。" },
        { sentence: "Yesterday, the company ___ a technician immediately.", answer: "dispatched", base: "dispatch", hint: "d_______", ja: "発送する、派遣する", sentenceJa: "昨日、その会社はすぐに技術者を派遣した。" },
        { sentence: "Customers can ___ their order online.", answer: "personalize", base: "personalize", hint: "p__________", ja: "個別化する、カスタマイズする", sentenceJa: "顧客はオンラインで注文をカスタマイズできる。" },
        { sentence: "Yesterday, the manager ___ the worried staff.", answer: "reassured", base: "reassure", hint: "r_______", ja: "安心させる", sentenceJa: "昨日、マネージャーは心配しているスタッフを安心させた。" },
        { sentence: "This technology could ___ the industry.", answer: "revolutionize", base: "revolutionize", hint: "r____________", ja: "革命的に変える", sentenceJa: "この技術は業界を革命的に変える可能性がある。" },
        { sentence: "A red light always ___ danger in this factory.", answer: "signifies", base: "signify", hint: "s______", ja: "示す、意味する", sentenceJa: "この工場では、赤いランプはいつも危険を示す。" },
        { sentence: "Last week, the new CEO ___ the company toward new markets.", answer: "steered", base: "steer", hint: "s____", ja: "操縦する、導く", sentenceJa: "先週、新しいCEOは会社を新しい市場へと導いた。" },
        { sentence: "Please ___ this memo to all staff.", answer: "circulate", base: "circulate", hint: "c________", ja: "回覧する、循環する", sentenceJa: "このメモを全スタッフに回覧してください。" },
        { sentence: "Yesterday, the designer ___ a video in the webpage.", answer: "embedded", base: "embed", hint: "e____", ja: "埋め込む", sentenceJa: "昨日、デザイナーはウェブページに動画を埋め込んだ。" },
        { sentence: "Everyone must ___ the building during a fire drill.", answer: "evacuate", base: "evacuate", hint: "e_______", ja: "避難する、避難させる", sentenceJa: "火災訓練中は全員が建物から避難しなければならない。" },
        { sentence: "Last week, we ___ the shipping process for the client.", answer: "expedited", base: "expedite", hint: "e_______", ja: "迅速化する", sentenceJa: "先週、私たちはクライアントのために配送手続きを迅速化した。" },
        { sentence: "Exchange rates ___ constantly.", answer: "fluctuate", base: "fluctuate", hint: "f________", ja: "変動する", sentenceJa: "為替レートは絶えず変動している。" },
        { sentence: "Please don't ___ with the ongoing negotiation.", answer: "interfere", base: "interfere", hint: "i________", ja: "干渉する、邪魔する", sentenceJa: "進行中の交渉に干渉しないでください。" },
        { sentence: "Yesterday, the client accidentally ___ the invoice.", answer: "overpaid", base: "overpay", hint: "o______", ja: "払い過ぎる", sentenceJa: "昨日、クライアントは誤って請求書に対して払い過ぎた。" },
        { sentence: "Last month, the league ___ the team for the violation.", answer: "penalized", base: "penalize", hint: "p_______", ja: "罰する、不利益を与える", sentenceJa: "先月、リーグはその違反に対してチームを罰した。" },
        { sentence: "The factory's waste ___ the nearby river last year.", answer: "polluted", base: "pollute", hint: "p______", ja: "汚染する", sentenceJa: "去年、その工場の廃棄物は近くの川を汚染した。" },
        { sentence: "Yesterday, the doctor ___ new medication.", answer: "prescribed", base: "prescribe", hint: "p________", ja: "処方する、規定する", sentenceJa: "昨日、医者は新しい薬を処方した。" },
        { sentence: "Yesterday, the IT team ___ the lost files.", answer: "retrieved", base: "retrieve", hint: "r_______", ja: "取り戻す、検索する", sentenceJa: "昨日、IT部門は失われたファイルを取り戻した。" },
        { sentence: "The government ___ renewable energy projects.", answer: "subsidizes", base: "subsidize", hint: "s________", ja: "補助金を出す", sentenceJa: "政府は再生可能エネルギープロジェクトに補助金を出している。" },
      ],
    },
    {
      name: "Day 24",
      items: [
        { sentence: "She works at a research ___ downtown.", answer: "institute", base: "institute", hint: "i________", ja: "研究所、協会", sentenceJa: "彼女は繁華街の研究所で働いている。" },
        { sentence: "The ___ process took nearly two months.", answer: "recruitment", base: "recruitment", hint: "r__________", ja: "採用、募集", sentenceJa: "その採用プロセスは2ヶ月近くかかった。" },
        { sentence: "She got the job through a ___ from a colleague.", answer: "referral", base: "referral", hint: "r_______", ja: "紹介、紹介状", sentenceJa: "彼女は同僚からの紹介でその仕事を得た。" },
        { sentence: "He was proud of his quick ___ at the company.", answer: "advancement", base: "advancement", hint: "a__________", ja: "昇進、進歩", sentenceJa: "彼は会社での急速な昇進を誇りに思っていた。" },
        { sentence: "You need ___ from the manager to access this file.", answer: "authorization", base: "authorization", hint: "a____________", ja: "許可、承認", sentenceJa: "このファイルにアクセスするにはマネージャーの許可が必要だ。" },
        { sentence: "Please submit all the required ___.", answer: "documentation", base: "documentation", hint: "d____________", ja: "書類、記録", sentenceJa: "必要な書類をすべて提出してください。" },
        { sentence: "The young ___ launched three companies before turning thirty.", answer: "entrepreneur", base: "entrepreneur", hint: "e___________", ja: "起業家", sentenceJa: "その若い起業家は30歳になる前に3つの会社を立ち上げた。" },
        { sentence: "The new ___ saved the factory a lot of time.", answer: "invention", base: "invention", hint: "i________", ja: "発明、発明品", sentenceJa: "その新しい発明は工場の多くの時間を節約した。" },
        { sentence: "The company filed a ___ for its new design.", answer: "patent", base: "patent", hint: "p_____", ja: "特許", sentenceJa: "その会社は新しいデザインの特許を出願した。" },
        { sentence: "The ___ finished the document in record time.", answer: "translator", base: "translator", hint: "t_________", ja: "翻訳者", sentenceJa: "その翻訳者は記録的な速さで書類を仕上げた。" },
        { sentence: "College ___ has increased significantly this year.", answer: "tuition", base: "tuition", hint: "t______", ja: "授業料", sentenceJa: "大学の授業料は今年大幅に上がった。" },
        { sentence: "The inspector reported a serious safety ___.", answer: "violation", base: "violation", hint: "v________", ja: "違反", sentenceJa: "検査官は重大な安全違反を報告した。" },
        { sentence: "She received her ___ letter from the university.", answer: "acceptance", base: "acceptance", hint: "a_________", ja: "受諾、承認", sentenceJa: "彼女は大学からの合格通知を受け取った。" },
        { sentence: "Please make the ___ before submitting the form.", answer: "correction", base: "correction", hint: "c_________", ja: "訂正、修正", sentenceJa: "フォームを提出する前に訂正をしてください。" },
        { sentence: "Her ___ to the project impressed the whole team.", answer: "dedication", base: "dedication", hint: "d_________", ja: "献身、専念", sentenceJa: "そのプロジェクトへの彼女の献身はチーム全体を感心させた。" },
        { sentence: "The long ___ damaged crops across the region.", answer: "drought", base: "drought", hint: "d______", ja: "干ばつ", sentenceJa: "長引く干ばつはその地域一帯の作物に被害を与えた。" },
        { sentence: "This car gets excellent ___ on the highway.", answer: "mileage", base: "mileage", hint: "m______", ja: "走行距離、マイル数", sentenceJa: "この車は高速道路で優れた燃費が出る。" },
        { sentence: "She sent a ___ about the deadline to the whole team.", answer: "reminder", base: "reminder", hint: "r_______", ja: "リマインダー", sentenceJa: "彼女は締め切りについてのリマインダーをチーム全員に送った。" },
        { sentence: "He spoke English with a slight French ___.", answer: "accent", base: "accent", hint: "a_____", ja: "訛り", sentenceJa: "彼はわずかにフランス語なまりの英語を話した。" },
        { sentence: "She stored her documents in a separate ___.", answer: "compartment", base: "compartment", hint: "c__________", ja: "区画", sentenceJa: "彼女は書類を別の区画に保管した。" },
      ],
    },
    {
      name: "Day 25",
      items: [
        { sentence: "Energy ___ drops during the holidays.", answer: "consumption", base: "consumption", hint: "c__________", ja: "消費、消費量", sentenceJa: "休暇中はエネルギー消費が減る。" },
        { sentence: "As a ___, the hotel offers free breakfast to all guests.", answer: "courtesy", base: "courtesy", hint: "c_______", ja: "礼儀、親切", sentenceJa: "サービスとして、そのホテルは全宿泊客に無料の朝食を提供している。" },
        { sentence: "The award celebrates ___ in design.", answer: "creativity", base: "creativity", hint: "c_________", ja: "創造性", sentenceJa: "その賞はデザインにおける創造性を称える。" },
        { sentence: "There was a brief ___ about the budget.", answer: "disagreement", base: "disagreement", hint: "d___________", ja: "意見の相違", sentenceJa: "予算について短い意見の相違があった。" },
        { sentence: "The ___ voted to change the schedule.", answer: "faculty", base: "faculty", hint: "f______", ja: "教員、学部", sentenceJa: "教員たちはスケジュールの変更に投票した。" },
        { sentence: "The company's ___ still works there part-time.", answer: "founder", base: "founder", hint: "f______", ja: "創業者", sentenceJa: "その会社の創業者は今もパートタイムでそこに勤めている。" },
        { sentence: "The company offers excellent ___ benefits.", answer: "healthcare", base: "healthcare", hint: "h_________", ja: "医療", sentenceJa: "その会社は優れた医療給付を提供している。" },
        { sentence: "The scandal brought unwanted ___ to the brand.", answer: "publicity", base: "publicity", hint: "p________", ja: "宣伝、注目", sentenceJa: "そのスキャンダルはそのブランドに望まない注目をもたらした。" },
        { sentence: "She updated the ___ with the latest figures.", answer: "spreadsheet", base: "spreadsheet", hint: "s__________", ja: "表計算シート", sentenceJa: "彼女は最新の数字で表計算シートを更新した。" },
        { sentence: "The company hired a new ___ for the region.", answer: "distributor", base: "distributor", hint: "d__________", ja: "販売代理店、卸売業者", sentenceJa: "その会社はその地域の新しい販売代理店を雇った。" },
        { sentence: "New employees receive ___ from a mentor.", answer: "guidance", base: "guidance", hint: "g_______", ja: "指導、助言", sentenceJa: "新入社員はメンターから指導を受ける。" },
        { sentence: "Sales figures are a key ___ of company health.", answer: "indicator", base: "indicator", hint: "i________", ja: "指標", sentenceJa: "売上高は会社の健全性を示す重要な指標だ。" },
        { sentence: "Remote work changed his entire ___.", answer: "lifestyle", base: "lifestyle", hint: "l________", ja: "ライフスタイル", sentenceJa: "リモートワークは彼のライフスタイル全体を変えた。" },
        { sentence: "The company's financial ___ improved this quarter.", answer: "outlook", base: "outlook", hint: "o______", ja: "見通し、展望", sentenceJa: "その会社の財務見通しは今四半期改善した。" },
        { sentence: "He bought his car from a local ___.", answer: "dealership", base: "dealership", hint: "d_________", ja: "販売代理店（自動車等）", sentenceJa: "彼は地元の販売代理店で車を買った。" },
        { sentence: "Turn off your phone to avoid ___ during the meeting.", answer: "distraction", base: "distraction", hint: "d__________", ja: "気を散らすもの", sentenceJa: "会議中に気が散らないよう携帯電話の電源を切ってください。" },
        { sentence: "The new schedule offers more ___ for employees.", answer: "flexibility", base: "flexibility", hint: "f__________", ja: "柔軟性", sentenceJa: "新しいスケジュールは従業員により多くの柔軟性を与える。" },
        { sentence: "The office uses a backup ___ during power outages.", answer: "generator", base: "generator", hint: "g________", ja: "発電機", sentenceJa: "そのオフィスは停電の際に予備の発電機を使う。" },
        { sentence: "The client requested a small ___ to the design.", answer: "modification", base: "modification", hint: "m___________", ja: "変更、修正", sentenceJa: "クライアントはデザインの小さな変更を求めた。" },
        { sentence: "Employees can request ___ for travel expenses.", answer: "reimbursement", base: "reimbursement", hint: "r____________", ja: "払い戻し、返金", sentenceJa: "従業員は出張費の払い戻しを請求できる。" },
      ],
    },
    {
      name: "Day 26",
      items: [
        { sentence: "Exposure to the chemical can be ___.", answer: "harmful", base: "harmful", hint: "h______", ja: "有害な", sentenceJa: "その化学物質にさらされることは有害な場合がある。" },
        { sentence: "The client found the final result ___.", answer: "satisfactory", base: "satisfactory", hint: "s___________", ja: "満足のいく", sentenceJa: "クライアントは最終的な結果に満足した。" },
        { sentence: "The hotel lobby has an ___ design.", answer: "elegant", base: "elegant", hint: "e______", ja: "上品な、優雅な", sentenceJa: "そのホテルのロビーは上品なデザインだ。" },
        { sentence: "The manager criticized the team's ___ spending.", answer: "excessive", base: "excessive", hint: "e________", ja: "過度な", sentenceJa: "マネージャーはチームの過度な支出を批判した。" },
        { sentence: "The store sells both brand-name and ___ products.", answer: "generic", base: "generic", hint: "g______", ja: "一般的な", sentenceJa: "その店はブランド品とジェネリック製品の両方を販売している。" },
        { sentence: "She received an ___ performance review.", answer: "exceptional", base: "exceptional", hint: "e__________", ja: "非常に優れた、例外的な", sentenceJa: "彼女は非常に優れた人事評価を受けた。" },
        { sentence: "He set an ___ goal for next year.", answer: "ambitious", base: "ambitious", hint: "a________", ja: "野心的な", sentenceJa: "彼は来年に向けて野心的な目標を立てた。" },
        { sentence: "The company promotes an ___ workplace.", answer: "inclusive", base: "inclusive", hint: "i________", ja: "包括的な", sentenceJa: "その会社は包括的な職場作りを推進している。" },
        { sentence: "The report was rejected due to ___ evidence.", answer: "insufficient", base: "insufficient", hint: "i___________", ja: "不十分な", sentenceJa: "その報告書は証拠不十分のため却下された。" },
        { sentence: "The restaurant serves ___ Italian cuisine.", answer: "authentic", base: "authentic", hint: "a________", ja: "本物の、本場の", sentenceJa: "そのレストランは本場のイタリア料理を提供している。" },
        { sentence: "Make sure the device is ___ with your computer.", answer: "compatible", base: "compatible", hint: "c_________", ja: "互換性のある", sentenceJa: "その機器がお使いのコンピューターと互換性があることを確認してください。" },
        { sentence: "The client responded to the proposal in a ___ way.", answer: "favorable", base: "favorable", hint: "f________", ja: "好意的な、有利な", sentenceJa: "クライアントはその提案に好意的に反応した。" },
        { sentence: "Workers must wear gear near ___ materials.", answer: "hazardous", base: "hazardous", hint: "h________", ja: "危険な", sentenceJa: "作業員は危険物の近くでは装備を着用しなければならない。" },
        { sentence: "She is one of the most ___ people in the industry.", answer: "influential", base: "influential", hint: "i__________", ja: "影響力のある", sentenceJa: "彼女はその業界で最も影響力のある人物の一人だ。" },
        { sentence: "The new manager brings an ___ approach to the team.", answer: "energetic", base: "energetic", hint: "e________", ja: "精力的な、活気のある", sentenceJa: "新しいマネージャーはチームに精力的な姿勢をもたらしている。" },
        { sentence: "We appreciate your ___ response to our request.", answer: "timely", base: "timely", hint: "t_____", ja: "時宜を得た", sentenceJa: "私たちの依頼への時宜を得たご返信に感謝いたします。" },
        { sentence: "The old chairs in the office are quite ___.", answer: "uncomfortable", base: "uncomfortable", hint: "u____________", ja: "不快な、座り心地の悪い", sentenceJa: "オフィスの古い椅子はかなり座り心地が悪い。" },
        { sentence: "The company made a ___ decision to enter a new market.", answer: "strategic", base: "strategic", hint: "s________", ja: "戦略的な", sentenceJa: "その会社は新市場に参入するという戦略的な決断をした。" },
        { sentence: "It is ___ that everyone attend the safety training.", answer: "imperative", base: "imperative", hint: "i_________", ja: "不可欠な、必須の", sentenceJa: "全員が安全研修に出席することが不可欠だ。" },
        { sentence: "She wanted her work to feel more ___.", answer: "meaningful", base: "meaningful", hint: "m_________", ja: "やりがいのある、意味のある", sentenceJa: "彼女は自分の仕事がもっとやりがいのあるものに感じられることを望んでいた。" },
      ],
    },
    {
      name: "Day 27",
      items: [
        { sentence: "The new policy affects small businesses ___.", answer: "economically", base: "economically", hint: "e___________", ja: "経済的に", sentenceJa: "その新しい方針は中小企業に経済的な影響を与える。" },
        { sentence: "This offer is available ___ to members.", answer: "exclusively", base: "exclusively", hint: "e__________", ja: "独占的に、限定で", sentenceJa: "このオファーは会員限定でご利用いただけます。" },
        { sentence: "The merger was ___ announced this morning.", answer: "officially", base: "officially", hint: "o_________", ja: "正式に", sentenceJa: "その合併は今朝、正式に発表された。" },
        { sentence: "The event was ___ organized this year.", answer: "poorly", base: "poorly", hint: "p_____", ja: "不十分に、下手に", sentenceJa: "そのイベントは今年、準備が不十分だった。" },
        { sentence: "He complained ___ about the delay.", answer: "loudly", base: "loudly", hint: "l_____", ja: "大声で", sentenceJa: "彼は遅延について大声で不満を言った。" },
        { sentence: "The company has ___ hired from local universities.", answer: "traditionally", base: "traditionally", hint: "t____________", ja: "伝統的に", sentenceJa: "その会社は伝統的に地元の大学から採用してきた。" },
        { sentence: "The new chairs let employees sit ___ all day.", answer: "comfortably", base: "comfortably", hint: "c__________", ja: "快適に", sentenceJa: "新しい椅子は従業員が一日中快適に座れるようにしている。" },
        { sentence: "All invoices are now submitted ___.", answer: "electronically", base: "electronically", hint: "e_____________", ja: "電子的に", sentenceJa: "全ての請求書は現在、電子的に提出されている。" },
        { sentence: "The flight was delayed, but they arrived on time ___.", answer: "anyhow", base: "anyhow", hint: "a_____", ja: "とにかく、それでも", sentenceJa: "フライトは遅れたが、それでも彼らは時間通りに到着した。" },
        { sentence: "Sales were ___ high this month.", answer: "unusually", base: "unusually", hint: "u________", ja: "異常に、いつになく", sentenceJa: "今月の売上は異常に高かった。" },
        { sentence: "___, the shipment arrived before the deadline.", answer: "fortunately", base: "fortunately", hint: "f__________", ja: "幸いにも", sentenceJa: "幸いにも、その荷物は締め切り前に到着した。" },
        { sentence: "The new factory was designed to be ___ friendly.", answer: "environmentally", base: "environmentally", hint: "e______________", ja: "環境的に", sentenceJa: "その新しい工場は環境に優しく設計された。" },
        { sentence: "The staff ___ welcomed the new policy.", answer: "enthusiastically", base: "enthusiastically", hint: "e_______________", ja: "熱心に", sentenceJa: "スタッフはその新しい方針を熱心に歓迎した。" },
        { sentence: "The old branch was ___ closed last year.", answer: "permanently", base: "permanently", hint: "p__________", ja: "恒久的に", sentenceJa: "その古い支店は去年、恒久的に閉鎖された。" },
        { sentence: "The project was only ___ completed by the deadline.", answer: "partially", base: "partially", hint: "p________", ja: "部分的に", sentenceJa: "そのプロジェクトは締め切りまでに部分的にしか完了しなかった。" },
        { sentence: "Prices ___ increased after the shortage.", answer: "drastically", base: "drastically", hint: "d__________", ja: "急激に", sentenceJa: "その不足の後、価格は急激に上昇した。" },
        { sentence: "She is ___ looking for a new job.", answer: "actively", base: "actively", hint: "a_______", ja: "積極的に", sentenceJa: "彼女は積極的に新しい仕事を探している。" },
        { sentence: "The interviewer listened ___ to every answer.", answer: "intently", base: "intently", hint: "i_______", ja: "熱心に、じっと", sentenceJa: "面接官は一つ一つの回答に熱心に耳を傾けた。" },
        { sentence: "I ___ confirm my attendance at the meeting.", answer: "hereby", base: "hereby", hint: "h_____", ja: "ここに、これをもって", sentenceJa: "私はここに、会議への出席を確認いたします。" },
        { sentence: "The system ___ saves your work every five minutes.", answer: "automatically", base: "automatically", hint: "a____________", ja: "自動的に", sentenceJa: "そのシステムは5分ごとに自動的に作業内容を保存する。" },
      ],
    },
    {
      name: "Day 29",
      items: [
        { sentence: "Last year, the CEO ___ the team's effort at the ceremony.", answer: "acknowledged", base: "acknowledge", hint: "a__________", ja: "認める、謝意を示す", sentenceJa: "昨年、CEOは式典でチームの努力を認めた。" },
        { sentence: "Last week, the company ___ record profits.", answer: "announced", base: "announce", hint: "a_______", ja: "発表する", sentenceJa: "先週、その会社は記録的な利益を発表した。" },
        { sentence: "The board will ___ a new CFO next month.", answer: "appoint", base: "appoint", hint: "a______", ja: "任命する", sentenceJa: "取締役会は来月、新しいCFOを任命する予定だ。" },
        { sentence: "Please ___ this task to a junior staff member.", answer: "assign", base: "assign", hint: "a_____", ja: "割り当てる", sentenceJa: "このタスクは若手スタッフに割り当ててください。" },
        { sentence: "Last year, the committee ___ the prize to a local scientist.", answer: "awarded", base: "award", hint: "a____", ja: "授与する", sentenceJa: "昨年、委員会はその賞を地元の科学者に授与した。" },
        { sentence: "Last quarter, the new campaign ___ sales significantly.", answer: "boosted", base: "boost", hint: "b____", ja: "押し上げる、高める", sentenceJa: "前四半期、その新しいキャンペーンは売上を大幅に押し上げた。" },
        { sentence: "Yesterday, the manager ___ the staff on the new policy.", answer: "briefed", base: "brief", hint: "b____", ja: "説明する、簡単に伝える", sentenceJa: "昨日、マネージャーはスタッフに新しい方針について説明した。" },
        { sentence: "Please ___ for the workshop before Friday.", answer: "register", base: "register", hint: "r_______", ja: "登録する", sentenceJa: "金曜日までにワークショップに登録してください。" },
        { sentence: "Last month, the hotel ___ an extra fee for late checkout.", answer: "charged", base: "charge", hint: "c_____", ja: "請求する", sentenceJa: "先月、そのホテルは遅いチェックアウトに追加料金を請求した。" },
        { sentence: "She will ___ the committee meeting on Thursday.", answer: "chair", base: "chair", hint: "c____", ja: "議長を務める", sentenceJa: "彼女は木曜日の委員会会議で議長を務める予定だ。" },
        { sentence: "Last quarter, the two departments ___ closely on the launch.", answer: "collaborated", base: "collaborate", hint: "c__________", ja: "協力する", sentenceJa: "前四半期、その二つの部署は発売に向けて緊密に協力した。" },
        { sentence: "Please ___ the two reports into one document.", answer: "combine", base: "combine", hint: "c______", ja: "組み合わせる", sentenceJa: "その二つの報告書を一つの文書にまとめてください。" },
        { sentence: "Construction ___ last Monday.", answer: "commenced", base: "commence", hint: "c_______", ja: "開始する", sentenceJa: "工事は先週の月曜日に開始した。" },
        { sentence: "Last year, the museum ___ a new sculpture.", answer: "commissioned", base: "commission", hint: "c_________", ja: "委託する、依頼する", sentenceJa: "昨年、その美術館は新しい彫刻を依頼した。" },
        { sentence: "Please ___ your supervisor before making changes.", answer: "consult", base: "consult", hint: "c______", ja: "相談する", sentenceJa: "変更を加える前に上司に相談してください。" },
        { sentence: "The panel ___ last week to review the case.", answer: "convened", base: "convene", hint: "c______", ja: "招集する、開催する", sentenceJa: "審査団は先週、その案件を検討するために招集された。" },
        { sentence: "Last year, the company ___ costs across all departments.", answer: "cut", base: "cut", hint: "c__", ja: "削減する", sentenceJa: "昨年、その会社は全部署にわたってコストを削減した。" },
        { sentence: "Last week, the company ___ its offer after negotiations failed.", answer: "withdrew", base: "withdraw", hint: "w_______", ja: "撤回する、引き出す", sentenceJa: "先週、その会社は交渉が決裂した後に申し出を撤回した。" },
        { sentence: "He decided to ___ the job offer.", answer: "decline", base: "decline", hint: "d______", ja: "断る、減少する", sentenceJa: "彼はその仕事のオファーを断ることに決めた。" },
        { sentence: "Last year, she ___ the award to her mentor.", answer: "dedicated", base: "dedicate", hint: "d_______", ja: "捧げる", sentenceJa: "昨年、彼女はその賞を恩師に捧げた。" },
      ],
    },
    {
      name: "Day 30",
      items: [
        { sentence: "Yesterday, the courier ___ the package by noon.", answer: "delivered", base: "deliver", hint: "d______", ja: "配達する、実現する", sentenceJa: "昨日、配達員は正午までにその荷物を配達した。" },
        { sentence: "Last month, the company ___ the new system company-wide.", answer: "deployed", base: "deploy", hint: "d_____", ja: "配備する、展開する", sentenceJa: "先月、その会社は新しいシステムを全社的に展開した。" },
        { sentence: "The sensor can ___ even small changes in temperature.", answer: "detect", base: "detect", hint: "d_____", ja: "検出する", sentenceJa: "そのセンサーはわずかな温度変化さえも検出できる。" },
        { sentence: "Last year, the firm ___ into new markets.", answer: "diversified", base: "diversify", hint: "d________", ja: "多角化する", sentenceJa: "昨年、その企業は新しい市場へと多角化した。" },
        { sentence: "Last year, she ___ a promotion after years of hard work.", answer: "earned", base: "earn", hint: "e___", ja: "稼ぐ、獲得する", sentenceJa: "昨年、彼女は長年の努力の末、昇進を勝ち取った。" },
        { sentence: "Last year, the celebrity ___ the new product.", answer: "endorsed", base: "endorse", hint: "e______", ja: "支持する、推薦する", sentenceJa: "昨年、その有名人は新製品を宣伝した。" },
        { sentence: "Last week, the speaker ___ the audience with real examples.", answer: "engaged", base: "engage", hint: "e_____", ja: "従事させる、引き付ける", sentenceJa: "先週、その講演者は実例で聴衆を引き付けた。" },
        { sentence: "The manager decided to ___ help from another department.", answer: "enlist", base: "enlist", hint: "e_____", ja: "協力を求める、入隊する", sentenceJa: "マネージャーは他部署から協力を求めることに決めた。" },
        { sentence: "Last week, the dispute ___ quickly.", answer: "escalated", base: "escalate", hint: "e_______", ja: "拡大する", sentenceJa: "先週、その論争は急速にエスカレートした。" },
        { sentence: "Sales this quarter will ___ last year's total.", answer: "exceed", base: "exceed", hint: "e_____", ja: "超える", sentenceJa: "今四半期の売上は昨年の総計を超える予定だ。" },
        { sentence: "Please ___ the deadline by one week.", answer: "extend", base: "extend", hint: "e_____", ja: "延長する", sentenceJa: "締め切りを1週間延長してください。" },
        { sentence: "Last month, the company ___ a patent for its new invention.", answer: "filed", base: "file", hint: "f___", ja: "提出する、申請する", sentenceJa: "先月、その会社は新しい発明の特許を出願した。" },
        { sentence: "Last month, analysts ___ steady growth for next year.", answer: "forecasted", base: "forecast", hint: "f_______", ja: "予測する", sentenceJa: "先月、アナリストは来年の着実な成長を予測した。" },
        { sentence: "The company wants to ___ its top talent.", answer: "retain", base: "retain", hint: "r_____", ja: "保持する、維持する", sentenceJa: "その会社は優秀な人材を維持したいと考えている。" },
        { sentence: "Last year, the government ___ the company a special license.", answer: "granted", base: "grant", hint: "g____", ja: "付与する、認める", sentenceJa: "昨年、政府はその会社に特別な免許を付与した。" },
        { sentence: "The company plans to ___ ten new employees this year.", answer: "hire", base: "hire", hint: "h___", ja: "雇う", sentenceJa: "その会社は今年、新入社員を10人雇う計画だ。" },
        { sentence: "Last quarter, the school ___ a new grading system.", answer: "implemented", base: "implement", hint: "i________", ja: "実施する", sentenceJa: "前四半期、その学校は新しい成績評価システムを実施した。" },
        { sentence: "The company will ___ the new product next month.", answer: "launch", base: "launch", hint: "l_____", ja: "開始する、発売する", sentenceJa: "その会社は来月、新製品を発売する予定だ。" },
        { sentence: "Last year, the bank ___ the annual charity run.", answer: "sponsored", base: "sponsor", hint: "s______", ja: "後援する", sentenceJa: "昨年、その銀行は毎年恒例のチャリティーランを後援した。" },
        { sentence: "Please ___ the contract before Friday.", answer: "sign", base: "sign", hint: "s___", ja: "署名する", sentenceJa: "金曜日までに契約書に署名してください。" },
      ],
    },
  ],
};
