// IELTS 単語テスト問題（PDFのWord List例文から生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
module.exports = {
  label: "IELTS",
  series: [
    {
      name: "Day 1",
      items: [
        { sentence: "Last year, researchers ___ the data from a large national survey.", answer: "obtained", base: "obtain", hint: "o_______", ja: "得る、入手する", sentenceJa: "昨年、研究者たちは大規模な全国調査からデータを入手した。" },
        { sentence: "Modern technology currently ___ communication between countries.", answer: "facilitates", base: "facilitate", hint: "f__________", ja: "促進する、容易にする", sentenceJa: "現代の技術は現在、国家間のコミュニケーションを促進している。" },
        { sentence: "Children learn social skills by ___ with others.", answer: "interacting", base: "interact", hint: "i__________", ja: "相互に作用する、交流する", sentenceJa: "子供たちは他者と交流することで社会的スキルを学ぶ。" },
        { sentence: "It is difficult to ___ the two closely related species.", answer: "differentiate", base: "differentiate", hint: "d____________", ja: "区別する", sentenceJa: "近縁の2種を区別するのは難しい。" },
        { sentence: "Scientists must carefully ___ the results of the study.", answer: "interpret", base: "interpret", hint: "i________", ja: "解釈する", sentenceJa: "科学者は研究結果を慎重に解釈しなければならない。" },
        { sentence: "Last month, researchers ___ the temperature to test the reaction.", answer: "manipulated", base: "manipulate", hint: "m__________", ja: "操作する", sentenceJa: "先月、研究者たちは反応を調べるために温度を操作した。" },
        { sentence: "Currently, wind farms ___ electricity without producing pollution.", answer: "generate", base: "generate", hint: "g_______", ja: "生み出す、発生させる", sentenceJa: "現在、風力発電所は汚染を出さずに電気を生み出している。" },
        { sentence: "It is hard to ___ of a society without any rules.", answer: "conceive", base: "conceive", hint: "c_______", ja: "思いつく、想像する", sentenceJa: "ルールが全くない社会を思い描くのは難しい。" },
        { sentence: "The company currently ___ natural resources in the region.", answer: "exploits", base: "exploit", hint: "e_______", ja: "活用する、搾取する", sentenceJa: "その会社は現在、その地域の天然資源を活用している。" },
        { sentence: "Last year, limited funding ___ the scope of the research.", answer: "constrained", base: "constrain", hint: "c__________", ja: "制約する", sentenceJa: "昨年、限られた資金が研究の範囲を制約した。" },
        { sentence: "Historically, many modern words still ___ from Latin and Greek.", answer: "derive", base: "derive", hint: "d_____", ja: "（～から）得る、由来する", sentenceJa: "歴史的に、多くの現代語は今でもラテン語やギリシャ語に由来する。" },
        { sentence: "Certain chemicals can ___ changes in cell growth.", answer: "induce", base: "induce", hint: "i_____", ja: "引き起こす、誘発する", sentenceJa: "特定の化学物質は細胞の成長に変化を引き起こすことがある。" },
        { sentence: "This painting still ___ a busy market in the old city.", answer: "depicts", base: "depict", hint: "d______", ja: "描く、表現する", sentenceJa: "この絵は今も旧市街の賑やかな市場を描いている。" },
        { sentence: "To this day, the author ___ that education reduces inequality.", answer: "asserts", base: "assert", hint: "a______", ja: "主張する、断言する", sentenceJa: "今日に至るまで、その著者は教育が不平等を減らすと主張している。" },
        { sentence: "The school aims to ___ technology into every subject.", answer: "integrate", base: "integrate", hint: "i________", ja: "統合する", sentenceJa: "その学校はあらゆる科目に技術を統合することを目指している。" },
        { sentence: "The government may ___ when prices rise too sharply.", answer: "intervene", base: "intervene", hint: "i________", ja: "介入する", sentenceJa: "価格が急激に上昇した場合、政府が介入することがある。" },
        { sentence: "The teacher tried to ___ the difficult concept.", answer: "clarify", base: "clarify", hint: "c______", ja: "明確にする", sentenceJa: "先生はその難しい概念を明確にしようとした。" },
        { sentence: "Currently, a few large firms ___ the global market.", answer: "dominate", base: "dominate", hint: "d_______", ja: "支配する、優位を占める", sentenceJa: "現在、少数の大企業が世界市場を支配している。" },
        { sentence: "The city has ___ major changes in recent decades.", answer: "undergone", base: "undergo", hint: "u________", ja: "経験する、受ける", sentenceJa: "その都市はここ数十年で大きな変化を経験した。" },
        { sentence: "Even now, sediment ___ slowly at the bottom of the lake.", answer: "accumulates", base: "accumulate", hint: "a__________", ja: "蓄積する", sentenceJa: "今でも、堆積物は湖の底にゆっくりと蓄積している。" },
      ],
    },
    {
      name: "Day 2",
      items: [
        { sentence: "The government will ___ more funds to public health.", answer: "allocate", base: "allocate", hint: "a_______", ja: "割り当てる、配分する", sentenceJa: "政府は公衆衛生にさらに多くの資金を割り当てる予定だ。" },
        { sentence: "Extra training can ___ for a lack of experience.", answer: "compensate", base: "compensate", hint: "c_________", ja: "埋め合わせる、補償する", sentenceJa: "追加の訓練は経験不足を埋め合わせることができる。" },
        { sentence: "Generally, scientists ___ living things into several kingdoms.", answer: "classify", base: "classify", hint: "c_______", ja: "分類する", sentenceJa: "一般的に、科学者は生物をいくつかの界に分類する。" },
        { sentence: "We should ___ water during the dry season.", answer: "conserve", base: "conserve", hint: "c_______", ja: "保存する、節約する", sentenceJa: "乾季には水を節約すべきだ。" },
        { sentence: "Generally, plants ___ sunlight into energy.", answer: "convert", base: "convert", hint: "c______", ja: "変える、転換する", sentenceJa: "一般的に、植物は太陽光をエネルギーに変換する。" },
        { sentence: "The new system aims to ___ waste.", answer: "eliminate", base: "eliminate", hint: "e________", ja: "排除する", sentenceJa: "新しいシステムは無駄を排除することを目指している。" },
        { sentence: "Reading widely can ___ your writing skills.", answer: "enhance", base: "enhance", hint: "e______", ja: "高める、向上させる", sentenceJa: "幅広く読書することは文章力を高めることができる。" },
        { sentence: "Experts currently ___ that the population will double by 2050.", answer: "estimate", base: "estimate", hint: "e_______", ja: "推定する、見積もる", sentenceJa: "専門家は現在、2050年までに人口が倍増すると推定している。" },
        { sentence: "These days, teachers ___ students through exams and projects.", answer: "evaluate", base: "evaluate", hint: "e_______", ja: "評価する", sentenceJa: "近頃、教師は試験や課題を通して生徒を評価する。" },
        { sentence: "This study currently ___ the effects of stress on health.", answer: "examines", base: "examine", hint: "e_______", ja: "詳しく調べる", sentenceJa: "この研究は現在、ストレスが健康に与える影響を詳しく調べている。" },
        { sentence: "These results currently ___ a clear link between diet and health.", answer: "demonstrate", base: "demonstrate", hint: "d__________", ja: "実証する、示す", sentenceJa: "これらの結果は現在、食事と健康の明確な関連性を示している。" },
        { sentence: "New evidence has ___ about the cause of the illness.", answer: "emerged", base: "emerge", hint: "e______", ja: "現れる、明らかになる", sentenceJa: "その病気の原因について新たな証拠が明らかになった。" },
        { sentence: "Last month, engineers ___ the design to reduce the cost.", answer: "modified", base: "modify", hint: "m_______", ja: "修正する、変更する", sentenceJa: "先月、エンジニアはコストを削減するために設計を変更した。" },
        { sentence: "Burning fossil fuels currently ___ to climate change.", answer: "contributes", base: "contribute", hint: "c__________", ja: "貢献する、一因となる", sentenceJa: "化石燃料の燃焼は現在、気候変動の一因となっている。" },
        { sentence: "Generally, children ___ language quickly in their early years.", answer: "acquire", base: "acquire", hint: "a______", ja: "習得する、獲得する", sentenceJa: "一般的に、子供は幼少期に言語を素早く習得する。" },
        { sentence: "Doctors always ___ each patient before deciding on treatment.", answer: "assess", base: "assess", hint: "a_____", ja: "評価する、査定する", sentenceJa: "医師はいつも、治療方針を決める前に各患者を評価する。" },
        { sentence: "Wealth is not evenly ___ across the country.", answer: "distributed", base: "distribute", hint: "d__________", ja: "分配する、分布させる", sentenceJa: "富はその国全体に均等に分配されていない。" },
        { sentence: "This survey currently ___ that most people support the plan.", answer: "indicates", base: "indicate", hint: "i________", ja: "示す、示唆する", sentenceJa: "この調査は現在、大多数の人がその計画を支持していることを示している。" },
        { sentence: "These findings currently ___ the need for stricter rules.", answer: "reinforce", base: "reinforce", hint: "r________", ja: "強化する、補強する", sentenceJa: "これらの調査結果は現在、より厳格な規則の必要性を強化している。" },
        { sentence: "It is hard to ___ economic growth for many years.", answer: "sustain", base: "sustain", hint: "s______", ja: "維持する、持続させる", sentenceJa: "長年にわたって経済成長を維持することは難しい。" },
      ],
    },
    {
      name: "Day 3",
      items: [
        { sentence: "The experiment was designed to test the ___.", answer: "hypothesis", base: "hypothesis", hint: "h_________", ja: "仮説", sentenceJa: "その実験は仮説を検証するために設計された。" },
        { sentence: "The essay examines several ___ of urban life.", answer: "aspects", base: "aspect", hint: "a______", ja: "側面、観点", sentenceJa: "そのエッセイは都市生活のいくつかの側面を考察している。" },
        { sentence: "Applications are judged against three main ___.", answer: "criteria", base: "criteria", hint: "c_______", ja: "基準", sentenceJa: "応募は3つの主要な基準に基づいて審査される。" },
        { sentence: "The company has a strict ___ of management.", answer: "hierarchy", base: "hierarchy", hint: "h________", ja: "階層、序列", sentenceJa: "その会社には厳格な管理階層がある。" },
        { sentence: "Global warming is a worldwide ___.", answer: "phenomenon", base: "phenomenon", hint: "p_________", ja: "現象", sentenceJa: "地球温暖化は世界的な現象である。" },
        { sentence: "Scientists have reached a ___ on climate change.", answer: "consensus", base: "consensus", hint: "c________", ja: "合意、総意", sentenceJa: "科学者たちは気候変動について合意に達した。" },
        { sentence: "She faced a ___ between work and family.", answer: "dilemma", base: "dilemma", hint: "d______", ja: "ジレンマ、板挟み", sentenceJa: "彼女は仕事と家庭の間でジレンマに直面した。" },
        { sentence: "The study provides a useful ___ for future research.", answer: "framework", base: "framework", hint: "f________", ja: "枠組み", sentenceJa: "その研究は今後の研究に役立つ枠組みを提供している。" },
        { sentence: "The ___ of the disease has fallen in recent years.", answer: "incidence", base: "incidence", hint: "i________", ja: "発生率", sentenceJa: "その病気の発生率は近年低下している。" },
        { sentence: "The country invested heavily in its ___.", answer: "infrastructure", base: "infrastructure", hint: "i_____________", ja: "インフラ、社会基盤", sentenceJa: "その国はインフラに多額の投資をした。" },
        { sentence: "The researchers explained their ___ in detail.", answer: "methodology", base: "methodology", hint: "m__________", ja: "方法論", sentenceJa: "研究者たちは自分たちの方法論を詳しく説明した。" },
        { sentence: "Working from home has become the ___ for many people.", answer: "norm", base: "norm", hint: "n___", ja: "規範、標準", sentenceJa: "在宅勤務は多くの人にとって当たり前のことになった。" },
        { sentence: "The ___ of the election surprised many people.", answer: "outcome", base: "outcome", hint: "o______", ja: "結果", sentenceJa: "選挙の結果は多くの人を驚かせた。" },
        { sentence: "It is a ___ that the wealthiest nations waste the most food.", answer: "paradox", base: "paradox", hint: "p______", ja: "逆説、矛盾", sentenceJa: "最も裕福な国々が最も多くの食料を無駄にしているのは逆説的だ。" },
        { sentence: "The book offers a fresh ___ on history.", answer: "perspective", base: "perspective", hint: "p__________", ja: "観点、見方", sentenceJa: "その本は歴史について新しい視点を提供している。" },
        { sentence: "There is a wide ___ in income between regions.", answer: "disparity", base: "disparity", hint: "d________", ja: "格差、相違", sentenceJa: "地域間の所得格差は大きい。" },
        { sentence: "The ___ that the earth was flat lasted for centuries.", answer: "notion", base: "notion", hint: "n_____", ja: "観念、概念", sentenceJa: "地球が平らだという考えは何世紀にもわたって続いた。" },
        { sentence: "The ecosystem maintains a delicate ___.", answer: "equilibrium", base: "equilibrium", hint: "e__________", ja: "均衡", sentenceJa: "その生態系は微妙な均衡を保っている。" },
        { sentence: "Each branch operates as a separate legal ___.", answer: "entity", base: "entity", hint: "e_____", ja: "存在、実体", sentenceJa: "各支店は独立した法人として運営されている。" },
        { sentence: "The ___ of the internet changed daily life.", answer: "emergence", base: "emergence", hint: "e________", ja: "出現", sentenceJa: "インターネットの出現は日常生活を変えた。" },
      ],
    },
    {
      name: "Day 4",
      items: [
        { sentence: "A careful ___ of the data revealed a clear pattern.", answer: "analysis", base: "analysis", hint: "a_______", ja: "分析", sentenceJa: "データの慎重な分析により、明確なパターンが明らかになった。" },
        { sentence: "Diet is an important ___ in good health.", answer: "factor", base: "factor", hint: "f_____", ja: "要因", sentenceJa: "食事は健康にとって重要な要因である。" },
        { sentence: "Soil erosion is a serious ___ of deforestation.", answer: "consequence", base: "consequence", hint: "c__________", ja: "結果、影響", sentenceJa: "土壌浸食は森林伐採の深刻な結果である。" },
        { sentence: "The study has several important ___ for public policy.", answer: "implications", base: "implication", hint: "i___________", ja: "影響、含意", sentenceJa: "その研究は公共政策にとっていくつかの重要な影響を持つ。" },
        { sentence: "There is a growing ___ toward remote working.", answer: "trend", base: "trend", hint: "t____", ja: "傾向、動向", sentenceJa: "リモートワークへの傾向が高まっている。" },
        { sentence: "A large ___ of students own a smartphone.", answer: "proportion", base: "proportion", hint: "p_________", ja: "割合", sentenceJa: "学生の大部分がスマートフォンを持っている。" },
        { sentence: "The map shows the ___ of rainfall across the country.", answer: "distribution", base: "distribution", hint: "d___________", ja: "分布、分配", sentenceJa: "その地図は国内の降雨の分布を示している。" },
        { sentence: "There is a strong ___ between income and education.", answer: "correlation", base: "correlation", hint: "c__________", ja: "相関関係", sentenceJa: "収入と教育の間には強い相関関係がある。" },
        { sentence: "The experiment controlled every ___ except temperature.", answer: "variable", base: "variable", hint: "v_______", ja: "変数、変化要因", sentenceJa: "その実験は温度以外のすべての変数を制御した。" },
        { sentence: "Trust is a key ___ of any good relationship.", answer: "element", base: "element", hint: "e______", ja: "要素", sentenceJa: "信頼はどんな良い関係にとっても重要な要素である。" },
        { sentence: "There is strong ___ that exercise improves mood.", answer: "evidence", base: "evidence", hint: "e_______", ja: "証拠", sentenceJa: "運動が気分を改善するという強い証拠がある。" },
        { sentence: "The ___ of voters supported the new law.", answer: "majority", base: "majority", hint: "m_______", ja: "大多数", sentenceJa: "有権者の大多数が新しい法律を支持した。" },
        { sentence: "The city has changed greatly over the past ___.", answer: "decade", base: "decade", hint: "d_____", ja: "10年間", sentenceJa: "その都市はこの10年間で大きく変化した。" },
        { sentence: "The main ___ of the heart is to pump blood.", answer: "function", base: "function", hint: "f_______", ja: "機能", sentenceJa: "心臓の主な機能は血液を送り出すことである。" },
        { sentence: "Books in the library are arranged by ___.", answer: "category", base: "category", hint: "c_______", ja: "カテゴリー、分類", sentenceJa: "図書館の本はカテゴリー別に並べられている。" },
        { sentence: "Safety is the company's top ___.", answer: "priority", base: "priority", hint: "p_______", ja: "優先事項", sentenceJa: "安全はその会社の最優先事項である。" },
        { sentence: "Water is a precious natural ___.", answer: "resource", base: "resource", hint: "r_______", ja: "資源", sentenceJa: "水は貴重な天然資源である。" },
        { sentence: "The two groups have been in ___ for years.", answer: "conflict", base: "conflict", hint: "c_______", ja: "対立、紛争", sentenceJa: "その2つのグループは長年対立してきた。" },
        { sentence: "The country is going through a ___ to clean energy.", answer: "transition", base: "transition", hint: "t_________", ja: "移行、変遷", sentenceJa: "その国はクリーンエネルギーへの移行を経験している。" },
        { sentence: "The government is responsible for the ___ of its citizens.", answer: "welfare", base: "welfare", hint: "w______", ja: "福祉、幸福", sentenceJa: "政府は国民の福祉に責任がある。" },
      ],
    },
    {
      name: "Day 5",
      items: [
        { sentence: "There was a ___ increase in average temperatures.", answer: "significant", base: "significant", hint: "s__________", ja: "重要な、著しい", sentenceJa: "平均気温に著しい上昇があった。" },
        { sentence: "English is the ___ language in international business.", answer: "dominant", base: "dominant", hint: "d_______", ja: "支配的な、優勢な", sentenceJa: "英語は国際ビジネスにおいて支配的な言語である。" },
        { sentence: "The instructions were ___ about what to do.", answer: "explicit", base: "explicit", hint: "e_______", ja: "明示的な、明確な", sentenceJa: "指示は何をすべきかについて明確だった。" },
        { sentence: "The book gives a ___ overview of the subject.", answer: "comprehensive", base: "comprehensive", hint: "c____________", ja: "包括的な、総合的な", sentenceJa: "その本はそのテーマについて包括的な概要を示している。" },
        { sentence: "The city is home to a ___ range of cultures.", answer: "diverse", base: "diverse", hint: "d______", ja: "多様な", sentenceJa: "その都市には多様な文化がある。" },
        { sentence: "Some conflict is ___ in any large group.", answer: "inevitable", base: "inevitable", hint: "i_________", ja: "避けられない", sentenceJa: "どんな大きな集団にも、ある程度の対立は避けられない。" },
        { sentence: "The project required a ___ amount of money.", answer: "substantial", base: "substantial", hint: "s__________", ja: "かなりの、相当な", sentenceJa: "そのプロジェクトにはかなりの額のお金が必要だった。" },
        { sentence: "A good essay presents a ___ argument.", answer: "coherent", base: "coherent", hint: "c_______", ja: "首尾一貫した", sentenceJa: "良いエッセイは首尾一貫した論旨を示す。" },
        { sentence: "It was ___ that the new method had failed.", answer: "evident", base: "evident", hint: "e______", ja: "明白な", sentenceJa: "新しい方法が失敗したことは明白だった。" },
        { sentence: "The claim is supported by strong ___ evidence.", answer: "empirical", base: "empirical", hint: "e________", ja: "経験的な、実証的な", sentenceJa: "その主張は強力な実証的証拠に裏付けられている。" },
        { sentence: "Sleep plays a ___ role in learning and memory.", answer: "crucial", base: "crucial", hint: "c______", ja: "極めて重要な", sentenceJa: "睡眠は学習と記憶において極めて重要な役割を果たす。" },
        { sentence: "Please include only ___ information in your essay.", answer: "relevant", base: "relevant", hint: "r_______", ja: "関連のある", sentenceJa: "エッセイには関連のある情報だけを含めてください。" },
        { sentence: "The funding was barely ___ for the research.", answer: "adequate", base: "adequate", hint: "a_______", ja: "十分な、適切な", sentenceJa: "その研究資金はかろうじて十分な程度だった。" },
        { sentence: "The two species have ___ markings.", answer: "distinct", base: "distinct", hint: "d_______", ja: "明確に異なる", sentenceJa: "その2種は明確に異なる模様を持っている。" },
        { sentence: "The survey question was ___ and confused readers.", answer: "ambiguous", base: "ambiguous", hint: "a________", ja: "曖昧な", sentenceJa: "その調査質問は曖昧で、回答者を混乱させた。" },
        { sentence: "Building the bridge in one year is not ___.", answer: "feasible", base: "feasible", hint: "f_______", ja: "実行可能な", sentenceJa: "1   年でその橋を建設するのは実行可能ではない。" },
        { sentence: "Smartphones are now ___ among young people.", answer: "prevalent", base: "prevalent", hint: "p________", ja: "広く行き渡った", sentenceJa: "スマートフォンは今、若者の間で広く行き渡っている。" },
        { sentence: "The product went through ___ safety testing.", answer: "rigorous", base: "rigorous", hint: "r_______", ja: "厳密な、厳格な", sentenceJa: "その製品は厳密な安全性試験を受けた。" },
        { sentence: "The first test failed, but ___ attempts succeeded.", answer: "subsequent", base: "subsequent", hint: "s_________", ja: "その後の", sentenceJa: "最初のテストは失敗したが、その後の試みは成功した。" },
        { sentence: "Clean water is ___ for human health.", answer: "vital", base: "vital", hint: "v____", ja: "極めて重要な、不可欠な", sentenceJa: "清潔な水は人間の健康にとって極めて重要だ。" },
      ],
    },
  ],
};
