// TOEIC 単語テスト問題（PDFのWord List例文から生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
module.exports = {
  label: "TOEIC",
  series: [
    {
      name: "Day 1",
      items: [
        { sentence: "The company will ___ its annual report next week.", answer: "publish", base: "publish", hint: "p______", ja: "出版する、公表する", sentenceJa: "その会社は来週、年次報告書を公表する予定だ。" },
        { sentence: "Please ___ a copy of your receipt with the form.", answer: "enclose", base: "enclose", hint: "e______", ja: "同封する", sentenceJa: "フォームに領収書のコピーを同封してください。" },
        { sentence: "We will ___ you as soon as your order ships.", answer: "notify", base: "notify", hint: "n_____", ja: "通知する", sentenceJa: "ご注文の発送準備が整い次第、ご連絡いたします。" },
        { sentence: "You can ___ a visitor's pass at the front desk.", answer: "obtain", base: "obtain", hint: "o_____", ja: "入手する、得る", sentenceJa: "受付で来客用パスを受け取ることができます。" },
        { sentence: "The manager decided to ___ the meeting until Friday.", answer: "postpone", base: "postpone", hint: "p_______", ja: "延期する", sentenceJa: "マネージャーは会議を金曜日まで延期することにした。" },
        { sentence: "The express train will ___ from platform 3.", answer: "depart", base: "depart", hint: "d_____", ja: "出発する", sentenceJa: "急行電車は3番線から出発します。" },
        { sentence: "Don't forget to ___ your membership before it expires.", answer: "renew", base: "renew", hint: "r____", ja: "更新する", sentenceJa: "期限が切れる前に会員資格を更新するのを忘れないでください。" },
        { sentence: "Your parking permit will ___ at the end of the month.", answer: "expire", base: "expire", hint: "e_____", ja: "期限が切れる", sentenceJa: "あなたの駐車許可証は月末に期限が切れます。" },
        { sentence: "A technician will ___ the equipment tomorrow.", answer: "inspect", base: "inspect", hint: "i______", ja: "検査する", sentenceJa: "明日、技術者が設備を点検する予定です。" },
        { sentence: "Several customers called to ___ about the new service.", answer: "inquire", base: "inquire", hint: "i______", ja: "問い合わせる", sentenceJa: "何人かの顧客が新しいサービスについて問い合わせるために電話をかけてきた。" },
        { sentence: "Currently, company rules ___ the use of phones during meetings.", answer: "prohibit", base: "prohibit", hint: "p_______", ja: "禁止する", sentenceJa: "現在、会社の規則で会議中の携帯電話の使用は禁止されている。" },
        { sentence: "She will ___ the new team of interns.", answer: "supervise", base: "supervise", hint: "s________", ja: "監督する", sentenceJa: "彼女は新しいインターンチームを監督する予定だ。" },
        { sentence: "These days, many readers ___ to our weekly newsletter.", answer: "subscribe", base: "subscribe", hint: "s________", ja: "定期購読する、加入する", sentenceJa: "最近、多くの読者が私たちの週刊ニュースレターを定期購読している。" },
        { sentence: "Only the director can ___ these payments.", answer: "authorize", base: "authorize", hint: "a________", ja: "許可する、承認する", sentenceJa: "これらの支払いを承認できるのはディレクターだけだ。" },
        { sentence: "The hall can ___ up to 300 guests.", answer: "accommodate", base: "accommodate", hint: "a__________", ja: "収容する、対応する", sentenceJa: "そのホールは最大300人の来客を収容できる。" },
        { sentence: "These days, he ___ to the office by train every day.", answer: "commutes", base: "commute", hint: "c_______", ja: "通勤する", sentenceJa: "最近、彼は毎日電車でオフィスに通勤している。" },
        { sentence: "The firm plans to ___ its head office next year.", answer: "relocate", base: "relocate", hint: "r_______", ja: "移転する", sentenceJa: "その会社は来年、本社を移転する計画だ。" },
        { sentence: "Please ___ your email address before logging in.", answer: "verify", base: "verify", hint: "v_____", ja: "確認する、検証する", sentenceJa: "ログインする前にメールアドレスを確認してください。" },
        { sentence: "Could you ___ your reservation by Friday?", answer: "confirm", base: "confirm", hint: "c______", ja: "確認する、確定する", sentenceJa: "金曜日までにご予約を確認していただけますか？" },
        { sentence: "Hundreds of students ___ in the program each year.", answer: "enroll", base: "enroll", hint: "e_____", ja: "登録する、入会する", sentenceJa: "毎年何百人もの学生がこのプログラムに登録している。" },
      ],
    },
    {
      name: "Day 2",
      items: [
        { sentence: "Workers usually ___ the furniture before it is shipped.", answer: "assemble", base: "assemble", hint: "a_______", ja: "組み立てる、集める", sentenceJa: "作業員はたいてい、発送する前に家具を組み立てる。" },
        { sentence: "She will ___ the schedules of all the departments.", answer: "coordinate", base: "coordinate", hint: "c_________", ja: "調整する、まとめる", sentenceJa: "彼女は全部署のスケジュールを調整する予定だ。" },
        { sentence: "The company will ___ a new area for parking.", answer: "designate", base: "designate", hint: "d________", ja: "指定する、任命する", sentenceJa: "その会社は駐車場のための新しいエリアを指定する予定だ。" },
        { sentence: "Volunteers will ___ brochures at the entrance.", answer: "distribute", base: "distribute", hint: "d_________", ja: "配布する、流通させる", sentenceJa: "ボランティアが入口でパンフレットを配布する予定だ。" },
        { sentence: "The company will ___ you for travel costs.", answer: "reimburse", base: "reimburse", hint: "r________", ja: "払い戻す、精算する", sentenceJa: "その会社はあなたに旅費を払い戻す予定だ。" },
        { sentence: "It may take a few days to ___ your refund.", answer: "process", base: "process", hint: "p______", ja: "処理する", sentenceJa: "返金の処理には数日かかる場合があります。" },
        { sentence: "The new software will ___ online ordering.", answer: "facilitate", base: "facilitate", hint: "f_________", ja: "促進する、容易にする", sentenceJa: "新しいソフトウェアがオンライン注文を容易にする。" },
        { sentence: "All factories must ___ with safety regulations.", answer: "comply", base: "comply", hint: "c_____", ja: "（規則に）従う", sentenceJa: "すべての工場は安全規則に従わなければならない。" },
        { sentence: "Managers ___ the performance of each employee yearly.", answer: "assess", base: "assess", hint: "a_____", ja: "評価する、査定する", sentenceJa: "マネージャーは毎年各従業員の業績を評価する。" },
        { sentence: "The firm will ___ a survey of its customers.", answer: "conduct", base: "conduct", hint: "c______", ja: "（業務などを）行う", sentenceJa: "その会社は顧客への調査を実施する予定だ。" },
        { sentence: "A technician came to ___ the new printer.", answer: "install", base: "install", hint: "i______", ja: "設置する、導入する", sentenceJa: "技術者が新しいプリンターを設置しに来た。" },
        { sentence: "Please ___ your report by the end of the day.", answer: "submit", base: "submit", hint: "s_____", ja: "提出する", sentenceJa: "今日中にレポートを提出してください。" },
        { sentence: "You can ___ tickets at the front counter.", answer: "purchase", base: "purchase", hint: "p_______", ja: "購入する", sentenceJa: "フロントカウンターでチケットを購入できます。" },
        { sentence: "The manager will ___ the terms of the contract.", answer: "negotiate", base: "negotiate", hint: "n________", ja: "交渉する", sentenceJa: "マネージャーが契約条件について交渉する予定だ。" },
        { sentence: "The company is trying to ___ skilled engineers.", answer: "recruit", base: "recruit", hint: "r______", ja: "採用する、募集する", sentenceJa: "その会社は熟練したエンジニアを採用しようとしている。" },
        { sentence: "Last week, the builder ___ the cost of the repairs.", answer: "estimated", base: "estimate", hint: "e________", ja: "見積もる", sentenceJa: "先週、建築業者は修理費用を見積もった。" },
        { sentence: "Only trained staff may ___ this machine.", answer: "operate", base: "operate", hint: "o______", ja: "操作する、運営する", sentenceJa: "訓練を受けたスタッフだけがこの機械を操作できる。" },
        { sentence: "The store will ___ its sale on social media.", answer: "promote", base: "promote", hint: "p______", ja: "昇進させる、宣伝する", sentenceJa: "その店はSNSでセールを宣伝する予定だ。" },
        { sentence: "The board must ___ the new budget.", answer: "approve", base: "approve", hint: "a______", ja: "承認する", sentenceJa: "取締役会は新しい予算を承認しなければならない。" },
        { sentence: "All managers must ___ the monthly meeting.", answer: "attend", base: "attend", hint: "a_____", ja: "出席する", sentenceJa: "すべてのマネージャーは月例会議に出席しなければならない。" },
      ],
    },
    {
      name: "Day 3",
      items: [
        { sentence: "She is taking a two-week ___ in July.", answer: "vacation", base: "vacation", hint: "v_______", ja: "休暇", sentenceJa: "彼女は7月に2週間の休暇を取る予定だ。" },
        { sentence: "Our biggest ___ signed a new contract today.", answer: "client", base: "client", hint: "c_____", ja: "顧客、依頼人", sentenceJa: "今日、私たちの最大の顧客が新しい契約に署名した。" },
        { sentence: "I made a ___ for four at the restaurant.", answer: "reservation", base: "reservation", hint: "r__________", ja: "予約", sentenceJa: "私はそのレストランで4人分の予約をした。" },
        { sentence: "Ask your ___ before changing the schedule.", answer: "supervisor", base: "supervisor", hint: "s_________", ja: "上司、監督者", sentenceJa: "予定を変更する前に上司に確認してください。" },
        { sentence: "Customers can request a full ___ within 30 days.", answer: "refund", base: "refund", hint: "r_____", ja: "返金", sentenceJa: "顧客は30日以内であれば全額返金を請求できる。" },
        { sentence: "We must finish the project before the ___.", answer: "deadline", base: "deadline", hint: "d_______", ja: "締め切り", sentenceJa: "私たちは締め切り前にプロジェクトを終わらせなければならない。" },
        { sentence: "The supplier sent an ___ for last month's order.", answer: "invoice", base: "invoice", hint: "i______", ja: "請求書", sentenceJa: "仕入先は先月分の注文の請求書を送ってきた。" },
        { sentence: "Pick up a ___ for details about the tour.", answer: "brochure", base: "brochure", hint: "b_______", ja: "パンフレット", sentenceJa: "ツアーの詳細はパンフレットを手に取ってご覧ください。" },
        { sentence: "Each ___ must attend an interview.", answer: "applicant", base: "applicant", hint: "a________", ja: "応募者", sentenceJa: "各応募者は面接を受けなければならない。" },
        { sentence: "Keep your ___ in case you return the item.", answer: "receipt", base: "receipt", hint: "r______", ja: "レシート、領収書", sentenceJa: "商品を返品する場合に備えてレシートを保管しておいてください。" },
        { sentence: "The ___ of supplies arrived this morning.", answer: "shipment", base: "shipment", hint: "s_______", ja: "発送、出荷", sentenceJa: "今朝、物資の発送が届いた。" },
        { sentence: "This laptop comes with a two-year ___.", answer: "warranty", base: "warranty", hint: "w_______", ja: "保証（書）", sentenceJa: "このノートパソコンには2年間の保証が付いている。" },
        { sentence: "The staff check the ___ every month.", answer: "inventory", base: "inventory", hint: "i________", ja: "在庫（品）", sentenceJa: "スタッフは毎月在庫を確認する。" },
        { sentence: "She attended a marketing ___ last week.", answer: "seminar", base: "seminar", hint: "s______", ja: "セミナー、研修会", sentenceJa: "彼女は先週マーケティングのセミナーに参加した。" },
        { sentence: "The hotel is a popular ___ for conferences.", answer: "venue", base: "venue", hint: "v____", ja: "会場", sentenceJa: "そのホテルは会議の会場として人気がある。" },
        { sentence: "The ___ of the two firms was announced today.", answer: "merger", base: "merger", hint: "m_____", ja: "合併", sentenceJa: "今日、2社の合併が発表された。" },
        { sentence: "The travel agent emailed us the ___.", answer: "itinerary", base: "itinerary", hint: "i________", ja: "旅程（表）", sentenceJa: "旅行代理店が私たちに旅程表をメールで送ってきた。" },
        { sentence: "He earned extra pay for working ___.", answer: "overtime", base: "overtime", hint: "o_______", ja: "残業", sentenceJa: "彼は残業をして追加の給料を得た。" },
        { sentence: "We welcome your ___ on our new service.", answer: "feedback", base: "feedback", hint: "f_______", ja: "意見、フィードバック", sentenceJa: "私たちの新しいサービスについてのご意見をお待ちしています。" },
        { sentence: "All travel ___ will be paid by the company.", answer: "expenses", base: "expense", hint: "e_______", ja: "費用、経費", sentenceJa: "すべての旅費は会社が負担します。" },
      ],
    },
    {
      name: "Day 4",
      items: [
        { sentence: "The first item on the ___ is the budget review.", answer: "agenda", base: "agenda", hint: "a_____", ja: "議題", sentenceJa: "議題の最初の項目は予算の見直しだ。" },
        { sentence: "The team went over its ___ last quarter.", answer: "budget", base: "budget", hint: "b_____", ja: "予算", sentenceJa: "チームは前四半期に予算を超過した。" },
        { sentence: "She had lunch with two ___ from her team.", answer: "colleagues", base: "colleague", hint: "c_________", ja: "同僚", sentenceJa: "彼女はチームの同僚2人と昼食を食べた。" },
        { sentence: "Both companies signed the ___ yesterday.", answer: "contract", base: "contract", hint: "c_______", ja: "契約（書）", sentenceJa: "両社は昨日その契約書に署名した。" },
        { sentence: "He works in the accounting ___.", answer: "department", base: "department", hint: "d_________", ja: "部署、部門", sentenceJa: "彼は経理部門で働いている。" },
        { sentence: "The gym bought new ___ this year.", answer: "equipment", base: "equipment", hint: "e________", ja: "機器、設備", sentenceJa: "そのジムは今年、新しい機器を購入した。" },
        { sentence: "The new sports ___ has a pool and a gym.", answer: "facility", base: "facility", hint: "f_______", ja: "施設、設備", sentenceJa: "新しいスポーツ施設にはプールとジムがある。" },
        { sentence: "The company's ___ is in Chicago.", answer: "headquarters", base: "headquarters", hint: "h___________", ja: "本社、本部", sentenceJa: "その会社の本社はシカゴにある。" },
        { sentence: "The store sells every kitchen ___ you need.", answer: "appliance", base: "appliance", hint: "a________", ja: "家電製品", sentenceJa: "その店には必要な台所用家電製品が何でも揃っている。" },
        { sentence: "We received a ___ about the late delivery.", answer: "complaint", base: "complaint", hint: "c________", ja: "苦情", sentenceJa: "配達の遅れについて苦情を受けた。" },
        { sentence: "Every ___ gets ten days of paid leave.", answer: "employee", base: "employee", hint: "e_______", ja: "従業員", sentenceJa: "すべての従業員は10日間の有給休暇を取得できる。" },
        { sentence: "This job is a great ___ to learn new skills.", answer: "opportunity", base: "opportunity", hint: "o__________", ja: "機会", sentenceJa: "この仕事は新しいスキルを学ぶ絶好の機会だ。" },
        { sentence: "The new train ___ starts next month.", answer: "schedule", base: "schedule", hint: "s_______", ja: "予定、スケジュール", sentenceJa: "新しい電車の時刻表は来月から始まる。" },
        { sentence: "Our bank opened a new ___ downtown.", answer: "branch", base: "branch", hint: "b_____", ja: "支店", sentenceJa: "私たちの銀行は繁華街に新しい支店を開いた。" },
        { sentence: "Free ___ is available for orders over $50.", answer: "delivery", base: "delivery", hint: "d_______", ja: "配達", sentenceJa: "50   ドルを超える注文には無料配達が利用できる。" },
        { sentence: "The job offers a good ___ and benefits.", answer: "salary", base: "salary", hint: "s_____", ja: "給料", sentenceJa: "その仕事は良い給料と福利厚生を提供している。" },
        { sentence: "We found a cheaper ___ for the materials.", answer: "supplier", base: "supplier", hint: "s_______", ja: "供給業者、仕入先", sentenceJa: "私たちは材料のより安い仕入先を見つけた。" },
        { sentence: "___ for the workshop closes on Friday.", answer: "registration", base: "registration", hint: "r___________", ja: "登録", sentenceJa: "研修会の登録は金曜日で締め切られる。" },
        { sentence: "You need a ___ to park in this area.", answer: "permit", base: "permit", hint: "p_____", ja: "許可証", sentenceJa: "このエリアに駐車するには許可証が必要だ。" },
        { sentence: "The company sent a ___ for the repair work.", answer: "quotation", base: "quotation", hint: "q________", ja: "見積もり", sentenceJa: "その会社は修理作業の見積もりを送ってきた。" },
      ],
    },
    {
      name: "Day 5",
      items: [
        { sentence: "Her explanation was clear and ___.", answer: "logical", base: "logical", hint: "l______", ja: "論理的な", sentenceJa: "彼女の説明は明確で論理的だった。" },
        { sentence: "The station is in a very ___ location.", answer: "convenient", base: "convenient", hint: "c_________", ja: "便利な", sentenceJa: "その駅はとても便利な場所にある。" },
        { sentence: "Your ticket is ___ for one month.", answer: "valid", base: "valid", hint: "v____", ja: "有効な", sentenceJa: "あなたのチケットは1ヶ月間有効です。" },
        { sentence: "Full-time staff are ___ for the bonus.", answer: "eligible", base: "eligible", hint: "e_______", ja: "資格のある", sentenceJa: "正社員はボーナスの対象資格がある。" },
        { sentence: "She received an award for her ___ work.", answer: "outstanding", base: "outstanding", hint: "o__________", ja: "傑出した、未払いの", sentenceJa: "彼女は傑出した仕事で賞を受賞した。" },
        { sentence: "Safety training is ___ for all new staff.", answer: "mandatory", base: "mandatory", hint: "m________", ja: "義務的な、必須の", sentenceJa: "安全研修は全ての新入社員に義務付けられている。" },
        { sentence: "These boots are strong and ___.", answer: "durable", base: "durable", hint: "d______", ja: "耐久性のある、丈夫な", sentenceJa: "このブーツは丈夫で耐久性がある。" },
        { sentence: "The store offers stylish but ___ clothes.", answer: "affordable", base: "affordable", hint: "a_________", ja: "手頃な価格の", sentenceJa: "その店はおしゃれで手頃な価格の服を提供している。" },
        { sentence: "All medical records are kept ___.", answer: "confidential", base: "confidential", hint: "c___________", ja: "機密の", sentenceJa: "すべての医療記録は機密として保管されている。" },
        { sentence: "Please reply soon; this is an ___ matter.", answer: "urgent", base: "urgent", hint: "u_____", ja: "緊急の", sentenceJa: "至急ご返信ください。緊急の件です。" },
        { sentence: "They hired some ___ staff for the holidays.", answer: "temporary", base: "temporary", hint: "t________", ja: "一時的な", sentenceJa: "彼らは休暇シーズンのために一時的なスタッフを雇った。" },
        { sentence: "The new system is faster and more ___.", answer: "efficient", base: "efficient", hint: "e________", ja: "効率的な", sentenceJa: "新しいシステムはより速く、効率的だ。" },
        { sentence: "We need a ___ supplier for our parts.", answer: "reliable", base: "reliable", hint: "r_______", ja: "信頼できる", sentenceJa: "私たちは部品の信頼できる供給業者が必要だ。" },
        { sentence: "The hotel offers a ___ breakfast.", answer: "complimentary", base: "complimentary", hint: "c____________", ja: "無料の", sentenceJa: "そのホテルは無料の朝食を提供している。" },
        { sentence: "Attendance at the evening session is ___.", answer: "optional", base: "optional", hint: "o_______", ja: "任意の、選択できる", sentenceJa: "夜のセッションへの出席は任意です。" },
        { sentence: "The new office is bright and ___.", answer: "spacious", base: "spacious", hint: "s_______", ja: "広々とした", sentenceJa: "新しいオフィスは明るくて広々としている。" },
        { sentence: "The agent showed the house to several ___ buyers.", answer: "prospective", base: "prospective", hint: "p__________", ja: "見込みのある、将来の", sentenceJa: "不動産業者は何人かの見込み客にその家を見せた。" },
        { sentence: "The building is ___ to wheelchair users.", answer: "accessible", base: "accessible", hint: "a_________", ja: "利用しやすい、行きやすい", sentenceJa: "その建物は車椅子利用者にとって利用しやすい。" },
        { sentence: "The shop offers ___ prices on electronics.", answer: "competitive", base: "competitive", hint: "c__________", ja: "競争力のある", sentenceJa: "その店は電化製品で競争力のある価格を提供している。" },
        { sentence: "Our company offers ___ working hours.", answer: "flexible", base: "flexible", hint: "f_______", ja: "柔軟な", sentenceJa: "私たちの会社は柔軟な勤務時間を提供している。" },
      ],
    },
    {
      name: "Day 6",
      items: [
        { sentence: "We ___ apologize for the delay in shipping.", answer: "sincerely", base: "sincerely", hint: "s________", ja: "心から、敬具", sentenceJa: "私たちは配送の遅れについて心よりお詫び申し上げます。" },
        { sentence: "Please make sure the form is filled out ___.", answer: "correctly", base: "correctly", hint: "c________", ja: "正しく", sentenceJa: "フォームが正しく記入されているか確認してください。" },
        { sentence: "The technician responded ___ to our request.", answer: "promptly", base: "promptly", hint: "p_______", ja: "迅速に、時間通りに", sentenceJa: "その技術者は私たちの依頼に迅速に対応した。" },
        { sentence: "The manager will be with you ___.", answer: "shortly", base: "shortly", hint: "s______", ja: "まもなく", sentenceJa: "マネージャーがまもなく参ります。" },
        { sentence: "The report ___ reflects last quarter's sales.", answer: "accurately", base: "accurately", hint: "a_________", ja: "正確に", sentenceJa: "その報告書は前四半期の売上を正確に反映している。" },
        { sentence: "This software is ___ used in accounting departments.", answer: "commonly", base: "commonly", hint: "c_______", ja: "一般的に", sentenceJa: "このソフトウェアは経理部門で一般的に使われている。" },
        { sentence: "Please review the contract ___ before signing.", answer: "thoroughly", base: "thoroughly", hint: "t_________", ja: "徹底的に", sentenceJa: "署名する前に契約書を徹底的に確認してください。" },
        { sentence: "The conference is held ___ in Chicago.", answer: "annually", base: "annually", hint: "a_______", ja: "毎年", sentenceJa: "その会議はシカゴで毎年開催される。" },
        { sentence: "Sales dropped, so we adjusted the budget ___.", answer: "accordingly", base: "accordingly", hint: "a__________", ja: "それに応じて", sentenceJa: "売上が落ちたので、それに応じて予算を調整した。" },
        { sentence: "You can pay online, or ___, visit our office.", answer: "alternatively", base: "alternatively", hint: "a____________", ja: "あるいは、その代わりに", sentenceJa: "オンラインで支払うか、あるいは事務所に来ていただくこともできます。" },
        { sentence: "The team has ___ met its monthly targets.", answer: "consistently", base: "consistently", hint: "c___________", ja: "一貫して", sentenceJa: "そのチームは月ごとの目標を一貫して達成している。" },
        { sentence: "Please invoice the two orders ___.", answer: "separately", base: "separately", hint: "s_________", ja: "別々に", sentenceJa: "2つの注文は別々に請求してください。" },
        { sentence: "All our vegetables are sourced ___.", answer: "locally", base: "locally", hint: "l______", ja: "地元で", sentenceJa: "私たちの野菜はすべて地元で仕入れています。" },
        { sentence: "The merger was ___ announced this morning.", answer: "formally", base: "formally", hint: "f_______", ja: "正式に", sentenceJa: "その合併は今朝正式に発表された。" },
        { sentence: "Make sure the workload is divided ___ among the team.", answer: "evenly", base: "evenly", hint: "e_____", ja: "均等に", sentenceJa: "作業量がチームに均等に分配されるようにしてください。" },
        { sentence: "Fuel prices rose ___ last month.", answer: "sharply", base: "sharply", hint: "s______", ja: "急激に", sentenceJa: "先月、燃料価格が急激に上昇した。" },
        { sentence: "All complaints should be handled ___.", answer: "professionally", base: "professionally", hint: "p_____________", ja: "プロらしく、専門的に", sentenceJa: "苦情はすべてプロらしく対応されるべきだ。" },
        { sentence: "The transition to the new system went ___.", answer: "smoothly", base: "smoothly", hint: "s_______", ja: "円滑に", sentenceJa: "新システムへの移行は円滑に進んだ。" },
        { sentence: "Membership numbers have grown ___ this year.", answer: "steadily", base: "steadily", hint: "s_______", ja: "着実に", sentenceJa: "今年、会員数は着実に増加している。" },
        { sentence: "___, the presentation could have been shorter.", answer: "honestly", base: "honestly", hint: "h_______", ja: "正直に言って", sentenceJa: "正直に言うと、そのプレゼンはもっと短くてもよかった。" },
      ],
    },
    {
      name: "Day 7",
      items: [
        { sentence: "We need to ___ the contract by Friday.", answer: "finalize", base: "finalize", hint: "f_______", ja: "最終決定する", sentenceJa: "金曜日までに契約を最終決定する必要がある。" },
        { sentence: "Last month, the manager ___ staff to update their passwords.", answer: "instructed", base: "instruct", hint: "i_________", ja: "指示する、指導する", sentenceJa: "先月、マネージャーはスタッフにパスワードを更新するよう指示した。", altAnswers: ["instructs"] },
        { sentence: "All departments are expected to ___ on the new policy.", answer: "cooperate", base: "cooperate", hint: "c________", ja: "協力する", sentenceJa: "すべての部署がこの新方針について協力することが求められている。" },
        { sentence: "The airline agreed to ___ passengers for the delay.", answer: "compensate", base: "compensate", hint: "c_________", ja: "補償する", sentenceJa: "その航空会社は遅延について乗客に補償することに同意した。" },
        { sentence: "The new software currently ___ the ordering process.", answer: "simplifies", base: "simplify", hint: "s_________", ja: "簡素化する", sentenceJa: "その新しいソフトウェアは現在、注文プロセスを簡素化している。" },
        { sentence: "She was ___ for Employee of the Year.", answer: "nominated", base: "nominate", hint: "n________", ja: "指名する、推薦する", sentenceJa: "彼女は今年の従業員賞に推薦された。" },
        { sentence: "The two companies plan to ___ next year.", answer: "merge", base: "merge", hint: "m____", ja: "合併する", sentenceJa: "その2社は来年合併する予定だ。" },
        { sentence: "The contract can be ___ with 30 days' notice.", answer: "terminated", base: "terminate", hint: "t_________", ja: "終了する、解除する", sentenceJa: "その契約は30日前の通知で解除できる。" },
        { sentence: "The team worked overtime to ___ the issue.", answer: "resolve", base: "resolve", hint: "r______", ja: "解決する", sentenceJa: "そのチームは問題を解決するために残業した。" },
        { sentence: "We currently ___ customer feedback closely.", answer: "monitor", base: "monitor", hint: "m______", ja: "監視する", sentenceJa: "私たちは現在、顧客の声を注意深く監視している。" },
        { sentence: "The new system currently ___ the approval process.", answer: "streamlines", base: "streamline", hint: "s__________", ja: "効率化する", sentenceJa: "その新しいシステムは現在、承認プロセスを効率化している。" },
        { sentence: "The budget was ___ to three main projects.", answer: "allocated", base: "allocate", hint: "a________", ja: "割り当てる", sentenceJa: "予算は3つの主要プロジェクトに割り当てられた。" },
        { sentence: "You can ___ the report to fit your needs.", answer: "customize", base: "customize", hint: "c________", ja: "カスタマイズする", sentenceJa: "レポートはニーズに合わせてカスタマイズできる。" },
        { sentence: "Yesterday, the technician ___ the problem quickly.", answer: "diagnosed", base: "diagnose", hint: "d________", ja: "診断する", sentenceJa: "昨日、その技術者は問題を素早く診断した。", altAnswers: ["diagnoses"] },
        { sentence: "The company will ___ this product line.", answer: "discontinue", base: "discontinue", hint: "d__________", ja: "中止する、廃止する", sentenceJa: "その会社はこの製品ラインを廃止する予定だ。" },
        { sentence: "Could you ___ what you mean by that?", answer: "clarify", base: "clarify", hint: "c______", ja: "明確にする", sentenceJa: "それがどういう意味か明確にしていただけますか。" },
        { sentence: "Last week, she ___ the data into a single report.", answer: "compiled", base: "compile", hint: "c_______", ja: "まとめる、編集する", sentenceJa: "先週、彼女はデータを1つの報告書にまとめた。", altAnswers: ["compiles"] },
        { sentence: "The HR department currently ___ employee benefits.", answer: "administers", base: "administer", hint: "a__________", ja: "管理する、運営する", sentenceJa: "人事部は現在、従業員の福利厚生を管理している。" },
        { sentence: "A good manager knows how to ___ tasks.", answer: "delegate", base: "delegate", hint: "d_______", ja: "委任する", sentenceJa: "優れたマネージャーは仕事を委任する方法を知っている。" },
        { sentence: "We took steps to ___ the risk of delays.", answer: "minimize", base: "minimize", hint: "m_______", ja: "最小限にする", sentenceJa: "私たちは遅延のリスクを最小限にするための対策を取った。" },
      ],
    },
  ],
};
